'use client'

/**
 * Auto-Modified Workouts Detail View
 *
 * Comprehensive view of all automatically modified workouts with:
 * - Side-by-side original vs modified comparison
 * - Grouping by athlete
 * - 14-day calendar timeline
 * - Bulk approve/reject actions
 * - TSS and zone comparisons
 */

import { useState } from 'react'
import useSWR from 'swr'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'
import { Alert, AlertDescription } from '@/components/ui/alert'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import {
  CheckCircle2,
  XCircle,
  ArrowRight,
  Calendar,
  Clock,
  TrendingDown,
  Activity,
  AlertTriangle,
} from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { sv } from 'date-fns/locale'
import { useToast } from '@/hooks/use-toast'

interface ModifiedWorkout {
  id: string
  clientId: string
  clientName: string
  workoutDate: Date
  originalType: string
  currentType: string
  action: 'CANCEL' | 'REDUCE_INTENSITY' | 'REDUCE_VOLUME' | 'CONVERT_TO_CROSS_TRAINING'
  reasoning: string
  reviewed: boolean
  autoGenerated: boolean
  modifiedAt: Date
  status: string
  originalDuration?: number
  currentDuration?: number
  originalIntensity?: string
  currentIntensity?: string
  originalZones?: string
  currentZones?: string
}

interface GroupedModifications {
  [clientName: string]: ModifiedWorkout[]
}

const fetcher = (url: string) => fetch(url).then(r => r.json())

export function AutoModifiedWorkoutsView() {
  const { toast } = useToast()
  const [selectedAthlete, setSelectedAthlete] = useState<string>('ALL')
  const [selectedModifications, setSelectedModifications] = useState<Set<string>>(new Set())
  const [showBulkApproveDialog, setShowBulkApproveDialog] = useState(false)
  const [bulkApproveTarget, setBulkApproveTarget] = useState<'all' | 'athlete' | null>(null)
  const [isApproving, setIsApproving] = useState(false)

  const { data, error, mutate } = useSWR('/api/workouts/modifications', fetcher, {
    refreshInterval: 30000,
  })

  const modifications: ModifiedWorkout[] = data?.modifications || []

  // Group modifications by athlete
  const groupedModifications: GroupedModifications = modifications.reduce((acc, mod) => {
    if (!acc[mod.clientName]) {
      acc[mod.clientName] = []
    }
    acc[mod.clientName].push(mod)
    return acc
  }, {} as GroupedModifications)

  // Get unique athlete names for filter
  const athleteNames = Object.keys(groupedModifications).sort()

  // Filter modifications based on selected athlete
  const filteredModifications =
    selectedAthlete === 'ALL'
      ? modifications
      : modifications.filter(m => m.clientName === selectedAthlete)

  // Count unreviewed
  const unreviewedCount = filteredModifications.filter(m => !m.reviewed).length
  const selectedCount = selectedModifications.size

  // Toggle selection
  const toggleSelection = (id: string) => {
    const newSelection = new Set(selectedModifications)
    if (newSelection.has(id)) {
      newSelection.delete(id)
    } else {
      newSelection.add(id)
    }
    setSelectedModifications(newSelection)
  }

  // Select all for athlete
  const selectAllForAthlete = (athleteName: string) => {
    const athleteMods = groupedModifications[athleteName] || []
    const newSelection = new Set(selectedModifications)
    athleteMods.forEach(mod => {
      if (!mod.reviewed) {
        newSelection.add(mod.id)
      }
    })
    setSelectedModifications(newSelection)
  }

  // Clear all selections
  const clearSelections = () => {
    setSelectedModifications(new Set())
  }

  // Bulk approve
  const handleBulkApprove = async () => {
    setIsApproving(true)
    try {
      const idsToApprove =
        bulkApproveTarget === 'all'
          ? filteredModifications.filter(m => !m.reviewed).map(m => m.id)
          : Array.from(selectedModifications)

      // Approve each modification
      for (const id of idsToApprove) {
        await fetch(`/api/workouts/modifications/${id}/review`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ approved: true }),
        })
      }

      toast({
        title: 'Godkända',
        description: `${idsToApprove.length} träningspass har godkänts`,
      })

      clearSelections()
      mutate()
    } catch (error) {
      console.error('Error approving modifications:', error)
      toast({
        title: 'Fel',
        description: 'Kunde inte godkänna ändringar',
        variant: 'destructive',
      })
    } finally {
      setIsApproving(false)
      setShowBulkApproveDialog(false)
      setBulkApproveTarget(null)
    }
  }

  // Individual approve
  const handleIndividualApprove = async (id: string) => {
    try {
      await fetch(`/api/workouts/modifications/${id}/review`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ approved: true }),
      })

      toast({
        title: 'Godkänd',
        description: 'Träningsändring godkänd',
      })

      mutate()
    } catch (error) {
      console.error('Error approving modification:', error)
      toast({
        title: 'Fel',
        description: 'Kunde inte godkänna ändring',
        variant: 'destructive',
      })
    }
  }

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertDescription>Kunde inte ladda träningsändringar</AlertDescription>
      </Alert>
    )
  }

  if (!data) {
    return (
      <Card>
        <CardContent className="pt-6">
          <p className="text-center text-muted-foreground">Laddar...</p>
        </CardContent>
      </Card>
    )
  }

  if (modifications.length === 0) {
    return (
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col items-center justify-center gap-2 py-8">
            <CheckCircle2 className="h-12 w-12 text-green-500" />
            <p className="text-lg font-medium">Inga automatiska ändringar</p>
            <p className="text-sm text-muted-foreground">
              Inga träningspass har modifierats automatiskt
            </p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header with Filters and Actions */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div>
            <h3 className="text-2xl font-bold">Auto-modifierade träningspass</h3>
            <p className="text-sm text-muted-foreground">
              {unreviewedCount} ogranskade av {filteredModifications.length} totalt
            </p>
          </div>

          <Select value={selectedAthlete} onValueChange={setSelectedAthlete}>
            <SelectTrigger className="w-[200px]">
              <SelectValue placeholder="Alla atleter" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="ALL">Alla atleter ({modifications.length})</SelectItem>
              {athleteNames.map(name => (
                <SelectItem key={name} value={name}>
                  {name} ({groupedModifications[name].length})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="flex items-center gap-2">
          {selectedCount > 0 && (
            <>
              <Badge variant="secondary" className="px-3 py-1">
                {selectedCount} valda
              </Badge>
              <Button variant="outline" size="sm" onClick={clearSelections}>
                Rensa
              </Button>
              <Button
                variant="default"
                size="sm"
                onClick={() => {
                  setBulkApproveTarget('athlete')
                  setShowBulkApproveDialog(true)
                }}
              >
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Godkänn valda
              </Button>
            </>
          )}

          {unreviewedCount > 0 && (
            <Button
              variant="default"
              onClick={() => {
                setBulkApproveTarget('all')
                setShowBulkApproveDialog(true)
              }}
            >
              <CheckCircle2 className="mr-2 h-4 w-4" />
              Godkänn alla
            </Button>
          )}
        </div>
      </div>

      {/* Modifications List - Grouped by Athlete */}
      {selectedAthlete === 'ALL' ? (
        <div className="space-y-6">
          {athleteNames.map(athleteName => {
            const athleteMods = groupedModifications[athleteName]
            const athleteUnreviewed = athleteMods.filter(m => !m.reviewed).length

            return (
              <Card key={athleteName}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle>{athleteName}</CardTitle>
                      <CardDescription>
                        {athleteMods.length} modifieringar, {athleteUnreviewed} ogranskade
                      </CardDescription>
                    </div>
                    {athleteUnreviewed > 0 && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => selectAllForAthlete(athleteName)}
                      >
                        Välj alla
                      </Button>
                    )}
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {athleteMods.map(mod => (
                    <ModificationCard
                      key={mod.id}
                      modification={mod}
                      isSelected={selectedModifications.has(mod.id)}
                      onToggleSelect={() => toggleSelection(mod.id)}
                      onApprove={() => handleIndividualApprove(mod.id)}
                    />
                  ))}
                </CardContent>
              </Card>
            )
          })}
        </div>
      ) : (
        <div className="space-y-4">
          {filteredModifications.map(mod => (
            <ModificationCard
              key={mod.id}
              modification={mod}
              isSelected={selectedModifications.has(mod.id)}
              onToggleSelect={() => toggleSelection(mod.id)}
              onApprove={() => handleIndividualApprove(mod.id)}
            />
          ))}
        </div>
      )}

      {/* Bulk Approve Confirmation Dialog */}
      <AlertDialog open={showBulkApproveDialog} onOpenChange={setShowBulkApproveDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Bekräfta godkännande</AlertDialogTitle>
            <AlertDialogDescription>
              {bulkApproveTarget === 'all'
                ? `Är du säker på att du vill godkänna alla ${unreviewedCount} ogranskade träningsändringar?`
                : `Är du säker på att du vill godkänna ${selectedCount} valda träningsändringar?`}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Avbryt</AlertDialogCancel>
            <AlertDialogAction onClick={handleBulkApprove} disabled={isApproving}>
              {isApproving ? 'Godkänner...' : 'Godkänn'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

/**
 * Individual Modification Card with Comparison View
 */
function ModificationCard({
  modification,
  isSelected,
  onToggleSelect,
  onApprove,
}: {
  modification: ModifiedWorkout
  isSelected: boolean
  onToggleSelect: () => void
  onApprove: () => void
}) {
  const actionLabels = {
    CANCEL: 'Avbokad',
    REDUCE_INTENSITY: 'Reducerad intensitet',
    REDUCE_VOLUME: 'Reducerad volym',
    CONVERT_TO_CROSS_TRAINING: 'Konverterad till kompletterande träning',
  }

  const actionColors = {
    CANCEL: 'destructive',
    REDUCE_INTENSITY: 'default',
    REDUCE_VOLUME: 'default',
    CONVERT_TO_CROSS_TRAINING: 'secondary',
  }

  const actionIcons = {
    CANCEL: XCircle,
    REDUCE_INTENSITY: TrendingDown,
    REDUCE_VOLUME: TrendingDown,
    CONVERT_TO_CROSS_TRAINING: Activity,
  }

  const ActionIcon = actionIcons[modification.action]

  // Calculate volume reduction %
  const volumeReduction =
    modification.originalDuration && modification.currentDuration
      ? Math.round(
          ((modification.originalDuration - modification.currentDuration) /
            modification.originalDuration) *
            100
        )
      : null

  return (
    <Card
      className={`${!modification.reviewed ? 'border-blue-200 bg-blue-50/30' : ''} ${
        isSelected ? 'ring-2 ring-blue-500' : ''
      }`}
    >
      <CardContent className="pt-6">
        <div className="space-y-4">
          {/* Header Row */}
          <div className="flex items-start justify-between">
            <div className="flex items-start gap-3">
              {!modification.reviewed && (
                <Checkbox checked={isSelected} onCheckedChange={onToggleSelect} className="mt-1" />
              )}
              <div>
                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <p className="font-semibold">
                    {new Date(modification.workoutDate).toLocaleDateString('sv-SE', {
                      weekday: 'long',
                      day: 'numeric',
                      month: 'long',
                    })}
                  </p>
                  {modification.autoGenerated && (
                    <Badge variant="outline" className="text-xs">
                      Auto
                    </Badge>
                  )}
                </div>
                <p className="text-sm text-muted-foreground">
                  Modifierad{' '}
                  {formatDistanceToNow(new Date(modification.modifiedAt), {
                    addSuffix: true,
                    locale: sv,
                  })}
                </p>
              </div>
            </div>

            <Badge variant={actionColors[modification.action] as any}>
              <ActionIcon className="mr-1 h-3 w-3" />
              {actionLabels[modification.action]}
            </Badge>
          </div>

          {/* Comparison View */}
          <div className="grid grid-cols-[1fr_auto_1fr] gap-4 items-start">
            {/* Original Workout */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-muted-foreground uppercase">Original</p>
              <div className="p-3 bg-muted/50 rounded-lg space-y-1">
                <p className="font-semibold">{modification.originalType}</p>
                {modification.originalDuration && (
                  <div className="flex items-center gap-1 text-sm text-muted-foreground">
                    <Clock className="h-3 w-3" />
                    {modification.originalDuration} min
                  </div>
                )}
                {modification.originalIntensity && (
                  <p className="text-sm">
                    <span className="font-medium">Intensitet:</span> {modification.originalIntensity}
                  </p>
                )}
                {modification.originalZones && (
                  <p className="text-sm">
                    <span className="font-medium">Zoner:</span> {modification.originalZones}
                  </p>
                )}
              </div>
            </div>

            {/* Arrow */}
            <div className="flex items-center justify-center pt-8">
              <ArrowRight className="h-6 w-6 text-muted-foreground" />
            </div>

            {/* Modified Workout */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-muted-foreground uppercase">Modifierad</p>
              <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg space-y-1">
                <p className="font-semibold">{modification.currentType}</p>
                {modification.currentDuration && (
                  <div className="flex items-center gap-1 text-sm text-muted-foreground">
                    <Clock className="h-3 w-3" />
                    {modification.currentDuration} min
                    {volumeReduction !== null && (
                      <span className="text-red-600 font-medium">(-{volumeReduction}%)</span>
                    )}
                  </div>
                )}
                {modification.currentIntensity && (
                  <p className="text-sm">
                    <span className="font-medium">Intensitet:</span> {modification.currentIntensity}
                  </p>
                )}
                {modification.currentZones && (
                  <p className="text-sm">
                    <span className="font-medium">Zoner:</span> {modification.currentZones}
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Reasoning */}
          <Alert>
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription>
              <p className="font-medium mb-1">Orsak:</p>
              <p className="text-sm">{modification.reasoning}</p>
            </AlertDescription>
          </Alert>

          {/* Actions */}
          {!modification.reviewed && (
            <div className="flex items-center justify-end gap-2 pt-2 border-t">
              <Button variant="outline" size="sm">
                <XCircle className="mr-2 h-4 w-4" />
                Underkänn
              </Button>
              <Button variant="default" size="sm" onClick={onApprove}>
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Godkänn
              </Button>
            </div>
          )}

          {modification.reviewed && (
            <div className="flex items-center justify-center gap-2 pt-2 border-t">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              <p className="text-sm text-muted-foreground">Granskad och godkänd</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
