'use client'

/**
 * Injury Alert Center Component
 *
 * Coach dashboard showing:
 * - Active injury alerts from daily check-ins
 * - ACWR warnings (injury risk)
 * - Auto-modified workouts requiring review
 * - Recent injury assessments
 *
 * Real-time monitoring of all athletes with automatic injury responses.
 */

import { useState, useEffect } from 'react'
import useSWR from 'swr'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  AlertTriangle,
  TrendingUp,
  Activity,
  CheckCircle2,
  Clock,
  User,
  Calendar,
  ArrowRight,
} from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { sv } from 'date-fns/locale'
import { InfoTooltip } from '@/components/ui/InfoTooltip'

interface InjuryAlert {
  id: string
  clientId: string
  clientName: string
  injuryType: string
  painLevel: number
  detectedAt: Date
  status: 'ACTIVE' | 'MONITORING' | 'RESOLVED'
  urgency: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'
  estimatedReturnWeeks: number
  workoutsModified: number
  lastCheckIn?: Date
  phase?: number
}

interface ACWRWarning {
  id: string
  clientId: string
  clientName: string
  acwr: number
  risk: 'CRITICAL' | 'DANGER' | 'CAUTION'
  date: Date
  recommendedAction: string
}

interface ModifiedWorkout {
  id: string
  clientId: string
  clientName: string
  workoutDate: Date
  originalType: string
  action: 'CANCEL' | 'REDUCE_INTENSITY' | 'REDUCE_VOLUME' | 'CONVERT_TO_CROSS_TRAINING'
  reasoning: string
  reviewed: boolean
  autoGenerated: boolean
}

const fetcher = (url: string) => fetch(url).then(r => r.json())

export function InjuryAlertCenter() {
  const [activeTab, setActiveTab] = useState('alerts')

  const { data: alertsData, error: alertsError, mutate: mutateAlerts } = useSWR(
    '/api/injury/alerts',
    fetcher,
    { refreshInterval: 30000 } // Refresh every 30 seconds
  )

  const { data: acwrData, error: acwrError } = useSWR(
    '/api/training-load/warnings',
    fetcher,
    { refreshInterval: 60000 } // Refresh every minute
  )

  const { data: modificationsData, error: modificationsError, mutate: mutateModifications } = useSWR(
    '/api/workouts/modifications?unreviewed=true',
    fetcher,
    { refreshInterval: 30000 }
  )

  const isLoading = !alertsData && !alertsError
  const hasAlerts = alertsData?.alerts?.length > 0
  const hasACWRWarnings = acwrData?.warnings?.length > 0
  const hasModifications = modificationsData?.modifications?.length > 0

  const totalUnreviewed =
    (alertsData?.alerts?.filter((a: InjuryAlert) => a.status === 'ACTIVE').length || 0) +
    (modificationsData?.modifications?.filter((m: ModifiedWorkout) => !m.reviewed).length || 0)

  return (
    <div className="space-y-6">
      {/* Header with Summary Stats */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight flex items-center gap-1.5">Skadeövervakning <InfoTooltip conceptKey="coachAlerts" /></h2>
          <p className="text-muted-foreground">
            Automatisk skadedetektering och träningsjustering
          </p>
        </div>

        {totalUnreviewed > 0 && (
          <Badge variant="destructive" className="text-lg px-4 py-2">
            {totalUnreviewed} kräver granskning
          </Badge>
        )}
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Aktiva skador</CardTitle>
            <AlertTriangle className="h-4 w-4 text-destructive" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {alertsData?.alerts?.filter((a: InjuryAlert) => a.status === 'ACTIVE').length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {alertsData?.alerts?.filter((a: InjuryAlert) => a.urgency === 'CRITICAL').length || 0}{' '}
              kritiska
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">ACWR-varningar</CardTitle>
            <TrendingUp className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {acwrData?.warnings?.length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {acwrData?.warnings?.filter((w: ACWRWarning) => w.risk === 'CRITICAL').length || 0}{' '}
              kritiska
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Auto-modifierade pass</CardTitle>
            <Activity className="h-4 w-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {modificationsData?.modifications?.length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {modificationsData?.modifications?.filter((m: ModifiedWorkout) => !m.reviewed).length || 0}{' '}
              ogranskade
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Tabs for Different Alert Types */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="alerts" className="relative">
            Skadevarningar
            {hasAlerts && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-destructive rounded-full" />
            )}
          </TabsTrigger>
          <TabsTrigger value="acwr" className="relative">
            ACWR-övervakning
            {hasACWRWarnings && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-yellow-500 rounded-full" />
            )}
          </TabsTrigger>
          <TabsTrigger value="modifications" className="relative">
            Modifierade pass
            {hasModifications && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-blue-500 rounded-full" />
            )}
          </TabsTrigger>
        </TabsList>

        {/* Active Injury Alerts Tab */}
        <TabsContent value="alerts" className="space-y-4">
          {isLoading ? (
            <Card>
              <CardContent className="pt-6">
                <p className="text-center text-muted-foreground">Laddar varningar...</p>
              </CardContent>
            </Card>
          ) : !hasAlerts ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-green-500" />
                  <p className="text-lg font-medium">Inga aktiva skadevarningar</p>
                  <p className="text-sm text-muted-foreground">
                    Alla atleeter rapporterar normala värden
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {alertsData.alerts
                .sort((a: InjuryAlert, b: InjuryAlert) => {
                  const urgencyOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 }
                  return urgencyOrder[a.urgency] - urgencyOrder[b.urgency]
                })
                .map((alert: InjuryAlert) => (
                  <InjuryAlertCard key={alert.id} alert={alert} onResolve={() => mutateAlerts()} />
                ))}
            </div>
          )}
        </TabsContent>

        {/* ACWR Warnings Tab */}
        <TabsContent value="acwr" className="space-y-4">
          {!hasACWRWarnings ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-green-500" />
                  <p className="text-lg font-medium">Inga ACWR-varningar</p>
                  <p className="text-sm text-muted-foreground">
                    Träningsbelastningen är inom säkra zoner för alla atleeter
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {acwrData.warnings
                .sort((a: ACWRWarning, b: ACWRWarning) => {
                  const riskOrder = { CRITICAL: 0, DANGER: 1, CAUTION: 2 }
                  return riskOrder[a.risk] - riskOrder[b.risk]
                })
                .map((warning: ACWRWarning) => (
                  <ACWRWarningCard key={warning.id} warning={warning} />
                ))}
            </div>
          )}
        </TabsContent>

        {/* Modified Workouts Tab */}
        <TabsContent value="modifications" className="space-y-4">
          {!hasModifications ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-green-500" />
                  <p className="text-lg font-medium">Inga modifierade pass</p>
                  <p className="text-sm text-muted-foreground">
                    Inga automatiska träningsjusteringar har gjorts
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {modificationsData.modifications.map((modification: ModifiedWorkout) => (
                <ModifiedWorkoutCard
                  key={modification.id}
                  modification={modification}
                  onReview={() => mutateModifications()}
                />
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  )
}

/**
 * Individual Injury Alert Card
 */
function InjuryAlertCard({
  alert,
  onResolve,
}: {
  alert: InjuryAlert
  onResolve: () => void
}) {
  const [isResolving, setIsResolving] = useState(false)

  const urgencyColors = {
    CRITICAL: 'bg-red-500',
    HIGH: 'bg-orange-500',
    MEDIUM: 'bg-yellow-500',
    LOW: 'bg-blue-500',
  }

  const handleResolve = async () => {
    setIsResolving(true)
    try {
      await fetch(`/api/injury/alerts/${alert.id}/resolve`, {
        method: 'PUT',
      })
      onResolve()
    } catch (error) {
      console.error('Error resolving alert:', error)
    } finally {
      setIsResolving(false)
    }
  }

  return (
    <Card className="border-l-4" style={{ borderLeftColor: urgencyColors[alert.urgency] }}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-lg">{alert.clientName}</CardTitle>
              <Badge variant={alert.urgency === 'CRITICAL' ? 'destructive' : 'default'}>
                {alert.urgency}
              </Badge>
              <Badge variant="outline">{alert.status}</Badge>
            </div>
            <CardDescription>
              {alert.injuryType.replace(/_/g, ' ')} · Smärtnivå {alert.painLevel}/10
            </CardDescription>
          </div>

          <div className="text-right text-sm text-muted-foreground">
            <div className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatDistanceToNow(new Date(alert.detectedAt), {
                addSuffix: true,
                locale: sv,
              })}
            </div>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="grid grid-cols-3 gap-4 text-sm">
          <div>
            <p className="text-muted-foreground">Pass modifierade</p>
            <p className="font-medium">{alert.workoutsModified} st</p>
          </div>
          <div>
            <p className="text-muted-foreground">Beräknad återhämtning</p>
            <p className="font-medium">{alert.estimatedReturnWeeks} veckor</p>
          </div>
          {alert.phase && (
            <div>
              <p className="text-muted-foreground">Rehab-fas</p>
              <p className="font-medium">Fas {alert.phase}/5</p>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between pt-2 border-t">
          <Button variant="outline" size="sm" asChild>
            <a href={`/coach/clients/${alert.clientId}`}>
              <User className="mr-2 h-4 w-4" />
              Visa atleet
            </a>
          </Button>

          {alert.status === 'ACTIVE' && (
            <Button
              variant="secondary"
              size="sm"
              onClick={handleResolve}
              disabled={isResolving}
            >
              <CheckCircle2 className="mr-2 h-4 w-4" />
              {isResolving ? 'Löser...' : 'Markera som löst'}
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  )
}

/**
 * ACWR Warning Card
 */
function ACWRWarningCard({ warning }: { warning: ACWRWarning }) {
  const riskColors = {
    CRITICAL: 'destructive',
    DANGER: 'default',
    CAUTION: 'secondary',
  }

  const riskLabels = {
    CRITICAL: 'Kritisk risk',
    DANGER: 'Hög risk',
    CAUTION: 'Måttlig risk',
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-lg">{warning.clientName}</CardTitle>
              <Badge variant={riskColors[warning.risk] as any}>
                {riskLabels[warning.risk]}
              </Badge>
            </div>
            <CardDescription>ACWR: {warning.acwr.toFixed(2)}</CardDescription>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <Alert>
          <AlertDescription>
            <p className="font-medium mb-1">Rekommenderad åtgärd:</p>
            <p className="text-sm">{warning.recommendedAction}</p>
          </AlertDescription>
        </Alert>

        <Button variant="outline" size="sm" asChild className="w-full">
          <a href={`/coach/clients/${warning.clientId}/monitoring`}>
            <TrendingUp className="mr-2 h-4 w-4" />
            Visa träningsbelastning
          </a>
        </Button>
      </CardContent>
    </Card>
  )
}

/**
 * Modified Workout Card
 */
function ModifiedWorkoutCard({
  modification,
  onReview,
}: {
  modification: ModifiedWorkout
  onReview: () => void
}) {
  const [isReviewing, setIsReviewing] = useState(false)

  const actionLabels = {
    CANCEL: 'Avbokad',
    REDUCE_INTENSITY: 'Reducerad intensitet',
    REDUCE_VOLUME: 'Reducerad volym',
    CONVERT_TO_CROSS_TRAINING: 'Konverterad till kompletterande träning',
  }

  const actionColors = {
    CANCEL: 'destructive',
    REDUCE_INTENSITY: 'default',
    REDUCE_VOLUME: 'default',
    CONVERT_TO_CROSS_TRAINING: 'secondary',
  }

  const handleReview = async () => {
    setIsReviewing(true)
    try {
      await fetch(`/api/workouts/modifications/${modification.id}/review`, {
        method: 'PUT',
      })
      onReview()
    } catch (error) {
      console.error('Error reviewing modification:', error)
    } finally {
      setIsReviewing(false)
    }
  }

  return (
    <Card className={!modification.reviewed ? 'border-blue-200 bg-blue-50/50' : ''}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-base">{modification.clientName}</CardTitle>
              {modification.autoGenerated && (
                <Badge variant="outline" className="text-xs">
                  Auto
                </Badge>
              )}
            </div>
            <CardDescription>
              {new Date(modification.workoutDate).toLocaleDateString('sv-SE', {
                weekday: 'long',
                day: 'numeric',
                month: 'long',
              })}
            </CardDescription>
          </div>

          <Badge variant={actionColors[modification.action] as any}>
            {actionLabels[modification.action]}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="flex items-center gap-2 text-sm">
          <span className="font-medium">{modification.originalType}</span>
          <ArrowRight className="h-4 w-4 text-muted-foreground" />
          <span className="text-muted-foreground">{actionLabels[modification.action]}</span>
        </div>

        <Alert>
          <AlertDescription className="text-sm">{modification.reasoning}</AlertDescription>
        </Alert>

        {!modification.reviewed && (
          <Button
            variant="default"
            size="sm"
            onClick={handleReview}
            disabled={isReviewing}
            className="w-full"
          >
            <CheckCircle2 className="mr-2 h-4 w-4" />
            {isReviewing ? 'Granskar...' : 'Granska och godkänn'}
          </Button>
        )}
      </CardContent>
    </Card>
  )
}
