'use client'

/**
 * Injury Alert Center Component
 *
 * Coach dashboard showing:
 * - Active injury alerts from daily check-ins
 * - ACWR warnings (injury risk)
 * - Auto-modified workouts requiring review
 * - Recent injury assessments
 *
 * Real-time monitoring of all athletes with automatic injury responses.
 */

import { useState, useEffect } from 'react'
import useSWR from 'swr'
import {
  RolePanel as Card,
  RolePanelContent as CardContent,
  RolePanelDescription as CardDescription,
  RolePanelHeader as CardHeader,
  RolePanelTitle as CardTitle,
} from '@/components/layouts/role-shell/RolePage'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  AlertTriangle,
  TrendingUp,
  Activity,
  CheckCircle2,
  Clock,
  User,
  Calendar,
  ArrowRight,
} from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { enUS, sv } from 'date-fns/locale'
import { usePathname } from 'next/navigation'
import { useLocale } from 'next-intl'
import { InfoTooltip } from '@/components/ui/InfoTooltip'

function useBasePath() {
  const pathname = usePathname()
  const slugMatch = pathname.match(/^\/([^/]+)\/coach/)
  return slugMatch ? `/${slugMatch[1]}` : ''
}

interface InjuryAlert {
  id: string
  clientId: string
  clientName: string
  injuryType: string
  painLevel: number
  detectedAt: Date
  status: 'ACTIVE' | 'MONITORING' | 'RESOLVED'
  urgency: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'
  estimatedReturnWeeks: number
  workoutsModified: number
  lastCheckIn?: Date
  phase?: number
}

interface ACWRWarning {
  id: string
  clientId: string
  clientName: string
  acwr: number
  risk: 'CRITICAL' | 'DANGER' | 'CAUTION'
  date: Date
  recommendedAction: string
}

interface ModifiedWorkout {
  id: string
  clientId: string
  clientName: string
  workoutDate: Date
  originalType: string
  action: 'CANCEL' | 'REDUCE_INTENSITY' | 'REDUCE_VOLUME' | 'CONVERT_TO_CROSS_TRAINING'
  reasoning: string
  reviewed: boolean
  autoGenerated: boolean
}

type AppLocale = 'en' | 'sv'

const labels: Record<AppLocale, {
  title: string
  description: string
  requiresReview: string
  activeInjuries: string
  critical: string
  acwrWarnings: string
  autoModifiedWorkouts: string
  unreviewed: string
  injuryWarnings: string
  acwrMonitoring: string
  modifiedWorkouts: string
  loadingWarnings: string
  noActiveInjuryWarnings: string
  normalValues: string
  noAcwrWarnings: string
  safeTrainingLoad: string
  noModifiedWorkouts: string
  noAutomaticAdjustments: string
  painLevel: string
  workoutsModified: string
  countSuffix: string
  estimatedRecovery: string
  weeks: string
  rehabPhase: string
  phase: string
  viewAthlete: string
  resolving: string
  markResolved: string
  criticalRisk: string
  highRisk: string
  moderateRisk: string
  recommendedAction: string
  viewTrainingLoad: string
  cancel: string
  reduceIntensity: string
  reduceVolume: string
  convertCrossTraining: string
  reviewing: string
  reviewApprove: string
}> = {
  en: {
    title: 'Injury monitoring',
    description: 'Automatic injury detection and training adjustment',
    requiresReview: 'requires review',
    activeInjuries: 'Active injuries',
    critical: 'critical',
    acwrWarnings: 'ACWR warnings',
    autoModifiedWorkouts: 'Auto-modified workouts',
    unreviewed: 'unreviewed',
    injuryWarnings: 'Injury warnings',
    acwrMonitoring: 'ACWR monitoring',
    modifiedWorkouts: 'Modified workouts',
    loadingWarnings: 'Loading warnings...',
    noActiveInjuryWarnings: 'No active injury warnings',
    normalValues: 'All athletes are reporting normal values',
    noAcwrWarnings: 'No ACWR warnings',
    safeTrainingLoad: 'Training load is within safe zones for all athletes',
    noModifiedWorkouts: 'No modified workouts',
    noAutomaticAdjustments: 'No automatic training adjustments have been made',
    painLevel: 'Pain level',
    workoutsModified: 'Workouts modified',
    countSuffix: '',
    estimatedRecovery: 'Estimated recovery',
    weeks: 'weeks',
    rehabPhase: 'Rehab phase',
    phase: 'Phase',
    viewAthlete: 'View athlete',
    resolving: 'Resolving...',
    markResolved: 'Mark as resolved',
    criticalRisk: 'Critical risk',
    highRisk: 'High risk',
    moderateRisk: 'Moderate risk',
    recommendedAction: 'Recommended action:',
    viewTrainingLoad: 'View training load',
    cancel: 'Cancelled',
    reduceIntensity: 'Reduced intensity',
    reduceVolume: 'Reduced volume',
    convertCrossTraining: 'Converted to cross-training',
    reviewing: 'Reviewing...',
    reviewApprove: 'Review and approve',
  },
  sv: {
    title: 'Skadeövervakning',
    description: 'Automatisk skadedetektering och träningsjustering',
    requiresReview: 'kräver granskning',
    activeInjuries: 'Aktiva skador',
    critical: 'kritiska',
    acwrWarnings: 'ACWR-varningar',
    autoModifiedWorkouts: 'Auto-modifierade pass',
    unreviewed: 'ogranskade',
    injuryWarnings: 'Skadevarningar',
    acwrMonitoring: 'ACWR-övervakning',
    modifiedWorkouts: 'Modifierade pass',
    loadingWarnings: 'Laddar varningar...',
    noActiveInjuryWarnings: 'Inga aktiva skadevarningar',
    normalValues: 'Alla atleeter rapporterar normala värden',
    noAcwrWarnings: 'Inga ACWR-varningar',
    safeTrainingLoad: 'Träningsbelastningen är inom säkra zoner för alla atleeter',
    noModifiedWorkouts: 'Inga modifierade pass',
    noAutomaticAdjustments: 'Inga automatiska träningsjusteringar har gjorts',
    painLevel: 'Smärtnivå',
    workoutsModified: 'Pass modifierade',
    countSuffix: 'st',
    estimatedRecovery: 'Beräknad återhämtning',
    weeks: 'veckor',
    rehabPhase: 'Rehab-fas',
    phase: 'Fas',
    viewAthlete: 'Visa atleet',
    resolving: 'Löser...',
    markResolved: 'Markera som löst',
    criticalRisk: 'Kritisk risk',
    highRisk: 'Hög risk',
    moderateRisk: 'Måttlig risk',
    recommendedAction: 'Rekommenderad åtgärd:',
    viewTrainingLoad: 'Visa träningsbelastning',
    cancel: 'Avbokad',
    reduceIntensity: 'Reducerad intensitet',
    reduceVolume: 'Reducerad volym',
    convertCrossTraining: 'Konverterad till kompletterande träning',
    reviewing: 'Granskar...',
    reviewApprove: 'Granska och godkänn',
  },
}

const fetcher = (url: string) => fetch(url).then(r => r.json())

export function InjuryAlertCenter() {
  const locale: AppLocale = useLocale() === 'sv' ? 'sv' : 'en'
  const copy = labels[locale]
  const [activeTab, setActiveTab] = useState('alerts')

  const { data: alertsData, error: alertsError, mutate: mutateAlerts } = useSWR(
    '/api/injury/alerts',
    fetcher,
    { refreshInterval: 30000 } // Refresh every 30 seconds
  )

  const { data: acwrData, error: acwrError } = useSWR(
    '/api/training-load/warnings',
    fetcher,
    { refreshInterval: 60000 } // Refresh every minute
  )

  const { data: modificationsData, error: modificationsError, mutate: mutateModifications } = useSWR(
    '/api/workouts/modifications?unreviewed=true',
    fetcher,
    { refreshInterval: 30000 }
  )

  const isLoading = !alertsData && !alertsError
  const hasAlerts = alertsData?.alerts?.length > 0
  const hasACWRWarnings = acwrData?.warnings?.length > 0
  const hasModifications = modificationsData?.modifications?.length > 0

  const totalUnreviewed =
    (alertsData?.alerts?.filter((a: InjuryAlert) => a.status === 'ACTIVE').length || 0) +
    (modificationsData?.modifications?.filter((m: ModifiedWorkout) => !m.reviewed).length || 0)

  return (
    <div className="space-y-6">
      {/* Header with Summary Stats */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight flex items-center gap-1.5">{copy.title} <InfoTooltip conceptKey="coachAlerts" /></h2>
          <p className="text-muted-foreground">
            {copy.description}
          </p>
        </div>

        {totalUnreviewed > 0 && (
          <Badge variant="destructive" className="text-lg px-4 py-2">
            {totalUnreviewed} {copy.requiresReview}
          </Badge>
        )}
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{copy.activeInjuries}</CardTitle>
            <AlertTriangle className="h-4 w-4 text-destructive" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {alertsData?.alerts?.filter((a: InjuryAlert) => a.status === 'ACTIVE').length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {alertsData?.alerts?.filter((a: InjuryAlert) => a.urgency === 'CRITICAL').length || 0}{' '}
              {copy.critical}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{copy.acwrWarnings}</CardTitle>
            <TrendingUp className="h-4 w-4 text-amber-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {acwrData?.warnings?.length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {acwrData?.warnings?.filter((w: ACWRWarning) => w.risk === 'CRITICAL').length || 0}{' '}
              {copy.critical}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{copy.autoModifiedWorkouts}</CardTitle>
            <Activity className="h-4 w-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {modificationsData?.modifications?.length || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              {modificationsData?.modifications?.filter((m: ModifiedWorkout) => !m.reviewed).length || 0}{' '}
              {copy.unreviewed}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Tabs for Different Alert Types */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="alerts" className="relative">
            {copy.injuryWarnings}
            {hasAlerts && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-destructive rounded-full" />
            )}
          </TabsTrigger>
          <TabsTrigger value="acwr" className="relative">
            {copy.acwrMonitoring}
            {hasACWRWarnings && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-amber-500 rounded-full" />
            )}
          </TabsTrigger>
          <TabsTrigger value="modifications" className="relative">
            {copy.modifiedWorkouts}
            {hasModifications && (
              <span className="absolute -top-1 -right-1 h-3 w-3 bg-blue-500 rounded-full" />
            )}
          </TabsTrigger>
        </TabsList>

        {/* Active Injury Alerts Tab */}
        <TabsContent value="alerts" className="space-y-4">
          {isLoading ? (
            <Card>
              <CardContent className="pt-6">
                <p className="text-center text-muted-foreground">{copy.loadingWarnings}</p>
              </CardContent>
            </Card>
          ) : !hasAlerts ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-emerald-500" />
                  <p className="text-lg font-medium">{copy.noActiveInjuryWarnings}</p>
                  <p className="text-sm text-muted-foreground">
                    {copy.normalValues}
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {alertsData.alerts
                .sort((a: InjuryAlert, b: InjuryAlert) => {
                  const urgencyOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 }
                  return urgencyOrder[a.urgency] - urgencyOrder[b.urgency]
                })
                .map((alert: InjuryAlert) => (
                  <InjuryAlertCard key={alert.id} alert={alert} onResolve={() => mutateAlerts()} />
                ))}
            </div>
          )}
        </TabsContent>

        {/* ACWR Warnings Tab */}
        <TabsContent value="acwr" className="space-y-4">
          {!hasACWRWarnings ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-emerald-500" />
                  <p className="text-lg font-medium">{copy.noAcwrWarnings}</p>
                  <p className="text-sm text-muted-foreground">
                    {copy.safeTrainingLoad}
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {acwrData.warnings
                .sort((a: ACWRWarning, b: ACWRWarning) => {
                  const riskOrder = { CRITICAL: 0, DANGER: 1, CAUTION: 2 }
                  return riskOrder[a.risk] - riskOrder[b.risk]
                })
                .map((warning: ACWRWarning) => (
                  <ACWRWarningCard key={warning.id} warning={warning} />
                ))}
            </div>
          )}
        </TabsContent>

        {/* Modified Workouts Tab */}
        <TabsContent value="modifications" className="space-y-4">
          {!hasModifications ? (
            <Card>
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center gap-2 py-8">
                  <CheckCircle2 className="h-12 w-12 text-emerald-500" />
                  <p className="text-lg font-medium">{copy.noModifiedWorkouts}</p>
                  <p className="text-sm text-muted-foreground">
                    {copy.noAutomaticAdjustments}
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {modificationsData.modifications.map((modification: ModifiedWorkout) => (
                <ModifiedWorkoutCard
                  key={modification.id}
                  modification={modification}
                  onReview={() => mutateModifications()}
                />
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  )
}

/**
 * Individual Injury Alert Card
 */
function InjuryAlertCard({
  alert,
  onResolve,
}: {
  alert: InjuryAlert
  onResolve: () => void
}) {
  const locale: AppLocale = useLocale() === 'sv' ? 'sv' : 'en'
  const copy = labels[locale]
  const dateLocale = locale === 'sv' ? sv : enUS
  const basePath = useBasePath()
  const [isResolving, setIsResolving] = useState(false)

  const urgencyColors = {
    CRITICAL: 'bg-red-500',
    HIGH: 'bg-orange-500',
    MEDIUM: 'bg-amber-500',
    LOW: 'bg-blue-500',
  }

  const handleResolve = async () => {
    setIsResolving(true)
    try {
      await fetch(`/api/injury/alerts/${alert.id}/resolve`, {
        method: 'PUT',
      })
      onResolve()
    } catch (error) {
      console.error('Error resolving alert:', error)
    } finally {
      setIsResolving(false)
    }
  }

  return (
    <Card className="border-l-4" style={{ borderLeftColor: urgencyColors[alert.urgency] }}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-lg">{alert.clientName}</CardTitle>
              <Badge variant={alert.urgency === 'CRITICAL' ? 'destructive' : 'default'}>
                {alert.urgency}
              </Badge>
              <Badge variant="outline">{alert.status}</Badge>
            </div>
            <CardDescription>
              {alert.injuryType.replace(/_/g, ' ')} · {copy.painLevel} {alert.painLevel}/10
            </CardDescription>
          </div>

          <div className="text-right text-sm text-muted-foreground">
            <div className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatDistanceToNow(new Date(alert.detectedAt), {
                addSuffix: true,
                locale: dateLocale,
              })}
            </div>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="grid grid-cols-3 gap-4 text-sm">
          <div>
            <p className="text-muted-foreground">{copy.workoutsModified}</p>
            <p className="font-medium">{alert.workoutsModified} {copy.countSuffix}</p>
          </div>
          <div>
            <p className="text-muted-foreground">{copy.estimatedRecovery}</p>
            <p className="font-medium">{alert.estimatedReturnWeeks} {copy.weeks}</p>
          </div>
          {alert.phase && (
            <div>
              <p className="text-muted-foreground">{copy.rehabPhase}</p>
              <p className="font-medium">{copy.phase} {alert.phase}/5</p>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between pt-2 border-t">
          <Button variant="outline" size="sm" asChild>
            <a href={`${basePath}/coach/clients/${alert.clientId}`}>
              <User className="mr-2 h-4 w-4" />
              {copy.viewAthlete}
            </a>
          </Button>

          {alert.status === 'ACTIVE' && (
            <Button
              variant="secondary"
              size="sm"
              onClick={handleResolve}
              disabled={isResolving}
            >
              <CheckCircle2 className="mr-2 h-4 w-4" />
              {isResolving ? copy.resolving : copy.markResolved}
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  )
}

/**
 * ACWR Warning Card
 */
function ACWRWarningCard({ warning }: { warning: ACWRWarning }) {
  const locale: AppLocale = useLocale() === 'sv' ? 'sv' : 'en'
  const copy = labels[locale]
  const basePath = useBasePath()
  const riskColors = {
    CRITICAL: 'destructive',
    DANGER: 'default',
    CAUTION: 'secondary',
  }

  const riskLabels = {
    CRITICAL: copy.criticalRisk,
    DANGER: copy.highRisk,
    CAUTION: copy.moderateRisk,
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-lg">{warning.clientName}</CardTitle>
              <Badge variant={riskColors[warning.risk] as any}>
                {riskLabels[warning.risk]}
              </Badge>
            </div>
            <CardDescription>ACWR: {warning.acwr.toFixed(2)}</CardDescription>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <Alert>
          <AlertDescription>
            <p className="font-medium mb-1">{copy.recommendedAction}</p>
            <p className="text-sm">{warning.recommendedAction}</p>
          </AlertDescription>
        </Alert>

        <Button variant="outline" size="sm" asChild className="w-full">
          <a href={`${basePath}/coach/clients/${warning.clientId}/monitoring`}>
            <TrendingUp className="mr-2 h-4 w-4" />
            {copy.viewTrainingLoad}
          </a>
        </Button>
      </CardContent>
    </Card>
  )
}

/**
 * Modified Workout Card
 */
function ModifiedWorkoutCard({
  modification,
  onReview,
}: {
  modification: ModifiedWorkout
  onReview: () => void
}) {
  const locale: AppLocale = useLocale() === 'sv' ? 'sv' : 'en'
  const copy = labels[locale]
  const dateLocale = locale === 'sv' ? 'sv-SE' : 'en-US'
  const [isReviewing, setIsReviewing] = useState(false)

  const actionLabels = {
    CANCEL: copy.cancel,
    REDUCE_INTENSITY: copy.reduceIntensity,
    REDUCE_VOLUME: copy.reduceVolume,
    CONVERT_TO_CROSS_TRAINING: copy.convertCrossTraining,
  }

  const actionColors = {
    CANCEL: 'destructive',
    REDUCE_INTENSITY: 'default',
    REDUCE_VOLUME: 'default',
    CONVERT_TO_CROSS_TRAINING: 'secondary',
  }

  const handleReview = async () => {
    setIsReviewing(true)
    try {
      await fetch(`/api/workouts/modifications/${modification.id}/review`, {
        method: 'PUT',
      })
      onReview()
    } catch (error) {
      console.error('Error reviewing modification:', error)
    } finally {
      setIsReviewing(false)
    }
  }

  return (
    <Card className={!modification.reviewed ? 'border-blue-200 bg-blue-50/50' : ''}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <CardTitle className="text-base">{modification.clientName}</CardTitle>
              {modification.autoGenerated && (
                <Badge variant="outline" className="text-xs">
                  Auto
                </Badge>
              )}
            </div>
            <CardDescription>
              {new Date(modification.workoutDate).toLocaleDateString(dateLocale, {
                weekday: 'long',
                day: 'numeric',
                month: 'long',
              })}
            </CardDescription>
          </div>

          <Badge variant={actionColors[modification.action] as any}>
            {actionLabels[modification.action]}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="flex items-center gap-2 text-sm">
          <span className="font-medium">{modification.originalType}</span>
          <ArrowRight className="h-4 w-4 text-muted-foreground" />
          <span className="text-muted-foreground">{actionLabels[modification.action]}</span>
        </div>

        <Alert>
          <AlertDescription className="text-sm">{modification.reasoning}</AlertDescription>
        </Alert>

        {!modification.reviewed && (
          <Button
            variant="default"
            size="sm"
            onClick={handleReview}
            disabled={isReviewing}
            className="w-full"
          >
            <CheckCircle2 className="mr-2 h-4 w-4" />
            {isReviewing ? copy.reviewing : copy.reviewApprove}
          </Button>
        )}
      </CardContent>
    </Card>
  )
}
