'use client'

/**
 * AutoGenerateDialog
 *
 * Dialog for coaches to auto-generate strength sessions based on
 * athlete profile, goals, phase, and equipment.
 */

import { useState } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import {
  Wand2,
  Loader2,
  Dumbbell,
  Zap,
  Shield,
  TrendingUp,
  CheckCircle2,
  Flame,
  Target,
  Sparkles,
} from 'lucide-react'
import { toast } from 'sonner'

const GOALS = [
  { value: 'strength', label: 'Generell Styrka', labelSv: 'Generell Styrka', icon: Dumbbell },
  { value: 'power', label: 'Power/Explosivitet', labelSv: 'Kraft & Explosivitet', icon: Zap },
  { value: 'injury-prevention', label: 'Injury Prevention', labelSv: 'Skadeförebyggande', icon: Shield },
  { value: 'running-economy', label: 'Running Economy', labelSv: 'Löpekonomi', icon: TrendingUp },
] as const

const PHASES = [
  { value: 'ANATOMICAL_ADAPTATION', label: 'Anatomisk Anpassning', description: 'Grundläggande (12-20 reps)' },
  { value: 'MAXIMUM_STRENGTH', label: 'Maxstyrka', description: 'Tung (3-6 reps)' },
  { value: 'POWER', label: 'Power', description: 'Explosiv (4-6 reps)' },
  { value: 'MAINTENANCE', label: 'Underhåll', description: 'Minimal (3-5 reps)' },
  { value: 'TAPER', label: 'Taper', description: 'Reducerad (3-5 reps)' },
] as const

const LEVELS = [
  { value: 'BEGINNER', label: 'Nybörjare' },
  { value: 'INTERMEDIATE', label: 'Mellan' },
  { value: 'ADVANCED', label: 'Avancerad' },
  { value: 'ELITE', label: 'Elit' },
] as const

const EQUIPMENT_OPTIONS = [
  { value: 'barbell', label: 'Skivstång' },
  { value: 'dumbbell', label: 'Hantlar' },
  { value: 'kettlebell', label: 'Kettlebell' },
  { value: 'bodyweight', label: 'Kroppsvikt' },
  { value: 'cable', label: 'Kablar' },
  { value: 'machine', label: 'Maskiner' },
  { value: 'bands', label: 'Gummiband' },
  { value: 'box', label: 'Plyo-box' },
]

interface GeneratedSession {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: Array<{
    type: string
    exercises: Array<{
      exerciseId: string
      exerciseName: string
      sets: number
      reps: number | string
      weight?: number
      restSeconds?: number
      tempo?: string
      notes?: string
    }>
    notes?: string
    duration?: number
  }>
  totalExercises: number
  totalSets: number
}

interface AutoGenerateDialogProps {
  clientId?: string
  onGenerated: (session: GeneratedSession) => void
  trigger?: React.ReactNode
}

export function AutoGenerateDialog({
  clientId,
  onGenerated,
  trigger,
}: AutoGenerateDialogProps) {
  const [open, setOpen] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [generated, setGenerated] = useState(false)

  // Form state
  const [goal, setGoal] = useState<typeof GOALS[number]['value']>('strength')
  const [phase, setPhase] = useState<typeof PHASES[number]['value']>('ANATOMICAL_ADAPTATION')
  const [athleteLevel, setAthleteLevel] = useState<typeof LEVELS[number]['value']>('INTERMEDIATE')
  const [sessionsPerWeek, setSessionsPerWeek] = useState<1 | 2 | 3>(2)
  const [timePerSession, setTimePerSession] = useState(45)
  const [equipment, setEquipment] = useState<string[]>(['barbell', 'dumbbell', 'bodyweight'])
  const [includeWarmup, setIncludeWarmup] = useState(true)
  const [includeCore, setIncludeCore] = useState(true)
  const [includeCooldown, setIncludeCooldown] = useState(true)

  const toggleEquipment = (value: string) => {
    setEquipment((prev) =>
      prev.includes(value)
        ? prev.filter((e) => e !== value)
        : [...prev, value]
    )
  }

  const handleGenerate = async () => {
    if (equipment.length === 0) {
      toast.error('Välj minst en utrustningstyp')
      return
    }

    setIsGenerating(true)
    setGenerated(false)

    try {
      const response = await fetch('/api/strength-sessions/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientId,
          goal,
          phase,
          sessionsPerWeek,
          equipmentAvailable: equipment,
          timePerSession,
          athleteLevel,
          includeWarmup,
          includeCore,
          includeCooldown,
        }),
      })

      const result = await response.json()

      if (!response.ok) {
        throw new Error(result.error || 'Failed to generate')
      }

      setGenerated(true)

      // Transform the response to match the expected format
      const session: GeneratedSession = {
        name: result.data.name,
        description: result.data.description,
        phase: result.data.phase,
        estimatedDuration: result.data.estimatedDuration,
        sections: result.data.sections,
        totalExercises: result.data.totalExercises,
        totalSets: result.data.totalSets,
      }

      toast.success('Pass genererat!', {
        description: `${session.totalExercises} övningar, ${session.totalSets} set`,
      })

      // Small delay to show success state
      setTimeout(() => {
        onGenerated(session)
        setOpen(false)
        setGenerated(false)
      }, 800)
    } catch (error) {
      console.error('Generation error:', error)
      toast.error('Kunde inte generera pass', {
        description: error instanceof Error ? error.message : 'Ett fel uppstod',
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const selectedGoal = GOALS.find((g) => g.value === goal)
  const GoalIcon = selectedGoal?.icon || Dumbbell

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline">
            <Wand2 className="h-4 w-4 mr-2" />
            Auto-generera
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[550px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5 text-primary" />
            Auto-generera styrkepass
          </DialogTitle>
          <DialogDescription>
            Skapa ett anpassat styrkepass baserat på mål, fas och utrustning.
          </DialogDescription>
        </DialogHeader>

        {generated ? (
          <div className="py-12 text-center">
            <CheckCircle2 className="h-16 w-16 text-green-500 mx-auto mb-4" />
            <p className="text-lg font-medium">Pass genererat!</p>
            <p className="text-sm text-muted-foreground mt-1">
              Öppnar i byggaren...
            </p>
          </div>
        ) : (
          <div className="space-y-6 py-4">
            {/* Goal Selection */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">Träningsmål</Label>
              <div className="grid grid-cols-2 gap-2">
                {GOALS.map((g) => {
                  const Icon = g.icon
                  const isSelected = goal === g.value
                  return (
                    <Button
                      key={g.value}
                      type="button"
                      variant={isSelected ? 'default' : 'outline'}
                      className="h-auto py-3 justify-start"
                      onClick={() => setGoal(g.value)}
                    >
                      <Icon className="h-4 w-4 mr-2" />
                      {g.labelSv}
                    </Button>
                  )
                })}
              </div>
            </div>

            {/* Phase Selection */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">Träningsfas</Label>
              <Select value={phase} onValueChange={(v: typeof phase) => setPhase(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {PHASES.map((p) => (
                    <SelectItem key={p.value} value={p.value}>
                      <div className="flex flex-col">
                        <span>{p.label}</span>
                        <span className="text-xs text-muted-foreground">{p.description}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Level Selection */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">Atletnivå</Label>
              <Select value={athleteLevel} onValueChange={(v: typeof athleteLevel) => setAthleteLevel(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {LEVELS.map((l) => (
                    <SelectItem key={l.value} value={l.value}>
                      {l.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Sessions per week */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">
                Pass per vecka: <span className="text-primary">{sessionsPerWeek}</span>
              </Label>
              <div className="flex gap-2">
                {([1, 2, 3] as const).map((n) => (
                  <Button
                    key={n}
                    type="button"
                    variant={sessionsPerWeek === n ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setSessionsPerWeek(n)}
                  >
                    {n}x
                  </Button>
                ))}
              </div>
            </div>

            {/* Time per session */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">
                Tid per pass: <span className="text-primary">{timePerSession} min</span>
              </Label>
              <Slider
                value={[timePerSession]}
                onValueChange={(v) => setTimePerSession(v[0])}
                min={20}
                max={90}
                step={5}
                className="w-full"
              />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>20 min</span>
                <span>90 min</span>
              </div>
            </div>

            {/* Equipment Selection */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">Tillgänglig utrustning</Label>
              <div className="flex flex-wrap gap-2">
                {EQUIPMENT_OPTIONS.map((eq) => (
                  <Badge
                    key={eq.value}
                    variant={equipment.includes(eq.value) ? 'default' : 'outline'}
                    className="cursor-pointer"
                    onClick={() => toggleEquipment(eq.value)}
                  >
                    {eq.label}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Section Toggles */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">Inkludera sektioner</Label>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Flame className="h-4 w-4 text-yellow-500" />
                    <span className="text-sm">Uppvärmning</span>
                  </div>
                  <Switch checked={includeWarmup} onCheckedChange={setIncludeWarmup} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Target className="h-4 w-4 text-purple-500" />
                    <span className="text-sm">Core-övningar</span>
                  </div>
                  <Switch checked={includeCore} onCheckedChange={setIncludeCore} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Nedvarvning</span>
                  </div>
                  <Switch checked={includeCooldown} onCheckedChange={setIncludeCooldown} />
                </div>
              </div>
            </div>
          </div>
        )}

        {!generated && (
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              Avbryt
            </Button>
            <Button onClick={handleGenerate} disabled={isGenerating || equipment.length === 0}>
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Genererar...
                </>
              ) : (
                <>
                  <GoalIcon className="h-4 w-4 mr-2" />
                  Generera pass
                </>
              )}
            </Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  )
}

export default AutoGenerateDialog
