'use client'

/**
 * AutoGenerateDialog
 *
 * Dialog for coaches to auto-generate strength sessions based on
 * athlete profile, goals, phase, and equipment.
 */

import { useState, useEffect } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import {
  Wand2,
  Loader2,
  Dumbbell,
  Zap,
  Shield,
  TrendingUp,
  CheckCircle2,
  Flame,
  Target,
  Sparkles,
  User,
  AlertTriangle,
} from 'lucide-react'
import { toast } from 'sonner'
import { useLocale } from 'next-intl'

type AppLocale = 'en' | 'sv'

const copy = (locale: AppLocale, en: string, sv: string) => locale === 'sv' ? sv : en

const GOALS = [
  { value: 'strength', label: { en: 'General strength', sv: 'Generell Styrka' }, icon: Dumbbell },
  { value: 'power', label: { en: 'Power/Explosiveness', sv: 'Kraft & Explosivitet' }, icon: Zap },
  { value: 'injury-prevention', label: { en: 'Injury prevention', sv: 'Skadeförebyggande' }, icon: Shield },
  { value: 'running-economy', label: { en: 'Running economy', sv: 'Löpekonomi' }, icon: TrendingUp },
] as const

const PHASES = [
  { value: 'ANATOMICAL_ADAPTATION', label: { en: 'Anatomical adaptation', sv: 'Anatomisk Anpassning' }, description: { en: 'Foundational (12-20 reps)', sv: 'Grundläggande (12-20 reps)' } },
  { value: 'MAXIMUM_STRENGTH', label: { en: 'Maximum strength', sv: 'Maxstyrka' }, description: { en: 'Heavy (3-6 reps)', sv: 'Tung (3-6 reps)' } },
  { value: 'POWER', label: { en: 'Power', sv: 'Power' }, description: { en: 'Explosive (4-6 reps)', sv: 'Explosiv (4-6 reps)' } },
  { value: 'MAINTENANCE', label: { en: 'Maintenance', sv: 'Underhåll' }, description: { en: 'Minimal (3-5 reps)', sv: 'Minimal (3-5 reps)' } },
  { value: 'TAPER', label: { en: 'Taper', sv: 'Taper' }, description: { en: 'Reduced (3-5 reps)', sv: 'Reducerad (3-5 reps)' } },
] as const

const LEVELS = [
  { value: 'BEGINNER', label: { en: 'Beginner', sv: 'Nybörjare' } },
  { value: 'INTERMEDIATE', label: { en: 'Intermediate', sv: 'Mellan' } },
  { value: 'ADVANCED', label: { en: 'Advanced', sv: 'Avancerad' } },
  { value: 'ELITE', label: { en: 'Elite', sv: 'Elit' } },
] as const

const EQUIPMENT_OPTIONS = [
  { value: 'barbell', label: { en: 'Barbell', sv: 'Skivstång' } },
  { value: 'dumbbell', label: { en: 'Dumbbells', sv: 'Hantlar' } },
  { value: 'kettlebell', label: { en: 'Kettlebell', sv: 'Kettlebell' } },
  { value: 'bodyweight', label: { en: 'Bodyweight', sv: 'Kroppsvikt' } },
  { value: 'cable', label: { en: 'Cables', sv: 'Kablar' } },
  { value: 'machine', label: { en: 'Machines', sv: 'Maskiner' } },
  { value: 'bands', label: { en: 'Bands', sv: 'Gummiband' } },
  { value: 'box', label: { en: 'Plyo box', sv: 'Plyo-box' } },
]

interface GeneratedSession {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: Array<{
    type: string
    exercises: Array<{
      exerciseId: string
      exerciseName: string
      sets: number
      reps: number | string
      weight?: number
      restSeconds?: number
      tempo?: string
      notes?: string
    }>
    notes?: string
    duration?: number
  }>
  totalExercises: number
  totalSets: number
}

interface AutoGenerateDialogProps {
  clientId?: string
  onGenerated: (session: GeneratedSession) => void
  onWeeklyGenerated?: (sessions: GeneratedSession[], options?: { athleteId?: string; athleteName?: string; calendar?: { blockedDates: string[]; reducedDates: string[] } }) => void
  trigger?: React.ReactNode
}

interface AthleteOption {
  id: string
  name: string
  sport?: string | null
  hasRestrictions?: boolean
}

interface ClientApiOption {
  id: string
  name?: string
  firstName?: string
  lastName?: string
  sport?: string | null
}

interface GeneratedSessionApi {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: GeneratedSession['sections']
  totalExercises: number
  totalSets: number
}

export function AutoGenerateDialog({
  clientId,
  onGenerated,
  onWeeklyGenerated,
  trigger,
}: AutoGenerateDialogProps) {
  const locale: AppLocale = useLocale() === 'sv' ? 'sv' : 'en'
  const [open, setOpen] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [generated, setGenerated] = useState(false)

  // Athlete state
  const [athletes, setAthletes] = useState<AthleteOption[]>([])
  const [selectedAthleteId, setSelectedAthleteId] = useState<string>(clientId || 'none')
  const [athleteContext, setAthleteContext] = useState<{
    level?: string
    restrictions?: Array<{ type: string; bodyParts: string[]; severity: string }>
    recentPain?: Array<{ bodyPart: string; pain: number }>
    sport?: string
  } | null>(null)

  // Form state
  const [generateMode, setGenerateMode] = useState<'single' | 'weekly'>('single')
  const [weekStartDate, setWeekStartDate] = useState(() => {
    // Default to next Monday
    const now = new Date()
    const day = now.getDay()
    const daysUntilMonday = day === 0 ? 1 : 8 - day
    const nextMonday = new Date(now)
    nextMonday.setDate(now.getDate() + daysUntilMonday)
    return nextMonday.toISOString().split('T')[0]
  })
  const [goal, setGoal] = useState<typeof GOALS[number]['value']>('strength')
  const [phase, setPhase] = useState<typeof PHASES[number]['value']>('ANATOMICAL_ADAPTATION')
  const [athleteLevel, setAthleteLevel] = useState<typeof LEVELS[number]['value']>('INTERMEDIATE')
  const [sessionsPerWeek, setSessionsPerWeek] = useState<1 | 2 | 3>(2)
  const [timePerSession, setTimePerSession] = useState(45)
  const [equipment, setEquipment] = useState<string[]>(['barbell', 'dumbbell', 'bodyweight'])
  const [includeWarmup, setIncludeWarmup] = useState(true)
  const [includePrehab, setIncludePrehab] = useState(false)
  const [includeCore, setIncludeCore] = useState(true)
  const [includeCooldown, setIncludeCooldown] = useState(true)

  // Fetch athletes when dialog opens
  useEffect(() => {
    if (!open) return
    async function loadAthletes() {
      try {
        const res = await fetch('/api/clients')
        if (res.ok) {
          const data = await res.json()
          const rawClients: ClientApiOption[] = data.clients || data || []
          const list = rawClients.map((c) => ({
            id: c.id,
            name: c.name || `${c.firstName || ''} ${c.lastName || ''}`.trim() || copy(locale, 'Unnamed', 'Namnlös'),
            sport: c.sport,
            hasRestrictions: false,
          }))
          setAthletes(list)
        }
      } catch { /* non-critical */ }
    }
    void loadAthletes()
  }, [open, locale])

  // Fetch athlete context when athlete selected
  useEffect(() => {
    if (!selectedAthleteId || selectedAthleteId === 'none') {
      const timeout = window.setTimeout(() => setAthleteContext(null), 0)
      return () => window.clearTimeout(timeout)
    }
    async function loadContext() {
      try {
        const res = await fetch(`/api/strength-sessions/generate/context?clientId=${selectedAthleteId}`)
        if (res.ok) {
          const data = await res.json()
          setAthleteContext(data.data || null)
          // Auto-set level if available
          if (data.data?.level) {
            const levelMap: Record<string, typeof LEVELS[number]['value']> = {
              BEGINNER: 'BEGINNER',
              RECREATIONAL: 'BEGINNER',
              ADVANCED: 'ADVANCED',
              ELITE: 'ELITE',
            }
            setAthleteLevel(levelMap[data.data.level] || 'INTERMEDIATE')
          }
          if (
            data.data?.sport?.toLowerCase?.().includes('hockey') ||
            (data.data?.restrictions?.length ?? 0) > 0 ||
            (data.data?.recentPain?.length ?? 0) > 0
          ) {
            setIncludePrehab(true)
          }
        }
      } catch { /* non-critical */ }
    }
    void loadContext()
  }, [selectedAthleteId])

  const toggleEquipment = (value: string) => {
    setEquipment((prev) =>
      prev.includes(value)
        ? prev.filter((e) => e !== value)
        : [...prev, value]
    )
  }

  const handleGenerate = async () => {
    if (equipment.length === 0) {
      toast.error(copy(locale, 'Select at least one equipment type', 'Välj minst en utrustningstyp'))
      return
    }

    setIsGenerating(true)
    setGenerated(false)

    try {
      const resolvedClientId = (selectedAthleteId && selectedAthleteId !== 'none') ? selectedAthleteId : clientId || undefined

      const response = await fetch('/api/strength-sessions/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientId: resolvedClientId,
          goal,
          phase,
          sessionsPerWeek,
          equipmentAvailable: equipment,
          timePerSession,
          athleteLevel,
          includeWarmup,
          includePrehab,
          includeCore,
          includeCooldown,
          mode: generateMode,
          weekStartDate: generateMode === 'weekly' ? weekStartDate : undefined,
        }),
      })

      const result = await response.json()

      if (!response.ok) {
        throw new Error(result.error || 'Failed to generate')
      }

      setGenerated(true)

      if (generateMode === 'weekly' && Array.isArray(result.data)) {
        // Weekly program mode — multiple sessions
        const sessions: GeneratedSession[] = (result.data as GeneratedSessionApi[]).map((s) => ({
          name: s.name,
          description: s.description,
          phase: s.phase,
          estimatedDuration: s.estimatedDuration,
          sections: s.sections,
          totalExercises: s.totalExercises,
          totalSets: s.totalSets,
        }))

        const totalExercises = sessions.reduce((sum, s) => sum + s.totalExercises, 0)
        toast.success(copy(locale, `${sessions.length} sessions generated!`, `${sessions.length} pass genererade!`), {
          description: copy(locale, `${totalExercises} exercises total`, `Totalt ${totalExercises} övningar`),
        })

        setTimeout(() => {
          if (onWeeklyGenerated) {
            const selectedAthlete = athletes.find((a) => a.id === resolvedClientId)
            onWeeklyGenerated(sessions, {
              athleteId: resolvedClientId,
              athleteName: selectedAthlete?.name,
              calendar: result.calendar,
            })
          } else {
            // Fallback: load first session into single builder
            onGenerated(sessions[0])
          }
          setOpen(false)
          setGenerated(false)
        }, 800)
      } else {
        // Single session mode
        const session: GeneratedSession = {
          name: result.data.name,
          description: result.data.description,
          phase: result.data.phase,
          estimatedDuration: result.data.estimatedDuration,
          sections: result.data.sections,
          totalExercises: result.data.totalExercises,
          totalSets: result.data.totalSets,
        }

        toast.success(copy(locale, 'Session generated!', 'Pass genererat!'), {
          description: copy(locale, `${session.totalExercises} exercises, ${session.totalSets} sets`, `${session.totalExercises} övningar, ${session.totalSets} set`),
        })

        setTimeout(() => {
          onGenerated(session)
          setOpen(false)
          setGenerated(false)
        }, 800)
      }
    } catch (error) {
      console.error('Generation error:', error)
      toast.error(copy(locale, 'Could not generate session', 'Kunde inte generera pass'), {
        description: error instanceof Error ? error.message : copy(locale, 'An error occurred', 'Ett fel uppstod'),
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const selectedGoal = GOALS.find((g) => g.value === goal)
  const GoalIcon = selectedGoal?.icon || Dumbbell

  return (
    <Dialog open={open} onOpenChange={(v) => {
      setOpen(v)
      if (!v) {
        // Reset form on close
        setGenerated(false)
        setSelectedAthleteId(clientId || 'none')
        setAthleteContext(null)
        setGenerateMode('single')
        setGoal('strength')
        setPhase('ANATOMICAL_ADAPTATION')
        setAthleteLevel('INTERMEDIATE')
        setSessionsPerWeek(2)
        setTimePerSession(45)
        setEquipment(['barbell', 'dumbbell', 'bodyweight'])
        setIncludeWarmup(true)
        setIncludeCore(true)
        setIncludeCooldown(true)
      }
    }}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline">
            <Wand2 className="h-4 w-4 mr-2" />
            {copy(locale, 'Auto-generate', 'Auto-generera')}
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[550px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5 text-primary" />
            {copy(locale, 'Auto-generate strength session', 'Auto-generera styrkepass')}
          </DialogTitle>
          <DialogDescription>
            {copy(locale, 'Create a tailored strength session based on goal, phase, and equipment.', 'Skapa ett anpassat styrkepass baserat på mål, fas och utrustning.')}
          </DialogDescription>
        </DialogHeader>

        {generated ? (
          <div className="py-12 text-center">
            <CheckCircle2 className="h-16 w-16 text-emerald-500 mx-auto mb-4" />
            <p className="text-lg font-medium">{copy(locale, 'Session generated!', 'Pass genererat!')}</p>
            <p className="text-sm text-muted-foreground mt-1">
              {copy(locale, 'Opening in the builder...', 'Öppnar i byggaren...')}
            </p>
          </div>
        ) : (
          <div className="space-y-6 py-4">
            {/* Athlete Picker */}
            <div className="space-y-2">
              <Label className="text-sm font-medium flex items-center gap-2">
                <User className="h-4 w-4" />
                {copy(locale, 'Athlete (optional)', 'Atlet (valfritt)')}
              </Label>
              <Select value={selectedAthleteId} onValueChange={setSelectedAthleteId}>
                <SelectTrigger>
                  <SelectValue placeholder={copy(locale, 'Select athlete for tailored session...', 'Välj atlet för anpassat pass...')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">{copy(locale, 'No specific athlete', 'Ingen specifik atlet')}</SelectItem>
                  {athletes.map((a) => (
                    <SelectItem key={a.id} value={a.id}>
                      {a.name}{a.sport ? ` (${a.sport})` : ''}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {selectedAthleteId && selectedAthleteId !== 'none' && (
                <p className="text-xs text-muted-foreground">
                  {copy(locale, "The session adapts to the athlete's 1RM, injuries, and restrictions.", 'Passet anpassas efter atletens 1RM, skador och restriktioner.')}
                </p>
              )}
            </div>

            {/* Restriction warnings */}
            {athleteContext?.restrictions && athleteContext.restrictions.length > 0 && (
              <div className="rounded-md border border-amber-200 bg-amber-50 p-3 space-y-1">
                <div className="flex items-center gap-2 text-amber-800 text-sm font-medium">
                  <AlertTriangle className="h-4 w-4" />
                  {copy(locale, 'Active restrictions', 'Aktiva restriktioner')}
                </div>
                {athleteContext.restrictions.map((r, i) => (
                  <p key={i} className="text-xs text-amber-700">
                    {r.type.replace(/_/g, ' ')} — {r.bodyParts.join(', ')} ({r.severity.toLowerCase()})
                  </p>
                ))}
                <p className="text-xs text-amber-600 mt-1">
                  {copy(locale, 'Exercises that conflict with these restrictions are excluded automatically.', 'Övningar som strider mot dessa restriktioner exkluderas automatiskt.')}
                </p>
              </div>
            )}

            {/* Recent pain warnings */}
            {athleteContext?.recentPain && athleteContext.recentPain.length > 0 && (
              <div className="rounded-md border border-amber-200 bg-amber-50 p-3 space-y-1">
                <p className="text-xs text-amber-700 font-medium">{copy(locale, 'Recent pain reports:', 'Senaste smärtrapporter:')}</p>
                {athleteContext.recentPain.map((p, i) => (
                  <p key={i} className="text-xs text-amber-600">
                    {p.bodyPart}: {p.pain}/10
                  </p>
                ))}
              </div>
            )}

            {/* Goal Selection */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">{copy(locale, 'Training goal', 'Träningsmål')}</Label>
              <div className="grid grid-cols-2 gap-2">
                {GOALS.map((g) => {
                  const Icon = g.icon
                  const isSelected = goal === g.value
                  return (
                    <Button
                      key={g.value}
                      type="button"
                      variant={isSelected ? 'default' : 'outline'}
                      className="h-auto py-3 justify-start"
                      onClick={() => setGoal(g.value)}
                    >
                      <Icon className="h-4 w-4 mr-2" />
                      {g.label[locale]}
                    </Button>
                  )
                })}
              </div>
            </div>

            {/* Phase Selection */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">{copy(locale, 'Training phase', 'Träningsfas')}</Label>
              <Select value={phase} onValueChange={(v: typeof phase) => setPhase(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {PHASES.map((p) => (
                    <SelectItem key={p.value} value={p.value}>
                      <div className="flex flex-col">
                        <span>{p.label[locale]}</span>
                        <span className="text-xs text-muted-foreground">{p.description[locale]}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Level Selection */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">{copy(locale, 'Athlete level', 'Atletnivå')}</Label>
              <Select value={athleteLevel} onValueChange={(v: typeof athleteLevel) => setAthleteLevel(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {LEVELS.map((l) => (
                    <SelectItem key={l.value} value={l.value}>
                      {l.label[locale]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Generation mode */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">{copy(locale, 'Generation mode', 'Genereringsläge')}</Label>
              <div className="grid grid-cols-2 gap-2">
                <Button
                  type="button"
                  variant={generateMode === 'single' ? 'default' : 'outline'}
                  className="h-auto py-2.5"
                  onClick={() => setGenerateMode('single')}
                >
                  <Dumbbell className="h-4 w-4 mr-2" />
                  {copy(locale, 'Single session', 'Enskilt pass')}
                </Button>
                <Button
                  type="button"
                  variant={generateMode === 'weekly' ? 'default' : 'outline'}
                  className="h-auto py-2.5"
                  onClick={() => setGenerateMode('weekly')}
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  {copy(locale, 'Weekly program', 'Veckoprogram')}
                </Button>
              </div>
              {generateMode === 'weekly' && (
                <p className="text-xs text-muted-foreground">
                  {copy(locale, `Generates ${sessionsPerWeek} complementary sessions with varied focus (A/B/C).`, `Genererar ${sessionsPerWeek} kompletterande pass med varierad fokus (A/B/C).`)}
                </p>
              )}
            </div>

            {/* Week start date (weekly mode only) */}
            {generateMode === 'weekly' && (
              <div className="space-y-2">
                <Label className="text-sm font-medium">{copy(locale, 'Week starts', 'Vecka börjar')}</Label>
                <input
                  type="date"
                  value={weekStartDate}
                  onChange={(e) => setWeekStartDate(e.target.value)}
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                />
                {selectedAthleteId && selectedAthleteId !== 'none' && (
                  <p className="text-xs text-muted-foreground">
                    {copy(locale, 'The calendar is checked for blocked days.', 'Kalendern kontrolleras för blockerade dagar.')}
                  </p>
                )}
              </div>
            )}

            {/* Sessions per week */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">
                {copy(locale, 'Sessions per week', 'Pass per vecka')}: <span className="text-primary">{sessionsPerWeek}</span>
              </Label>
              <div className="flex gap-2">
                {([1, 2, 3] as const).map((n) => (
                  <Button
                    key={n}
                    type="button"
                    variant={sessionsPerWeek === n ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setSessionsPerWeek(n)}
                  >
                    {n}x
                  </Button>
                ))}
              </div>
            </div>

            {/* Time per session */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">
                {copy(locale, 'Time per session', 'Tid per pass')}: <span className="text-primary">{timePerSession} min</span>
              </Label>
              <Slider
                value={[timePerSession]}
                onValueChange={(v) => setTimePerSession(v[0])}
                min={20}
                max={90}
                step={5}
                className="w-full"
              />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>20 min</span>
                <span>90 min</span>
              </div>
            </div>

            {/* Equipment Selection */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">{copy(locale, 'Available equipment', 'Tillgänglig utrustning')}</Label>
              <div className="flex flex-wrap gap-2">
                {EQUIPMENT_OPTIONS.map((eq) => (
                  <Badge
                    key={eq.value}
                    variant={equipment.includes(eq.value) ? 'default' : 'outline'}
                    className="cursor-pointer"
                    onClick={() => toggleEquipment(eq.value)}
                  >
                    {eq.label[locale]}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Section Toggles */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">{copy(locale, 'Include sections', 'Inkludera sektioner')}</Label>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Flame className="h-4 w-4 text-amber-500" />
                    <span className="text-sm">{copy(locale, 'Warm-up', 'Uppvärmning')}</span>
                  </div>
                  <Switch checked={includeWarmup} onCheckedChange={setIncludeWarmup} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Target className="h-4 w-4 text-purple-500" />
                    <span className="text-sm">{copy(locale, 'Core exercises', 'Core-övningar')}</span>
                  </div>
                  <Switch checked={includeCore} onCheckedChange={setIncludeCore} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Shield className="h-4 w-4 text-teal-500" />
                    <span className="text-sm">{copy(locale, 'Stability / Prehab', 'Stabilitet / Prehab')}</span>
                  </div>
                  <Switch checked={includePrehab} onCheckedChange={setIncludePrehab} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-emerald-500" />
                    <span className="text-sm">{copy(locale, 'Cool-down', 'Nedvarvning')}</span>
                  </div>
                  <Switch checked={includeCooldown} onCheckedChange={setIncludeCooldown} />
                </div>
              </div>
            </div>
          </div>
        )}

        {!generated && (
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              {copy(locale, 'Cancel', 'Avbryt')}
            </Button>
            <Button onClick={handleGenerate} disabled={isGenerating || equipment.length === 0}>
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {copy(locale, 'Generating...', 'Genererar...')}
                </>
              ) : (
                <>
                  <GoalIcon className="h-4 w-4 mr-2" />
                  {generateMode === 'weekly' ? copy(locale, `Generate ${sessionsPerWeek} sessions`, `Generera ${sessionsPerWeek} pass`) : copy(locale, 'Generate session', 'Generera pass')}
                </>
              )}
            </Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  )
}

export default AutoGenerateDialog
