'use client'

import React, { useEffect, useState } from 'react'
import { useSearchParams, usePathname } from 'next/navigation'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Activity, Calendar, Library, Plus, FolderOpen, Wand2, CalendarPlus, CheckCircle2, Loader2, FileUp } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { toast } from 'sonner'
import dynamic from 'next/dynamic'
import { usePageContextOptional } from '@/components/ai-studio/PageContextProvider'
import { GlassCard, GlassCardContent, GlassCardHeader, GlassCardTitle, GlassCardDescription } from '@/components/ui/GlassCard'

const ExerciseLibraryBrowser = dynamic(
  () => import('@/components/coach/exercise-library/ExerciseLibraryBrowser').then(mod => mod.ExerciseLibraryBrowser),
  { ssr: false, loading: () => <div className="p-8 text-center text-muted-foreground">Laddar övningsbibliotek...</div> }
)
import { CustomExerciseCreator } from '@/components/coach/exercise-library/CustomExerciseCreator'
import { SessionBuilder } from './SessionBuilder'
import { SectionWorkoutBuilder } from './SectionWorkoutBuilder'
import { StrengthSessionLibrary } from './StrengthSessionLibrary'
import { AutoGenerateDialog } from './AutoGenerateDialog'
import type { StrengthSessionData } from '@/types'
import { CalendarAssignDialog } from '@/components/calendar/CalendarAssignDialog'
import { MuscleGroupDashboard } from '@/components/strength/MuscleGroupDashboard'
import { ImportWorkoutDialog } from '@/components/workouts/import/ImportWorkoutDialog'
import { toStrengthSessionData } from '@/components/workouts/import/converters'
import { TeamCalendarStudioContextBanner } from '@/components/coach/team-calendar/TeamCalendarStudioContextBanner'
import { useTeamCalendarWorkoutLink } from '@/lib/team-calendar/use-team-calendar-workout-link'

const ProgressionDashboard = dynamic(
  () => import('@/components/coach/progression/ProgressionDashboard').then(mod => mod.ProgressionDashboard),
  { ssr: false, loading: () => <div className="p-8 text-center text-muted-foreground">Laddar progression...</div> }
)

interface GeneratedSession {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: Array<{
    type: string
    exercises: Array<{
      exerciseId: string
      exerciseName: string
      sets: number
      reps: number | string
      weight?: number
      restSeconds?: number
      tempo?: string
      notes?: string
    }>
    notes?: string
    duration?: number
  }>
  totalExercises: number
  totalSets: number
  rationale?: string
}

interface StrengthStats {
  totalExercises: number
  exercisesAddedThisWeek: number
  activePrograms: number
  athletesWithPrograms: number
  complianceRate: number
  complianceChange: string
  prsThisWeek: number
  topPrExercises: string | null
}

interface StrengthDashboardProps {
  businessId?: string
}

export function StrengthDashboard({ businessId }: StrengthDashboardProps) {
  const pageCtx = usePageContextOptional()
  const searchParams = useSearchParams()
  const pathname = usePathname()
  const [showCreator, setShowCreator] = React.useState(false)
  const [showImporter, setShowImporter] = React.useState(false)
  const [activeTab, setActiveTab] = React.useState('builder')
  const [editSession, setEditSession] = React.useState<StrengthSessionData | null>(null)
  const [useSectionBuilder, setUseSectionBuilder] = React.useState(true) // Default to section builder
  const [stats, setStats] = useState<StrengthStats | null>(null)
  const [weeklySessionQueue, setWeeklySessionQueue] = useState<StrengthSessionData[]>([])
  const [currentWeeklyIndex, setCurrentWeeklyIndex] = useState(0)
  const [weeklyRationales, setWeeklyRationales] = useState<string[]>([])
  const [weeklySavedIds, setWeeklySavedIds] = useState<string[]>([])
  const [weeklyAthleteId, setWeeklyAthleteId] = useState<string | null>(null)
  const [weeklyAthleteName, setWeeklyAthleteName] = useState<string | null>(null)
  const [showWeeklyAssignDialog, setShowWeeklyAssignDialog] = useState(false)
  const teamCalendarLink = useTeamCalendarWorkoutLink('STRENGTH')

  // Progression tab state
  const [progressionAthletes, setProgressionAthletes] = useState<Array<{ id: string; name: string }>>([])
  const [progressionClientId, setProgressionClientId] = useState<string>('')

  // Calendar assignment flow
  const fromCalendar = searchParams.get('fromCalendar') === 'true'
  const calendarClientId = searchParams.get('clientId')
  const calendarDate = searchParams.get('date')
  const editSessionId = searchParams.get('editSessionId')
  const appliedEditSessionIdRef = React.useRef<string | null>(null)
  const [calendarAssignSessionId, setCalendarAssignSessionId] = useState<string | null>(null)

  // Extract businessSlug from pathname (e.g. /my-business/coach/strength)
  const businessSlug = React.useMemo(() => {
    if (!pathname) return undefined
    const match = pathname.match(/^\/([^/]+)\/coach\//)
    if (match && match[1] !== 'coach') return match[1]
    return undefined
  }, [pathname])

  useEffect(() => {
    if (!editSessionId || appliedEditSessionIdRef.current === editSessionId) return
    appliedEditSessionIdRef.current = editSessionId

    let cancelled = false
    fetch(`/api/strength-sessions/${editSessionId}`)
      .then(async (res) => {
        if (!res.ok) {
          const body = await res.json().catch(() => ({}))
          throw new Error(body.error || 'Kunde inte öppna styrkepasset')
        }
        return res.json()
      })
      .then((session: StrengthSessionData) => {
        if (cancelled) return
        setEditSession(session)
        setUseSectionBuilder(true)
        setActiveTab('builder')
      })
      .catch((error) => {
        if (cancelled) return
        toast.error('Kunde inte öppna passet', {
          description: error instanceof Error ? error.message : undefined,
        })
      })

    return () => {
      cancelled = true
    }
  }, [editSessionId])

  // Set rich page context for AI chat
  useEffect(() => {
    if (!stats) return
    pageCtx?.setPageContext({
      type: 'strength',
      title: 'Strength Studio',
      conceptKeys: ['oneRM', 'twoForTwo', 'strengthPhases', 'rpe'],
      data: {
        totalExercises: stats.totalExercises,
        exercisesAddedThisWeek: stats.exercisesAddedThisWeek,
        activePrograms: stats.activePrograms,
        athletesWithPrograms: stats.athletesWithPrograms,
        complianceRate: stats.complianceRate,
        prsThisWeek: stats.prsThisWeek,
        topPrExercises: stats.topPrExercises,
        capabilities: {
          autoGenerate: 'Kan auto-generera enskilda pass eller veckoprogram (A/B/C) med varierad pelarfokus',
          athleteAware: 'Generering anpassas efter atletens profil, restriktioner, smärta och kalender',
          exerciseLibrary: 'Övningsbibliotek med favoriter och mest använda',
          periodization: 'Anatomisk anpassning → Maxstyrka → Power → Underhåll → Taper',
          biomechanicalPillars: 'Posterior chain, Knee dominance, Unilateral, Foot/ankle, Anti-rotation/core, Upper body',
        },
      },
      summary: `Styrketräning: ${stats.totalExercises} övningar, ${stats.activePrograms} aktiva pass, ${stats.complianceRate}% genomförande, ${stats.prsThisWeek} PR denna vecka. Auto-generering stödjer enskilda pass och veckoprogram med atletmedveten restriktionsfiltrering.`,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stats])

  // Fetch stats on mount
  useEffect(() => {
    async function fetchStats() {
      try {
        // Use business-scoped API if businessId is provided
        const url = businessId
          ? `/api/business/${businessId}/strength/stats`
          : '/api/coach/strength/stats'
        const res = await fetch(url)
        if (res.ok) {
          const data = await res.json()
          setStats(data)
        }
      } catch (error) {
        console.error('Failed to fetch strength stats:', error)
      }
    }
    fetchStats()
    // Also fetch athletes for progression tab
    async function fetchAthletes() {
      try {
        const res = await fetch('/api/clients')
        if (res.ok) {
          const data = await res.json()
          const list = (data.clients || data || []).map((c: any) => ({
            id: c.id,
            name: c.name || `${c.firstName || ''} ${c.lastName || ''}`.trim() || 'Unnamed',
          }))
          setProgressionAthletes(list)
        }
      } catch { /* non-critical */ }
    }
    fetchAthletes()
  }, [businessId])

  // Handle auto-generated session
  const handleAutoGenerated = (session: GeneratedSession) => {
    // Convert generated session to editable format for SectionWorkoutBuilder
    const warmupSection = session.sections.find((s) => s.type === 'WARMUP')
    const mainSection = session.sections.find((s) => s.type === 'MAIN')
    const prehabSection = session.sections.find((s) => s.type === 'PREHAB')
    const coreSection = session.sections.find((s) => s.type === 'CORE')
    const cooldownSection = session.sections.find((s) => s.type === 'COOLDOWN')

    const editableSession: StrengthSessionData = {
      name: session.name,
      description: session.description,
      phase: session.phase,
      exercises: (mainSection?.exercises || []).map((e) => ({
        exerciseId: e.exerciseId,
        exerciseName: e.exerciseName,
        sets: e.sets,
        reps: typeof e.reps === 'number' ? e.reps : parseInt(e.reps as string) || 10,
        weight: e.weight,
        restSeconds: e.restSeconds,
        notes: e.notes,
      })),
      warmupData: warmupSection
        ? {
            notes: warmupSection.notes,
            duration: warmupSection.duration,
            exercises: warmupSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              notes: e.notes,
            })),
        }
        : undefined,
      prehabData: prehabSection
        ? {
            notes: prehabSection.notes,
            duration: prehabSection.duration,
            exercises: prehabSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              restSeconds: e.restSeconds,
              notes: e.notes,
            })),
          }
        : undefined,
      coreData: coreSection
        ? {
            notes: coreSection.notes,
            duration: coreSection.duration,
            exercises: coreSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              restSeconds: e.restSeconds,
              notes: e.notes,
            })),
          }
        : undefined,
      cooldownData: cooldownSection
        ? {
            notes: cooldownSection.notes,
            duration: cooldownSection.duration,
            exercises: cooldownSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets || 1,
              reps: e.reps || '30s',
              duration: typeof e.reps === 'number' ? e.reps : 30,
              notes: e.notes,
            })),
          }
        : undefined,
    }

    setEditSession(editableSession)
    setUseSectionBuilder(true)
    setActiveTab('builder')
  }

  // Handle weekly generated sessions (multiple)
  const handleWeeklyGenerated = (sessions: GeneratedSession[], options?: { athleteId?: string; athleteName?: string }) => {
    const converted = sessions.map((session) => {
      const warmupSection = session.sections.find((s) => s.type === 'WARMUP')
      const mainSection = session.sections.find((s) => s.type === 'MAIN')
      const prehabSection = session.sections.find((s) => s.type === 'PREHAB')
      const coreSection = session.sections.find((s) => s.type === 'CORE')
      const cooldownSection = session.sections.find((s) => s.type === 'COOLDOWN')

      const data: StrengthSessionData = {
        name: session.name,
        description: session.description,
        phase: session.phase,
        exercises: (mainSection?.exercises || []).map((e) => ({
          exerciseId: e.exerciseId,
          exerciseName: e.exerciseName,
          sets: e.sets,
          reps: typeof e.reps === 'number' ? e.reps : parseInt(e.reps as string) || 10,
          weight: e.weight,
          restSeconds: e.restSeconds,
          notes: e.notes,
        })),
        warmupData: warmupSection
          ? {
              notes: warmupSection.notes,
              duration: warmupSection.duration,
              exercises: warmupSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets,
                reps: e.reps,
                notes: e.notes,
              })),
          }
          : undefined,
        prehabData: prehabSection
          ? {
              notes: prehabSection.notes,
              duration: prehabSection.duration,
              exercises: prehabSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets,
                reps: e.reps,
                restSeconds: e.restSeconds,
                notes: e.notes,
              })),
            }
          : undefined,
        coreData: coreSection
          ? {
              notes: coreSection.notes,
              duration: coreSection.duration,
              exercises: coreSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets,
                reps: e.reps,
                restSeconds: e.restSeconds,
                notes: e.notes,
              })),
            }
          : undefined,
        cooldownData: cooldownSection
          ? {
              notes: cooldownSection.notes,
              duration: cooldownSection.duration,
              exercises: cooldownSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets || 1,
                reps: e.reps || '30s',
                duration: typeof e.reps === 'number' ? e.reps : 30,
                notes: e.notes,
              })),
            }
          : undefined,
      }
      return data
    })

    // Store rationales, athlete info, and reset saved IDs
    setWeeklyRationales(sessions.map((s) => s.rationale || ''))
    setWeeklySavedIds([])
    setWeeklyAthleteId(options?.athleteId || null)
    setWeeklyAthleteName(options?.athleteName || null)

    // Load first session into builder, store rest in queue
    setWeeklySessionQueue(converted)
    setCurrentWeeklyIndex(0)
    setEditSession(converted[0])
    setUseSectionBuilder(true)
    setActiveTab('builder')
  }

  // Navigate weekly session queue
  const handleNextWeeklySession = () => {
    const nextIndex = currentWeeklyIndex + 1
    if (nextIndex < weeklySessionQueue.length) {
      setCurrentWeeklyIndex(nextIndex)
      setEditSession(weeklySessionQueue[nextIndex])
    } else {
      // All sessions done
      setWeeklySessionQueue([])
      setCurrentWeeklyIndex(0)
      setEditSession(null)
    }
  }

  // Assign all weekly sessions to athlete
  const [assignStartDate, setAssignStartDate] = useState(() => {
    const now = new Date()
    const day = now.getDay()
    const daysUntilMonday = day === 0 ? 1 : 8 - day
    const next = new Date(now)
    next.setDate(now.getDate() + daysUntilMonday)
    return next.toISOString().split('T')[0]
  })
  const [isAssigning, setIsAssigning] = useState(false)

  const handleBatchAssign = async () => {
    if (!weeklyAthleteId || weeklySavedIds.length === 0) return

    setIsAssigning(true)
    try {
      const startDate = new Date(assignStartDate)
      let assignedCount = 0

      // Spread sessions across the week (e.g., Mon/Wed/Fri for 3 sessions)
      const dayOffsets = weeklySavedIds.length === 1 ? [0]
        : weeklySavedIds.length === 2 ? [0, 2] // Mon, Wed
        : [0, 2, 4] // Mon, Wed, Fri

      for (let i = 0; i < weeklySavedIds.length; i++) {
        const date = new Date(startDate)
        date.setDate(date.getDate() + (dayOffsets[i] || i * 2))

        const res = await fetch(`/api/strength-sessions/${weeklySavedIds[i]}/assign`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            athleteIds: [weeklyAthleteId],
            assignedDate: date.toISOString().split('T')[0],
            createCalendarEvent: true,
          }),
        })

        if (res.ok) assignedCount++
      }

      toast.success(`${assignedCount} pass tilldelade`, {
        description: `Tilldelat ${weeklyAthleteName} med start ${assignStartDate}`,
      })

      setShowWeeklyAssignDialog(false)
      cleanupWeeklyState()
      setActiveTab('sessions')
    } catch {
      toast.error('Kunde inte tilldela pass')
    } finally {
      setIsAssigning(false)
    }
  }

  const cleanupWeeklyState = () => {
    setWeeklySavedIds([])
    setWeeklyAthleteId(null)
    setWeeklyAthleteName(null)
    setWeeklyRationales([])
  }

  const handleExerciseCreated = (_exerciseId: string) => {
    setShowCreator(false)
    // Refresh stats to reflect the new exercise
    async function refreshStats() {
      try {
        const url = businessId
          ? `/api/business/${businessId}/strength/stats`
          : '/api/coach/strength/stats'
        const res = await fetch(url)
        if (res.ok) {
          setStats(await res.json())
        }
      } catch {}
    }
    refreshStats()
  }

  return (
    <div className="container mx-auto py-6 px-4 space-y-8">
      <TeamCalendarStudioContextBanner />

      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">Strength Studio</h1>
          <p className="text-muted-foreground mt-1 sm:mt-2 text-sm sm:text-base">
            Manage exercises, build sophisticated strength programs, and track athlete progression.
          </p>
        </div>
        <div className="flex gap-2 shrink-0">
          <Button
            variant="outline"
            size="sm"
            className="sm:size-default"
            onClick={() => setShowImporter(true)}
          >
            <FileUp className="mr-2 h-4 w-4" />
            Importera pass
          </Button>
          <AutoGenerateDialog
            onGenerated={handleAutoGenerated}
            onWeeklyGenerated={handleWeeklyGenerated}
            trigger={
              <Button variant="secondary" size="sm" className="sm:size-default text-foreground">
                <Wand2 className="mr-2 h-4 w-4" />
                Auto-generera
              </Button>
            }
          />
          <Button onClick={() => setShowCreator(true)} size="sm" className="sm:size-default">
            <Plus className="mr-2 h-4 w-4" />
            Ny Övning
          </Button>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList className="w-full justify-start overflow-x-auto bg-slate-900/40 dark:bg-slate-950/30 border border-white/5 p-1 rounded-xl gap-1">
          <TabsTrigger value="builder" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm data-[state=active]:bg-blue-500/10 data-[state=active]:text-blue-400 data-[state=active]:border-blue-500/30">
            <Calendar className="h-4 w-4" />
            <span className="hidden sm:inline">Skapa </span>Pass
          </TabsTrigger>
          <TabsTrigger value="library" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm data-[state=active]:bg-blue-500/10 data-[state=active]:text-blue-400 data-[state=active]:border-blue-500/30">
            <Library className="h-4 w-4" />
            Övningar
          </TabsTrigger>
          <TabsTrigger value="sessions" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm data-[state=active]:bg-blue-500/10 data-[state=active]:text-blue-400 data-[state=active]:border-blue-500/30">
            <FolderOpen className="h-4 w-4" />
            <span className="hidden sm:inline">Pass</span>bibliotek
          </TabsTrigger>
          <TabsTrigger value="progression" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm data-[state=active]:bg-blue-500/10 data-[state=active]:text-blue-400 data-[state=active]:border-blue-500/30">
            <Activity className="h-4 w-4" />
            Progression
          </TabsTrigger>
        </TabsList>

        <TabsContent value="library" className="space-y-4">
          <ExerciseLibraryBrowser mode="browse" />
        </TabsContent>

        <TabsContent value="sessions" className="space-y-4">
          <StrengthSessionLibrary
            onNewSession={() => {
              setEditSession(null)
              setActiveTab('builder')
            }}
            onEditSession={(session) => {
              setEditSession(session)
              setActiveTab('builder')
            }}
            businessId={businessId}
          />
        </TabsContent>

        <TabsContent value="builder">
          <div className="mb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 bg-white/5 dark:bg-slate-950/20 border border-white/5 p-3 rounded-xl backdrop-blur-sm shadow-md">
            <div className="flex items-center gap-2 sm:gap-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setUseSectionBuilder(true)}
                className={`text-xs transition-all duration-300 ${
                  useSectionBuilder
                    ? 'bg-blue-500/10 text-blue-400 border border-blue-500/30 shadow-[0_0_10px_rgba(59,130,246,0.15)]'
                    : 'text-slate-400 hover:text-white hover:bg-white/5 border border-transparent'
                }`}
              >
                Sektionsbyggare
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setUseSectionBuilder(false)}
                className={`text-xs transition-all duration-300 ${
                  !useSectionBuilder
                    ? 'bg-blue-500/10 text-blue-400 border border-blue-500/30 shadow-[0_0_10px_rgba(59,130,246,0.15)]'
                    : 'text-slate-400 hover:text-white hover:bg-white/5 border border-transparent'
                }`}
              >
                Enkel byggare
              </Button>
            </div>
            {useSectionBuilder && (
              <p className="text-xs sm:text-sm text-slate-400">
                Bygg pass med uppvärmning, huvudpass, core och nedvarvning
              </p>
            )}
          </div>

          {/* Weekly program banner */}
          {weeklySessionQueue.length > 1 && weeklySessionQueue.length > currentWeeklyIndex && (
            <GlassCard glow="blue" className="mb-4">
              <GlassCardContent className="p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-semibold text-white">
                      Veckoprogram — Pass {currentWeeklyIndex + 1} av {weeklySessionQueue.length}
                    </p>
                    <p className="text-xs text-slate-400">
                      Spara detta pass för att gå vidare till nästa.
                    </p>
                  </div>
                  <div className="flex items-center gap-1.5">
                    {weeklySessionQueue.map((_, i) => (
                      <div
                        key={i}
                        className={`h-2.5 w-2.5 rounded-full transition-all duration-300 ${
                          i < currentWeeklyIndex ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]' :
                          i === currentWeeklyIndex ? 'bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.5)]' : 'bg-white/20'
                        }`}
                      />
                    ))}
                  </div>
                </div>
                {weeklyRationales[currentWeeklyIndex] && (
                  <p className="text-xs text-slate-300 border-t border-white/10 pt-2 font-light">
                    {weeklyRationales[currentWeeklyIndex]}
                  </p>
                )}
              </GlassCardContent>
            </GlassCard>
          )}

          {useSectionBuilder ? (
            <SectionWorkoutBuilder
              initialData={editSession}
              onSaved={async (sessionId, sessionName) => {
                if (teamCalendarLink.fromTeamCalendar && sessionId) {
                  await teamCalendarLink.linkSavedWorkout(sessionId, sessionName)
                  setEditSession(null)
                  setActiveTab('sessions')
                } else if (fromCalendar && calendarClientId && calendarDate && sessionId) {
                  setCalendarAssignSessionId(sessionId)
                } else if (weeklySessionQueue.length > 0) {
                  // Track saved session ID
                  if (sessionId) {
                    setWeeklySavedIds((prev) => [...prev, sessionId])
                  }
                  if (currentWeeklyIndex < weeklySessionQueue.length - 1) {
                    // Move to next session in weekly queue
                    handleNextWeeklySession()
                  } else {
                    // All sessions saved
                    setEditSession(null)
                    setWeeklySessionQueue([])
                    setCurrentWeeklyIndex(0)
                    setWeeklyRationales([])
                    // If generated for a specific athlete, offer to assign
                    if (weeklyAthleteId && weeklySavedIds.length > 0) {
                      // Include the last saved session ID
                      const allIds = sessionId ? [...weeklySavedIds, sessionId] : weeklySavedIds
                      setWeeklySavedIds(allIds)
                      setShowWeeklyAssignDialog(true)
                    } else {
                      setActiveTab('sessions')
                    }
                  }
                } else {
                  setEditSession(null)
                  setActiveTab('sessions')
                }
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setWeeklySessionQueue([])
                setCurrentWeeklyIndex(0)
                setWeeklyRationales([])
                setWeeklySavedIds([])
                setWeeklyAthleteId(null)
                setActiveTab('sessions')
              } : undefined}
            />
          ) : (
            <SessionBuilder
              initialData={editSession}
              onSaved={async (sessionId, sessionName) => {
                if (teamCalendarLink.fromTeamCalendar && sessionId) {
                  await teamCalendarLink.linkSavedWorkout(sessionId, sessionName)
                }
                setEditSession(null)
                setActiveTab('sessions')
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setActiveTab('sessions')
              } : undefined}
            />
          )}
        </TabsContent>

        <TabsContent value="progression">
          <div className="space-y-6">
            {/* Athlete selector for progression */}
            <div className="flex flex-col sm:flex-row sm:items-end gap-4 bg-white/5 dark:bg-slate-950/20 border border-white/5 p-4 rounded-xl backdrop-blur-sm shadow-md">
              <div className="flex-1 max-w-xs">
                <Label className="text-sm font-medium mb-1.5 block text-slate-300">Välj atlet</Label>
                <select
                  value={progressionClientId}
                  onChange={(e) => setProgressionClientId(e.target.value)}
                  className="flex h-10 w-full rounded-md border border-white/10 bg-slate-950/50 backdrop-blur-sm px-3 py-2 text-sm text-slate-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/50"
                >
                  <option value="" className="bg-slate-950 text-slate-200">Välj en atlet...</option>
                  {progressionAthletes.map((a) => (
                    <option key={a.id} value={a.id} className="bg-slate-950 text-slate-200">{a.name}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Progression dashboard for selected athlete */}
            {progressionClientId ? (
              <ProgressionDashboard
                clientId={progressionClientId}
                clientName={progressionAthletes.find((a) => a.id === progressionClientId)?.name}
              />
            ) : (
              <MuscleGroupDashboard businessId={businessId} />
            )}
          </div>
        </TabsContent>
      </Tabs>

      {/* Calendar Assignment Dialog */}
      {calendarAssignSessionId && calendarClientId && calendarDate && (
        <CalendarAssignDialog
          open={!!calendarAssignSessionId}
          onOpenChange={(open) => {
            if (!open) setCalendarAssignSessionId(null)
          }}
          sessionType="strength"
          sessionId={calendarAssignSessionId}
          clientId={calendarClientId}
          date={calendarDate}
          businessSlug={businessSlug}
          businessId={businessId}
        />
      )}

      {/* Weekly Assign Dialog */}
      <Dialog open={showWeeklyAssignDialog} onOpenChange={(open) => {
        if (!open) {
          setShowWeeklyAssignDialog(false)
          cleanupWeeklyState()
          setActiveTab('sessions')
        }
      }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CalendarPlus className="h-5 w-5 text-primary" />
              Tilldela veckoprogram
            </DialogTitle>
            <DialogDescription>
              {weeklySavedIds.length} pass sparade. Tilldela till {weeklyAthleteName}?
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label className="text-sm font-medium">Vecka börjar</Label>
              <input
                type="date"
                value={assignStartDate}
                onChange={(e) => setAssignStartDate(e.target.value)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              />
            </div>

            <div className="rounded-md bg-muted/50 p-3 space-y-1">
              <p className="text-xs font-medium text-muted-foreground">Schema:</p>
              {weeklySavedIds.map((_, i) => {
                const dayOffsets = weeklySavedIds.length === 1 ? [0]
                  : weeklySavedIds.length === 2 ? [0, 2]
                  : [0, 2, 4]
                const date = new Date(assignStartDate)
                date.setDate(date.getDate() + (dayOffsets[i] || i * 2))
                const dayName = date.toLocaleDateString('sv-SE', { weekday: 'long' })
                const dateStr = date.toLocaleDateString('sv-SE', { day: 'numeric', month: 'short' })
                return (
                  <p key={i} className="text-sm">
                    Pass {String.fromCharCode(65 + i)} → <span className="font-medium capitalize">{dayName}</span> {dateStr}
                  </p>
                )
              })}
            </div>
          </div>

          <DialogFooter className="gap-2">
            <Button variant="secondary" className="text-foreground" onClick={() => {
              setShowWeeklyAssignDialog(false)
              cleanupWeeklyState()
              setActiveTab('sessions')
            }}>
              Hoppa över
            </Button>
            <Button onClick={handleBatchAssign} disabled={isAssigning}>
              {isAssigning ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Tilldelar...
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-4 w-4 mr-2" />
                  Tilldela {weeklySavedIds.length} pass
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Custom Exercise Creator Dialog */}
      <CustomExerciseCreator
        open={showCreator}
        onClose={() => setShowCreator(false)}
        onSuccess={handleExerciseCreated}
      />

      <ImportWorkoutDialog
        workoutType="STRENGTH"
        open={showImporter}
        onOpenChange={setShowImporter}
        onImported={({ workout, mappings }) => {
          if (workout.workoutType !== 'STRENGTH') return
          setEditSession(toStrengthSessionData(workout, mappings))
          setUseSectionBuilder(true)
          setActiveTab('builder')
          toast.success('Pass importerat — granska och spara i byggaren')
        }}
      />
    </div>
  )
}
