'use client'

import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dumbbell, Activity, Calendar, Library, Plus, FolderOpen, Wand2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import dynamic from 'next/dynamic'

const ExerciseLibraryBrowser = dynamic(
  () => import('@/components/coach/exercise-library/ExerciseLibraryBrowser').then(mod => mod.ExerciseLibraryBrowser),
  { ssr: false, loading: () => <div className="p-8 text-center text-muted-foreground">Laddar övningsbibliotek...</div> }
)
import { ExerciseCreator } from './ExerciseCreator'
import { SessionBuilder } from './SessionBuilder'
import { SectionWorkoutBuilder } from './SectionWorkoutBuilder'
import { StrengthSessionLibrary } from './StrengthSessionLibrary'
import { AutoGenerateDialog } from './AutoGenerateDialog'
import type { StrengthSessionData } from '@/types'

interface GeneratedSession {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: Array<{
    type: string
    exercises: Array<{
      exerciseId: string
      exerciseName: string
      sets: number
      reps: number | string
      weight?: number
      restSeconds?: number
      tempo?: string
      notes?: string
    }>
    notes?: string
    duration?: number
  }>
  totalExercises: number
  totalSets: number
}

export function StrengthDashboard() {
  const [showCreator, setShowCreator] = React.useState(false)
  const [activeTab, setActiveTab] = React.useState('library')
  const [editSession, setEditSession] = React.useState<StrengthSessionData | null>(null)
  const [useSectionBuilder, setUseSectionBuilder] = React.useState(true) // Default to section builder

  // Handle auto-generated session
  const handleAutoGenerated = (session: GeneratedSession) => {
    // Convert generated session to editable format for SectionWorkoutBuilder
    const warmupSection = session.sections.find((s) => s.type === 'WARMUP')
    const mainSection = session.sections.find((s) => s.type === 'MAIN')
    const coreSection = session.sections.find((s) => s.type === 'CORE')
    const cooldownSection = session.sections.find((s) => s.type === 'COOLDOWN')

    const editableSession: StrengthSessionData = {
      name: session.name,
      description: session.description,
      phase: session.phase,
      exercises: (mainSection?.exercises || []).map((e) => ({
        exerciseId: e.exerciseId,
        exerciseName: e.exerciseName,
        sets: e.sets,
        reps: typeof e.reps === 'number' ? e.reps : parseInt(e.reps as string) || 10,
        weight: e.weight,
        restSeconds: e.restSeconds,
        notes: e.notes,
      })),
      warmupData: warmupSection
        ? {
            notes: warmupSection.notes,
            duration: warmupSection.duration,
            exercises: warmupSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              notes: e.notes,
            })),
          }
        : undefined,
      coreData: coreSection
        ? {
            notes: coreSection.notes,
            duration: coreSection.duration,
            exercises: coreSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              restSeconds: e.restSeconds,
              notes: e.notes,
            })),
          }
        : undefined,
      cooldownData: cooldownSection
        ? {
            notes: cooldownSection.notes,
            duration: cooldownSection.duration,
            exercises: cooldownSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets || 1,
              reps: e.reps || '30s',
              duration: typeof e.reps === 'number' ? e.reps : 30,
              notes: e.notes,
            })),
          }
        : undefined,
    }

    setEditSession(editableSession)
    setUseSectionBuilder(true)
    setActiveTab('builder')
  }

  if (showCreator) {
    return (
      <div className="container mx-auto py-6">
        <Button 
          variant="ghost" 
          onClick={() => setShowCreator(false)}
          className="mb-4"
        >
          ← Back to Dashboard
        </Button>
        <ExerciseCreator onClose={() => setShowCreator(false)} />
      </div>
    )
  }

  return (
    <div className="container mx-auto py-6 space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Strength Studio</h1>
          <p className="text-muted-foreground mt-2">
            Manage exercises, build sophisticated strength programs, and track athlete progression.
          </p>
        </div>
        <div className="flex gap-2">
          <AutoGenerateDialog
            onGenerated={handleAutoGenerated}
            trigger={
              <Button variant="outline">
                <Wand2 className="mr-2 h-4 w-4" />
                Auto-generera
              </Button>
            }
          />
          <Button onClick={() => setShowCreator(true)}>
            <Plus className="mr-2 h-4 w-4" />
            New Exercise
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Exercises</CardTitle>
            <Dumbbell className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">24</div>
            <p className="text-xs text-muted-foreground">+2 added this week</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Programs</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">12</div>
            <p className="text-xs text-muted-foreground">Across 8 athletes</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Compliance Rate</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">85%</div>
            <p className="text-xs text-muted-foreground">+2.5% from last month</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">PRs set this week</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">7</div>
            <p className="text-xs text-muted-foreground">3 Squat, 4 Deadlift</p>
          </CardContent>
        </Card>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList>
          <TabsTrigger value="library" className="flex items-center gap-2">
            <Library className="h-4 w-4" />
            Övningar
          </TabsTrigger>
          <TabsTrigger value="sessions" className="flex items-center gap-2">
            <FolderOpen className="h-4 w-4" />
            Passbibliotek
          </TabsTrigger>
          <TabsTrigger value="builder" className="flex items-center gap-2">
            <Calendar className="h-4 w-4" />
            Skapa Pass
          </TabsTrigger>
          <TabsTrigger value="progression" className="flex items-center gap-2">
            <Activity className="h-4 w-4" />
            Progression
          </TabsTrigger>
        </TabsList>

        <TabsContent value="library" className="space-y-4">
          <ExerciseLibraryBrowser mode="browse" />
        </TabsContent>

        <TabsContent value="sessions" className="space-y-4">
          <StrengthSessionLibrary
            onNewSession={() => {
              setEditSession(null)
              setActiveTab('builder')
            }}
            onEditSession={(session) => {
              setEditSession(session)
              setActiveTab('builder')
            }}
          />
        </TabsContent>

        <TabsContent value="builder">
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button
                variant={useSectionBuilder ? 'default' : 'outline'}
                size="sm"
                onClick={() => setUseSectionBuilder(true)}
              >
                Sektionsbyggare
              </Button>
              <Button
                variant={!useSectionBuilder ? 'default' : 'outline'}
                size="sm"
                onClick={() => setUseSectionBuilder(false)}
              >
                Enkel byggare
              </Button>
            </div>
            {useSectionBuilder && (
              <p className="text-sm text-muted-foreground">
                Bygg pass med uppvärmning, huvudpass, core och nedvarvning
              </p>
            )}
          </div>

          {useSectionBuilder ? (
            <SectionWorkoutBuilder
              initialData={editSession}
              onSaved={() => {
                setEditSession(null)
                setActiveTab('sessions')
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setActiveTab('sessions')
              } : undefined}
            />
          ) : (
            <SessionBuilder
              initialData={editSession}
              onSaved={() => {
                setEditSession(null)
                setActiveTab('sessions')
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setActiveTab('sessions')
              } : undefined}
            />
          )}
        </TabsContent>

        <TabsContent value="progression">
           <Card>
            <CardHeader>
              <CardTitle>Progression Tracking</CardTitle>
              <CardDescription>View athlete 1RM trends and volume loads.</CardDescription>
            </CardHeader>
            <CardContent className="h-[400px] flex items-center justify-center border-dashed border-2 rounded-lg m-4">
              <p className="text-muted-foreground">Progression Charts Coming Soon</p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

