'use client'

import React, { useEffect, useState } from 'react'
import { useSearchParams, usePathname } from 'next/navigation'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Activity, Calendar, Library, Plus, FolderOpen, Wand2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import dynamic from 'next/dynamic'
import { usePageContextOptional } from '@/components/ai-studio/PageContextProvider'

const ExerciseLibraryBrowser = dynamic(
  () => import('@/components/coach/exercise-library/ExerciseLibraryBrowser').then(mod => mod.ExerciseLibraryBrowser),
  { ssr: false, loading: () => <div className="p-8 text-center text-muted-foreground">Laddar övningsbibliotek...</div> }
)
import { CustomExerciseCreator } from '@/components/coach/exercise-library/CustomExerciseCreator'
import { SessionBuilder } from './SessionBuilder'
import { SectionWorkoutBuilder } from './SectionWorkoutBuilder'
import { StrengthSessionLibrary } from './StrengthSessionLibrary'
import { AutoGenerateDialog } from './AutoGenerateDialog'
import type { StrengthSessionData } from '@/types'
import { CalendarAssignDialog } from '@/components/calendar/CalendarAssignDialog'
import { MuscleGroupDashboard } from '@/components/strength/MuscleGroupDashboard'

interface GeneratedSession {
  name: string
  description: string
  phase: string
  estimatedDuration: number
  sections: Array<{
    type: string
    exercises: Array<{
      exerciseId: string
      exerciseName: string
      sets: number
      reps: number | string
      weight?: number
      restSeconds?: number
      tempo?: string
      notes?: string
    }>
    notes?: string
    duration?: number
  }>
  totalExercises: number
  totalSets: number
}

interface StrengthStats {
  totalExercises: number
  exercisesAddedThisWeek: number
  activePrograms: number
  athletesWithPrograms: number
  complianceRate: number
  complianceChange: string
  prsThisWeek: number
  topPrExercises: string | null
}

interface StrengthDashboardProps {
  businessId?: string
}

export function StrengthDashboard({ businessId }: StrengthDashboardProps) {
  const pageCtx = usePageContextOptional()
  const searchParams = useSearchParams()
  const pathname = usePathname()
  const [showCreator, setShowCreator] = React.useState(false)
  const [activeTab, setActiveTab] = React.useState('builder')
  const [editSession, setEditSession] = React.useState<StrengthSessionData | null>(null)
  const [useSectionBuilder, setUseSectionBuilder] = React.useState(true) // Default to section builder
  const [stats, setStats] = useState<StrengthStats | null>(null)
  const [weeklySessionQueue, setWeeklySessionQueue] = useState<StrengthSessionData[]>([])
  const [currentWeeklyIndex, setCurrentWeeklyIndex] = useState(0)

  // Calendar assignment flow
  const fromCalendar = searchParams.get('fromCalendar') === 'true'
  const calendarClientId = searchParams.get('clientId')
  const calendarDate = searchParams.get('date')
  const [calendarAssignSessionId, setCalendarAssignSessionId] = useState<string | null>(null)

  // Extract businessSlug from pathname (e.g. /my-business/coach/strength)
  const businessSlug = React.useMemo(() => {
    if (!pathname) return undefined
    const match = pathname.match(/^\/([^/]+)\/coach\//)
    if (match && match[1] !== 'coach') return match[1]
    return undefined
  }, [pathname])

  // Set rich page context for AI chat
  useEffect(() => {
    if (!stats) return
    pageCtx?.setPageContext({
      type: 'strength',
      title: 'Strength Studio',
      conceptKeys: ['oneRM', 'twoForTwo', 'strengthPhases', 'rpe'],
      data: {
        totalExercises: stats.totalExercises,
        exercisesAddedThisWeek: stats.exercisesAddedThisWeek,
        activePrograms: stats.activePrograms,
        athletesWithPrograms: stats.athletesWithPrograms,
        complianceRate: stats.complianceRate,
        prsThisWeek: stats.prsThisWeek,
        topPrExercises: stats.topPrExercises,
      },
      summary: `Styrketräning: ${stats.totalExercises} övningar, ${stats.activePrograms} aktiva pass, ${stats.complianceRate}% genomförande, ${stats.prsThisWeek} PR denna vecka.`,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stats])

  // Fetch stats on mount
  useEffect(() => {
    async function fetchStats() {
      try {
        // Use business-scoped API if businessId is provided
        const url = businessId
          ? `/api/business/${businessId}/strength/stats`
          : '/api/coach/strength/stats'
        const res = await fetch(url)
        if (res.ok) {
          const data = await res.json()
          setStats(data)
        }
      } catch (error) {
        console.error('Failed to fetch strength stats:', error)
      }
    }
    fetchStats()
  }, [businessId])

  // Handle auto-generated session
  const handleAutoGenerated = (session: GeneratedSession) => {
    // Convert generated session to editable format for SectionWorkoutBuilder
    const warmupSection = session.sections.find((s) => s.type === 'WARMUP')
    const mainSection = session.sections.find((s) => s.type === 'MAIN')
    const coreSection = session.sections.find((s) => s.type === 'CORE')
    const cooldownSection = session.sections.find((s) => s.type === 'COOLDOWN')

    const editableSession: StrengthSessionData = {
      name: session.name,
      description: session.description,
      phase: session.phase,
      exercises: (mainSection?.exercises || []).map((e) => ({
        exerciseId: e.exerciseId,
        exerciseName: e.exerciseName,
        sets: e.sets,
        reps: typeof e.reps === 'number' ? e.reps : parseInt(e.reps as string) || 10,
        weight: e.weight,
        restSeconds: e.restSeconds,
        notes: e.notes,
      })),
      warmupData: warmupSection
        ? {
            notes: warmupSection.notes,
            duration: warmupSection.duration,
            exercises: warmupSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              notes: e.notes,
            })),
          }
        : undefined,
      coreData: coreSection
        ? {
            notes: coreSection.notes,
            duration: coreSection.duration,
            exercises: coreSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets,
              reps: e.reps,
              restSeconds: e.restSeconds,
              notes: e.notes,
            })),
          }
        : undefined,
      cooldownData: cooldownSection
        ? {
            notes: cooldownSection.notes,
            duration: cooldownSection.duration,
            exercises: cooldownSection.exercises.map((e) => ({
              exerciseId: e.exerciseId,
              exerciseName: e.exerciseName,
              sets: e.sets || 1,
              reps: e.reps || '30s',
              duration: typeof e.reps === 'number' ? e.reps : 30,
              notes: e.notes,
            })),
          }
        : undefined,
    }

    setEditSession(editableSession)
    setUseSectionBuilder(true)
    setActiveTab('builder')
  }

  // Handle weekly generated sessions (multiple)
  const handleWeeklyGenerated = (sessions: GeneratedSession[]) => {
    const converted = sessions.map((session) => {
      const warmupSection = session.sections.find((s) => s.type === 'WARMUP')
      const mainSection = session.sections.find((s) => s.type === 'MAIN')
      const coreSection = session.sections.find((s) => s.type === 'CORE')
      const cooldownSection = session.sections.find((s) => s.type === 'COOLDOWN')

      const data: StrengthSessionData = {
        name: session.name,
        description: session.description,
        phase: session.phase,
        exercises: (mainSection?.exercises || []).map((e) => ({
          exerciseId: e.exerciseId,
          exerciseName: e.exerciseName,
          sets: e.sets,
          reps: typeof e.reps === 'number' ? e.reps : parseInt(e.reps as string) || 10,
          weight: e.weight,
          restSeconds: e.restSeconds,
          notes: e.notes,
        })),
        warmupData: warmupSection
          ? {
              notes: warmupSection.notes,
              duration: warmupSection.duration,
              exercises: warmupSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets,
                reps: e.reps,
                notes: e.notes,
              })),
            }
          : undefined,
        coreData: coreSection
          ? {
              notes: coreSection.notes,
              duration: coreSection.duration,
              exercises: coreSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets,
                reps: e.reps,
                restSeconds: e.restSeconds,
                notes: e.notes,
              })),
            }
          : undefined,
        cooldownData: cooldownSection
          ? {
              notes: cooldownSection.notes,
              duration: cooldownSection.duration,
              exercises: cooldownSection.exercises.map((e) => ({
                exerciseId: e.exerciseId,
                exerciseName: e.exerciseName,
                sets: e.sets || 1,
                reps: e.reps || '30s',
                duration: typeof e.reps === 'number' ? e.reps : 30,
                notes: e.notes,
              })),
            }
          : undefined,
      }
      return data
    })

    // Load first session into builder, store rest in queue
    setWeeklySessionQueue(converted)
    setCurrentWeeklyIndex(0)
    setEditSession(converted[0])
    setUseSectionBuilder(true)
    setActiveTab('builder')
  }

  // Navigate weekly session queue
  const handleNextWeeklySession = () => {
    const nextIndex = currentWeeklyIndex + 1
    if (nextIndex < weeklySessionQueue.length) {
      setCurrentWeeklyIndex(nextIndex)
      setEditSession(weeklySessionQueue[nextIndex])
    } else {
      // All sessions done
      setWeeklySessionQueue([])
      setCurrentWeeklyIndex(0)
      setEditSession(null)
    }
  }

  const handleExerciseCreated = (_exerciseId: string) => {
    setShowCreator(false)
    // Refresh stats to reflect the new exercise
    async function refreshStats() {
      try {
        const url = businessId
          ? `/api/business/${businessId}/strength/stats`
          : '/api/coach/strength/stats'
        const res = await fetch(url)
        if (res.ok) {
          setStats(await res.json())
        }
      } catch {}
    }
    refreshStats()
  }

  return (
    <div className="container mx-auto py-6 px-4 space-y-8">
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">Strength Studio</h1>
          <p className="text-muted-foreground mt-1 sm:mt-2 text-sm sm:text-base">
            Manage exercises, build sophisticated strength programs, and track athlete progression.
          </p>
        </div>
        <div className="flex gap-2 shrink-0">
          <AutoGenerateDialog
            onGenerated={handleAutoGenerated}
            onWeeklyGenerated={handleWeeklyGenerated}
            trigger={
              <Button variant="outline" size="sm" className="sm:size-default">
                <Wand2 className="mr-2 h-4 w-4" />
                Auto-generera
              </Button>
            }
          />
          <Button onClick={() => setShowCreator(true)} size="sm" className="sm:size-default">
            <Plus className="mr-2 h-4 w-4" />
            Ny Övning
          </Button>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList className="w-full justify-start overflow-x-auto">
          <TabsTrigger value="builder" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm">
            <Calendar className="h-4 w-4" />
            <span className="hidden sm:inline">Skapa </span>Pass
          </TabsTrigger>
          <TabsTrigger value="library" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm">
            <Library className="h-4 w-4" />
            Övningar
          </TabsTrigger>
          <TabsTrigger value="sessions" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm">
            <FolderOpen className="h-4 w-4" />
            <span className="hidden sm:inline">Pass</span>bibliotek
          </TabsTrigger>
          <TabsTrigger value="progression" className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm">
            <Activity className="h-4 w-4" />
            Progression
          </TabsTrigger>
        </TabsList>

        <TabsContent value="library" className="space-y-4">
          <ExerciseLibraryBrowser mode="browse" />
        </TabsContent>

        <TabsContent value="sessions" className="space-y-4">
          <StrengthSessionLibrary
            onNewSession={() => {
              setEditSession(null)
              setActiveTab('builder')
            }}
            onEditSession={(session) => {
              setEditSession(session)
              setActiveTab('builder')
            }}
            businessId={businessId}
          />
        </TabsContent>

        <TabsContent value="builder">
          <div className="mb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <div className="flex items-center gap-2 sm:gap-4">
              <Button
                variant={useSectionBuilder ? 'default' : 'outline'}
                size="sm"
                onClick={() => setUseSectionBuilder(true)}
              >
                Sektionsbyggare
              </Button>
              <Button
                variant={!useSectionBuilder ? 'default' : 'outline'}
                size="sm"
                onClick={() => setUseSectionBuilder(false)}
              >
                Enkel byggare
              </Button>
            </div>
            {useSectionBuilder && (
              <p className="text-xs sm:text-sm text-muted-foreground">
                Bygg pass med uppvärmning, huvudpass, core och nedvarvning
              </p>
            )}
          </div>

          {/* Weekly program banner */}
          {weeklySessionQueue.length > 1 && (
            <div className="mb-4 rounded-lg border border-primary/20 bg-primary/5 p-3 flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">
                  Veckoprogram — Pass {currentWeeklyIndex + 1} av {weeklySessionQueue.length}
                </p>
                <p className="text-xs text-muted-foreground">
                  Spara detta pass för att gå vidare till nästa.
                </p>
              </div>
              <div className="flex items-center gap-1.5">
                {weeklySessionQueue.map((_, i) => (
                  <div
                    key={i}
                    className={`h-2 w-2 rounded-full ${
                      i < currentWeeklyIndex ? 'bg-green-500' :
                      i === currentWeeklyIndex ? 'bg-primary' : 'bg-muted-foreground/30'
                    }`}
                  />
                ))}
              </div>
            </div>
          )}

          {useSectionBuilder ? (
            <SectionWorkoutBuilder
              initialData={editSession}
              onSaved={(sessionId) => {
                if (fromCalendar && calendarClientId && calendarDate && sessionId) {
                  setCalendarAssignSessionId(sessionId)
                } else if (weeklySessionQueue.length > 1 && currentWeeklyIndex < weeklySessionQueue.length - 1) {
                  // Move to next session in weekly queue
                  handleNextWeeklySession()
                } else {
                  setEditSession(null)
                  setWeeklySessionQueue([])
                  setCurrentWeeklyIndex(0)
                  setActiveTab('sessions')
                }
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setWeeklySessionQueue([])
                setCurrentWeeklyIndex(0)
                setActiveTab('sessions')
              } : undefined}
            />
          ) : (
            <SessionBuilder
              initialData={editSession}
              onSaved={() => {
                setEditSession(null)
                setActiveTab('sessions')
              }}
              onCancel={editSession ? () => {
                setEditSession(null)
                setActiveTab('sessions')
              } : undefined}
            />
          )}
        </TabsContent>

        <TabsContent value="progression">
          <MuscleGroupDashboard businessId={businessId} />
        </TabsContent>
      </Tabs>

      {/* Calendar Assignment Dialog */}
      {calendarAssignSessionId && calendarClientId && calendarDate && (
        <CalendarAssignDialog
          open={!!calendarAssignSessionId}
          onOpenChange={(open) => {
            if (!open) setCalendarAssignSessionId(null)
          }}
          sessionType="strength"
          sessionId={calendarAssignSessionId}
          clientId={calendarClientId}
          date={calendarDate}
          businessSlug={businessSlug}
        />
      )}

      {/* Custom Exercise Creator Dialog */}
      <CustomExerciseCreator
        open={showCreator}
        onClose={() => setShowCreator(false)}
        onSuccess={handleExerciseCreated}
      />
    </div>
  )
}

