-- CreateTable
CREATE TABLE "ThresholdCalculation" (
    "id" TEXT NOT NULL,
    "testId" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "confidence" TEXT NOT NULL,
    "polynomialCoeffs" JSONB,
    "r2" DOUBLE PRECISION,
    "dmaxIntensity" DOUBLE PRECISION,
    "dmaxLactate" DOUBLE PRECISION,
    "dmaxHr" DOUBLE PRECISION,
    "lt1Intensity" DOUBLE PRECISION NOT NULL,
    "lt1Lactate" DOUBLE PRECISION NOT NULL,
    "lt1Hr" DOUBLE PRECISION NOT NULL,
    "lt1Method" TEXT NOT NULL,
    "lt2Intensity" DOUBLE PRECISION NOT NULL,
    "lt2Lactate" DOUBLE PRECISION NOT NULL,
    "lt2Hr" DOUBLE PRECISION NOT NULL,
    "lt2PercentVO2max" DOUBLE PRECISION,
    "testDate" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "warnings" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ThresholdCalculation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AthleteProfile" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "vo2maxPercentile" DOUBLE PRECISION,
    "lt2AsPercentVO2max" DOUBLE PRECISION,
    "hrvBaseline" DOUBLE PRECISION,
    "hrvStdDev" DOUBLE PRECISION,
    "hrvLastUpdated" TIMESTAMP(3),
    "rhrBaseline" DOUBLE PRECISION,
    "rhrLastUpdated" TIMESTAMP(3),
    "trainingZones" JSONB,
    "zonesLastUpdated" TIMESTAMP(3),
    "hasLactateMeter" BOOLEAN NOT NULL DEFAULT false,
    "hasHRVMonitor" BOOLEAN NOT NULL DEFAULT false,
    "hasPowerMeter" BOOLEAN NOT NULL DEFAULT false,
    "yearsRunning" INTEGER,
    "typicalWeeklyKm" DOUBLE PRECISION,
    "longestLongRun" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AthleteProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DailyMetrics" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "hrvRMSSD" DOUBLE PRECISION,
    "hrvQuality" TEXT,
    "hrvArtifactPercent" DOUBLE PRECISION,
    "hrvDuration" DOUBLE PRECISION,
    "hrvPosition" TEXT,
    "hrvStatus" TEXT,
    "hrvPercent" DOUBLE PRECISION,
    "hrvTrend" TEXT,
    "restingHR" DOUBLE PRECISION,
    "restingHRDev" DOUBLE PRECISION,
    "restingHRStatus" TEXT,
    "sleepQuality" INTEGER,
    "sleepHours" DOUBLE PRECISION,
    "muscleSoreness" INTEGER,
    "energyLevel" INTEGER,
    "mood" INTEGER,
    "stress" INTEGER,
    "injuryPain" INTEGER,
    "wellnessScore" DOUBLE PRECISION,
    "wellnessStatus" TEXT,
    "readinessScore" DOUBLE PRECISION,
    "readinessLevel" TEXT,
    "recommendedAction" TEXT,
    "factorScores" JSONB,
    "redFlags" JSONB,
    "yellowFlags" JSONB,
    "athleteNotes" TEXT,
    "coachNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DailyMetrics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrainingLoad" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "dailyLoad" DOUBLE PRECISION NOT NULL,
    "loadType" TEXT NOT NULL,
    "acuteLoad" DOUBLE PRECISION,
    "chronicLoad" DOUBLE PRECISION,
    "acwr" DOUBLE PRECISION,
    "acwrZone" TEXT,
    "injuryRisk" TEXT,
    "duration" DOUBLE PRECISION NOT NULL,
    "distance" DOUBLE PRECISION,
    "avgHR" DOUBLE PRECISION,
    "maxHR" DOUBLE PRECISION,
    "avgPace" DOUBLE PRECISION,
    "intensity" TEXT NOT NULL,
    "workoutType" TEXT,
    "workoutId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TrainingLoad_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrainingProgramEngine" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "methodology" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "totalWeeks" INTEGER NOT NULL,
    "currentWeek" INTEGER NOT NULL DEFAULT 1,
    "currentPhase" TEXT,
    "targetRaceDate" TIMESTAMP(3),
    "targetDistance" TEXT,
    "targetTime" TEXT,
    "periodization" JSONB NOT NULL,
    "weeklyPlans" JSONB NOT NULL,
    "methodologyConfig" JSONB,
    "generatedBy" TEXT NOT NULL,
    "generatedFrom" JSONB,
    "completedWeeks" INTEGER NOT NULL DEFAULT 0,
    "missedWorkouts" INTEGER NOT NULL DEFAULT 0,
    "modifiedWorkouts" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TrainingProgramEngine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WorkoutModification" (
    "id" TEXT NOT NULL,
    "workoutId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "decision" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "plannedType" TEXT NOT NULL,
    "plannedDuration" DOUBLE PRECISION NOT NULL,
    "plannedDistance" DOUBLE PRECISION,
    "plannedIntensity" TEXT NOT NULL,
    "plannedDetails" JSONB,
    "modifiedType" TEXT,
    "modifiedDuration" DOUBLE PRECISION,
    "modifiedDistance" DOUBLE PRECISION,
    "modifiedIntensity" TEXT,
    "modifiedDetails" JSONB,
    "readinessScore" DOUBLE PRECISION,
    "factors" JSONB NOT NULL,
    "reasoning" TEXT NOT NULL,
    "methodology" TEXT,
    "dailyMetricsId" TEXT,
    "acwr" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkoutModification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FieldTest" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "testType" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "conditions" JSONB,
    "results" JSONB NOT NULL,
    "lt1Pace" DOUBLE PRECISION,
    "lt1HR" DOUBLE PRECISION,
    "lt2Pace" DOUBLE PRECISION,
    "lt2HR" DOUBLE PRECISION,
    "confidence" TEXT,
    "valid" BOOLEAN NOT NULL DEFAULT true,
    "warnings" JSONB,
    "errors" JSONB,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FieldTest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SelfReportedLactate" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "measurementType" TEXT NOT NULL,
    "workoutType" TEXT,
    "intensity" DOUBLE PRECISION,
    "lactate" DOUBLE PRECISION,
    "heartRate" DOUBLE PRECISION,
    "rpe" INTEGER,
    "measurements" JSONB,
    "meterBrand" TEXT,
    "calibrated" BOOLEAN NOT NULL DEFAULT false,
    "qualityRating" TEXT,
    "estimatedLT1" DOUBLE PRECISION,
    "estimatedLT2" DOUBLE PRECISION,
    "confidence" TEXT,
    "workoutId" TEXT,
    "notes" TEXT,
    "photos" JSONB,
    "validated" BOOLEAN NOT NULL DEFAULT false,
    "validatedBy" TEXT,
    "validatedAt" TIMESTAMP(3),
    "validationNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SelfReportedLactate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RaceCalendar" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "seasonName" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RaceCalendar_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Race" (
    "id" TEXT NOT NULL,
    "calendarId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "distance" TEXT NOT NULL,
    "classification" TEXT NOT NULL,
    "priority" INTEGER NOT NULL DEFAULT 1,
    "targetTime" TEXT,
    "targetPace" DOUBLE PRECISION,
    "taperWeeks" INTEGER,
    "lastQualityDate" TIMESTAMP(3),
    "actualTime" TEXT,
    "actualPace" DOUBLE PRECISION,
    "place" INTEGER,
    "avgHR" DOUBLE PRECISION,
    "maxHR" DOUBLE PRECISION,
    "splits" JSONB,
    "conditions" JSONB,
    "vdot" DOUBLE PRECISION,
    "equivalents" JSONB,
    "assessment" TEXT,
    "notes" TEXT,
    "photos" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Race_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InjuryAssessment" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "painLevel" INTEGER NOT NULL,
    "painLocation" TEXT,
    "painTiming" TEXT,
    "gaitAffected" BOOLEAN NOT NULL DEFAULT false,
    "painDuringWarmup" BOOLEAN NOT NULL DEFAULT false,
    "painContinuesThroughout" BOOLEAN NOT NULL DEFAULT false,
    "painDisappearsAfterWarmup" BOOLEAN NOT NULL DEFAULT false,
    "painRedevelopsLater" BOOLEAN NOT NULL DEFAULT false,
    "painPersists1HourPost" BOOLEAN NOT NULL DEFAULT false,
    "rangeOfMotion" TEXT,
    "swelling" BOOLEAN NOT NULL DEFAULT false,
    "discoloration" BOOLEAN NOT NULL DEFAULT false,
    "weightBearing" TEXT,
    "assessment" TEXT NOT NULL,
    "injuryType" TEXT,
    "phase" TEXT,
    "recommendedProtocol" JSONB,
    "estimatedTimeOff" TEXT,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "resolvedDate" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InjuryAssessment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrossTrainingSession" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "workoutId" TEXT,
    "modality" TEXT NOT NULL,
    "duration" DOUBLE PRECISION NOT NULL,
    "distance" DOUBLE PRECISION,
    "avgHR" DOUBLE PRECISION,
    "maxHR" DOUBLE PRECISION,
    "avgPower" DOUBLE PRECISION,
    "rpe" INTEGER,
    "intensity" TEXT NOT NULL,
    "structure" JSONB,
    "bodyWeightSupport" DOUBLE PRECISION,
    "resistance" TEXT,
    "strokeRate" DOUBLE PRECISION,
    "runningEquivalent" JSONB NOT NULL,
    "tssEquivalent" DOUBLE PRECISION,
    "reason" TEXT,
    "injuryType" TEXT,
    "effectiveness" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CrossTrainingSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StrengthTrainingSession" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "phase" TEXT NOT NULL,
    "sessionType" TEXT NOT NULL,
    "timingRelativeToRun" TEXT,
    "runningWorkoutId" TEXT,
    "strengthExercises" JSONB,
    "plyometricExercises" JSONB,
    "runningDrills" JSONB,
    "totalSets" INTEGER,
    "totalContacts" INTEGER,
    "duration" DOUBLE PRECISION NOT NULL,
    "rpe" INTEGER,
    "strengthLoad" DOUBLE PRECISION,
    "plyometricLoad" DOUBLE PRECISION,
    "runningPhase" TEXT,
    "priorityLevel" TEXT NOT NULL,
    "completionRate" DOUBLE PRECISION,
    "qualityRating" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StrengthTrainingSession_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ThresholdCalculation_testId_key" ON "ThresholdCalculation"("testId");

-- CreateIndex
CREATE INDEX "ThresholdCalculation_testId_idx" ON "ThresholdCalculation"("testId");

-- CreateIndex
CREATE UNIQUE INDEX "AthleteProfile_clientId_key" ON "AthleteProfile"("clientId");

-- CreateIndex
CREATE INDEX "AthleteProfile_clientId_idx" ON "AthleteProfile"("clientId");

-- CreateIndex
CREATE INDEX "AthleteProfile_category_idx" ON "AthleteProfile"("category");

-- CreateIndex
CREATE INDEX "DailyMetrics_clientId_date_idx" ON "DailyMetrics"("clientId", "date");

-- CreateIndex
CREATE UNIQUE INDEX "DailyMetrics_clientId_date_key" ON "DailyMetrics"("clientId", "date");

-- CreateIndex
CREATE INDEX "TrainingLoad_clientId_date_idx" ON "TrainingLoad"("clientId", "date");

-- CreateIndex
CREATE INDEX "TrainingProgramEngine_clientId_status_idx" ON "TrainingProgramEngine"("clientId", "status");

-- CreateIndex
CREATE INDEX "TrainingProgramEngine_clientId_startDate_endDate_idx" ON "TrainingProgramEngine"("clientId", "startDate", "endDate");

-- CreateIndex
CREATE INDEX "WorkoutModification_workoutId_idx" ON "WorkoutModification"("workoutId");

-- CreateIndex
CREATE INDEX "WorkoutModification_date_idx" ON "WorkoutModification"("date");

-- CreateIndex
CREATE INDEX "WorkoutModification_decision_idx" ON "WorkoutModification"("decision");

-- CreateIndex
CREATE INDEX "FieldTest_clientId_date_idx" ON "FieldTest"("clientId", "date");

-- CreateIndex
CREATE INDEX "FieldTest_testType_date_idx" ON "FieldTest"("testType", "date");

-- CreateIndex
CREATE INDEX "SelfReportedLactate_clientId_date_idx" ON "SelfReportedLactate"("clientId", "date");

-- CreateIndex
CREATE INDEX "SelfReportedLactate_clientId_measurementType_idx" ON "SelfReportedLactate"("clientId", "measurementType");

-- CreateIndex
CREATE INDEX "SelfReportedLactate_validated_idx" ON "SelfReportedLactate"("validated");

-- CreateIndex
CREATE INDEX "RaceCalendar_clientId_idx" ON "RaceCalendar"("clientId");

-- CreateIndex
CREATE INDEX "Race_clientId_date_idx" ON "Race"("clientId", "date");

-- CreateIndex
CREATE INDEX "Race_classification_date_idx" ON "Race"("classification", "date");

-- CreateIndex
CREATE INDEX "InjuryAssessment_clientId_date_idx" ON "InjuryAssessment"("clientId", "date");

-- CreateIndex
CREATE INDEX "InjuryAssessment_painLevel_gaitAffected_idx" ON "InjuryAssessment"("painLevel", "gaitAffected");

-- CreateIndex
CREATE INDEX "CrossTrainingSession_clientId_date_idx" ON "CrossTrainingSession"("clientId", "date");

-- CreateIndex
CREATE INDEX "CrossTrainingSession_modality_date_idx" ON "CrossTrainingSession"("modality", "date");

-- CreateIndex
CREATE INDEX "StrengthTrainingSession_clientId_date_idx" ON "StrengthTrainingSession"("clientId", "date");

-- CreateIndex
CREATE INDEX "StrengthTrainingSession_phase_date_idx" ON "StrengthTrainingSession"("phase", "date");

-- AddForeignKey
ALTER TABLE "ThresholdCalculation" ADD CONSTRAINT "ThresholdCalculation_testId_fkey" FOREIGN KEY ("testId") REFERENCES "Test"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AthleteProfile" ADD CONSTRAINT "AthleteProfile_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DailyMetrics" ADD CONSTRAINT "DailyMetrics_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrainingLoad" ADD CONSTRAINT "TrainingLoad_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrainingProgramEngine" ADD CONSTRAINT "TrainingProgramEngine_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FieldTest" ADD CONSTRAINT "FieldTest_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SelfReportedLactate" ADD CONSTRAINT "SelfReportedLactate_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceCalendar" ADD CONSTRAINT "RaceCalendar_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Race" ADD CONSTRAINT "Race_calendarId_fkey" FOREIGN KEY ("calendarId") REFERENCES "RaceCalendar"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Race" ADD CONSTRAINT "Race_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InjuryAssessment" ADD CONSTRAINT "InjuryAssessment_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrossTrainingSession" ADD CONSTRAINT "CrossTrainingSession_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StrengthTrainingSession" ADD CONSTRAINT "StrengthTrainingSession_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
