'use client';

/**
 * Generative Chart Component
 *
 * Renders Recharts configurations generated by AI.
 * Supports line, bar, area, composed, radar, and pie charts.
 */

import {
  LineChart,
  Line,
  BarChart,
  Bar,
  AreaChart,
  Area,
  ComposedChart,
  RadarChart,
  Radar,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  ReferenceLine,
} from 'recharts';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Lightbulb } from 'lucide-react';

interface ChartDataPoint {
  name: string;
  value: number;
  value2?: number;
  category?: string;
}

interface ChartAnnotation {
  type: 'line' | 'area' | 'label';
  value: number;
  label: string;
  color: string;
}

interface ChartConfig {
  chartType: 'line' | 'bar' | 'area' | 'composed' | 'radar' | 'pie';
  title: string;
  subtitle?: string;
  data: ChartDataPoint[];
  xAxisLabel: string;
  yAxisLabel: string;
  yAxis2Label?: string;
  colors: {
    primary: string;
    secondary: string;
    tertiary: string;
  };
  showLegend: boolean;
  showGrid: boolean;
  showTooltip: boolean;
  annotations?: ChartAnnotation[];
  insights: string[];
}

interface GenerativeChartProps {
  config: ChartConfig;
  className?: string;
}

export function GenerativeChart({ config, className }: GenerativeChartProps) {
  const {
    chartType,
    title,
    subtitle,
    data,
    xAxisLabel,
    yAxisLabel,
    yAxis2Label,
    colors,
    showLegend,
    showGrid,
    showTooltip,
    annotations,
    insights,
  } = config;

  const renderChart = () => {
    const commonProps = {
      data,
      margin: { top: 10, right: 30, left: 0, bottom: 0 },
    };

    switch (chartType) {
      case 'line':
        return (
          <LineChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" />}
            <XAxis dataKey="name" label={{ value: xAxisLabel, position: 'bottom' }} />
            <YAxis label={{ value: yAxisLabel, angle: -90, position: 'insideLeft' }} />
            {yAxis2Label && (
              <YAxis
                yAxisId="right"
                orientation="right"
                label={{ value: yAxis2Label, angle: 90, position: 'insideRight' }}
              />
            )}
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Line
              type="monotone"
              dataKey="value"
              stroke={colors.primary}
              strokeWidth={2}
              dot={{ r: 4 }}
              name={yAxisLabel}
            />
            {data.some(d => d.value2 !== undefined) && (
              <Line
                type="monotone"
                dataKey="value2"
                stroke={colors.secondary}
                strokeWidth={2}
                yAxisId={yAxis2Label ? 'right' : undefined}
                name={yAxis2Label || 'Value 2'}
              />
            )}
            {annotations?.filter(a => a.type === 'line').map((ann, i) => (
              <ReferenceLine
                key={i}
                y={ann.value}
                stroke={ann.color}
                strokeDasharray="5 5"
                label={{ value: ann.label, position: 'right' }}
              />
            ))}
          </LineChart>
        );

      case 'bar':
        return (
          <BarChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" />}
            <XAxis dataKey="name" />
            <YAxis label={{ value: yAxisLabel, angle: -90, position: 'insideLeft' }} />
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Bar dataKey="value" fill={colors.primary} name={yAxisLabel} />
            {data.some(d => d.value2 !== undefined) && (
              <Bar dataKey="value2" fill={colors.secondary} name={yAxis2Label || 'Value 2'} />
            )}
          </BarChart>
        );

      case 'area':
        return (
          <AreaChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" />}
            <XAxis dataKey="name" />
            <YAxis label={{ value: yAxisLabel, angle: -90, position: 'insideLeft' }} />
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Area
              type="monotone"
              dataKey="value"
              stroke={colors.primary}
              fill={colors.primary}
              fillOpacity={0.3}
              name={yAxisLabel}
            />
            {annotations?.filter(a => a.type === 'line').map((ann, i) => (
              <ReferenceLine
                key={i}
                y={ann.value}
                stroke={ann.color}
                strokeDasharray="5 5"
                label={{ value: ann.label, position: 'right' }}
              />
            ))}
          </AreaChart>
        );

      case 'composed':
        return (
          <ComposedChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" />}
            <XAxis dataKey="name" />
            <YAxis label={{ value: yAxisLabel, angle: -90, position: 'insideLeft' }} />
            {yAxis2Label && (
              <YAxis
                yAxisId="right"
                orientation="right"
                label={{ value: yAxis2Label, angle: 90, position: 'insideRight' }}
              />
            )}
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Area
              type="monotone"
              dataKey="value"
              fill={colors.primary}
              fillOpacity={0.3}
              stroke={colors.primary}
              name={yAxisLabel}
            />
            {data.some(d => d.value2 !== undefined) && (
              <Line
                type="monotone"
                dataKey="value2"
                stroke={colors.secondary}
                strokeWidth={2}
                yAxisId={yAxis2Label ? 'right' : undefined}
                name={yAxis2Label || 'Value 2'}
              />
            )}
            {annotations?.filter(a => a.type === 'line').map((ann, i) => (
              <ReferenceLine
                key={i}
                y={ann.value}
                stroke={ann.color}
                strokeDasharray="5 5"
                label={{ value: ann.label, position: 'right' }}
              />
            ))}
          </ComposedChart>
        );

      case 'radar':
        return (
          <RadarChart outerRadius={90} data={data}>
            <PolarGrid />
            <PolarAngleAxis dataKey="name" />
            <PolarRadiusAxis />
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Radar
              name={yAxisLabel}
              dataKey="value"
              stroke={colors.primary}
              fill={colors.primary}
              fillOpacity={0.5}
            />
          </RadarChart>
        );

      case 'pie':
        const COLORS = [colors.primary, colors.secondary, colors.tertiary, '#8884d8', '#82ca9d'];
        return (
          <PieChart>
            {showTooltip && <Tooltip />}
            {showLegend && <Legend />}
            <Pie
              data={data as any[]}
              cx="50%"
              cy="50%"
              labelLine={false}
              label={({ name, percent }) => `${name} ${(Number(percent ?? 0) * 100).toFixed(0)}%`}
              outerRadius={80}
              fill={colors.primary}
              dataKey="value"
            >
              {data.map((_, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
              ))}
            </Pie>
          </PieChart>
        );

      default:
        return <div>Unsupported chart type: {chartType}</div>;
    }
  };

  return (
    <Card className={className}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>{title}</CardTitle>
            {subtitle && <CardDescription>{subtitle}</CardDescription>}
          </div>
          <Badge variant="outline" className="text-xs">
            AI-genererad
          </Badge>
        </div>
      </CardHeader>
      <CardContent>
        <div className="h-[300px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            {renderChart()}
          </ResponsiveContainer>
        </div>

        {/* Insights */}
        {insights && insights.length > 0 && (
          <div className="mt-4 p-3 bg-blue-50 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Lightbulb className="h-4 w-4 text-blue-600" />
              <span className="text-sm font-medium text-blue-900">Insikter</span>
            </div>
            <ul className="text-sm text-blue-800 space-y-1">
              {insights.map((insight, i) => (
                <li key={i}>• {insight}</li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

/**
 * Loading state for generative chart
 */
export function GenerativeChartSkeleton() {
  return (
    <Card>
      <CardHeader>
        <div className="h-6 w-48 bg-gray-200 rounded animate-pulse" />
        <div className="h-4 w-64 bg-gray-200 rounded animate-pulse mt-2" />
      </CardHeader>
      <CardContent>
        <div className="h-[300px] w-full bg-gray-100 rounded animate-pulse flex items-center justify-center">
          <span className="text-gray-400">Genererar diagram...</span>
        </div>
      </CardContent>
    </Card>
  );
}
