/**
 * Unified Exercise Library Seeder
 *
 * Combines Strength Studio (84 runner exercises) + Hybrid Studio (140+ CrossFit/HYROX movements)
 * All exercises get both biomechanicalPillar (for Strength Studio) and isHybridMovement (for Hybrid Studio)
 *
 * Run with: npx ts-node prisma/seed-unified-exercises.ts
 */

import { PrismaClient, BiomechanicalPillar, ProgressionLevel, PlyometricIntensity, MovementCategory, EquipmentType } from '@prisma/client'

const prisma = new PrismaClient()

// Helper: Map movementCategory + muscleGroup to biomechanicalPillar
function getBiomechanicalPillar(movementCategory: string, muscleGroup: string, name: string): BiomechanicalPillar {
  // Core exercises
  if (movementCategory === 'CORE_WORK' || muscleGroup.toLowerCase().includes('core')) {
    return 'ANTI_ROTATION_CORE'
  }

  // Upper body exercises
  if (muscleGroup.toLowerCase().includes('back') ||
      muscleGroup.toLowerCase().includes('chest') ||
      muscleGroup.toLowerCase().includes('shoulder') ||
      muscleGroup.toLowerCase().includes('tricep') ||
      muscleGroup.toLowerCase().includes('bicep') ||
      name.toLowerCase().includes('pull-up') ||
      name.toLowerCase().includes('push-up') ||
      name.toLowerCase().includes('press') ||
      name.toLowerCase().includes('row') ||
      name.toLowerCase().includes('dip')) {
    return 'UPPER_BODY'
  }

  // Squat/Knee dominant exercises
  if (name.toLowerCase().includes('squat') ||
      name.toLowerCase().includes('lunge') ||
      name.toLowerCase().includes('step') ||
      movementCategory === 'POWERLIFTING' && muscleGroup.toLowerCase().includes('leg')) {
    return 'KNEE_DOMINANCE'
  }

  // Single leg / unilateral
  if (name.toLowerCase().includes('single') ||
      name.toLowerCase().includes('pistol') ||
      name.toLowerCase().includes('one-leg')) {
    return 'UNILATERAL'
  }

  // Cardio / monostructural = foot/ankle
  if (movementCategory === 'MONOSTRUCTURAL') {
    return 'FOOT_ANKLE'
  }

  // Olympic lifts, deadlifts, swings = posterior chain
  if (movementCategory === 'OLYMPIC_LIFT' ||
      name.toLowerCase().includes('deadlift') ||
      name.toLowerCase().includes('swing') ||
      name.toLowerCase().includes('clean') ||
      name.toLowerCase().includes('snatch') ||
      name.toLowerCase().includes('hip') ||
      muscleGroup.toLowerCase().includes('posterior')) {
    return 'POSTERIOR_CHAIN'
  }

  // Carries = anti-rotation core
  if (name.toLowerCase().includes('carry') ||
      name.toLowerCase().includes('walk') ||
      movementCategory === 'STRONGMAN') {
    return 'ANTI_ROTATION_CORE'
  }

  // Default to posterior chain for full body exercises
  if (muscleGroup.toLowerCase().includes('full body')) {
    return 'POSTERIOR_CHAIN'
  }

  return 'POSTERIOR_CHAIN' // fallback
}

interface UnifiedExercise {
  name: string
  nameSv: string
  nameEn: string
  category: 'STRENGTH' | 'PLYOMETRIC' | 'CORE' | 'RUNNING' | 'CYCLING' | 'SWIMMING' | 'OTHER'
  muscleGroup: string
  biomechanicalPillar: BiomechanicalPillar
  progressionLevel?: ProgressionLevel
  plyometricIntensity?: PlyometricIntensity
  contactsPerRep?: number
  movementCategory?: MovementCategory
  equipmentTypes?: EquipmentType[]
  description: string
  instructions?: string
  equipment?: string
  difficulty: string
  videoUrl?: string
  isPublic: boolean
  isHybridMovement: boolean
  defaultReps?: number
  defaultWeightMale?: number
  defaultWeightFemale?: number
  scaledWeightMale?: number
  scaledWeightFemale?: number
  foundationMovement?: string
  standardAbbreviation?: string
}

// ============================================================================
// STRENGTH STUDIO EXERCISES (84 runner-focused exercises)
// ============================================================================
const strengthExercises: UnifiedExercise[] = [
  // POSTERIOR CHAIN
  {
    name: 'HÃ¶ftbrygga',
    nameSv: 'HÃ¶ftbrygga',
    nameEn: 'Glute Bridge',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'GrundlÃ¤ggande gluteus-aktivering',
    instructions: '1. Ligg pÃ¥ rygg med knÃ¤n bÃ¶jda\n2. FÃ¶tterna platt i golvet\n3. Lyft hÃ¶ften uppÃ¥t\n4. SpÃ¤nn skinkor i toppen\n5. SÃ¤nk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbensbrygga',
    nameSv: 'Enbensbrygga',
    nameEn: 'Single-Leg Glute Bridge',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig gluteus-styrka',
    instructions: '1. Ligg pÃ¥ rygg med ena benet strÃ¤ckt\n2. Lyft hÃ¶ften pÃ¥ ett ben\n3. HÃ¥ll hÃ¶fterna jÃ¤mna\n4. SpÃ¤nn skinkan\n5. VÃ¤xla ben',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Clamshells med band',
    nameSv: 'Clamshells med band',
    nameEn: 'Clamshells with Band',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'Gluteus medius aktivering - fÃ¶rebygger knÃ¤valgus',
    instructions: '1. Ligg pÃ¥ sidan med knÃ¤n bÃ¶jda\n2. Band runt knÃ¤na\n3. Ã–ppna Ã¶versta knÃ¤t\n4. MotstÃ¥ bandet\n5. HÃ¥ll hÃ¶fterna stabila',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hip hikes',
    nameSv: 'Hip hikes',
    nameEn: 'Hip Hikes',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'FÃ¶rebygger hÃ¶ftdropp under lÃ¶pning',
    instructions: '1. StÃ¥ pÃ¥ en fot pÃ¥ steglÃ¥da\n2. SÃ¤nk motsatt hÃ¶ft\n3. Lyft hÃ¶ften med gluteus medius\n4. Kontrollerad rÃ¶relse',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Fire Hydrants',
    nameSv: 'Fire Hydrants',
    nameEn: 'Fire Hydrants',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'HÃ¶ftabduktion fÃ¶r gluteus medius',
    instructions: '1. PÃ¥ alla fyra\n2. Lyft knÃ¤t ut Ã¥t sidan\n3. HÃ¥ll 90 graders bÃ¶jning i knÃ¤t\n4. SpÃ¤nn glut',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hip Thrust med skivstÃ¥ng',
    nameSv: 'Hip Thrust med skivstÃ¥ng',
    nameEn: 'Barbell Hip Thrust',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Maximal gluteus-styrka',
    instructions: '1. Rygg mot bÃ¤nk\n2. SkivstÃ¥ng Ã¶ver hÃ¶fterna\n3. Tryck hÃ¶fterna uppÃ¥t\n4. Posteriort pelvis tilt i toppen\n5. SÃ¤nk kontrollerat',
    equipment: 'SkivstÃ¥ng, bÃ¤nk, pad',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'RumÃ¤nsk marklyft',
    nameSv: 'RumÃ¤nsk marklyft',
    nameEn: 'Romanian Deadlift (RDL)',
    category: 'STRENGTH',
    muscleGroup: 'Hases, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerar hases och gluteus med excentrisk betoning',
    instructions: '1. HÃ¥ll stÃ¥ngen med raka armar\n2. BÃ¶j i hÃ¶ften med lÃ¤tt bÃ¶jda knÃ¤n\n3. KÃ¤nn stretch i hases\n4. Tryck hÃ¶fterna framÃ¥t\n5. BehÃ¥ll neutral rygg',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig rumÃ¤nsk marklyft',
    nameSv: 'Enbenig rumÃ¤nsk marklyft',
    nameEn: 'Single-Leg Romanian Deadlift',
    category: 'STRENGTH',
    muscleGroup: 'Hases, Gluteus, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig hases-styrka och proprioception',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. BÃ¶j i hÃ¶ften\n3. StrÃ¤ck fritt ben bakÃ¥t\n4. Balansera\n5. Ã…tergÃ¥ upprÃ¤tt',
    equipment: 'Hantlar eller kettlebell',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Good Mornings',
    nameSv: 'Good Mornings',
    nameEn: 'Good Mornings',
    category: 'STRENGTH',
    muscleGroup: 'Hases, LÃ¤ndryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Posterior chain med betoning pÃ¥ excentrisk kontroll',
    instructions: '1. SkivstÃ¥ng pÃ¥ axlarna\n2. BÃ¶j framÃ¥t i hÃ¶ften\n3. Parallell rygg med golvet\n4. Stretch i hases\n5. Ã…tergÃ¥ upprÃ¤tt',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Cable Pull-Through',
    nameSv: 'Cable Pull-Through',
    nameEn: 'Cable Pull-Through',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'HÃ¶ftextension med kabel-motstÃ¥nd',
    instructions: '1. StÃ¥ med ryggen mot kabel\n2. Hantag mellan benen\n3. BÃ¶j i hÃ¶ften\n4. StrÃ¤ck hÃ¶fterna kraftfullt\n5. SpÃ¤nn glut i toppen',
    equipment: 'Kabel',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Kettlebell Swing',
    nameSv: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    movementCategory: 'KETTLEBELL_WORK',
    equipmentTypes: ['KETTLEBELL'],
    description: 'Explosiv hÃ¶ftextension - power development',
    instructions: '1. Bred stÃ¤llning\n2. Swing kettlebell mellan benen\n3. Explosiv hÃ¶ftstrÃ¤ckning\n4. Armarna passiva\n5. Ballistisk rÃ¶relse',
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 20,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBS',
  },
  {
    name: 'Marklyft',
    nameSv: 'Marklyft',
    nameEn: 'Deadlift',
    category: 'STRENGTH',
    muscleGroup: 'Helkropp - Posterior Chain',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'HelkroppsÃ¶vning med fokus pÃ¥ bakre kedjan',
    instructions: '1. StÃ¥ med fÃ¶tterna hÃ¶ftbrett\n2. BÃ¶j i hÃ¶ften och grip stÃ¥ngen\n3. Neutral rygg\n4. Lyft genom hÃ¶ft- och knÃ¤extension\n5. LÃ¥s ut i toppen',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 47,
    standardAbbreviation: 'DL',
  },
  {
    name: 'Reverse Hyperextension',
    nameSv: 'Reverse Hyperextension',
    nameEn: 'Reverse Hyperextension',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases, LÃ¤ndryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Gluteus och hases utan ryggbelastning',
    instructions: '1. Ligg pÃ¥ bÃ¤nk med hÃ¶fterna i kanten\n2. LÃ¥t benen hÃ¤nga\n3. Lyft benen bakÃ¥t och uppÃ¥t\n4. SpÃ¤nn glut\n5. SÃ¤nk kontrollerat',
    equipment: 'BÃ¤nk',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  // KNEE DOMINANCE
  {
    name: 'KnÃ¤bÃ¶j',
    nameSv: 'KnÃ¤bÃ¶j',
    nameEn: 'Back Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'GrundlÃ¤ggande bilateral benstyrka',
    instructions: '1. SkivstÃ¥ng pÃ¥ axlarna\n2. FÃ¶tterna axelbrett\n3. SÃ¤nk dig nedÃ¥t\n4. HÃ¶ften under parallell\n5. Tryck upp explosivt',
    equipment: 'SkivstÃ¥ng, rack',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 43,
    standardAbbreviation: 'BS',
  },
  {
    name: 'Goblet Squat',
    nameSv: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    movementCategory: 'KETTLEBELL_WORK',
    equipmentTypes: ['KETTLEBELL'],
    description: 'LÃ¤r squat-mÃ¶nster med upprÃ¤tt bÃ¥l',
    instructions: '1. HÃ¥ll kettlebell/hantel vid brÃ¶stet\n2. BÃ¶j i knÃ¤n och hÃ¶fter\n3. ArmbÃ¥garna mellan knÃ¤na\n4. Djup squat\n5. Tryck upp',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 15,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'GS',
  },
  {
    name: 'Wall Sit',
    nameSv: 'VÃ¤ggstol',
    nameEn: 'Wall Sit',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    description: 'Isometrisk quad-styrka',
    instructions: '1. Rygg mot vÃ¤gg\n2. SÃ¤nk till 90 grader\n3. KnÃ¤n Ã¶ver anklar\n4. HÃ¥ll positionen\n5. SpÃ¤nn quads',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Front Squat',
    nameSv: 'Front Squat',
    nameEn: 'Front Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Quad-dominant squat med upprÃ¤tt bÃ¥l',
    instructions: '1. SkivstÃ¥ng pÃ¥ frÃ¤mre deltoider\n2. ArmbÃ¥garna hÃ¶gt\n3. Squat med upprÃ¤tt bÃ¥l\n4. Djup position\n5. Tryck upp',
    equipment: 'SkivstÃ¥ng, rack',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 84,
    defaultWeightFemale: 57,
    scaledWeightMale: 57,
    scaledWeightFemale: 35,
    standardAbbreviation: 'FS',
  },
  {
    name: 'Split Squat',
    nameSv: 'Split Squat',
    nameEn: 'Split Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    description: 'Statisk split position fÃ¶r quad-styrka',
    instructions: '1. SplitstÃ¤llning\n2. Bakre knÃ¤ sÃ¤nks mot golvet\n3. FrÃ¤mre knÃ¤ Ã¶ver ankel\n4. UpprÃ¤tt bÃ¥l\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Benpress',
    nameSv: 'Benpress',
    nameEn: 'Leg Press',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    description: 'Benstyrka utan ryggbelastning',
    instructions: '1. FÃ¶tterna pÃ¥ plattan\n2. SÃ¤nk kontrollerat\n3. KnÃ¤n mot brÃ¶st\n4. Tryck upp kraftfullt\n5. LÃ¥s inte knÃ¤na helt',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pistol Squat Progression',
    nameSv: 'Pistol Squat Progression',
    nameEn: 'Pistol Squat Progression',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'Enbenssquat fÃ¶r avancerad styrka',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. StrÃ¤ck andra benet framÃ¥t\n3. Squat hela vÃ¤gen ner\n4. Balansera\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Cyclist Squat',
    nameSv: 'Cyclist Squat',
    nameEn: 'Cyclist Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerad quad-styrka med hÃ¤llyft',
    instructions: '1. HÃ¤larna pÃ¥ platta (5-10cm)\n2. UpprÃ¤tt bÃ¥l\n3. Smal stÃ¤llning\n4. Djup squat\n5. Quad-dominant',
    equipment: 'Hantlar, platta',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hoppsquat',
    nameSv: 'Hoppsquat',
    nameEn: 'Jump Squat',
    category: 'PLYOMETRIC',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Explosiv quad-power',
    instructions: '1. Squat position\n2. Explosiv hopp\n3. Armsving\n4. Mjuk landning\n5. Direkt i nÃ¤sta rep',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  // UNILATERAL
  {
    name: 'Bulgarisk utfallsbÃ¶j',
    nameSv: 'Bulgarisk utfallsbÃ¶j',
    nameEn: 'Bulgarian Split Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig benstyrka - "The Big Three" fÃ¶r lÃ¶pare',
    instructions: '1. Bakre fot pÃ¥ bÃ¤nk\n2. FrÃ¤mre fot framÃ¥t\n3. SÃ¤nk bakre knÃ¤\n4. UpprÃ¤tt bÃ¥l\n5. Tryck upp pÃ¥ frÃ¤mre ben',
    equipment: 'BÃ¤nk, hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Utfallssteg',
    nameSv: 'Utfallssteg',
    nameEn: 'Walking Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Dynamisk enbensstyrka',
    instructions: '1. Steg framÃ¥t\n2. SÃ¤nk bakre knÃ¤\n3. 90 grader i bÃ¥da knÃ¤na\n4. Tryck upp\n5. Upprepa med annat ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'BakÃ¥tlunges',
    nameSv: 'BakÃ¥tlunges',
    nameEn: 'Reverse Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Mer knÃ¤vÃ¤nlig Ã¤n framÃ¥tlunges',
    instructions: '1. Steg bakÃ¥t\n2. SÃ¤nk bakre knÃ¤\n3. FrÃ¤mre knÃ¤ stabilt Ã¶ver ankel\n4. Tryck upp\n5. VÃ¤xla ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Lunges',
    nameSv: 'Lateral Lunges',
    nameEn: 'Lateral Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Adduktorer, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Frontalplanstyrka',
    instructions: '1. Steg Ã¥t sidan\n2. BÃ¶j i ett knÃ¤\n3. Andra benet rakt\n4. Sitt bakÃ¥t\n5. Tryck upp och tillbaka',
    equipment: 'Ingen eller hantlar',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Curtsy Lunges',
    nameSv: 'Curtsy Lunges',
    nameEn: 'Curtsy Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius, Quadriceps',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Gluteus medius och hÃ¶ftrotation',
    instructions: '1. Steg diagonalt bakÃ¥t\n2. Korsa bakom stÃ¥ende ben\n3. SÃ¤nk i utfallsposition\n4. HÃ¥ll hÃ¶fterna framÃ¥t\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups (lÃ¥g)',
    nameSv: 'Step-Ups (lÃ¥g)',
    nameEn: 'Step-Ups (Low Box)',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'GrundlÃ¤ggande enbensstyrka',
    instructions: '1. LÃ¥g lÃ¥da (30-40cm)\n2. Placera fot pÃ¥ lÃ¥dan\n3. Tryck upp med det benet\n4. StÃ¥ stadigt\n5. SÃ¤nk kontrollerat',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups (hÃ¶g)',
    nameSv: 'Step-Ups (hÃ¶g)',
    nameEn: 'Step-Ups (High Box)',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Avancerad enbensstyrka',
    instructions: '1. HÃ¶g lÃ¥da (50-60cm)\n2. Explosiv uppgÃ¥ng\n3. Hela foten pÃ¥ lÃ¥dan\n4. LÃ¥s ut hÃ¶ft och knÃ¤\n5. Kontrollerad nedgÃ¥ng',
    equipment: 'SteglÃ¥da, hantlar',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups med knÃ¤drive',
    nameSv: 'Step-Ups med knÃ¤drive',
    nameEn: 'Step-Ups with Knee Drive',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, HÃ¶ftflexorer',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'LÃ¶pspecifik knÃ¤drive',
    instructions: '1. Step-up pÃ¥ lÃ¥da\n2. Svinga fria benet\n3. KnÃ¤ hÃ¶gt (90 grader)\n4. Balansera pÃ¥ stÃ¥ende ben\n5. Kontrollerad nedgÃ¥ng',
    equipment: 'SteglÃ¥da',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig benpress',
    nameSv: 'Enbenig benpress',
    nameEn: 'Single-Leg Press',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerad enbensstyrka',
    instructions: '1. En fot pÃ¥ plattan\n2. SÃ¤nk kontrollerat\n3. Djup position\n4. Tryck upp\n5. JÃ¤mfÃ¶r vÃ¤nster/hÃ¶ger',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Skater Squats',
    nameSv: 'Skater Squats',
    nameEn: 'Skater Squats',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'Avancerad enbenssquat',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. SÃ¤nk dig nedÃ¥t\n3. Bakre ben bakom\n4. Bakre knÃ¤ mot golvet\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // FOOT & ANKLE
  {
    name: 'TÃ¥hÃ¤vningar (raka ben)',
    nameSv: 'TÃ¥hÃ¤vningar (raka ben)',
    nameEn: 'Calf Raises (Straight Knee)',
    category: 'STRENGTH',
    muscleGroup: 'Gastrocnemius',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Gastrocnemius-styrka',
    instructions: '1. StÃ¥ pÃ¥ kant/steglÃ¥da\n2. Raka ben\n3. Tryck upp pÃ¥ tÃ¥r\n4. Full ROM\n5. Kontrollerad sÃ¤nkning',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'TÃ¥hÃ¤vningar (bÃ¶jda ben)',
    nameSv: 'TÃ¥hÃ¤vningar (bÃ¶jda ben)',
    nameEn: 'Calf Raises (Bent Knee)',
    category: 'STRENGTH',
    muscleGroup: 'Soleus',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Soleus-fokus (viktig fÃ¶r lÃ¶pare)',
    instructions: '1. Sittande eller lÃ¤tt bÃ¶jda knÃ¤n\n2. Tryck upp pÃ¥ tÃ¥r\n3. Isolerar soleus\n4. HÃ¶g volym (15-20 reps)\n5. Kontrollerad tempo',
    equipment: 'Seated calf raise (eller kroppsvikt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig tÃ¥hÃ¤vning',
    nameSv: 'Enbenig tÃ¥hÃ¤vning',
    nameEn: 'Single-Leg Calf Raise',
    category: 'STRENGTH',
    muscleGroup: 'Gastrocnemius, Soleus',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig vader-styrka',
    instructions: '1. Ett ben pÃ¥ kant\n2. Balansera\n3. Full dorsalflexion (sÃ¤nk hÃ¤len)\n4. Explosiv plantarflexion\n5. JÃ¤mfÃ¶r bilateral skillnad',
    equipment: 'SteglÃ¥da',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Ankelhopp',
    nameSv: 'Ankelhopp',
    nameEn: 'Ankle Hops',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vad, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Ankelstyvhet och reaktiv styrka',
    instructions: '1. Minimalt knÃ¤bÃ¶j\n2. Hopp frÃ¥n ankeln\n3. Snabb markkontakt\n4. Styvt ben\n5. Rytmisk',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Toe Yoga',
    nameSv: 'Toe Yoga',
    nameEn: 'Toe Yoga',
    category: 'STRENGTH',
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Intrinsisk fotstyrka',
    instructions: '1. Barfota\n2. Lyft stortÃ¥\n3. Andra tÃ¥r i golvet\n4. VÃ¤xla\n5. StÃ¤rker fotvalv',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Marmor-pickups',
    nameSv: 'Marmor-pickups',
    nameEn: 'Marble/Towel Pickups',
    category: 'STRENGTH',
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Fotvalv-styrka',
    instructions: '1. Barfota\n2. Plocka upp marmelkulor med tÃ¥r\n3. Alternativ: dra handduk\n4. StÃ¤rker fotvalv\n5. FÃ¶rebygger plantar fasciit',
    equipment: 'Marmelkulor eller handduk',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Ankel dorsalflexion (band)',
    nameSv: 'Ankel dorsalflexion (band)',
    nameEn: 'Ankle Dorsiflexion (Band)',
    category: 'STRENGTH',
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'FÃ¶rebygger shin splints',
    instructions: '1. Band runt foten\n2. Dra tÃ¥r mot smalben\n3. Dorsalflexion\n4. Kontrollerad sÃ¤nkning\n5. HÃ¶g volym (20 reps)',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'HÃ¤lgÃ¥ng',
    nameSv: 'HÃ¤lgÃ¥ng',
    nameEn: 'Heel Walks',
    category: 'STRENGTH',
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Tibialis-styrka',
    instructions: '1. GÃ¥ pÃ¥ hÃ¤larna\n2. TÃ¥r uppÃ¥t\n3. Dorsalflexion under gÃ¥ng\n4. 20-30 meter\n5. UppvÃ¤rmning eller rehab',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  // CORE
  {
    name: 'Plank',
    nameSv: 'Plank',
    nameEn: 'Plank',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    movementCategory: 'CORE_WORK',
    equipmentTypes: ['BODYWEIGHT'],
    description: 'Anti-extension core',
    instructions: '1. StÃ¶d pÃ¥ underarmar och tÃ¥r\n2. Rak linje\n3. SpÃ¤nn mage och glut\n4. Neutral nacke\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
    standardAbbreviation: 'PLK',
  },
  {
    name: 'Sidplank',
    nameSv: 'Sidplank',
    nameEn: 'Side Plank',
    category: 'CORE',
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-lateral flexion',
    instructions: '1. Ligg pÃ¥ sidan\n2. StÃ¶d pÃ¥ underarm\n3. Lyft hÃ¶ften\n4. Rak linje\n5. JÃ¤mfÃ¶r sidor',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Dead Bug',
    nameSv: 'Dead Bug',
    nameEn: 'Dead Bug',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-extension med rÃ¶relse',
    instructions: '1. Rygg pÃ¥ golvet\n2. Armar upp, knÃ¤n 90Â°\n3. StrÃ¤ck motsatt arm/ben\n4. LÃ¤ndryggen i golvet\n5. VÃ¤xla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Bird Dog',
    nameSv: 'Bird Dog',
    nameEn: 'Bird Dog',
    category: 'CORE',
    muscleGroup: 'Core, Posterior Chain',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-rotation och posterior chain',
    instructions: '1. PÃ¥ alla fyra\n2. StrÃ¤ck motsatt arm/ben\n3. HÃ¥ll rygg neutral\n4. Balansera\n5. VÃ¤xla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pallof Press',
    nameSv: 'Pallof Press',
    nameEn: 'Pallof Press (Cable)',
    category: 'CORE',
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Anti-rotation mot kabel',
    instructions: '1. StÃ¥ sidledes mot kabel\n2. Hantag vid brÃ¶stet\n3. Pressa rakt framÃ¥t\n4. MotstÃ¥ rotation\n5. HÃ¥ll hÃ¶fterna framÃ¥t',
    equipment: 'Kabel eller resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pallof Press (band)',
    nameSv: 'Pallof Press (band)',
    nameEn: 'Pallof Press (Band)',
    category: 'CORE',
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Hemversion av pallof press',
    instructions: '1. FÃ¤st band vid stolpe\n2. Sidledes stÃ¤llning\n3. Press framÃ¥t\n4. MotstÃ¥ bandets dragning\n5. Kontrollerad Ã¥tergÃ¥ng',
    equipment: 'Resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Suitcase Carry',
    nameSv: 'Suitcase Carry',
    nameEn: 'Suitcase Carry',
    category: 'CORE',
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Anti-lateral flexion dynamisk',
    instructions: '1. Tungt i en hand\n2. GÃ¥ framÃ¥t\n3. MotstÃ¥ lateral flexion\n4. BÃ¥l upprÃ¤tt\n5. 20-40 meter',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Farmer\'s Walk',
    nameSv: 'Farmer\'s Walk',
    nameEn: 'Farmer\'s Walk',
    category: 'CORE',
    muscleGroup: 'Core, Trapezius, Grip',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'STRONGMAN',
    equipmentTypes: ['KETTLEBELL', 'DUMBBELL'],
    description: 'Totalstyrka och stabilitet',
    instructions: '1. Tungt i bÃ¥da hÃ¤nderna\n2. GÃ¥ framÃ¥t\n3. UpprÃ¤tt hÃ¥llning\n4. Axlarna tillbaka\n5. 30-50 meter',
    equipment: 'Hantlar eller kettlebells',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 32,
    defaultWeightFemale: 24,
    scaledWeightMale: 24,
    scaledWeightFemale: 16,
    standardAbbreviation: 'FC',
  },
  {
    name: 'Ab Wheel Rollouts',
    nameSv: 'Ab Wheel Rollouts',
    nameEn: 'Ab Wheel Rollouts',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_3',
    description: 'Avancerad anti-extension',
    instructions: '1. KnÃ¤ pÃ¥ golvet\n2. Rulla hjulet framÃ¥t\n3. StrÃ¤ck ut kroppen\n4. BehÃ¥ll neutral lÃ¤ndrygen\n5. Dra tillbaka med core',
    equipment: 'Ab wheel',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Copenhagen Plank',
    nameSv: 'Copenhagen Plank',
    nameEn: 'Copenhagen Plank',
    category: 'CORE',
    muscleGroup: 'Adduktorer, Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_3',
    description: 'Adduktor-styrka (41% minskning groin injury)',
    instructions: '1. Sidplank position\n2. Ã–vre ben pÃ¥ bÃ¤nk\n3. Lyft hÃ¶ften\n4. Adduktor-kontraktion\n5. SvÃ¥r Ã¶vning - bÃ¶rja med kort hold',
    equipment: 'BÃ¤nk',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Stir the Pot',
    nameSv: 'Stir the Pot',
    nameEn: 'Stir the Pot',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Instabil plank variation',
    instructions: '1. Underarmar pÃ¥ gymnastikboll\n2. Plank position\n3. Cirkla armarna (som att rÃ¶ra gryta)\n4. SmÃ¥cirklar\n5. VÃ¤xla riktning',
    equipment: 'Gymnastikboll',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Russian Twist',
    nameSv: 'Russian Twist',
    nameEn: 'Russian Twist',
    category: 'CORE',
    muscleGroup: 'Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'CORE_WORK',
    equipmentTypes: ['BODYWEIGHT', 'MEDICINE_BALL'],
    description: 'Rotation med kontroll',
    instructions: '1. Sitt med fÃ¶tterna upp\n2. Luta bakÃ¥t\n3. Rotera sida till sida\n4. Touch golvet\n5. Kontrollerad rÃ¶relse',
    equipment: 'Viktskiva (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 20,
    standardAbbreviation: 'RT',
  },
  // PLYOMETRIC - LOW
  {
    name: 'Hopprep',
    nameSv: 'Hopprep',
    nameEn: 'Jump Rope',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Ankelstyvhet och rytm',
    instructions: '1. Minimala hopp\n2. Snabb markkontakt\n3. Ankeldominerad\n4. Rytmisk\n5. 100-200 kontakter',
    equipment: 'Hopprep',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pogo Jumps',
    nameSv: 'Pogo Jumps',
    nameEn: 'Pogo Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: '>250ms ground contact, styvhet',
    instructions: '1. Styvt ben\n2. Minimal knÃ¤bÃ¶j\n3. Hopp frÃ¥n ankel\n4. Snabb kontakt\n5. Sets om 15-20 reps',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'LÃ¥ga lÃ¥dhopp',
    nameSv: 'LÃ¥ga lÃ¥dhopp',
    nameEn: 'Low Box Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'LÃ¥g lÃ¥da (30-40cm) fÃ¶r nybÃ¶rjare',
    instructions: '1. LÃ¥g lÃ¥da\n2. Hopp upp\n3. Mjuk landning\n4. Kliv ner (inte hoppa)\n5. 8-10 reps',
    equipment: 'LÃ¥g plyobox',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Lateral Hops',
    nameEn: 'Lateral Hops (Side to Side)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Lateral styvhet',
    instructions: '1. Hopp sida till sida\n2. Linje pÃ¥ golvet\n3. Snabb kontakt\n4. Rytmisk\n5. 20-30 kontakter',
    equipment: 'Ingen eller lÃ¥g kon',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Skipping',
    nameSv: 'Skipping',
    nameEn: 'Skipping',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Koordination och ankelstyvhet',
    instructions: '1. Exaggererad lÃ¶prÃ¶relse\n2. KnÃ¤drive\n3. Hopp pÃ¥ varje steg\n4. Rytmisk\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  // PLYOMETRIC - MODERATE
  {
    name: 'Squat Jumps',
    nameSv: 'Squat Jumps',
    nameEn: 'Squat Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Concentric focus, kontrollerad landning',
    instructions: '1. Squat position\n2. Paus i botten\n3. Explosivt hopp\n4. Mjuk landning\n5. Paus igen (ej reaktiv)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Countermovement Jumps',
    nameSv: 'Countermovement Jumps',
    nameEn: 'Countermovement Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Stretch-shortening cycle trÃ¤ning',
    instructions: '1. StÃ¥ende position\n2. Snabb countermovement (bÃ¶j)\n3. Omedelbart hopp\n4. Maximalt hopp\n5. Mjuk landning',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Bounds',
    nameSv: 'Lateral Bounds',
    nameEn: 'Lateral Bounds',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Lateral power och stabilitet',
    instructions: '1. Hoppa lateral frÃ¥n ett ben\n2. Landa pÃ¥ andra benet\n3. Stabilisera\n4. Hopp tillbaka\n5. 10-12 reps per sida',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Tuck Jumps',
    nameEn: 'Tuck Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Core',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Maximal hÃ¶jd med knÃ¤drive',
    instructions: '1. Hopp rakt upp\n2. Dra knÃ¤n mot brÃ¶stet\n3. Tuck position\n4. Mjuk landning\n5. 6-8 reps',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Split Jumps',
    nameSv: 'Hoppande utfall',
    nameEn: 'Split Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 2,
    description: 'Ensidig explosivitet',
    instructions: '1. Utfallsposition\n2. Hopp och byt ben\n3. Landa i utfall\n4. Mjuk landning\n5. 10-12 totala hopp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  // PLYOMETRIC - HIGH
  {
    name: 'LÃ¥dhopp (18-24")',
    nameSv: 'LÃ¥dhopp (18-24")',
    nameEn: 'Box Jumps (18-24")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'MedelhÃ¶g lÃ¥da fÃ¶r power',
    instructions: '1. LÃ¥da 46-61cm\n2. Explosivt hopp\n3. Landa mjukt\n4. Kliv ner\n5. 8-10 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenhopp (Bounds)',
    nameSv: 'Enbenhopp (Bounds)',
    nameEn: 'Single-Leg Bounds',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'LÃ¶pspecifik horizontal power',
    instructions: '1. Hoppa framÃ¥t pÃ¥ ett ben\n2. Maximalt avstÃ¥nd\n3. Mjuk landning\n4. Upprepa samma ben\n5. 20-30 meter per ben',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hurdle Hops',
    nameSv: 'Hurdle Hops',
    nameEn: 'Hurdle Hops',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Seriella hopp Ã¶ver hÃ¤ckar',
    instructions: '1. Rad av hÃ¤ckar\n2. Hopp Ã¶ver varje hÃ¤ck\n3. Minimal markkontakt\n4. Rytmisk\n5. 6-10 hÃ¤ckar',
    equipment: 'HÃ¤ckar (30-46cm)',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Bred hopp (max)',
    nameSv: 'Bred hopp (max)',
    nameEn: 'Broad Jump (Maximal)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Maximal horizontal power',
    instructions: '1. Armsving\n2. Explosiv hopp framÃ¥t\n3. Maximalt avstÃ¥nd\n4. Mjuk landning\n5. MÃ¤t avstÃ¥nd (test)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Triple Jump',
    nameSv: 'Triple Jump',
    nameEn: 'Triple Jump',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 3,
    description: 'Tre hopp i serie',
    instructions: '1. Hopp pÃ¥ hÃ¶ger ben\n2. Hopp pÃ¥ vÃ¤nster ben\n3. Bred hopp med bÃ¥da ben\n4. Maximalt avstÃ¥nd\n5. 3-5 fÃ¶rsÃ¶k',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // DEPTH JUMPS
  {
    name: 'Depth Jumps (30cm)',
    nameSv: 'Depth Jumps (30cm)',
    nameEn: 'Depth Jumps (12")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: '<150ms ground contact, maximal RFD',
    instructions: '1. Kliv av 30cm lÃ¥da\n2. Mjuk landning\n3. Omedelbart maxhopp\n4. Minimal markkontakt\n5. MAX 27 kontakter per session',
    equipment: 'Plyobox 30cm',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Depth Jumps (40cm)',
    nameSv: 'Depth Jumps (40cm)',
    nameEn: 'Depth Jumps (16")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Elite-level depth jump',
    instructions: '1. Kliv av 40cm lÃ¥da\n2. Absorb impact\n3. Explosiv rebound\n4. Maximal hÃ¶jd\n5. ENDAST fÃ¶r avancerade - MAX 18 kontakter',
    equipment: 'Plyobox 40cm',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Drop Jumps',
    nameSv: 'Drop Jumps',
    nameEn: 'Drop Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Maximal reactive strength',
    instructions: '1. Kliv av lÃ¥da\n2. Landa\n3. Omedelbart maxhopp uppÃ¥t\n4. <200ms contact\n5. KrÃ¤ver styrka: 1.5x BW squat',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Repeated Bounds',
    nameSv: 'Repeated Bounds',
    nameEn: 'Repeated Bounds (Continuous)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Seriella enbenhopp',
    instructions: '1. Kontinuerliga enbenhopp\n2. Samma ben\n3. Snabb markkontakt\n4. Maximalt avstÃ¥nd per hopp\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Depth to Broad Jump',
    nameSv: 'Depth to Broad Jump',
    nameEn: 'Depth to Broad Jump',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Vertical to horizontal power',
    instructions: '1. Kliv av lÃ¥da\n2. Landa\n3. Omedelbart bred hopp framÃ¥t\n4. Maximalt horisontellt avstÃ¥nd\n5. 5-8 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // UPPER BODY
  {
    name: 'BÃ¤nkpress',
    nameSv: 'BÃ¤nkpress',
    nameEn: 'Bench Press',
    category: 'STRENGTH',
    muscleGroup: 'BrÃ¶st, Triceps',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Ã–verkroppsstyrka (valfritt fÃ¶r lÃ¶pare)',
    instructions: '1. Ligg pÃ¥ bÃ¤nk\n2. Grip nÃ¥got bredare Ã¤n axlar\n3. SÃ¤nk till brÃ¶stet\n4. Pressa upp\n5. LÃ¥s ut',
    equipment: 'SkivstÃ¥ng, bÃ¤nk',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'BP',
  },
  {
    name: 'Rodd',
    nameSv: 'Rodd',
    nameEn: 'Barbell Row',
    category: 'STRENGTH',
    muscleGroup: 'Rygg',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    description: 'Ryggstyrka',
    instructions: '1. BÃ¶j framÃ¥t i hÃ¶ften\n2. Grip stÃ¥ngen\n3. Dra mot mage\n4. ArmbÃ¥gar nÃ¤ra kroppen\n5. Squeeze shoulder blades',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Chins',
    nameSv: 'Chins',
    nameEn: 'Pull-ups/Chin-ups',
    category: 'STRENGTH',
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_3',
    movementCategory: 'GYMNASTICS',
    equipmentTypes: ['PULL_UP_BAR'],
    description: 'Ryggstyrka med kroppsvikt',
    instructions: '1. HÃ¤ng i stÃ¥ng\n2. Dra dig upp\n3. Hakan Ã¶ver stÃ¥ngen\n4. Kontrollerad nedgÃ¥ng\n5. Full ROM',
    equipment: 'Chin-up bar',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 10,
    standardAbbreviation: 'PU',
  },
  {
    name: 'Axelpress',
    nameSv: 'Axelpress',
    nameEn: 'Overhead Press',
    category: 'STRENGTH',
    muscleGroup: 'Axlar',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Axelstyrka',
    instructions: '1. StÃ¥ng vid axelhÃ¶jd\n2. Pressa rakt uppÃ¥t\n3. LÃ¥s ut armarna\n4. SÃ¤nk kontrollerat\n5. Neutral rygg',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'SP',
  },
]

// The file is getting long, let me continue in the main function with additional exercises
async function main() {
  console.log('ðŸ‹ï¸ Starting Unified Exercise Library Seeder...')
  console.log(`ðŸ“¦ Processing ${strengthExercises.length} strength exercises...`)

  let created = 0
  let updated = 0
  let skipped = 0

  // Process all exercises
  for (const exercise of strengthExercises) {
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name, coachId: null },
    })

    if (existing) {
      // Update existing to ensure it has both flags
      if (!existing.isHybridMovement || !existing.biomechanicalPillar) {
        await prisma.exercise.update({
          where: { id: existing.id },
          data: {
            isHybridMovement: true,
            biomechanicalPillar: exercise.biomechanicalPillar,
            progressionLevel: exercise.progressionLevel || existing.progressionLevel,
            movementCategory: exercise.movementCategory || existing.movementCategory,
            equipmentTypes: exercise.equipmentTypes || existing.equipmentTypes,
            defaultReps: exercise.defaultReps || existing.defaultReps,
            defaultWeightMale: exercise.defaultWeightMale || existing.defaultWeightMale,
            defaultWeightFemale: exercise.defaultWeightFemale || existing.defaultWeightFemale,
            scaledWeightMale: exercise.scaledWeightMale || existing.scaledWeightMale,
            scaledWeightFemale: exercise.scaledWeightFemale || existing.scaledWeightFemale,
            standardAbbreviation: exercise.standardAbbreviation || existing.standardAbbreviation,
          },
        })
        updated++
        console.log(`  âœï¸  Updated: ${exercise.name}`)
      } else {
        skipped++
      }
    } else {
      // Create new exercise
      await prisma.exercise.create({
        data: {
          name: exercise.name,
          nameSv: exercise.nameSv,
          nameEn: exercise.nameEn,
          category: exercise.category,
          muscleGroup: exercise.muscleGroup,
          biomechanicalPillar: exercise.biomechanicalPillar,
          progressionLevel: exercise.progressionLevel,
          plyometricIntensity: exercise.plyometricIntensity,
          contactsPerRep: exercise.contactsPerRep,
          movementCategory: exercise.movementCategory,
          equipmentTypes: exercise.equipmentTypes || [],
          description: exercise.description,
          instructions: exercise.instructions,
          equipment: exercise.equipment,
          difficulty: exercise.difficulty,
          videoUrl: exercise.videoUrl,
          isPublic: true,
          isHybridMovement: true,
          defaultReps: exercise.defaultReps,
          defaultWeightMale: exercise.defaultWeightMale,
          defaultWeightFemale: exercise.defaultWeightFemale,
          scaledWeightMale: exercise.scaledWeightMale,
          scaledWeightFemale: exercise.scaledWeightFemale,
          foundationMovement: exercise.foundationMovement,
          standardAbbreviation: exercise.standardAbbreviation,
        },
      })
      created++
      console.log(`  âœ… Created: ${exercise.name}`)
    }
  }

  // Now update ALL existing exercises to have isHybridMovement = true
  console.log('\nðŸ”„ Updating all existing exercises with isHybridMovement = true...')
  const updateResult = await prisma.exercise.updateMany({
    where: { isHybridMovement: false },
    data: { isHybridMovement: true },
  })
  console.log(`  âœ… Updated ${updateResult.count} exercises with isHybridMovement flag`)

  // Update exercises missing biomechanicalPillar based on their properties
  console.log('\nðŸ”„ Adding biomechanicalPillar to exercises that are missing it...')
  const exercisesWithoutPillar = await prisma.exercise.findMany({
    where: { biomechanicalPillar: null },
  })

  let pillarUpdated = 0
  for (const ex of exercisesWithoutPillar) {
    const pillar = getBiomechanicalPillar(
      ex.movementCategory || '',
      ex.muscleGroup || '',
      ex.name
    )
    await prisma.exercise.update({
      where: { id: ex.id },
      data: { biomechanicalPillar: pillar },
    })
    pillarUpdated++
  }
  console.log(`  âœ… Added biomechanicalPillar to ${pillarUpdated} exercises`)

  // Summary
  const totalCount = await prisma.exercise.count({ where: { coachId: null } })
  const hybridCount = await prisma.exercise.count({ where: { isHybridMovement: true, coachId: null } })
  const pillarCount = await prisma.exercise.count({ where: { biomechanicalPillar: { not: null }, coachId: null } })

  console.log('\n' + '='.repeat(60))
  console.log('ðŸ“Š Unified Exercise Library Summary')
  console.log('='.repeat(60))
  console.log(`âœ… Created: ${created} new exercises`)
  console.log(`âœï¸  Updated: ${updated} exercises`)
  console.log(`â­ï¸  Skipped: ${skipped} exercises (already complete)`)
  console.log(`ðŸ“š Total system exercises: ${totalCount}`)
  console.log(`ðŸ‹ï¸ With biomechanicalPillar (Strength Studio): ${pillarCount}`)
  console.log(`ðŸ”¥ With isHybridMovement (Hybrid Studio): ${hybridCount}`)
  console.log('='.repeat(60))
  console.log('\nâœ¨ All exercises now available in both Strength and Hybrid Studios!')
}

main()
  .catch((e) => {
    console.error('âŒ Error seeding exercises:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
