// prisma/seed-agility-drills.ts
// Seed file for Agility Studio drill library
// Run with: npx ts-node prisma/seed-agility-drills.ts

import { PrismaClient, AgilityDrillCategory, DevelopmentStage, SportType } from '@prisma/client'

const prisma = new PrismaClient()

interface AgilityDrillSeed {
  name: string
  nameSv: string
  description: string
  descriptionSv: string
  category: AgilityDrillCategory
  requiredEquipment: string[]
  optionalEquipment: string[]
  distanceMeters?: number
  durationSeconds?: number
  defaultReps?: number
  defaultSets?: number
  restSeconds?: number
  minDevelopmentStage: DevelopmentStage
  maxDevelopmentStage: DevelopmentStage
  primarySports: SportType[]
  difficultyLevel: number
  setupInstructions: string
  executionCues: string[]
}

const agilityDrills: AgilityDrillSeed[] = [
  // ==================== CHANGE OF DIRECTION (COD) ====================
  {
    name: '5-10-5 Pro Agility',
    nameSv: '5-10-5 Pro Agility',
    description: 'Start in 3-point stance, sprint 5 yards to one side, touch line, sprint 10 yards to opposite side, touch line, sprint 5 yards back through start.',
    descriptionSv: 'Starta i 3-punktsställning, sprinta 5 yards åt ena hållet, rör linjen, sprinta 10 yards åt motsatt håll, rör linjen, sprinta 5 yards tillbaka genom start.',
    category: 'COD',
    requiredEquipment: ['cones', 'timing_gates'],
    optionalEquipment: [],
    distanceMeters: 18.3,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up 3 cones 5 yards apart in a straight line. Start position is at middle cone in 3-point stance.',
    executionCues: ['Stay low through turns', 'Push off outside foot', 'Eyes up', 'Accelerate out of turns']
  },
  {
    name: 'T-Test',
    nameSv: 'T-Test',
    description: 'Sprint forward 10m to center cone, shuffle left 5m, shuffle right 10m, shuffle left 5m back to center, backpedal to start.',
    descriptionSv: 'Sprinta framåt 10m till mittkonen, sidosteg vänster 5m, sidosteg höger 10m, sidosteg vänster 5m tillbaka till mitten, backa till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 40,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up cones in T-shape: start cone, center cone 10m away, left and right cones 5m from center.',
    executionCues: ['Face forward entire drill', 'Stay in athletic stance', 'Touch cones with hand', 'Quick feet on direction changes']
  },
  {
    name: 'Illinois Agility Test',
    nameSv: 'Illinois-testet',
    description: 'Lie face down at start, sprint 10m, weave through 4 cones, sprint 10m, turn and repeat pattern back to start.',
    descriptionSv: 'Ligg på magen vid start, sprinta 10m, väva genom 4 koner, sprinta 10m, vänd och upprepa mönstret tillbaka till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 60,
    defaultReps: 2,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Set up 10m x 5m rectangle with 4 cones in center spaced 3.3m apart for weaving.',
    executionCues: ['Explosive start from prone', 'Stay low through cones', 'Tight turns around cones', 'Accelerate on straights']
  },
  {
    name: 'L-Drill (3 Cone Drill)',
    nameSv: 'L-Drill (3-konövning)',
    description: 'Sprint 5 yards, touch line, return to start, sprint 5 yards again, turn left around cone, weave figure-8 around second cone, return.',
    descriptionSv: 'Sprinta 5 yards, rör linjen, återvänd till start, sprinta 5 yards igen, sväng vänster runt konen, väv figur-8 runt andra konen, återvänd.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 27,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Set up 3 cones in L-shape, each 5 yards apart.',
    executionCues: ['Plant and drive', 'Low center of gravity', 'Quick hip rotation', 'Eyes forward']
  },
  {
    name: 'Arrowhead Agility Test',
    nameSv: 'Pilspets-agilitytest',
    description: 'Sprint forward to center cone, angle left to outer cone, return through center, angle right to outer cone, return through start.',
    descriptionSv: 'Sprinta framåt till mittkonen, vinkla vänster till yttre konen, återvänd genom mitten, vinkla höger till yttre konen, återvänd genom start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 24,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_FLOORBALL', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set cones in arrowhead pattern: start, center 10m away, left and right cones at 45-degree angles from center.',
    executionCues: ['Approach cone at angle', 'Plant outside foot', 'Drive off planted foot', 'Maintain speed through turns']
  },
  {
    name: '180-Degree Turns',
    nameSv: '180-graders vändningar',
    description: 'Sprint 10m, perform 180-degree turn around cone, sprint back. Alternate left and right turn directions.',
    descriptionSv: 'Sprinta 10m, utför 180-graders vändning runt konen, sprinta tillbaka. Alternera vänster och höger vändningsriktning.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Place single cone 10m from start line.',
    executionCues: ['Decelerate efficiently', 'Drop hips to turn', 'Push off outside foot', 'Accelerate immediately']
  },
  {
    name: 'Box Drill',
    nameSv: 'Rutövning',
    description: 'Navigate a 5m x 5m box pattern: sprint forward, shuffle right, backpedal, shuffle left back to start.',
    descriptionSv: 'Navigera ett 5m x 5m rutmönster: sprinta framåt, sidosteg höger, backa, sidosteg vänster tillbaka till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up 4 cones in 5m x 5m square.',
    executionCues: ['Stay in athletic stance', 'Face forward throughout', 'Quick direction changes', 'Touch each cone']
  },
  {
    name: 'Star Drill',
    nameSv: 'Stjärnövning',
    description: 'From center, sprint to each of 5 outer cones and back, covering all points of a star pattern.',
    descriptionSv: 'Från mitten, sprinta till var och en av 5 yttre koner och tillbaka, täck alla punkter i ett stjärnmönster.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 50,
    defaultReps: 2,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_BASKETBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set center cone with 5 outer cones at 5m distance in star pattern (like points on a star).',
    executionCues: ['Sprint to outer cone', 'Touch and return', 'Quick feet at center', 'Maintain intensity throughout']
  },
  {
    name: 'W-Drill',
    nameSv: 'W-övning',
    description: 'Sprint diagonally between cones set in W pattern, combining forward sprints with angle cuts.',
    descriptionSv: 'Sprinta diagonalt mellan koner placerade i W-mönster, kombinera framåtsprintar med vinkelbyten.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 25,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set 5 cones in W pattern with 5m between each cone.',
    executionCues: ['Plant and cut at each cone', 'Stay low', 'Quick direction change', 'Accelerate between cones']
  },
  {
    name: 'Lane Agility (Basketball)',
    nameSv: 'Lane Agility (Basketball)',
    description: 'Navigate basketball key area: sprint forward, defensive slide left, backpedal, defensive slide right, sprint to finish.',
    descriptionSv: 'Navigera basketplanens målområde: sprinta framåt, försvarsrörelse vänster, backa, försvarsrörelse höger, sprinta i mål.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 28,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set cones to match basketball key dimensions (4.9m x 5.8m).',
    executionCues: ['Stay low in defensive slides', 'Quick hip transitions', 'Face baseline throughout', 'Explosive starts']
  },

  // ==================== REACTIVE AGILITY ====================
  {
    name: 'Mirror Drill (Partner)',
    nameSv: 'Spegelövning (partner)',
    description: 'Face partner 2m apart. Leader moves laterally, follower mirrors movements. React to sudden direction changes.',
    descriptionSv: 'Stå mittemot partner 2m ifrån varandra. Ledaren rör sig i sidled, följaren speglar rörelserna. Reagera på plötsliga riktningsändringar.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    durationSeconds: 20,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 40,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark 5m wide zone. Partners face each other 2m apart.',
    executionCues: ['Stay in athletic stance', 'React to hips not shoulders', 'Quick first step', 'Stay balanced']
  },
  {
    name: 'Reaction Ball Catches',
    nameSv: 'Reaktionsboll fångningar',
    description: 'Drop or throw reaction ball (hexagonal ball) and catch on unpredictable bounce.',
    descriptionSv: 'Släpp eller kasta reaktionsboll (hexagonal boll) och fånga vid oförutsägbar studs.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['reaction_ball'],
    optionalEquipment: ['wall'],
    durationSeconds: 30,
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL', 'TEAM_VOLLEYBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Use against wall or partner throws. Start 2-3m from wall.',
    executionCues: ['Stay ready position', 'React quickly', 'Use peripheral vision', 'Soft hands on catch']
  },
  {
    name: 'Blazepod Reaction Lights',
    nameSv: 'Blazepod reaktionsljus',
    description: 'React to randomly illuminating light pods, touching each as quickly as possible.',
    descriptionSv: 'Reagera på slumpmässigt tändande ljuspods, rör varje så snabbt som möjligt.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['reaction_lights'],
    optionalEquipment: ['cones'],
    durationSeconds: 30,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_ICE_HOCKEY', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Place 4-6 light pods in pattern appropriate for sport. Set reaction time and sequence in app.',
    executionCues: ['Central starting position', 'Use peripheral vision', 'Quick first step', 'Return to center']
  },
  {
    name: 'Coach Signal Reaction',
    nameSv: 'Coachsignal reaktion',
    description: 'React to visual or audio signals from coach indicating direction of movement.',
    descriptionSv: 'Reagera på visuella eller ljudsignaler från coach som indikerar rörelseriktning.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: [],
    optionalEquipment: ['cones', 'whistle'],
    durationSeconds: 30,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up movement area with cones. Coach stands visible to athletes.',
    executionCues: ['Watch coach peripherally', 'React to first cue', 'Explosive start', 'Commit to direction']
  },
  {
    name: 'Random Sprint Directions',
    nameSv: 'Slumpmässiga sprintriktningar',
    description: 'From center, sprint to randomly called numbered cones (1-4 or 1-6 pattern).',
    descriptionSv: 'Från mitten, sprinta till slumpmässigt kallade numrerade koner (1-4 eller 1-6 mönster).',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set numbered cones in circle or diamond pattern around center position, 5m from center.',
    executionCues: ['Stay ready', 'React immediately to call', 'Sprint to cone and back', 'Quick recovery to center']
  },
  {
    name: 'Tennis Ball Drop',
    nameSv: 'Tennisbollssläpp',
    description: 'Partner holds tennis ball at shoulder height, drops randomly. Catch before second bounce.',
    descriptionSv: 'Partner håller tennisboll i axelhöjd, släpper slumpmässigt. Fånga före andra studsen.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['tennis_ball'],
    optionalEquipment: [],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand 2m from partner who holds ball at shoulder height.',
    executionCues: ['Watch the ball', 'Explosive first step', 'Low catch position', 'Soft hands']
  },
  {
    name: 'Y-Test with Decision',
    nameSv: 'Y-test med beslut',
    description: 'Sprint forward, at decision point react to signal and cut left or right to finish.',
    descriptionSv: 'Sprinta framåt, vid beslutspunkten reagera på signal och sväng vänster eller höger till mål.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['reaction_lights'],
    distanceMeters: 15,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up Y-pattern: start cone, decision cone 10m away, finish cones 5m at 45-degree angles.',
    executionCues: ['Full speed to decision point', 'React late', 'Plant and cut sharply', 'Accelerate through finish']
  },
  {
    name: 'Agility Ladder with Random Exits',
    nameSv: 'Stege med slumpmässiga utgångar',
    description: 'Navigate agility ladder, on signal exit and sprint to designated side cone.',
    descriptionSv: 'Navigera agilitetsstege, på signal avsluta och sprinta till angiven sidokägle.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['agility_ladder', 'cones'],
    optionalEquipment: ['whistle'],
    distanceMeters: 10,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Place agility ladder with cones 3m to each side for sprint exits.',
    executionCues: ['Maintain ladder rhythm', 'Listen for signal', 'Explosive lateral exit', 'Sprint through cone']
  },

  // ==================== SPEED & ACCELERATION ====================
  {
    name: '10m Sprint',
    nameSv: '10m sprint',
    description: 'Maximal acceleration sprint over 10 meters from standing or 3-point stance.',
    descriptionSv: 'Maximal accelerationssprint över 10 meter från stående eller 3-punktsställning.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark start and finish lines 10m apart. Optional timing gates at both ends.',
    executionCues: ['Explosive first step', 'Forward lean', 'Drive knees high', 'Pump arms hard']
  },
  {
    name: '20m Sprint',
    nameSv: '20m sprint',
    description: 'Acceleration sprint developing into max velocity over 20 meters.',
    descriptionSv: 'Accelerationssprint som utvecklas till maxhastighet över 20 meter.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL', 'RUNNING'],
    difficultyLevel: 2,
    setupInstructions: 'Mark start and finish lines 20m apart.',
    executionCues: ['Strong start', 'Gradual rise to upright', 'Drive through finish', 'Relax face and shoulders']
  },
  {
    name: '40m Sprint',
    nameSv: '40m sprint',
    description: 'Full acceleration and max velocity sprint over 40 meters.',
    descriptionSv: 'Full acceleration och maxhastighetssprint över 40 meter.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 40,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING'],
    difficultyLevel: 3,
    setupInstructions: 'Mark start and finish lines 40m apart. Split timing at 10m and 20m optional.',
    executionCues: ['Powerful drive phase', 'Rise gradually', 'Maintain mechanics at max velocity', 'Run through finish']
  },
  {
    name: 'Flying 10m',
    nameSv: 'Flygande 10m',
    description: 'Build-up zone followed by timed 10m at maximum velocity.',
    descriptionSv: 'Uppbyggnadszon följt av tidtagning på 10m med maximal hastighet.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones', 'timing_gates'],
    optionalEquipment: [],
    distanceMeters: 30,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark 20m build-up zone, then 10m timed section.',
    executionCues: ['Build to max speed in zone', 'Maintain velocity through timing', 'Relaxed at top speed', 'Tall posture']
  },
  {
    name: 'Acceleration Ladder',
    nameSv: 'Accelerationsstege',
    description: 'Progressive sprints: 5m, 10m, 15m, 20m with walk-back recovery.',
    descriptionSv: 'Progressiva sprinter: 5m, 10m, 15m, 20m med gång-tillbaka återhämtning.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 50,
    defaultReps: 1,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark cones at 5m, 10m, 15m, and 20m from start.',
    executionCues: ['Max effort each sprint', 'Walk back for recovery', 'Focus on technique', 'Maintain quality']
  },
  {
    name: 'Sprint with Resistance Band',
    nameSv: 'Sprint med motståndsband',
    description: 'Partner-resisted sprints using resistance band for overspeed training effect.',
    descriptionSv: 'Partnermotståndssprinter med motståndsband för överhastighetstränande effekt.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['resistance_band'],
    optionalEquipment: ['cones'],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Attach band around waist. Partner provides resistance from behind.',
    executionCues: ['Drive against resistance', 'Forward lean', 'Powerful arm action', 'Quick foot contacts']
  },
  {
    name: 'Hill Sprints',
    nameSv: 'Backsprinter',
    description: 'Sprint up moderate incline (5-10%) to develop acceleration power.',
    descriptionSv: 'Sprinta uppför moderat lutning (5-10%) för att utveckla accelerationskraft.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 30,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING'],
    difficultyLevel: 4,
    setupInstructions: 'Find grassy hill with 5-10% gradient. Mark 20-30m sprint distance.',
    executionCues: ['Drive knees high', 'Pump arms powerfully', 'Lean into hill', 'Walk down for recovery']
  },
  {
    name: 'Standing Triple Jump for Distance',
    nameSv: 'Stående tresteg för längd',
    description: 'Horizontal plyometric: hop, step, jump for maximum distance.',
    descriptionSv: 'Horisontell plyometrisk: hopp, steg, hopp för maximal distans.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: [],
    optionalEquipment: ['measuring_tape'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark starting line. Ensure soft landing surface. Mark best distance.',
    executionCues: ['Explosive takeoff', 'Drive knee forward', 'Swing arms', 'Land balanced']
  },

  // ==================== PLYOMETRICS ====================
  {
    name: 'Box Jumps',
    nameSv: 'Lådhopp',
    description: 'Jump onto box from standing position, step down, repeat.',
    descriptionSv: 'Hoppa upp på låda från stående position, steg ner, upprepa.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Place box on stable surface. Start with 12-18 inch height and progress.',
    executionCues: ['Arms back to start', 'Swing arms up', 'Drive knees up', 'Land softly on box', 'Step down']
  },
  {
    name: 'Broad Jump',
    nameSv: 'Längdhopp från stående',
    description: 'Maximum distance horizontal jump from standing position.',
    descriptionSv: 'Maximal distans horisontellt hopp från stående position.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['measuring_tape'],
    distanceMeters: 3,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'RUNNING'],
    difficultyLevel: 2,
    setupInstructions: 'Mark starting line. Ensure clear landing area with good surface.',
    executionCues: ['Load hips back', 'Swing arms', 'Explode forward', 'Reach forward on landing']
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Sidohopp',
    description: 'Continuous lateral hops over line or mini hurdle, single or double leg.',
    descriptionSv: 'Kontinuerliga sidohopp över linje eller minihäck, ett eller två ben.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['mini_hurdles'],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark line or place mini hurdle. Progress from line to higher obstacles.',
    executionCues: ['Stay in athletic stance', 'Push off outside leg', 'Quick ground contact', 'Arms for balance']
  },
  {
    name: 'Single-Leg Bounds',
    nameSv: 'Enkelbenhopp',
    description: 'Continuous forward bounds on single leg, focusing on distance and height.',
    descriptionSv: 'Kontinuerliga framåthopp på ett ben, fokus på distans och höjd.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 30,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Mark 30m distance. Ensure flat, even surface.',
    executionCues: ['Drive knee forward', 'Extend hip fully', 'Swing opposite arm', 'Active landing']
  },
  {
    name: 'Depth Jumps',
    nameSv: 'Djuphopp',
    description: 'Step off box, absorb landing, immediately jump up. Develops reactive strength.',
    descriptionSv: 'Kliv av låda, absorbera landning, hoppa omedelbart upp. Utvecklar reaktiv styrka.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_FOOTBALL'],
    difficultyLevel: 5,
    setupInstructions: 'Start with 12 inch box. Progress height gradually. Maximum 27 contacts per session.',
    executionCues: ['Step off, dont jump off', 'Minimal ground time', 'Explode upward', 'Land softly on box']
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Knälyft-hopp',
    description: 'Jump and bring knees to chest at peak height, land softly and repeat.',
    descriptionSv: 'Hoppa och för knäna till bröstet på topphöjden, landa mjukt och upprepa.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Clear area required. Ensure good footing surface.',
    executionCues: ['Drive arms up', 'Pull knees high', 'Quick hip flexion', 'Extend before landing']
  },
  {
    name: 'Pogo Hops',
    nameSv: 'Pogo-hopp',
    description: 'Continuous small hops with minimal knee bend, focus on ankle stiffness.',
    descriptionSv: 'Kontinuerliga små hopp med minimal knäböjning, fokus på fotledsstyvhet.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 20,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['RUNNING', 'TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS'],
    difficultyLevel: 1,
    setupInstructions: 'Stand in place on firm surface.',
    executionCues: ['Stiff ankles', 'Minimal knee bend', 'Quick ground contact', 'Stay tall']
  },
  {
    name: 'Hurdle Hops (Continuous)',
    nameSv: 'Häckhopp (kontinuerliga)',
    description: 'Continuous forward hops over series of mini hurdles.',
    descriptionSv: 'Kontinuerliga framåthopp över serie av minihäckar.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['mini_hurdles'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'RUNNING', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set 5-6 hurdles in line, spacing 1m apart. Height 6-18 inches based on ability.',
    executionCues: ['Arms drive upward', 'Quick feet over hurdles', 'Land softly', 'Immediately spring up']
  },
  {
    name: 'Split Squat Jumps',
    nameSv: 'Splithopp',
    description: 'Jump from lunge position, switch legs in air, land in lunge position.',
    descriptionSv: 'Hoppa från utfallsposition, byt ben i luften, landa i utfallsposition.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Clear area required. Start in lunge position.',
    executionCues: ['Drive through front leg', 'Get height', 'Switch legs quickly', 'Land softly in lunge']
  },
  {
    name: 'Rotational Box Jump',
    nameSv: 'Rotationshopp',
    description: 'Jump onto box with 90 or 180 degree rotation.',
    descriptionSv: 'Hoppa upp på låda med 90 eller 180 graders rotation.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Place lower box than normal box jumps. Start with 90-degree rotations.',
    executionCues: ['Swing arms for rotation', 'Turn head first', 'Land stable', 'Step down controlled']
  },

  // ==================== FOOTWORK ====================
  {
    name: 'Ladder - In-In-Out-Out (Icky Shuffle)',
    nameSv: 'Stege - In-In-Ut-Ut',
    description: 'Classic ladder pattern: both feet in square, both feet out sides, repeat down ladder.',
    descriptionSv: 'Klassiskt stegemönster: båda fötterna i rutan, båda fötterna ut på sidorna, upprepa nedför stegen.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Lay ladder flat on ground. Stand at one end.',
    executionCues: ['Stay on balls of feet', 'Quick feet', 'Arms bent at 90 degrees', 'Eyes up']
  },
  {
    name: 'Ladder - Lateral Shuffle',
    nameSv: 'Stege - Sidosteg',
    description: 'Move laterally through ladder, two feet in each square.',
    descriptionSv: 'Rör dig i sidled genom stegen, två fötter i varje ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL', 'TEAM_HANDBALL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand beside ladder at one end.',
    executionCues: ['Stay low', 'Quick shuffle', 'Dont cross feet', 'Face forward']
  },
  {
    name: 'Ladder - Single Leg Hops',
    nameSv: 'Stege - Enkelbenhopp',
    description: 'Hop through ladder on single leg, one foot per square.',
    descriptionSv: 'Hoppa genom stegen på ett ben, en fot per ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Lay ladder flat. Do both legs each set.',
    executionCues: ['Stay balanced', 'Quick hops', 'Use arms', 'Land softly']
  },
  {
    name: 'Ladder - High Knees',
    nameSv: 'Stege - Höga knän',
    description: 'Run through ladder with high knee drive, one foot per square.',
    descriptionSv: 'Spring genom stegen med höga knälyft, en fot per ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Stand at ladder end. Focus on knee height.',
    executionCues: ['Drive knees up', 'Quick contacts', 'Stay tall', 'Pump arms']
  },
  {
    name: 'Cone Zig-Zag',
    nameSv: 'Kon zigzag',
    description: 'Sprint diagonally between staggered cones, cutting at each cone.',
    descriptionSv: 'Sprinta diagonalt mellan förskjutna koner, sväng vid varje kon.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set 6-8 cones in zigzag pattern, 2-3m apart.',
    executionCues: ['Plant outside foot', 'Stay low', 'Quick direction change', 'Accelerate between cones']
  },
  {
    name: 'Quick Feet Drill',
    nameSv: 'Snabba fötter-övning',
    description: 'Rapid foot movement in place or over line, maximum speed footwork.',
    descriptionSv: 'Snabba fotrörelsen på stället eller över linje, maximal hastighet.',
    category: 'FOOTWORK',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    durationSeconds: 10,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand in athletic stance. Optional line or cone as reference.',
    executionCues: ['Balls of feet only', 'Maximum turnover', 'Stay light', 'Arms at 90 degrees']
  },
  {
    name: 'Figure 8 Around Cones',
    nameSv: 'Figur-8 runt koner',
    description: 'Navigate figure 8 pattern around two cones with continuous movement.',
    descriptionSv: 'Navigera figur-8 mönster runt två koner med kontinuerlig rörelse.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Place two cones 3-4m apart.',
    executionCues: ['Stay low', 'Tight turns', 'Push off outside foot', 'Control through curves']
  },
  {
    name: 'Ali Shuffle',
    nameSv: 'Ali-shuffle',
    description: 'Quick alternating forward-back foot pattern in place.',
    descriptionSv: 'Snabbt alternerande fram-bak fotmönster på stället.',
    category: 'FOOTWORK',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 15,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Stand in place, athletic stance.',
    executionCues: ['Light on feet', 'Quick switches', 'Stay centered', 'Relaxed upper body']
  },

  // ==================== BALANCE ====================
  {
    name: 'Single-Leg Balance',
    nameSv: 'Enkelbenbalans',
    description: 'Stand on single leg maintaining balance for specified time.',
    descriptionSv: 'Stå på ett ben och håll balansen under angiven tid.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 30,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 15,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand on flat surface. Progress to unstable surfaces.',
    executionCues: ['Eyes forward', 'Slight knee bend', 'Core engaged', 'Arms for balance']
  },
  {
    name: 'Single-Leg Balance with Eyes Closed',
    nameSv: 'Enkelbenbalans med slutna ögon',
    description: 'Single-leg balance with eyes closed to challenge proprioception.',
    descriptionSv: 'Enkelbenbalans med slutna ögon för att utmana proprioception.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 20,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 15,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING'],
    difficultyLevel: 2,
    setupInstructions: 'Ensure safe area. Progress from firm to unstable surface.',
    executionCues: ['Close eyes smoothly', 'Micro-adjustments', 'Core tight', 'Relax breathing']
  },
  {
    name: 'BOSU Single-Leg Balance',
    nameSv: 'BOSU enkelbenbalans',
    description: 'Single-leg balance on BOSU ball surface.',
    descriptionSv: 'Enkelbenbalans på BOSU-bollens yta.',
    category: 'BALANCE',
    requiredEquipment: ['bosu_ball'],
    optionalEquipment: [],
    durationSeconds: 30,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Place BOSU flat side down. Stand on dome side.',
    executionCues: ['Find center', 'Engage core', 'Micro-adjust ankle', 'Use arms if needed']
  },
  {
    name: 'Y-Balance Test Drill',
    nameSv: 'Y-balanstestövning',
    description: 'Reach in three directions (anterior, posterolateral, posteromedial) while standing on single leg.',
    descriptionSv: 'Nå i tre riktningar (framåt, posterolateral, posteromedial) medan du står på ett ben.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['y_balance_kit'],
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'RUNNING'],
    difficultyLevel: 3,
    setupInstructions: 'Mark Y-pattern on floor or use Y-balance kit.',
    executionCues: ['Control throughout', 'Reach as far as possible', 'Return to start', 'Maintain balance']
  },
  {
    name: 'Dynamic Balance Reaches',
    nameSv: 'Dynamiska balansnådder',
    description: 'Single-leg stance with reaches in multiple directions for dynamic stability.',
    descriptionSv: 'Enstående ställning med nådder i flera riktningar för dynamisk stabilitet.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    defaultReps: 8,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up cones in arc around standing position.',
    executionCues: ['Stable stance leg', 'Controlled reaches', 'Return to center', 'Progress speed']
  },
  {
    name: 'Perturbation Training',
    nameSv: 'Perturbationsträning',
    description: 'Partner provides random pushes while athlete maintains single-leg balance.',
    descriptionSv: 'Partner ger slumpmässiga skuff medan atleten håller enkelbenbalans.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['stability_pad'],
    durationSeconds: 20,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Partner stands ready to apply light, random pushes to hips and shoulders.',
    executionCues: ['Stay reactive', 'Quick recovery', 'Use core', 'Anticipate in game-like way']
  }
]

async function main() {
  console.log('Seeding agility drills...')

  let created = 0
  let skipped = 0

  for (const drill of agilityDrills) {
    // Check if drill already exists
    const existing = await prisma.agilityDrill.findFirst({
      where: {
        name: drill.name,
        isSystemDrill: true
      }
    })

    if (existing) {
      console.log(`Skipping existing drill: ${drill.name}`)
      skipped++
      continue
    }

    await prisma.agilityDrill.create({
      data: {
        name: drill.name,
        nameSv: drill.nameSv,
        description: drill.description,
        descriptionSv: drill.descriptionSv,
        category: drill.category,
        requiredEquipment: drill.requiredEquipment,
        optionalEquipment: drill.optionalEquipment,
        distanceMeters: drill.distanceMeters,
        durationSeconds: drill.durationSeconds,
        defaultReps: drill.defaultReps,
        defaultSets: drill.defaultSets,
        restSeconds: drill.restSeconds,
        minDevelopmentStage: drill.minDevelopmentStage,
        maxDevelopmentStage: drill.maxDevelopmentStage,
        primarySports: drill.primarySports,
        difficultyLevel: drill.difficultyLevel,
        setupInstructions: drill.setupInstructions,
        executionCues: drill.executionCues,
        isSystemDrill: true
      }
    })

    console.log(`Created drill: ${drill.name}`)
    created++
  }

  console.log(`\nSeeding complete!`)
  console.log(`Created: ${created} drills`)
  console.log(`Skipped: ${skipped} existing drills`)
  console.log(`Total in library: ${agilityDrills.length}`)
}

main()
  .catch((e) => {
    console.error('Error seeding drills:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
