// prisma/seed-exercises.ts
// Comprehensive exercise library based on scientific strength training framework
// Run with: npx ts-node prisma/seed-exercises.ts

import { PrismaClient, BiomechanicalPillar, ProgressionLevel, PlyometricIntensity } from '@prisma/client'

const prisma = new PrismaClient()

const exercises = [
  // ========================================
  // POSTERIOR CHAIN (Hip Dominance)
  // ========================================
  {
    name: 'Höftbrygga',
    nameSv: 'Höftbrygga',
    nameEn: 'Glute Bridge',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Grundläggande gluteus-aktivering',
    instructions: '1. Ligg på rygg med knän böjda\n2. Fötterna platt i golvet\n3. Lyft höften uppåt\n4. Spänn skinkor i toppen\n5. Sänk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    isPublic: true,
  },
  {
    name: 'Enbensbrygga',
    nameSv: 'Enbensbrygga',
    nameEn: 'Single-Leg Glute Bridge',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig gluteus-styrka',
    instructions: '1. Ligg på rygg med ena benet sträckt\n2. Lyft höften på ett ben\n3. Håll höfterna jämna\n4. Spänn skinkan\n5. Växla ben',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Clamshells med band',
    nameSv: 'Clamshells med band',
    nameEn: 'Clamshells with Band',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Gluteus medius aktivering - förebygger knävalgus',
    instructions: '1. Ligg på sidan med knän böjda\n2. Band runt knäna\n3. Öppna översta knät\n4. Motstå bandet\n5. Håll höfterna stabila',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=Wwq_VGpXd6s',
    isPublic: true,
  },
  {
    name: 'Hip hikes',
    nameSv: 'Hip hikes',
    nameEn: 'Hip Hikes',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Förebygger höftdropp under löpning',
    instructions: '1. Stå på en fot på steglåda\n2. Sänk motsatt höft\n3. Lyft höften med gluteus medius\n4. Kontrollerad rörelse',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Fire Hydrants',
    nameSv: 'Fire Hydrants',
    nameEn: 'Fire Hydrants',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Höftabduktion för gluteus medius',
    instructions: '1. På alla fyra\n2. Lyft knät ut åt sidan\n3. Håll 90 graders böjning i knät\n4. Spänn glut',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Hip Thrust med skivstång',
    nameSv: 'Hip Thrust med skivstång',
    nameEn: 'Barbell Hip Thrust',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Maximal gluteus-styrka',
    instructions: '1. Rygg mot bänk\n2. Skivstång över höfterna\n3. Tryck höfterna uppåt\n4. Posteriort pelvis tilt i toppen\n5. Sänk kontrollerat',
    equipment: 'Skivstång, bänk, pad',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
    isPublic: true,
  },
  {
    name: 'Rumänsk marklyft',
    nameSv: 'Rumänsk marklyft',
    nameEn: 'Romanian Deadlift (RDL)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerar hases och gluteus med excentrisk betoning',
    instructions: '1. Håll stången med raka armar\n2. Böj i höften med lätt böjda knän\n3. Känn stretch i hases\n4. Tryck höfterna framåt\n5. Behåll neutral rygg',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=r8VxLWzclSo',
    isPublic: true,
  },
  {
    name: 'Enbenig rumänsk marklyft',
    nameSv: 'Enbenig rumänsk marklyft',
    nameEn: 'Single-Leg Romanian Deadlift',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, Gluteus, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig hases-styrka och proprioception',
    instructions: '1. Stå på ett ben\n2. Böj i höften\n3. Sträck fritt ben bakåt\n4. Balansera\n5. Återgå upprätt',
    equipment: 'Hantlar eller kettlebell',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=jKw5_TaPogE',
    isPublic: true,
  },
  {
    name: 'Good Mornings',
    nameSv: 'Good Mornings',
    nameEn: 'Good Mornings',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, Ländryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Posterior chain med betoning på excentrisk kontroll',
    instructions: '1. Skivstång på axlarna\n2. Böj framåt i höften\n3. Parallell rygg med golvet\n4. Stretch i hases\n5. Återgå upprätt',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Cable Pull-Through',
    nameSv: 'Cable Pull-Through',
    nameEn: 'Cable Pull-Through',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Höftextension med kabel-motstånd',
    instructions: '1. Stå med ryggen mot kabel\n2. Hantag mellan benen\n3. Böj i höften\n4. Sträck höfterna kraftfullt\n5. Spänn glut i toppen',
    equipment: 'Kabel',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Kettlebell Swing',
    nameSv: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Explosiv höftextension - power development',
    instructions: '1. Bred ställning\n2. Swing kettlebell mellan benen\n3. Explosiv höftsträckning\n4. Armarna passiva\n5. Ballistisk rörelse',
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
    isPublic: true,
  },
  {
    name: 'Marklyft',
    nameSv: 'Marklyft',
    nameEn: 'Deadlift',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp - Posterior Chain',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Helkroppsövning med fokus på bakre kedjan',
    instructions: '1. Stå med fötterna höftbrett\n2. Böj i höften och grip stången\n3. Neutral rygg\n4. Lyft genom höft- och knäextension\n5. Lås ut i toppen',
    equipment: 'Skivstång',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    isPublic: true,
  },
  {
    name: 'Reverse Hyperextension',
    nameSv: 'Reverse Hyperextension',
    nameEn: 'Reverse Hyperextension',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases, Ländryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Gluteus och hases utan ryggbelastning',
    instructions: '1. Ligg på bänk med höfterna i kanten\n2. Låt benen hänga\n3. Lyft benen bakåt och uppåt\n4. Spänn glut\n5. Sänk kontrollerat',
    equipment: 'Bänk',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // KNEE DOMINANCE (Quadriceps Strength)
  // ========================================
  {
    name: 'Knäböj',
    nameSv: 'Knäböj',
    nameEn: 'Back Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Grundläggande bilateral benstyrka',
    instructions: '1. Skivstång på axlarna\n2. Fötterna axelbrett\n3. Sänk dig nedåt\n4. Höften under parallell\n5. Tryck upp explosivt',
    equipment: 'Skivstång, rack',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    isPublic: true,
  },
  {
    name: 'Goblet Squat',
    nameSv: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Lär squat-mönster med upprätt bål',
    instructions: '1. Håll kettlebell/hantel vid bröstet\n2. Böj i knän och höfter\n3. Armbågarna mellan knäna\n4. Djup squat\n5. Tryck upp',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    isPublic: true,
  },
  {
    name: 'Wall Sit',
    nameSv: 'Väggstol',
    nameEn: 'Wall Sit',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isometrisk quad-styrka',
    instructions: '1. Rygg mot vägg\n2. Sänk till 90 grader\n3. Knän över anklar\n4. Håll positionen\n5. Spänn quads',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Front Squat',
    nameSv: 'Front Squat',
    nameEn: 'Front Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Quad-dominant squat med upprätt bål',
    instructions: '1. Skivstång på främre deltoider\n2. Armbågarna högt\n3. Squat med upprätt bål\n4. Djup position\n5. Tryck upp',
    equipment: 'Skivstång, rack',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=wzqXrGi1Gl4',
    isPublic: true,
  },
  {
    name: 'Split Squat',
    nameSv: 'Split Squat',
    nameEn: 'Split Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Statisk split position för quad-styrka',
    instructions: '1. Splitställning\n2. Bakre knä sänks mot golvet\n3. Främre knä över ankel\n4. Upprätt bål\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Benpress',
    nameSv: 'Benpress',
    nameEn: 'Leg Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Benstyrka utan ryggbelastning',
    instructions: '1. Fötterna på plattan\n2. Sänk kontrollerat\n3. Knän mot bröst\n4. Tryck upp kraftfullt\n5. Lås inte knäna helt',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Pistol Squat Progression',
    nameSv: 'Pistol Squat Progression',
    nameEn: 'Pistol Squat Progression',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Enbenssquat för avancerad styrka',
    instructions: '1. Stå på ett ben\n2. Sträck andra benet framåt\n3. Squat hela vägen ner\n4. Balansera\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Cyclist Squat',
    nameSv: 'Cyclist Squat',
    nameEn: 'Cyclist Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerad quad-styrka med hällyft',
    instructions: '1. Hälarna på platta (5-10cm)\n2. Upprätt bål\n3. Smal ställning\n4. Djup squat\n5. Quad-dominant',
    equipment: 'Hantlar, platta',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Hoppsquat',
    nameSv: 'Hoppsquat',
    nameEn: 'Jump Squat',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Explosiv quad-power',
    instructions: '1. Squat position\n2. Explosiv hopp\n3. Armsving\n4. Mjuk landning\n5. Direkt i nästa rep',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    isPublic: true,
  },

  // ========================================
  // UNILATERAL (Single-Leg Bias)
  // ========================================
  {
    name: 'Bulgarisk utfallsböj',
    nameSv: 'Bulgarisk utfallsböj',
    nameEn: 'Bulgarian Split Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig benstyrka - "The Big Three" för löpare',
    instructions: '1. Bakre fot på bänk\n2. Främre fot framåt\n3. Sänk bakre knä\n4. Upprätt bål\n5. Tryck upp på främre ben',
    equipment: 'Bänk, hantlar (valfritt)',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    isPublic: true,
  },
  {
    name: 'Utfallssteg',
    nameSv: 'Utfallssteg',
    nameEn: 'Walking Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk enbensstyrka',
    instructions: '1. Steg framåt\n2. Sänk bakre knä\n3. 90 grader i båda knäna\n4. Tryck upp\n5. Upprepa med annat ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
    isPublic: true,
  },
  {
    name: 'Bakåtlunges',
    nameSv: 'Bakåtlunges',
    nameEn: 'Reverse Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Mer knävänlig än framåtlunges',
    instructions: '1. Steg bakåt\n2. Sänk bakre knä\n3. Främre knä stabilt över ankel\n4. Tryck upp\n5. Växla ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Lateral Lunges',
    nameSv: 'Lateral Lunges',
    nameEn: 'Lateral Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Adduktorer, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Frontalplanstyrka',
    instructions: '1. Steg åt sidan\n2. Böj i ett knä\n3. Andra benet rakt\n4. Sitt bakåt\n5. Tryck upp och tillbaka',
    equipment: 'Ingen eller hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Curtsy Lunges',
    nameSv: 'Curtsy Lunges',
    nameEn: 'Curtsy Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius, Quadriceps',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Gluteus medius och höftrotation',
    instructions: '1. Steg diagonalt bakåt\n2. Korsa bakom stående ben\n3. Sänk i utfallsposition\n4. Håll höfterna framåt\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Step-Ups (låg)',
    nameSv: 'Step-Ups (låg)',
    nameEn: 'Step-Ups (Low Box)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Grundläggande enbensstyrka',
    instructions: '1. Låg låda (30-40cm)\n2. Placera fot på lådan\n3. Tryck upp med det benet\n4. Stå stadigt\n5. Sänk kontrollerat',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Step-Ups (hög)',
    nameSv: 'Step-Ups (hög)',
    nameEn: 'Step-Ups (High Box)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Avancerad enbensstyrka',
    instructions: '1. Hög låda (50-60cm)\n2. Explosiv uppgång\n3. Hela foten på lådan\n4. Lås ut höft och knä\n5. Kontrollerad nedgång',
    equipment: 'Steglåda, hantlar',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Step-Ups med knädrive',
    nameSv: 'Step-Ups med knädrive',
    nameEn: 'Step-Ups with Knee Drive',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Höftflexorer',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Löpspecifik knädrive',
    instructions: '1. Step-up på låda\n2. Svinga fria benet\n3. Knä högt (90 grader)\n4. Balansera på stående ben\n5. Kontrollerad nedgång',
    equipment: 'Steglåda',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    isPublic: true,
  },
  {
    name: 'Enbenig benpress',
    nameSv: 'Enbenig benpress',
    nameEn: 'Single-Leg Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerad enbensstyrka',
    instructions: '1. En fot på plattan\n2. Sänk kontrollerat\n3. Djup position\n4. Tryck upp\n5. Jämför vänster/höger',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Skater Squats',
    nameSv: 'Skater Squats',
    nameEn: 'Skater Squats',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad enbenssquat',
    instructions: '1. Stå på ett ben\n2. Sänk dig nedåt\n3. Bakre ben bakom\n4. Bakre knä mot golvet\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // FOOT & ANKLE COMPLEX
  // ========================================
  {
    name: 'Tåhävningar (raka ben)',
    nameSv: 'Tåhävningar (raka ben)',
    nameEn: 'Calf Raises (Straight Knee)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gastrocnemius',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Gastrocnemius-styrka',
    instructions: '1. Stå på kant/steglåda\n2. Raka ben\n3. Tryck upp på tår\n4. Full ROM\n5. Kontrollerad sänkning',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    isPublic: true,
  },
  {
    name: 'Tåhävningar (böjda ben)',
    nameSv: 'Tåhävningar (böjda ben)',
    nameEn: 'Calf Raises (Bent Knee)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Soleus',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Soleus-fokus (viktig för löpare)',
    instructions: '1. Sittande eller lätt böjda knän\n2. Tryck upp på tår\n3. Isolerar soleus\n4. Hög volym (15-20 reps)\n5. Kontrollerad tempo',
    equipment: 'Seated calf raise (eller kroppsvikt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Enbenig tåhävning',
    nameSv: 'Enbenig tåhävning',
    nameEn: 'Single-Leg Calf Raise',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gastrocnemius, Soleus',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig vader-styrka',
    instructions: '1. Ett ben på kant\n2. Balansera\n3. Full dorsalflexion (sänk hälen)\n4. Explosiv plantarflexion\n5. Jämför bilateral skillnad',
    equipment: 'Steglåda',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=3j8-4PB0eEo',
    isPublic: true,
  },
  {
    name: 'Ankelhopp',
    nameSv: 'Ankelhopp',
    nameEn: 'Ankle Hops',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vad, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Ankelstyvhet och reaktiv styrka',
    instructions: '1. Minimalt knäböj\n2. Hopp från ankeln\n3. Snabb markkontakt\n4. Styvt ben\n5. Rytmisk',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Toe Yoga',
    nameSv: 'Toe Yoga',
    nameEn: 'Toe Yoga',
    category: 'STRENGTH' as const,
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Intrinsisk fotstyrka',
    instructions: '1. Barfota\n2. Lyft stortå\n3. Andra tår i golvet\n4. Växla\n5. Stärker fotvalv',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Marmor-pickups',
    nameSv: 'Marmor-pickups',
    nameEn: 'Marble/Towel Pickups',
    category: 'STRENGTH' as const,
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Fotvalv-styrka',
    instructions: '1. Barfota\n2. Plocka upp marmelkulor med tår\n3. Alternativ: dra handduk\n4. Stärker fotvalv\n5. Förebygger plantar fasciit',
    equipment: 'Marmelkulor eller handduk',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Ankel dorsalflexion (band)',
    nameSv: 'Ankel dorsalflexion (band)',
    nameEn: 'Ankle Dorsiflexion (Band)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Förebygger shin splints',
    instructions: '1. Band runt foten\n2. Dra tår mot smalben\n3. Dorsalflexion\n4. Kontrollerad sänkning\n5. Hög volym (20 reps)',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Hälgång',
    nameSv: 'Hälgång',
    nameEn: 'Heel Walks',
    category: 'STRENGTH' as const,
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Tibialis-styrka',
    instructions: '1. Gå på hälarna\n2. Tår uppåt\n3. Dorsalflexion under gång\n4. 20-30 meter\n5. Uppvärmning eller rehab',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ANTI-ROTATION CORE
  // ========================================
  {
    name: 'Plank',
    nameSv: 'Plank',
    nameEn: 'Plank',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-extension core',
    instructions: '1. Stöd på underarmar och tår\n2. Rak linje\n3. Spänn mage och glut\n4. Neutral nacke\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    isPublic: true,
  },
  {
    name: 'Sidplank',
    nameSv: 'Sidplank',
    nameEn: 'Side Plank',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-lateral flexion',
    instructions: '1. Ligg på sidan\n2. Stöd på underarm\n3. Lyft höften\n4. Rak linje\n5. Jämför sidor',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Dead Bug',
    nameSv: 'Dead Bug',
    nameEn: 'Dead Bug',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-extension med rörelse',
    instructions: '1. Rygg på golvet\n2. Armar upp, knän 90°\n3. Sträck motsatt arm/ben\n4. Ländryggen i golvet\n5. Växla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=g_BYB0R-4Ws',
    isPublic: true,
  },
  {
    name: 'Bird Dog',
    nameSv: 'Bird Dog',
    nameEn: 'Bird Dog',
    category: 'CORE' as const,
    muscleGroup: 'Core, Posterior Chain',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-rotation och posterior chain',
    instructions: '1. På alla fyra\n2. Sträck motsatt arm/ben\n3. Håll rygg neutral\n4. Balansera\n5. Växla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Pallof Press',
    nameSv: 'Pallof Press',
    nameEn: 'Pallof Press (Cable)',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Anti-rotation mot kabel',
    instructions: '1. Stå sidledes mot kabel\n2. Hantag vid bröstet\n3. Pressa rakt framåt\n4. Motstå rotation\n5. Håll höfterna framåt',
    equipment: 'Kabel eller resistance band',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=AH_QZLm_0-s',
    isPublic: true,
  },
  {
    name: 'Pallof Press (band)',
    nameSv: 'Pallof Press (band)',
    nameEn: 'Pallof Press (Band)',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Hemversion av pallof press',
    instructions: '1. Fäst band vid stolpe\n2. Sidledes ställning\n3. Press framåt\n4. Motstå bandets dragning\n5. Kontrollerad återgång',
    equipment: 'Resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Suitcase Carry',
    nameSv: 'Suitcase Carry',
    nameEn: 'Suitcase Carry',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Anti-lateral flexion dynamisk',
    instructions: '1. Tungt i en hand\n2. Gå framåt\n3. Motstå lateral flexion\n4. Bål upprätt\n5. 20-40 meter',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=s1MbfbOTWmA',
    isPublic: true,
  },
  {
    name: 'Farmer\'s Walk',
    nameSv: 'Farmer\'s Walk',
    nameEn: 'Farmer\'s Walk',
    category: 'CORE' as const,
    muscleGroup: 'Core, Trapezius, Grip',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Totalstyrka och stabilitet',
    instructions: '1. Tungt i båda händerna\n2. Gå framåt\n3. Upprätt hållning\n4. Axlarna tillbaka\n5. 30-50 meter',
    equipment: 'Hantlar eller kettlebells',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Ab Wheel Rollouts',
    nameSv: 'Ab Wheel Rollouts',
    nameEn: 'Ab Wheel Rollouts',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad anti-extension',
    instructions: '1. Knä på golvet\n2. Rulla hjulet framåt\n3. Sträck ut kroppen\n4. Behåll neutral ländrygen\n5. Dra tillbaka med core',
    equipment: 'Ab wheel',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=Rl1l7pDshaM',
    isPublic: true,
  },
  {
    name: 'Copenhagen Plank',
    nameSv: 'Copenhagen Plank',
    nameEn: 'Copenhagen Plank',
    category: 'CORE' as const,
    muscleGroup: 'Adduktorer, Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Adduktor-styrka (41% minskning groin injury)',
    instructions: '1. Sidplank position\n2. Övre ben på bänk\n3. Lyft höften\n4. Adduktor-kontraktion\n5. Svår övning - börja med kort hold',
    equipment: 'Bänk',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=ocGuiEnv1jE',
    isPublic: true,
  },
  {
    name: 'Stir the Pot',
    nameSv: 'Stir the Pot',
    nameEn: 'Stir the Pot',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Instabil plank variation',
    instructions: '1. Underarmar på gymnastikboll\n2. Plank position\n3. Cirkla armarna (som att röra gryta)\n4. Småcirklar\n5. Växla riktning',
    equipment: 'Gymnastikboll',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Russian Twist',
    nameSv: 'Russian Twist',
    nameEn: 'Russian Twist',
    category: 'CORE' as const,
    muscleGroup: 'Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Rotation med kontroll',
    instructions: '1. Sitt med fötterna upp\n2. Luta bakåt\n3. Rotera sida till sida\n4. Touch golvet\n5. Kontrollerad rörelse',
    equipment: 'Viktskiva (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - LOW INTENSITY (Extensive)
  // ========================================
  {
    name: 'Hopprep',
    nameSv: 'Hopprep',
    nameEn: 'Jump Rope',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Ankelstyvhet och rytm',
    instructions: '1. Minimala hopp\n2. Snabb markkontakt\n3. Ankeldominerad\n4. Rytmisk\n5. 100-200 kontakter',
    equipment: 'Hopprep',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Pogo Jumps',
    nameSv: 'Pogo Jumps',
    nameEn: 'Pogo Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: '>250ms ground contact, styvhet',
    instructions: '1. Styvt ben\n2. Minimal knäböj\n3. Hopp från ankel\n4. Snabb kontakt\n5. Sets om 15-20 reps',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=gFbxL5NDvfE',
    isPublic: true,
  },
  {
    name: 'Låga lådhopp',
    nameSv: 'Låga lådhopp',
    nameEn: 'Low Box Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Låg låda (30-40cm) för nybörjare',
    instructions: '1. Låg låda\n2. Hopp upp\n3. Mjuk landning\n4. Kliv ner (inte hoppa)\n5. 8-10 reps',
    equipment: 'Låg plyobox',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Lateral Hops',
    nameEn: 'Lateral Hops (Side to Side)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Lateral styvhet',
    instructions: '1. Hopp sida till sida\n2. Linje på golvet\n3. Snabb kontakt\n4. Rytmisk\n5. 20-30 kontakter',
    equipment: 'Ingen eller låg kon',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Skipping',
    nameSv: 'Skipping',
    nameEn: 'Skipping',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Koordination och ankelstyvhet',
    instructions: '1. Exaggererad löprörelse\n2. Knädrive\n3. Hopp på varje steg\n4. Rytmisk\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - MODERATE INTENSITY
  // ========================================
  {
    name: 'Squat Jumps',
    nameSv: 'Squat Jumps',
    nameEn: 'Squat Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Concentric focus, kontrollerad landning',
    instructions: '1. Squat position\n2. Paus i botten\n3. Explosivt hopp\n4. Mjuk landning\n5. Paus igen (ej reaktiv)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    isPublic: true,
  },
  {
    name: 'Countermovement Jumps',
    nameSv: 'Countermovement Jumps',
    nameEn: 'Countermovement Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Stretch-shortening cycle träning',
    instructions: '1. Stående position\n2. Snabb countermovement (böj)\n3. Omedelbart hopp\n4. Maximalt hopp\n5. Mjuk landning',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Lateral Bounds',
    nameSv: 'Lateral Bounds',
    nameEn: 'Lateral Bounds',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Lateral power och stabilitet',
    instructions: '1. Hoppa lateral från ett ben\n2. Landa på andra benet\n3. Stabilisera\n4. Hopp tillbaka\n5. 10-12 reps per sida',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Tuck Jumps',
    nameEn: 'Tuck Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Core',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal höjd med knädrive',
    instructions: '1. Hopp rakt upp\n2. Dra knän mot bröstet\n3. Tuck position\n4. Mjuk landning\n5. 6-8 reps',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Split Jumps',
    nameSv: 'Hoppande utfall',
    nameEn: 'Split Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 2,
    description: 'Ensidig explosivitet',
    instructions: '1. Utfallsposition\n2. Hopp och byt ben\n3. Landa i utfall\n4. Mjuk landning\n5. 10-12 totala hopp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - HIGH INTENSITY (Intensive)
  // ========================================
  {
    name: 'Lådhopp (18-24")',
    nameSv: 'Lådhopp (18-24")',
    nameEn: 'Box Jumps (18-24")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Medelhög låda för power',
    instructions: '1. Låda 46-61cm\n2. Explosivt hopp\n3. Landa mjukt\n4. Kliv ner\n5. 8-10 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=hxldG9FX4j4',
    isPublic: true,
  },
  {
    name: 'Enbenhopp (Bounds)',
    nameSv: 'Enbenhopp (Bounds)',
    nameEn: 'Single-Leg Bounds',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Löpspecifik horizontal power',
    instructions: '1. Hoppa framåt på ett ben\n2. Maximalt avstånd\n3. Mjuk landning\n4. Upprepa samma ben\n5. 20-30 meter per ben',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=FI1pCLFBr18',
    isPublic: true,
  },
  {
    name: 'Hurdle Hops',
    nameSv: 'Hurdle Hops',
    nameEn: 'Hurdle Hops',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Seriella hopp över häckar',
    instructions: '1. Rad av häckar\n2. Hopp över varje häck\n3. Minimal markkontakt\n4. Rytmisk\n5. 6-10 häckar',
    equipment: 'Häckar (30-46cm)',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Bred hopp (max)',
    nameSv: 'Bred hopp (max)',
    nameEn: 'Broad Jump (Maximal)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal horizontal power',
    instructions: '1. Armsving\n2. Explosiv hopp framåt\n3. Maximalt avstånd\n4. Mjuk landning\n5. Mät avstånd (test)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CJJ_sdtoLwY',
    isPublic: true,
  },
  {
    name: 'Triple Jump',
    nameSv: 'Triple Jump',
    nameEn: 'Triple Jump',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 3,
    description: 'Tre hopp i serie',
    instructions: '1. Hopp på höger ben\n2. Hopp på vänster ben\n3. Bred hopp med båda ben\n4. Maximalt avstånd\n5. 3-5 försök',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - ADVANCED (Depth Jumps)
  // ========================================
  {
    name: 'Depth Jumps (30cm)',
    nameSv: 'Depth Jumps (30cm)',
    nameEn: 'Depth Jumps (12")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: '<150ms ground contact, maximal RFD',
    instructions: '1. Kliv av 30cm låda\n2. Mjuk landning\n3. Omedelbart maxhopp\n4. Minimal markkontakt\n5. MAX 27 kontakter per session',
    equipment: 'Plyobox 30cm',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=dlN1bkx6cFg',
    isPublic: true,
  },
  {
    name: 'Depth Jumps (40cm)',
    nameSv: 'Depth Jumps (40cm)',
    nameEn: 'Depth Jumps (16")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Elite-level depth jump',
    instructions: '1. Kliv av 40cm låda\n2. Absorb impact\n3. Explosiv rebound\n4. Maximal höjd\n5. ENDAST för avancerade - MAX 18 kontakter',
    equipment: 'Plyobox 40cm',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Drop Jumps',
    nameSv: 'Drop Jumps',
    nameEn: 'Drop Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal reactive strength',
    instructions: '1. Kliv av låda\n2. Landa\n3. Omedelbart maxhopp uppåt\n4. <200ms contact\n5. Kräver styrka: 1.5x BW squat',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Repeated Bounds',
    nameSv: 'Repeated Bounds',
    nameEn: 'Repeated Bounds (Continuous)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Seriella enbenhopp',
    instructions: '1. Kontinuerliga enbenhopp\n2. Samma ben\n3. Snabb markkontakt\n4. Maximalt avstånd per hopp\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Depth to Broad Jump',
    nameSv: 'Depth to Broad Jump',
    nameEn: 'Depth to Broad Jump',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Vertical to horizontal power',
    instructions: '1. Kliv av låda\n2. Landa\n3. Omedelbart bred hopp framåt\n4. Maximalt horisontellt avstånd\n5. 5-8 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // UPPER BODY (Optional for runners)
  // ========================================
  {
    name: 'Bänkpress',
    nameSv: 'Bänkpress',
    nameEn: 'Bench Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bröst, Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Överkroppsstyrka (valfritt för löpare)',
    instructions: '1. Ligg på bänk\n2. Grip något bredare än axlar\n3. Sänk till bröstet\n4. Pressa upp\n5. Lås ut',
    equipment: 'Skivstång, bänk',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    isPublic: true,
  },
  {
    name: 'Rodd',
    nameSv: 'Rodd',
    nameEn: 'Barbell Row',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ryggstyrkavs',
    instructions: '1. Böj framåt i höften\n2. Grip stången\n3. Dra mot mage\n4. Armbågar nära kroppen\n5. Squee ze shoulder blades',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2yquMvCEgHs',
    isPublic: true,
  },
  {
    name: 'Chins',
    nameSv: 'Chins',
    nameEn: 'Pull-ups/Chin-ups',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Ryggstyrkavs med kroppsvikt',
    instructions: '1. Häng i stång\n2. Dra dig upp\n3. Hakan över stången\n4. Kontrollerad nedgång\n5. Full ROM',
    equipment: 'Chin-up bar',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Axelpress',
    nameSv: 'Axelpress',
    nameEn: 'Overhead Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Axelstyrka',
    instructions: '1. Stång vid axelhöjd\n2. Pressa rakt uppåt\n3. Lås ut armarna\n4. Sänk kontrollerat\n5. Neutral rygg',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL CORE EXERCISES
  // ========================================
  {
    name: 'Mountain Climbers',
    nameSv: 'Bergsklättrare',
    nameEn: 'Mountain Climbers',
    category: 'CORE' as const,
    muscleGroup: 'Core, Höftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk core-övning som höjer pulsen',
    instructions: '1. Börja i armhävningsposition\n2. Dra ett knä mot bröstet\n3. Byt snabbt ben\n4. Håll höfterna låga\n5. Fortsätt i angivet tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    isPublic: true,
  },
  {
    name: 'Bicycle Crunches',
    nameSv: 'Cykelcrunches',
    nameEn: 'Bicycle Crunches',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Roterande core-övning för obliques',
    instructions: '1. Ligg på rygg med händerna bakom huvudet\n2. Lyft axlarna från golvet\n3. För motsatt armbåge mot knä\n4. Växla sida i cykelrörelse\n5. Håll nedre ryggen i golvet',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=9FGilxCbdz8',
    isPublic: true,
  },
  {
    name: 'Leg Raises',
    nameSv: 'Benlyft',
    nameEn: 'Leg Raises',
    category: 'CORE' as const,
    muscleGroup: 'Nedre Magmuskler, Höftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Fokuserar på nedre magmusklerna',
    instructions: '1. Ligg på rygg med benen raka\n2. Händer under sätet för stöd\n3. Lyft benen rakt upp till 90 grader\n4. Sänk långsamt tillbaka\n5. Låt inte ryggen lyfta från golvet',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=JB2oyawG9KI',
    isPublic: true,
  },
  {
    name: 'V-ups',
    nameSv: 'V-ups',
    nameEn: 'V-ups',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis, Höftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad core-övning i V-form',
    instructions: '1. Ligg på rygg med armar och ben sträckta\n2. Lyft överkropp och ben samtidigt\n3. Försök röra tårna med händerna\n4. Bilda en V-form\n5. Sänk kontrollerat tillbaka',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=iP2fjvG0g3w',
    isPublic: true,
  },
  {
    name: 'Hollow Hold',
    nameSv: 'Hollow Hold',
    nameEn: 'Hollow Body Hold',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isometrisk core-övning för helkroppsspänning',
    instructions: '1. Ligg på rygg\n2. Pressa ländryggen i golvet\n3. Lyft armar, axlar och ben\n4. Bananform - håll kvar\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=44ScXWFaVBs',
    isPublic: true,
  },
  {
    name: 'Sit-ups',
    nameSv: 'Sit-ups',
    nameEn: 'Sit-ups',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Klassisk magövning',
    instructions: '1. Ligg på rygg med knän böjda\n2. Fötterna i golvet\n3. Händer vid öronen eller över bröstet\n4. Lyft överkroppen mot knäna\n5. Sänk kontrollerat tillbaka',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Crunches',
    nameSv: 'Crunches',
    nameEn: 'Crunches',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad magmuskel-aktivering',
    instructions: '1. Ligg på rygg med knän böjda\n2. Händer vid öronen\n3. Lyft endast axlarna från golvet\n4. Spänn magmusklerna i toppen\n5. Sänk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL UPPER BODY
  // ========================================
  {
    name: 'Armhävningar',
    nameSv: 'Armhävningar',
    nameEn: 'Push-ups',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bröst, Triceps, Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Grundläggande överkroppsövning med kroppsvikt',
    instructions: '1. Händer axelbrett på golvet\n2. Kroppen i rak linje\n3. Sänk bröstet mot golvet\n4. Pressa upp till raka armar\n5. Håll core spänd hela tiden',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    isPublic: true,
  },
  {
    name: 'Dips',
    nameSv: 'Dips',
    nameEn: 'Dips',
    category: 'STRENGTH' as const,
    muscleGroup: 'Triceps, Bröst',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Triceps och bröstträning',
    instructions: '1. Grip tag om bänk/barr bakom dig\n2. Sänk kroppen genom att böja armarna\n3. Armbågarna 90 grader\n4. Pressa upp till raka armar\n5. Undvik att sjunka för djupt',
    equipment: 'Bänk eller dipbarr',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    isPublic: true,
  },
  {
    name: 'Inverterad rodd',
    nameSv: 'Inverterad rodd',
    nameEn: 'Inverted Row',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ryggövning med kroppsvikt',
    instructions: '1. Häng under en stång\n2. Kroppen rak\n3. Dra bröstet mot stången\n4. Kläm ihop skulderbladen\n5. Sänk kontrollerat',
    equipment: 'Stång på låg höjd',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=1oed8roeY9Q',
    isPublic: true,
  },
  {
    name: 'Face Pulls',
    nameSv: 'Face Pulls',
    nameEn: 'Face Pulls',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bakre Axlar, Rotator Cuff',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Bakre axlar och hållning',
    instructions: '1. Kabel eller band i ansiktshöjd\n2. Dra mot ansiktet\n3. Händer går ut och bakåt\n4. Kläm ihop skulderbladen\n5. Kontrollerad återgång',
    equipment: 'Kabel eller band',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    isPublic: true,
  },
  {
    name: 'Latsdrag',
    nameSv: 'Latsdrag',
    nameEn: 'Lat Pulldown',
    category: 'STRENGTH' as const,
    muscleGroup: 'Latissimus Dorsi, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ryggens stora muskel',
    instructions: '1. Grip stången bredare än axlar\n2. Luta lätt bakåt\n3. Dra stången mot övre bröstet\n4. Kläm ihop skulderbladen\n5. Sträck ut armarna kontrollerat',
    equipment: 'Latsdragsmaskin',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    isPublic: true,
  },

  // ========================================
  // MOBILITY & WARMUP
  // ========================================
  {
    name: 'Höftcirklar',
    nameSv: 'Höftcirklar',
    nameEn: 'Hip Circles',
    category: 'STRENGTH' as const,
    muscleGroup: 'Höfter',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk höftmobilisering',
    instructions: '1. Stå på ett ben\n2. Lyft andra knät\n3. Rita cirklar med knät\n4. Stora, kontrollerade rörelser\n5. Gör båda riktningarna',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bensving',
    nameSv: 'Bensving',
    nameEn: 'Leg Swings',
    category: 'STRENGTH' as const,
    muscleGroup: 'Höfter, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk stretch för bakre lårmuskel',
    instructions: '1. Håll i ett stöd\n2. Svinga benet framåt och bakåt\n3. Håll benet rakt\n4. Kontrollerad sving\n5. Öka rörelseomfånget gradvis',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Världens bästa stretch',
    nameSv: 'Världens bästa stretch',
    nameEn: 'Worlds Greatest Stretch',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp mobilitet',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Komplett dynamisk stretch för hela kroppen',
    instructions: '1. Utfallsposition\n2. Rotera övre kroppen mot främre benet\n3. Sträck armen mot taket\n4. Sänk armbågen mot foten\n5. Växla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=mlP8lJ8W2zQ',
    isPublic: true,
  },
  {
    name: 'Katt-Ko',
    nameSv: 'Katt-Ko',
    nameEn: 'Cat-Cow',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg mobilitet',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ryggradsrörlighet',
    instructions: '1. På alla fyra\n2. Runda ryggen uppåt (katt)\n3. Böj ryggen nedåt (ko)\n4. Flytande rörelser\n5. Andas djupt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
    isPublic: true,
  },
  {
    name: 'Foam Rolling',
    nameSv: 'Foam Rolling',
    nameEn: 'Foam Rolling',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Mjukvävnadsmobilisering',
    instructions: '1. Placera foam roller under målområdet\n2. Rulla långsamt över muskeln\n3. Stanna på ömma punkter\n4. 30-60 sekunder per område\n5. Andas avslappnat',
    equipment: 'Foam roller',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Ankelrörlighet',
    nameSv: 'Ankelrörlighet',
    nameEn: 'Ankle Mobility',
    category: 'STRENGTH' as const,
    muscleGroup: 'Anklar',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ökar dorsalflexion i ankeln',
    instructions: '1. Stå med en fot framför\n2. Pressa knät framåt över tårna\n3. Håll hälen i golvet\n4. Känn stretch i vaden\n5. Upprepa på båda sidor',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL STRENGTH
  // ========================================
  {
    name: 'Sumo Squats',
    nameSv: 'Sumoknäböj',
    nameEn: 'Sumo Squats',
    category: 'STRENGTH' as const,
    muscleGroup: 'Adduktorer, Gluteus, Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Bred ställning för adduktorer och gluteus',
    instructions: '1. Bred ställning med tår utåt\n2. Sänk höfterna rakt nedåt\n3. Knän i linje med tårna\n4. Upprätt bål\n5. Tryck upp genom hälarna',
    equipment: 'Ingen eller kettlebell',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=9ZuXKqRbT9k',
    isPublic: true,
  },
  {
    name: 'Glute Kickbacks',
    nameSv: 'Sparkbaksparkar',
    nameEn: 'Glute Kickbacks',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad gluteus-aktivering',
    instructions: '1. På alla fyra\n2. Sparka ett ben bakåt och uppåt\n3. Spänn skinkan i toppen\n4. Kontrollerad återgång\n5. Håll höfterna stabila',
    equipment: 'Ingen eller band',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Wall Angels',
    nameSv: 'Väggänglar',
    nameEn: 'Wall Angels',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar, Övre rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Axelrörlighet och hållning',
    instructions: '1. Stå med ryggen mot väggen\n2. Armar i 90 grader mot väggen\n3. Glid armarna upp och ner\n4. Håll kontakt med väggen\n5. Kontrollerad rörelse',
    equipment: 'Vägg',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=M_ooIhKYs7c',
    isPublic: true,
  },
  {
    name: 'Prone Y-raise',
    nameSv: 'Y-lyft liggande',
    nameEn: 'Prone Y-Raise',
    category: 'STRENGTH' as const,
    muscleGroup: 'Nedre Trapezius, Bakre Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Skulderbladsaktivering och stabilitet',
    instructions: '1. Ligg på mage\n2. Lyft armarna i Y-form\n3. Tummar pekar uppåt\n4. Kläm ihop skulderbladen\n5. Håll i toppen',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Superman',
    nameSv: 'Superman',
    nameEn: 'Superman',
    category: 'STRENGTH' as const,
    muscleGroup: 'Ländryggen, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ryggextension och bakre kedjan',
    instructions: '1. Ligg på mage med armar sträckta\n2. Lyft armar och ben samtidigt\n3. Håll i toppen\n4. Spänn gluteus\n5. Sänk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=J9zXkxUAfUA',
    isPublic: true,
  },
  {
    name: 'Inchworm',
    nameSv: 'Inchworm',
    nameEn: 'Inchworm',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk helkroppsrörlighet',
    instructions: '1. Stå med raka ben\n2. Böj framåt och sätt händerna i golvet\n3. Gå ut med händerna till planka\n4. Gå tillbaka med händerna\n5. Res dig upp',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=ZY2ji_Ho0dA',
    isPublic: true,
  },
  {
    name: 'High Knees',
    nameSv: 'Höga knän',
    nameEn: 'High Knees',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Höftflexorer, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Dynamisk uppvärmning och knälyft',
    instructions: '1. Jogga på stället\n2. Lyft knäna högt (över höften)\n3. Snabb armrörelse\n4. Landa mjukt på framfoten\n5. Håll högt tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=D0Sn5k_coK8',
    isPublic: true,
  },
  {
    name: 'Butt Kicks',
    nameSv: 'Hälarmar',
    nameEn: 'Butt Kicks',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Hases, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Löpspecifik uppvärmning',
    instructions: '1. Jogga på stället\n2. Sparka hälarna mot rumpan\n3. Snabb växling\n4. Lätt framåtlutning\n5. Håll högt tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Jumping Jacks',
    nameSv: 'Hampelmannhopp',
    nameEn: 'Jumping Jacks',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Helkropp, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Klassisk uppvärmningsövning',
    instructions: '1. Börja med fötterna ihop\n2. Hoppa ut med fötterna\n3. Samtidigt lyft armarna över huvudet\n4. Hoppa tillbaka till start\n5. Rytmisk rörelse',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=c4DAnQ6DtF8',
    isPublic: true,
  },
  {
    name: 'Burpees',
    nameSv: 'Burpees',
    nameEn: 'Burpees',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 2,
    description: 'Helkropps konditions- och styrkeövning',
    instructions: '1. Stå upprätt\n2. Gå ner i squat och sätt händerna i golvet\n3. Hoppa fötterna bakåt till planka\n4. Gör en armhävning (valfritt)\n5. Hoppa fötterna framåt och hopp upp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=TU8QYVW0gDU',
    isPublic: true,
  },
]

async function main() {
  console.log('🏋️ Seeding comprehensive exercise library based on scientific framework...\n')

  let created = 0
  let skipped = 0

  for (const exercise of exercises) {
    // Check if exercise already exists (by name and coachId=null for system exercises)
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name, coachId: null },
    })

    if (existing) {
      console.log(`⏭️  Skipped (exists): ${exercise.name}`)
      skipped++
      continue
    }

    const createdExercise = await prisma.exercise.create({
      data: {
        ...exercise,
        nameSv: exercise.nameSv || exercise.name,
      },
    })
    console.log(`✅ Created: ${createdExercise.name} (${createdExercise.biomechanicalPillar || createdExercise.category})`)
    created++
  }

  console.log('\n' + '='.repeat(60))
  console.log('📊 Exercise Library Seeding Summary')
  console.log('='.repeat(60))
  console.log(`✅ Created: ${created} exercises`)
  console.log(`⏭️  Skipped: ${skipped} exercises (already existed)`)
  console.log(`📚 Total in library: ${created + skipped} exercises`)
  console.log('='.repeat(60))

  // Summary by category
  const summary = exercises.reduce((acc: any, ex) => {
    const pillar = ex.biomechanicalPillar || 'OTHER'
    acc[pillar] = (acc[pillar] || 0) + 1
    return acc
  }, {})

  console.log('\n📋 Breakdown by Biomechanical Pillar:')
  Object.entries(summary).forEach(([pillar, count]) => {
    console.log(`   ${pillar}: ${count} exercises`)
  })

  console.log('\n✨ Exercise library ready for Norwegian Singles integration!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding exercises:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
