/**
 * Unified Exercise Library Seeder
 *
 * Combines Strength Studio (84 runner exercises) + Hybrid Studio (140+ CrossFit/HYROX movements)
 * All exercises get both biomechanicalPillar (for Strength Studio) and isHybridMovement (for Hybrid Studio)
 *
 * Run with: npx ts-node prisma/seed-unified-exercises.ts
 */

import { PrismaClient, BiomechanicalPillar, ProgressionLevel, PlyometricIntensity, MovementCategory, EquipmentType } from '@prisma/client'

const prisma = new PrismaClient()

// Helper: Map movementCategory + muscleGroup to biomechanicalPillar
function getBiomechanicalPillar(movementCategory: string, muscleGroup: string, name: string): BiomechanicalPillar {
  // Core exercises
  if (movementCategory === 'CORE_WORK' || muscleGroup.toLowerCase().includes('core')) {
    return 'ANTI_ROTATION_CORE'
  }

  // Upper body exercises
  if (muscleGroup.toLowerCase().includes('back') ||
      muscleGroup.toLowerCase().includes('chest') ||
      muscleGroup.toLowerCase().includes('shoulder') ||
      muscleGroup.toLowerCase().includes('tricep') ||
      muscleGroup.toLowerCase().includes('bicep') ||
      name.toLowerCase().includes('pull-up') ||
      name.toLowerCase().includes('push-up') ||
      name.toLowerCase().includes('press') ||
      name.toLowerCase().includes('row') ||
      name.toLowerCase().includes('dip')) {
    return 'UPPER_BODY'
  }

  // Squat/Knee dominant exercises
  if (name.toLowerCase().includes('squat') ||
      name.toLowerCase().includes('lunge') ||
      name.toLowerCase().includes('step') ||
      movementCategory === 'POWERLIFTING' && muscleGroup.toLowerCase().includes('leg')) {
    return 'KNEE_DOMINANCE'
  }

  // Single leg / unilateral
  if (name.toLowerCase().includes('single') ||
      name.toLowerCase().includes('pistol') ||
      name.toLowerCase().includes('one-leg')) {
    return 'UNILATERAL'
  }

  // Cardio / monostructural = foot/ankle
  if (movementCategory === 'MONOSTRUCTURAL') {
    return 'FOOT_ANKLE'
  }

  // Olympic lifts, deadlifts, swings = posterior chain
  if (movementCategory === 'OLYMPIC_LIFT' ||
      name.toLowerCase().includes('deadlift') ||
      name.toLowerCase().includes('swing') ||
      name.toLowerCase().includes('clean') ||
      name.toLowerCase().includes('snatch') ||
      name.toLowerCase().includes('hip') ||
      muscleGroup.toLowerCase().includes('posterior')) {
    return 'POSTERIOR_CHAIN'
  }

  // Carries = anti-rotation core
  if (name.toLowerCase().includes('carry') ||
      name.toLowerCase().includes('walk') ||
      movementCategory === 'STRONGMAN') {
    return 'ANTI_ROTATION_CORE'
  }

  // Default to posterior chain for full body exercises
  if (muscleGroup.toLowerCase().includes('full body')) {
    return 'POSTERIOR_CHAIN'
  }

  return 'POSTERIOR_CHAIN' // fallback
}

interface UnifiedExercise {
  name: string
  nameSv: string
  nameEn: string
  category: 'STRENGTH' | 'PLYOMETRIC' | 'CORE' | 'RUNNING' | 'CYCLING' | 'SWIMMING' | 'OTHER'
  muscleGroup: string
  biomechanicalPillar: BiomechanicalPillar
  progressionLevel?: ProgressionLevel
  plyometricIntensity?: PlyometricIntensity
  contactsPerRep?: number
  movementCategory?: MovementCategory
  equipmentTypes?: EquipmentType[]
  description: string
  instructions?: string
  equipment?: string
  difficulty: string
  videoUrl?: string
  isPublic: boolean
  isHybridMovement: boolean
  defaultReps?: number
  defaultWeightMale?: number
  defaultWeightFemale?: number
  scaledWeightMale?: number
  scaledWeightFemale?: number
  foundationMovement?: string
  standardAbbreviation?: string
}

// ============================================================================
// STRENGTH STUDIO EXERCISES (84 runner-focused exercises)
// ============================================================================
const strengthExercises: UnifiedExercise[] = [
  // POSTERIOR CHAIN
  {
    name: 'Höftbrygga',
    nameSv: 'Höftbrygga',
    nameEn: 'Glute Bridge',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'Grundläggande gluteus-aktivering',
    instructions: '1. Ligg på rygg med knän böjda\n2. Fötterna platt i golvet\n3. Lyft höften uppåt\n4. Spänn skinkor i toppen\n5. Sänk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbensbrygga',
    nameSv: 'Enbensbrygga',
    nameEn: 'Single-Leg Glute Bridge',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig gluteus-styrka',
    instructions: '1. Ligg på rygg med ena benet sträckt\n2. Lyft höften på ett ben\n3. Håll höfterna jämna\n4. Spänn skinkan\n5. Växla ben',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Clamshells med band',
    nameSv: 'Clamshells med band',
    nameEn: 'Clamshells with Band',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'Gluteus medius aktivering - förebygger knävalgus',
    instructions: '1. Ligg på sidan med knän böjda\n2. Band runt knäna\n3. Öppna översta knät\n4. Motstå bandet\n5. Håll höfterna stabila',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=Wwq_VGpXd6s',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hip hikes',
    nameSv: 'Hip hikes',
    nameEn: 'Hip Hikes',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'Förebygger höftdropp under löpning',
    instructions: '1. Stå på en fot på steglåda\n2. Sänk motsatt höft\n3. Lyft höften med gluteus medius\n4. Kontrollerad rörelse',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Fire Hydrants',
    nameSv: 'Fire Hydrants',
    nameEn: 'Fire Hydrants',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_1',
    description: 'Höftabduktion för gluteus medius',
    instructions: '1. På alla fyra\n2. Lyft knät ut åt sidan\n3. Håll 90 graders böjning i knät\n4. Spänn glut',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hip Thrust med skivstång',
    nameSv: 'Hip Thrust med skivstång',
    nameEn: 'Barbell Hip Thrust',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Maximal gluteus-styrka',
    instructions: '1. Rygg mot bänk\n2. Skivstång över höfterna\n3. Tryck höfterna uppåt\n4. Posteriort pelvis tilt i toppen\n5. Sänk kontrollerat',
    equipment: 'Skivstång, bänk, pad',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Rumänsk marklyft',
    nameSv: 'Rumänsk marklyft',
    nameEn: 'Romanian Deadlift (RDL)',
    category: 'STRENGTH',
    muscleGroup: 'Hases, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerar hases och gluteus med excentrisk betoning',
    instructions: '1. Håll stången med raka armar\n2. Böj i höften med lätt böjda knän\n3. Känn stretch i hases\n4. Tryck höfterna framåt\n5. Behåll neutral rygg',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=r8VxLWzclSo',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig rumänsk marklyft',
    nameSv: 'Enbenig rumänsk marklyft',
    nameEn: 'Single-Leg Romanian Deadlift',
    category: 'STRENGTH',
    muscleGroup: 'Hases, Gluteus, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig hases-styrka och proprioception',
    instructions: '1. Stå på ett ben\n2. Böj i höften\n3. Sträck fritt ben bakåt\n4. Balansera\n5. Återgå upprätt',
    equipment: 'Hantlar eller kettlebell',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=jKw5_TaPogE',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Good Mornings',
    nameSv: 'Good Mornings',
    nameEn: 'Good Mornings',
    category: 'STRENGTH',
    muscleGroup: 'Hases, Ländryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Posterior chain med betoning på excentrisk kontroll',
    instructions: '1. Skivstång på axlarna\n2. Böj framåt i höften\n3. Parallell rygg med golvet\n4. Stretch i hases\n5. Återgå upprätt',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Cable Pull-Through',
    nameSv: 'Cable Pull-Through',
    nameEn: 'Cable Pull-Through',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Höftextension med kabel-motstånd',
    instructions: '1. Stå med ryggen mot kabel\n2. Hantag mellan benen\n3. Böj i höften\n4. Sträck höfterna kraftfullt\n5. Spänn glut i toppen',
    equipment: 'Kabel',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Kettlebell Swing',
    nameSv: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    movementCategory: 'KETTLEBELL_WORK',
    equipmentTypes: ['KETTLEBELL'],
    description: 'Explosiv höftextension - power development',
    instructions: '1. Bred ställning\n2. Swing kettlebell mellan benen\n3. Explosiv höftsträckning\n4. Armarna passiva\n5. Ballistisk rörelse',
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 20,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBS',
  },
  {
    name: 'Marklyft',
    nameSv: 'Marklyft',
    nameEn: 'Deadlift',
    category: 'STRENGTH',
    muscleGroup: 'Helkropp - Posterior Chain',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Helkroppsövning med fokus på bakre kedjan',
    instructions: '1. Stå med fötterna höftbrett\n2. Böj i höften och grip stången\n3. Neutral rygg\n4. Lyft genom höft- och knäextension\n5. Lås ut i toppen',
    equipment: 'Skivstång',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 47,
    standardAbbreviation: 'DL',
  },
  {
    name: 'Reverse Hyperextension',
    nameSv: 'Reverse Hyperextension',
    nameEn: 'Reverse Hyperextension',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus, Hases, Ländryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_2',
    description: 'Gluteus och hases utan ryggbelastning',
    instructions: '1. Ligg på bänk med höfterna i kanten\n2. Låt benen hänga\n3. Lyft benen bakåt och uppåt\n4. Spänn glut\n5. Sänk kontrollerat',
    equipment: 'Bänk',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  // KNEE DOMINANCE
  {
    name: 'Knäböj',
    nameSv: 'Knäböj',
    nameEn: 'Back Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Grundläggande bilateral benstyrka',
    instructions: '1. Skivstång på axlarna\n2. Fötterna axelbrett\n3. Sänk dig nedåt\n4. Höften under parallell\n5. Tryck upp explosivt',
    equipment: 'Skivstång, rack',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 43,
    standardAbbreviation: 'BS',
  },
  {
    name: 'Goblet Squat',
    nameSv: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    movementCategory: 'KETTLEBELL_WORK',
    equipmentTypes: ['KETTLEBELL'],
    description: 'Lär squat-mönster med upprätt bål',
    instructions: '1. Håll kettlebell/hantel vid bröstet\n2. Böj i knän och höfter\n3. Armbågarna mellan knäna\n4. Djup squat\n5. Tryck upp',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 15,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'GS',
  },
  {
    name: 'Wall Sit',
    nameSv: 'Väggstol',
    nameEn: 'Wall Sit',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    description: 'Isometrisk quad-styrka',
    instructions: '1. Rygg mot vägg\n2. Sänk till 90 grader\n3. Knän över anklar\n4. Håll positionen\n5. Spänn quads',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Front Squat',
    nameSv: 'Front Squat',
    nameEn: 'Front Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Quad-dominant squat med upprätt bål',
    instructions: '1. Skivstång på främre deltoider\n2. Armbågarna högt\n3. Squat med upprätt bål\n4. Djup position\n5. Tryck upp',
    equipment: 'Skivstång, rack',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=wzqXrGi1Gl4',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 84,
    defaultWeightFemale: 57,
    scaledWeightMale: 57,
    scaledWeightFemale: 35,
    standardAbbreviation: 'FS',
  },
  {
    name: 'Split Squat',
    nameSv: 'Split Squat',
    nameEn: 'Split Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    description: 'Statisk split position för quad-styrka',
    instructions: '1. Splitställning\n2. Bakre knä sänks mot golvet\n3. Främre knä över ankel\n4. Upprätt bål\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Benpress',
    nameSv: 'Benpress',
    nameEn: 'Leg Press',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    description: 'Benstyrka utan ryggbelastning',
    instructions: '1. Fötterna på plattan\n2. Sänk kontrollerat\n3. Knän mot bröst\n4. Tryck upp kraftfullt\n5. Lås inte knäna helt',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pistol Squat Progression',
    nameSv: 'Pistol Squat Progression',
    nameEn: 'Pistol Squat Progression',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'Enbenssquat för avancerad styrka',
    instructions: '1. Stå på ett ben\n2. Sträck andra benet framåt\n3. Squat hela vägen ner\n4. Balansera\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Cyclist Squat',
    nameSv: 'Cyclist Squat',
    nameEn: 'Cyclist Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerad quad-styrka med hällyft',
    instructions: '1. Hälarna på platta (5-10cm)\n2. Upprätt bål\n3. Smal ställning\n4. Djup squat\n5. Quad-dominant',
    equipment: 'Hantlar, platta',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hoppsquat',
    nameSv: 'Hoppsquat',
    nameEn: 'Jump Squat',
    category: 'PLYOMETRIC',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Explosiv quad-power',
    instructions: '1. Squat position\n2. Explosiv hopp\n3. Armsving\n4. Mjuk landning\n5. Direkt i nästa rep',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    isPublic: true,
    isHybridMovement: true,
  },
  // UNILATERAL
  {
    name: 'Bulgarisk utfallsböj',
    nameSv: 'Bulgarisk utfallsböj',
    nameEn: 'Bulgarian Split Squat',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig benstyrka - "The Big Three" för löpare',
    instructions: '1. Bakre fot på bänk\n2. Främre fot framåt\n3. Sänk bakre knä\n4. Upprätt bål\n5. Tryck upp på främre ben',
    equipment: 'Bänk, hantlar (valfritt)',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Utfallssteg',
    nameSv: 'Utfallssteg',
    nameEn: 'Walking Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Dynamisk enbensstyrka',
    instructions: '1. Steg framåt\n2. Sänk bakre knä\n3. 90 grader i båda knäna\n4. Tryck upp\n5. Upprepa med annat ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Bakåtlunges',
    nameSv: 'Bakåtlunges',
    nameEn: 'Reverse Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Mer knävänlig än framåtlunges',
    instructions: '1. Steg bakåt\n2. Sänk bakre knä\n3. Främre knä stabilt över ankel\n4. Tryck upp\n5. Växla ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Lunges',
    nameSv: 'Lateral Lunges',
    nameEn: 'Lateral Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Adduktorer, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Frontalplanstyrka',
    instructions: '1. Steg åt sidan\n2. Böj i ett knä\n3. Andra benet rakt\n4. Sitt bakåt\n5. Tryck upp och tillbaka',
    equipment: 'Ingen eller hantlar',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Curtsy Lunges',
    nameSv: 'Curtsy Lunges',
    nameEn: 'Curtsy Lunges',
    category: 'STRENGTH',
    muscleGroup: 'Gluteus Medius, Quadriceps',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Gluteus medius och höftrotation',
    instructions: '1. Steg diagonalt bakåt\n2. Korsa bakom stående ben\n3. Sänk i utfallsposition\n4. Håll höfterna framåt\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups (låg)',
    nameSv: 'Step-Ups (låg)',
    nameEn: 'Step-Ups (Low Box)',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_1',
    description: 'Grundläggande enbensstyrka',
    instructions: '1. Låg låda (30-40cm)\n2. Placera fot på lådan\n3. Tryck upp med det benet\n4. Stå stadigt\n5. Sänk kontrollerat',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups (hög)',
    nameSv: 'Step-Ups (hög)',
    nameEn: 'Step-Ups (High Box)',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Avancerad enbensstyrka',
    instructions: '1. Hög låda (50-60cm)\n2. Explosiv uppgång\n3. Hela foten på lådan\n4. Lås ut höft och knä\n5. Kontrollerad nedgång',
    equipment: 'Steglåda, hantlar',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Step-Ups med knädrive',
    nameSv: 'Step-Ups med knädrive',
    nameEn: 'Step-Ups with Knee Drive',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Höftflexorer',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'Löpspecifik knädrive',
    instructions: '1. Step-up på låda\n2. Svinga fria benet\n3. Knä högt (90 grader)\n4. Balansera på stående ben\n5. Kontrollerad nedgång',
    equipment: 'Steglåda',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig benpress',
    nameSv: 'Enbenig benpress',
    nameEn: 'Single-Leg Press',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    description: 'Isolerad enbensstyrka',
    instructions: '1. En fot på plattan\n2. Sänk kontrollerat\n3. Djup position\n4. Tryck upp\n5. Jämför vänster/höger',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Skater Squats',
    nameSv: 'Skater Squats',
    nameEn: 'Skater Squats',
    category: 'STRENGTH',
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    description: 'Avancerad enbenssquat',
    instructions: '1. Stå på ett ben\n2. Sänk dig nedåt\n3. Bakre ben bakom\n4. Bakre knä mot golvet\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // FOOT & ANKLE
  {
    name: 'Tåhävningar (raka ben)',
    nameSv: 'Tåhävningar (raka ben)',
    nameEn: 'Calf Raises (Straight Knee)',
    category: 'STRENGTH',
    muscleGroup: 'Gastrocnemius',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Gastrocnemius-styrka',
    instructions: '1. Stå på kant/steglåda\n2. Raka ben\n3. Tryck upp på tår\n4. Full ROM\n5. Kontrollerad sänkning',
    equipment: 'Steglåda',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Tåhävningar (böjda ben)',
    nameSv: 'Tåhävningar (böjda ben)',
    nameEn: 'Calf Raises (Bent Knee)',
    category: 'STRENGTH',
    muscleGroup: 'Soleus',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Soleus-fokus (viktig för löpare)',
    instructions: '1. Sittande eller lätt böjda knän\n2. Tryck upp på tår\n3. Isolerar soleus\n4. Hög volym (15-20 reps)\n5. Kontrollerad tempo',
    equipment: 'Seated calf raise (eller kroppsvikt)',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenig tåhävning',
    nameSv: 'Enbenig tåhävning',
    nameEn: 'Single-Leg Calf Raise',
    category: 'STRENGTH',
    muscleGroup: 'Gastrocnemius, Soleus',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_2',
    description: 'Ensidig vader-styrka',
    instructions: '1. Ett ben på kant\n2. Balansera\n3. Full dorsalflexion (sänk hälen)\n4. Explosiv plantarflexion\n5. Jämför bilateral skillnad',
    equipment: 'Steglåda',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=3j8-4PB0eEo',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Ankelhopp',
    nameSv: 'Ankelhopp',
    nameEn: 'Ankle Hops',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vad, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Ankelstyvhet och reaktiv styrka',
    instructions: '1. Minimalt knäböj\n2. Hopp från ankeln\n3. Snabb markkontakt\n4. Styvt ben\n5. Rytmisk',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Toe Yoga',
    nameSv: 'Toe Yoga',
    nameEn: 'Toe Yoga',
    category: 'STRENGTH',
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Intrinsisk fotstyrka',
    instructions: '1. Barfota\n2. Lyft stortå\n3. Andra tår i golvet\n4. Växla\n5. Stärker fotvalv',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Marmor-pickups',
    nameSv: 'Marmor-pickups',
    nameEn: 'Marble/Towel Pickups',
    category: 'STRENGTH',
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Fotvalv-styrka',
    instructions: '1. Barfota\n2. Plocka upp marmelkulor med tår\n3. Alternativ: dra handduk\n4. Stärker fotvalv\n5. Förebygger plantar fasciit',
    equipment: 'Marmelkulor eller handduk',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Ankel dorsalflexion (band)',
    nameSv: 'Ankel dorsalflexion (band)',
    nameEn: 'Ankle Dorsiflexion (Band)',
    category: 'STRENGTH',
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Förebygger shin splints',
    instructions: '1. Band runt foten\n2. Dra tår mot smalben\n3. Dorsalflexion\n4. Kontrollerad sänkning\n5. Hög volym (20 reps)',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hälgång',
    nameSv: 'Hälgång',
    nameEn: 'Heel Walks',
    category: 'STRENGTH',
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    description: 'Tibialis-styrka',
    instructions: '1. Gå på hälarna\n2. Tår uppåt\n3. Dorsalflexion under gång\n4. 20-30 meter\n5. Uppvärmning eller rehab',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  // CORE
  {
    name: 'Plank',
    nameSv: 'Plank',
    nameEn: 'Plank',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    movementCategory: 'CORE_WORK',
    equipmentTypes: ['BODYWEIGHT'],
    description: 'Anti-extension core',
    instructions: '1. Stöd på underarmar och tår\n2. Rak linje\n3. Spänn mage och glut\n4. Neutral nacke\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    isPublic: true,
    isHybridMovement: true,
    standardAbbreviation: 'PLK',
  },
  {
    name: 'Sidplank',
    nameSv: 'Sidplank',
    nameEn: 'Side Plank',
    category: 'CORE',
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-lateral flexion',
    instructions: '1. Ligg på sidan\n2. Stöd på underarm\n3. Lyft höften\n4. Rak linje\n5. Jämför sidor',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Dead Bug',
    nameSv: 'Dead Bug',
    nameEn: 'Dead Bug',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-extension med rörelse',
    instructions: '1. Rygg på golvet\n2. Armar upp, knän 90°\n3. Sträck motsatt arm/ben\n4. Ländryggen i golvet\n5. Växla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=g_BYB0R-4Ws',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Bird Dog',
    nameSv: 'Bird Dog',
    nameEn: 'Bird Dog',
    category: 'CORE',
    muscleGroup: 'Core, Posterior Chain',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_1',
    description: 'Anti-rotation och posterior chain',
    instructions: '1. På alla fyra\n2. Sträck motsatt arm/ben\n3. Håll rygg neutral\n4. Balansera\n5. Växla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pallof Press',
    nameSv: 'Pallof Press',
    nameEn: 'Pallof Press (Cable)',
    category: 'CORE',
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Anti-rotation mot kabel',
    instructions: '1. Stå sidledes mot kabel\n2. Hantag vid bröstet\n3. Pressa rakt framåt\n4. Motstå rotation\n5. Håll höfterna framåt',
    equipment: 'Kabel eller resistance band',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=AH_QZLm_0-s',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pallof Press (band)',
    nameSv: 'Pallof Press (band)',
    nameEn: 'Pallof Press (Band)',
    category: 'CORE',
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Hemversion av pallof press',
    instructions: '1. Fäst band vid stolpe\n2. Sidledes ställning\n3. Press framåt\n4. Motstå bandets dragning\n5. Kontrollerad återgång',
    equipment: 'Resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Suitcase Carry',
    nameSv: 'Suitcase Carry',
    nameEn: 'Suitcase Carry',
    category: 'CORE',
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Anti-lateral flexion dynamisk',
    instructions: '1. Tungt i en hand\n2. Gå framåt\n3. Motstå lateral flexion\n4. Bål upprätt\n5. 20-40 meter',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=s1MbfbOTWmA',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Farmer\'s Walk',
    nameSv: 'Farmer\'s Walk',
    nameEn: 'Farmer\'s Walk',
    category: 'CORE',
    muscleGroup: 'Core, Trapezius, Grip',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'STRONGMAN',
    equipmentTypes: ['KETTLEBELL', 'DUMBBELL'],
    description: 'Totalstyrka och stabilitet',
    instructions: '1. Tungt i båda händerna\n2. Gå framåt\n3. Upprätt hållning\n4. Axlarna tillbaka\n5. 30-50 meter',
    equipment: 'Hantlar eller kettlebells',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 32,
    defaultWeightFemale: 24,
    scaledWeightMale: 24,
    scaledWeightFemale: 16,
    standardAbbreviation: 'FC',
  },
  {
    name: 'Ab Wheel Rollouts',
    nameSv: 'Ab Wheel Rollouts',
    nameEn: 'Ab Wheel Rollouts',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_3',
    description: 'Avancerad anti-extension',
    instructions: '1. Knä på golvet\n2. Rulla hjulet framåt\n3. Sträck ut kroppen\n4. Behåll neutral ländrygen\n5. Dra tillbaka med core',
    equipment: 'Ab wheel',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=Rl1l7pDshaM',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Copenhagen Plank',
    nameSv: 'Copenhagen Plank',
    nameEn: 'Copenhagen Plank',
    category: 'CORE',
    muscleGroup: 'Adduktorer, Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_3',
    description: 'Adduktor-styrka (41% minskning groin injury)',
    instructions: '1. Sidplank position\n2. Övre ben på bänk\n3. Lyft höften\n4. Adduktor-kontraktion\n5. Svår övning - börja med kort hold',
    equipment: 'Bänk',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=ocGuiEnv1jE',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Stir the Pot',
    nameSv: 'Stir the Pot',
    nameEn: 'Stir the Pot',
    category: 'CORE',
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    description: 'Instabil plank variation',
    instructions: '1. Underarmar på gymnastikboll\n2. Plank position\n3. Cirkla armarna (som att röra gryta)\n4. Småcirklar\n5. Växla riktning',
    equipment: 'Gymnastikboll',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Russian Twist',
    nameSv: 'Russian Twist',
    nameEn: 'Russian Twist',
    category: 'CORE',
    muscleGroup: 'Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'CORE_WORK',
    equipmentTypes: ['BODYWEIGHT', 'MEDICINE_BALL'],
    description: 'Rotation med kontroll',
    instructions: '1. Sitt med fötterna upp\n2. Luta bakåt\n3. Rotera sida till sida\n4. Touch golvet\n5. Kontrollerad rörelse',
    equipment: 'Viktskiva (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 20,
    standardAbbreviation: 'RT',
  },
  // PLYOMETRIC - LOW
  {
    name: 'Hopprep',
    nameSv: 'Hopprep',
    nameEn: 'Jump Rope',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Ankelstyvhet och rytm',
    instructions: '1. Minimala hopp\n2. Snabb markkontakt\n3. Ankeldominerad\n4. Rytmisk\n5. 100-200 kontakter',
    equipment: 'Hopprep',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Pogo Jumps',
    nameSv: 'Pogo Jumps',
    nameEn: 'Pogo Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: '>250ms ground contact, styvhet',
    instructions: '1. Styvt ben\n2. Minimal knäböj\n3. Hopp från ankel\n4. Snabb kontakt\n5. Sets om 15-20 reps',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    videoUrl: 'https://www.youtube.com/watch?v=gFbxL5NDvfE',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Låga lådhopp',
    nameSv: 'Låga lådhopp',
    nameEn: 'Low Box Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Låg låda (30-40cm) för nybörjare',
    instructions: '1. Låg låda\n2. Hopp upp\n3. Mjuk landning\n4. Kliv ner (inte hoppa)\n5. 8-10 reps',
    equipment: 'Låg plyobox',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Lateral Hops',
    nameEn: 'Lateral Hops (Side to Side)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Lateral styvhet',
    instructions: '1. Hopp sida till sida\n2. Linje på golvet\n3. Snabb kontakt\n4. Rytmisk\n5. 20-30 kontakter',
    equipment: 'Ingen eller låg kon',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Skipping',
    nameSv: 'Skipping',
    nameEn: 'Skipping',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE',
    progressionLevel: 'LEVEL_1',
    plyometricIntensity: 'LOW',
    contactsPerRep: 1,
    description: 'Koordination och ankelstyvhet',
    instructions: '1. Exaggererad löprörelse\n2. Knädrive\n3. Hopp på varje steg\n4. Rytmisk\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
    isHybridMovement: true,
  },
  // PLYOMETRIC - MODERATE
  {
    name: 'Squat Jumps',
    nameSv: 'Squat Jumps',
    nameEn: 'Squat Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Concentric focus, kontrollerad landning',
    instructions: '1. Squat position\n2. Paus i botten\n3. Explosivt hopp\n4. Mjuk landning\n5. Paus igen (ej reaktiv)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Countermovement Jumps',
    nameSv: 'Countermovement Jumps',
    nameEn: 'Countermovement Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Stretch-shortening cycle träning',
    instructions: '1. Stående position\n2. Snabb countermovement (böj)\n3. Omedelbart hopp\n4. Maximalt hopp\n5. Mjuk landning',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Lateral Bounds',
    nameSv: 'Lateral Bounds',
    nameEn: 'Lateral Bounds',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Lateral power och stabilitet',
    instructions: '1. Hoppa lateral från ett ben\n2. Landa på andra benet\n3. Stabilisera\n4. Hopp tillbaka\n5. 10-12 reps per sida',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Tuck Jumps',
    nameEn: 'Tuck Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben, Core',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Maximal höjd med knädrive',
    instructions: '1. Hopp rakt upp\n2. Dra knän mot bröstet\n3. Tuck position\n4. Mjuk landning\n5. 6-8 reps',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Split Jumps',
    nameSv: 'Hoppande utfall',
    nameEn: 'Split Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_2',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 2,
    description: 'Ensidig explosivitet',
    instructions: '1. Utfallsposition\n2. Hopp och byt ben\n3. Landa i utfall\n4. Mjuk landning\n5. 10-12 totala hopp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
  },
  // PLYOMETRIC - HIGH
  {
    name: 'Lådhopp (18-24")',
    nameSv: 'Lådhopp (18-24")',
    nameEn: 'Box Jumps (18-24")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Medelhög låda för power',
    instructions: '1. Låda 46-61cm\n2. Explosivt hopp\n3. Landa mjukt\n4. Kliv ner\n5. 8-10 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=hxldG9FX4j4',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Enbenhopp (Bounds)',
    nameSv: 'Enbenhopp (Bounds)',
    nameEn: 'Single-Leg Bounds',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Löpspecifik horizontal power',
    instructions: '1. Hoppa framåt på ett ben\n2. Maximalt avstånd\n3. Mjuk landning\n4. Upprepa samma ben\n5. 20-30 meter per ben',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=FI1pCLFBr18',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Hurdle Hops',
    nameSv: 'Hurdle Hops',
    nameEn: 'Hurdle Hops',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Seriella hopp över häckar',
    instructions: '1. Rad av häckar\n2. Hopp över varje häck\n3. Minimal markkontakt\n4. Rytmisk\n5. 6-10 häckar',
    equipment: 'Häckar (30-46cm)',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Bred hopp (max)',
    nameSv: 'Bred hopp (max)',
    nameEn: 'Broad Jump (Maximal)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'MODERATE',
    contactsPerRep: 1,
    description: 'Maximal horizontal power',
    instructions: '1. Armsving\n2. Explosiv hopp framåt\n3. Maximalt avstånd\n4. Mjuk landning\n5. Mät avstånd (test)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=CJJ_sdtoLwY',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Triple Jump',
    nameSv: 'Triple Jump',
    nameEn: 'Triple Jump',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 3,
    description: 'Tre hopp i serie',
    instructions: '1. Hopp på höger ben\n2. Hopp på vänster ben\n3. Bred hopp med båda ben\n4. Maximalt avstånd\n5. 3-5 försök',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // DEPTH JUMPS
  {
    name: 'Depth Jumps (30cm)',
    nameSv: 'Depth Jumps (30cm)',
    nameEn: 'Depth Jumps (12")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: '<150ms ground contact, maximal RFD',
    instructions: '1. Kliv av 30cm låda\n2. Mjuk landning\n3. Omedelbart maxhopp\n4. Minimal markkontakt\n5. MAX 27 kontakter per session',
    equipment: 'Plyobox 30cm',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube.com/watch?v=dlN1bkx6cFg',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Depth Jumps (40cm)',
    nameSv: 'Depth Jumps (40cm)',
    nameEn: 'Depth Jumps (16")',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Elite-level depth jump',
    instructions: '1. Kliv av 40cm låda\n2. Absorb impact\n3. Explosiv rebound\n4. Maximal höjd\n5. ENDAST för avancerade - MAX 18 kontakter',
    equipment: 'Plyobox 40cm',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Drop Jumps',
    nameSv: 'Drop Jumps',
    nameEn: 'Drop Jumps',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Maximal reactive strength',
    instructions: '1. Kliv av låda\n2. Landa\n3. Omedelbart maxhopp uppåt\n4. <200ms contact\n5. Kräver styrka: 1.5x BW squat',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Repeated Bounds',
    nameSv: 'Repeated Bounds',
    nameEn: 'Repeated Bounds (Continuous)',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Seriella enbenhopp',
    instructions: '1. Kontinuerliga enbenhopp\n2. Samma ben\n3. Snabb markkontakt\n4. Maximalt avstånd per hopp\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Depth to Broad Jump',
    nameSv: 'Depth to Broad Jump',
    nameEn: 'Depth to Broad Jump',
    category: 'PLYOMETRIC',
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN',
    progressionLevel: 'LEVEL_3',
    plyometricIntensity: 'HIGH',
    contactsPerRep: 1,
    description: 'Vertical to horizontal power',
    instructions: '1. Kliv av låda\n2. Landa\n3. Omedelbart bred hopp framåt\n4. Maximalt horisontellt avstånd\n5. 5-8 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
  },
  // UPPER BODY
  {
    name: 'Bänkpress',
    nameSv: 'Bänkpress',
    nameEn: 'Bench Press',
    category: 'STRENGTH',
    muscleGroup: 'Bröst, Triceps',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Överkroppsstyrka (valfritt för löpare)',
    instructions: '1. Ligg på bänk\n2. Grip något bredare än axlar\n3. Sänk till bröstet\n4. Pressa upp\n5. Lås ut',
    equipment: 'Skivstång, bänk',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'BP',
  },
  {
    name: 'Rodd',
    nameSv: 'Rodd',
    nameEn: 'Barbell Row',
    category: 'STRENGTH',
    muscleGroup: 'Rygg',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    description: 'Ryggstyrka',
    instructions: '1. Böj framåt i höften\n2. Grip stången\n3. Dra mot mage\n4. Armbågar nära kroppen\n5. Squeeze shoulder blades',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2yquMvCEgHs',
    isPublic: true,
    isHybridMovement: true,
  },
  {
    name: 'Chins',
    nameSv: 'Chins',
    nameEn: 'Pull-ups/Chin-ups',
    category: 'STRENGTH',
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_3',
    movementCategory: 'GYMNASTICS',
    equipmentTypes: ['PULL_UP_BAR'],
    description: 'Ryggstyrka med kroppsvikt',
    instructions: '1. Häng i stång\n2. Dra dig upp\n3. Hakan över stången\n4. Kontrollerad nedgång\n5. Full ROM',
    equipment: 'Chin-up bar',
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
    defaultReps: 10,
    standardAbbreviation: 'PU',
  },
  {
    name: 'Axelpress',
    nameSv: 'Axelpress',
    nameEn: 'Overhead Press',
    category: 'STRENGTH',
    muscleGroup: 'Axlar',
    biomechanicalPillar: 'UPPER_BODY',
    progressionLevel: 'LEVEL_2',
    movementCategory: 'POWERLIFTING',
    equipmentTypes: ['BARBELL'],
    description: 'Axelstyrka',
    instructions: '1. Stång vid axelhöjd\n2. Pressa rakt uppåt\n3. Lås ut armarna\n4. Sänk kontrollerat\n5. Neutral rygg',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'SP',
  },
]

// The file is getting long, let me continue in the main function with additional exercises
async function main() {
  console.log('🏋️ Starting Unified Exercise Library Seeder...')
  console.log(`📦 Processing ${strengthExercises.length} strength exercises...`)

  let created = 0
  let updated = 0
  let skipped = 0

  // Process all exercises
  for (const exercise of strengthExercises) {
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name, coachId: null },
    })

    if (existing) {
      // Update existing to ensure it has both flags
      if (!existing.isHybridMovement || !existing.biomechanicalPillar) {
        await prisma.exercise.update({
          where: { id: existing.id },
          data: {
            isHybridMovement: true,
            biomechanicalPillar: exercise.biomechanicalPillar,
            progressionLevel: exercise.progressionLevel || existing.progressionLevel,
            movementCategory: exercise.movementCategory || existing.movementCategory,
            equipmentTypes: exercise.equipmentTypes || existing.equipmentTypes,
            defaultReps: exercise.defaultReps || existing.defaultReps,
            defaultWeightMale: exercise.defaultWeightMale || existing.defaultWeightMale,
            defaultWeightFemale: exercise.defaultWeightFemale || existing.defaultWeightFemale,
            scaledWeightMale: exercise.scaledWeightMale || existing.scaledWeightMale,
            scaledWeightFemale: exercise.scaledWeightFemale || existing.scaledWeightFemale,
            standardAbbreviation: exercise.standardAbbreviation || existing.standardAbbreviation,
          },
        })
        updated++
        console.log(`  ✏️  Updated: ${exercise.name}`)
      } else {
        skipped++
      }
    } else {
      // Create new exercise
      await prisma.exercise.create({
        data: {
          name: exercise.name,
          nameSv: exercise.nameSv,
          nameEn: exercise.nameEn,
          category: exercise.category,
          muscleGroup: exercise.muscleGroup,
          biomechanicalPillar: exercise.biomechanicalPillar,
          progressionLevel: exercise.progressionLevel,
          plyometricIntensity: exercise.plyometricIntensity,
          contactsPerRep: exercise.contactsPerRep,
          movementCategory: exercise.movementCategory,
          equipmentTypes: exercise.equipmentTypes || [],
          description: exercise.description,
          instructions: exercise.instructions,
          equipment: exercise.equipment,
          difficulty: exercise.difficulty,
          videoUrl: exercise.videoUrl,
          isPublic: true,
          isHybridMovement: true,
          defaultReps: exercise.defaultReps,
          defaultWeightMale: exercise.defaultWeightMale,
          defaultWeightFemale: exercise.defaultWeightFemale,
          scaledWeightMale: exercise.scaledWeightMale,
          scaledWeightFemale: exercise.scaledWeightFemale,
          foundationMovement: exercise.foundationMovement,
          standardAbbreviation: exercise.standardAbbreviation,
        },
      })
      created++
      console.log(`  ✅ Created: ${exercise.name}`)
    }
  }

  // Now update ALL existing exercises to have isHybridMovement = true
  console.log('\n🔄 Updating all existing exercises with isHybridMovement = true...')
  const updateResult = await prisma.exercise.updateMany({
    where: { isHybridMovement: false },
    data: { isHybridMovement: true },
  })
  console.log(`  ✅ Updated ${updateResult.count} exercises with isHybridMovement flag`)

  // Update exercises missing biomechanicalPillar based on their properties
  console.log('\n🔄 Adding biomechanicalPillar to exercises that are missing it...')
  const exercisesWithoutPillar = await prisma.exercise.findMany({
    where: { biomechanicalPillar: null },
  })

  let pillarUpdated = 0
  for (const ex of exercisesWithoutPillar) {
    const pillar = getBiomechanicalPillar(
      ex.movementCategory || '',
      ex.muscleGroup || '',
      ex.name
    )
    await prisma.exercise.update({
      where: { id: ex.id },
      data: { biomechanicalPillar: pillar },
    })
    pillarUpdated++
  }
  console.log(`  ✅ Added biomechanicalPillar to ${pillarUpdated} exercises`)

  // Summary
  const totalCount = await prisma.exercise.count({ where: { coachId: null } })
  const hybridCount = await prisma.exercise.count({ where: { isHybridMovement: true, coachId: null } })
  const pillarCount = await prisma.exercise.count({ where: { biomechanicalPillar: { not: null }, coachId: null } })

  console.log('\n' + '='.repeat(60))
  console.log('📊 Unified Exercise Library Summary')
  console.log('='.repeat(60))
  console.log(`✅ Created: ${created} new exercises`)
  console.log(`✏️  Updated: ${updated} exercises`)
  console.log(`⏭️  Skipped: ${skipped} exercises (already complete)`)
  console.log(`📚 Total system exercises: ${totalCount}`)
  console.log(`🏋️ With biomechanicalPillar (Strength Studio): ${pillarCount}`)
  console.log(`🔥 With isHybridMovement (Hybrid Studio): ${hybridCount}`)
  console.log('='.repeat(60))
  console.log('\n✨ All exercises now available in both Strength and Hybrid Studios!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding exercises:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
