/**
 * Hybrid Studio Movement Library Seeder
 *
 * Seeds 200+ functional fitness movements for CrossFit, HYROX, and hybrid workouts.
 * Includes Rx/Scaled weights, equipment requirements, and movement categories.
 */

import { PrismaClient, WorkoutType, MovementCategory, EquipmentType } from '@prisma/client';

const prisma = new PrismaClient();

interface HybridMovement {
  name: string;
  nameSv: string;
  nameEn: string;
  category: WorkoutType;
  movementCategory: MovementCategory;
  muscleGroup: string;
  description: string;
  equipmentTypes: EquipmentType[];
  defaultReps?: number;
  defaultWeightMale?: number;
  defaultWeightFemale?: number;
  scaledWeightMale?: number;
  scaledWeightFemale?: number;
  foundationMovement?: string;
  standardAbbreviation?: string;
  difficulty: string;
}

const hybridMovements: HybridMovement[] = [
  // ==================== OLYMPIC LIFTING ====================
  {
    name: 'Clean',
    nameSv: 'Frivändning',
    nameEn: 'Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Olympic lift from floor to front rack position',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Hang Power Clean',
    standardAbbreviation: 'C',
    difficulty: 'Advanced',
  },
  {
    name: 'Power Clean',
    nameSv: 'Power Frivändning',
    nameEn: 'Power Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Olympic clean caught above parallel',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Hang Power Clean',
    standardAbbreviation: 'PC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Hang Clean',
    nameSv: 'Hängande Frivändning',
    nameEn: 'Hang Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Clean starting from hang position above the knee',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'HC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Hang Power Clean',
    nameSv: 'Hängande Power Frivändning',
    nameEn: 'Hang Power Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Power clean starting from hang position',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'HPC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Squat Clean',
    nameSv: 'Squat Frivändning',
    nameEn: 'Squat Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Full clean with full depth squat catch',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Power Clean',
    standardAbbreviation: 'SQC',
    difficulty: 'Advanced',
  },
  {
    name: 'Clean & Jerk',
    nameSv: 'Stöt',
    nameEn: 'Clean & Jerk',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Olympic lift: clean to front rack then jerk overhead',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Push Press',
    standardAbbreviation: 'C&J',
    difficulty: 'Advanced',
  },
  {
    name: 'Snatch',
    nameSv: 'Ryck',
    nameEn: 'Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Olympic lift from floor to overhead in one motion',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    foundationMovement: 'Hang Power Snatch',
    standardAbbreviation: 'SN',
    difficulty: 'Advanced',
  },
  {
    name: 'Power Snatch',
    nameSv: 'Power Ryck',
    nameEn: 'Power Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Snatch caught above parallel',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'PSN',
    difficulty: 'Intermediate',
  },
  {
    name: 'Hang Snatch',
    nameSv: 'Hängande Ryck',
    nameEn: 'Hang Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Snatch starting from hang position',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'HSN',
    difficulty: 'Intermediate',
  },
  {
    name: 'Hang Power Snatch',
    nameSv: 'Hängande Power Ryck',
    nameEn: 'Hang Power Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Power snatch starting from hang position',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'HPS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Squat Snatch',
    nameSv: 'Squat Ryck',
    nameEn: 'Squat Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Full snatch with full depth overhead squat catch',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    foundationMovement: 'Power Snatch',
    standardAbbreviation: 'SQSN',
    difficulty: 'Advanced',
  },
  {
    name: 'Split Jerk',
    nameSv: 'Splitstöt',
    nameEn: 'Split Jerk',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Jerk with split stance catch',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Push Jerk',
    standardAbbreviation: 'SJ',
    difficulty: 'Advanced',
  },
  {
    name: 'Push Jerk',
    nameSv: 'Pushstöt',
    nameEn: 'Push Jerk',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Jerk with parallel stance catch',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    foundationMovement: 'Push Press',
    standardAbbreviation: 'PJ',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Snatch',
    nameSv: 'Hantel Ryck',
    nameEn: 'Dumbbell Snatch',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Single-arm snatch with dumbbell',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 30,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DB SN',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Clean',
    nameSv: 'Hantel Frivändning',
    nameEn: 'Dumbbell Clean',
    category: 'STRENGTH',
    movementCategory: 'OLYMPIC_LIFT',
    muscleGroup: 'Full Body',
    description: 'Clean with dumbbells',
    equipmentTypes: ['DUMBBELL'],
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DB C',
    difficulty: 'Intermediate',
  },

  // ==================== POWERLIFTING ====================
  {
    name: 'Back Squat',
    nameSv: 'Knäböj',
    nameEn: 'Back Squat',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Legs',
    description: 'Barbell squat with bar on upper back',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 43,
    standardAbbreviation: 'BS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Front Squat',
    nameSv: 'Frontknäböj',
    nameEn: 'Front Squat',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Legs',
    description: 'Barbell squat with bar in front rack position',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 84,
    defaultWeightFemale: 57,
    scaledWeightMale: 57,
    scaledWeightFemale: 35,
    standardAbbreviation: 'FS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Overhead Squat',
    nameSv: 'Overhead Knäböj',
    nameEn: 'Overhead Squat',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Full Body',
    description: 'Squat with barbell held overhead',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    foundationMovement: 'Front Squat',
    standardAbbreviation: 'OHS',
    difficulty: 'Advanced',
  },
  {
    name: 'Deadlift',
    nameSv: 'Marklyft',
    nameEn: 'Deadlift',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Posterior Chain',
    description: 'Lift barbell from floor with straight back',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 47,
    standardAbbreviation: 'DL',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sumo Deadlift',
    nameSv: 'Sumo Marklyft',
    nameEn: 'Sumo Deadlift',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Posterior Chain',
    description: 'Wide stance deadlift',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 47,
    standardAbbreviation: 'SDL',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sumo Deadlift High Pull',
    nameSv: 'Sumo Marklyft Högt Drag',
    nameEn: 'Sumo Deadlift High Pull',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Full Body',
    description: 'Wide stance deadlift to chin height',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'SDHP',
    difficulty: 'Intermediate',
  },
  {
    name: 'Bench Press',
    nameSv: 'Bänkpress',
    nameEn: 'Bench Press',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Chest',
    description: 'Horizontal pressing movement on bench',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'BP',
    difficulty: 'Beginner',
  },
  {
    name: 'Strict Press',
    nameSv: 'Militärpress',
    nameEn: 'Strict Press',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Shoulders',
    description: 'Standing overhead press without leg drive',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'SP',
    difficulty: 'Beginner',
  },
  {
    name: 'Push Press',
    nameSv: 'Pushpress',
    nameEn: 'Push Press',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Shoulders',
    description: 'Overhead press with leg drive',
    equipmentTypes: ['BARBELL'],
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'PP',
    difficulty: 'Intermediate',
  },

  // ==================== GYMNASTICS ====================
  {
    name: 'Pull-Up',
    nameSv: 'Chins',
    nameEn: 'Pull-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Back',
    description: 'Strict pull from hanging position',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 10,
    foundationMovement: 'Ring Row',
    standardAbbreviation: 'PU',
    difficulty: 'Intermediate',
  },
  {
    name: 'Kipping Pull-Up',
    nameSv: 'Kipping Chins',
    nameEn: 'Kipping Pull-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Back',
    description: 'Pull-up with hip kip for momentum',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 15,
    foundationMovement: 'Pull-Up',
    standardAbbreviation: 'KPU',
    difficulty: 'Intermediate',
  },
  {
    name: 'Butterfly Pull-Up',
    nameSv: 'Butterfly Chins',
    nameEn: 'Butterfly Pull-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Back',
    description: 'High-speed pull-up with continuous motion',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 15,
    foundationMovement: 'Kipping Pull-Up',
    standardAbbreviation: 'BPU',
    difficulty: 'Advanced',
  },
  {
    name: 'Chest-to-Bar Pull-Up',
    nameSv: 'Chest-to-Bar',
    nameEn: 'Chest-to-Bar Pull-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Back',
    description: 'Pull-up where chest touches the bar',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 10,
    foundationMovement: 'Kipping Pull-Up',
    standardAbbreviation: 'C2B',
    difficulty: 'Advanced',
  },
  {
    name: 'Muscle-Up (Bar)',
    nameSv: 'Muscle-Up (Stång)',
    nameEn: 'Bar Muscle-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Upper Body',
    description: 'Pull-up transitioning to dip above the bar',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 5,
    foundationMovement: 'Chest-to-Bar Pull-Up',
    standardAbbreviation: 'BMU',
    difficulty: 'Advanced',
  },
  {
    name: 'Muscle-Up (Ring)',
    nameSv: 'Muscle-Up (Ringar)',
    nameEn: 'Ring Muscle-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Upper Body',
    description: 'Pull-up transitioning to dip on rings',
    equipmentTypes: ['RINGS'],
    defaultReps: 5,
    foundationMovement: 'Strict Ring Dip',
    standardAbbreviation: 'RMU',
    difficulty: 'Advanced',
  },
  {
    name: 'Ring Dip',
    nameSv: 'Ring Dips',
    nameEn: 'Ring Dip',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Triceps',
    description: 'Dip performed on gymnastic rings',
    equipmentTypes: ['RINGS'],
    defaultReps: 10,
    foundationMovement: 'Box Dip',
    standardAbbreviation: 'RD',
    difficulty: 'Intermediate',
  },
  {
    name: 'Strict Ring Dip',
    nameSv: 'Strikt Ring Dips',
    nameEn: 'Strict Ring Dip',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Triceps',
    description: 'Dip on rings without kipping',
    equipmentTypes: ['RINGS'],
    defaultReps: 5,
    foundationMovement: 'Box Dip',
    standardAbbreviation: 'SRD',
    difficulty: 'Intermediate',
  },
  {
    name: 'Ring Row',
    nameSv: 'Ring Rodd',
    nameEn: 'Ring Row',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Back',
    description: 'Horizontal row using rings',
    equipmentTypes: ['RINGS'],
    defaultReps: 15,
    standardAbbreviation: 'RR',
    difficulty: 'Beginner',
  },
  {
    name: 'Toes-to-Bar',
    nameSv: 'Toes-to-Bar',
    nameEn: 'Toes-to-Bar',
    category: 'CORE',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Core',
    description: 'Hanging movement bringing toes to touch bar',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 15,
    foundationMovement: 'Hanging Knee Raise',
    standardAbbreviation: 'T2B',
    difficulty: 'Intermediate',
  },
  {
    name: 'Knees-to-Elbow',
    nameSv: 'Knees-to-Elbow',
    nameEn: 'Knees-to-Elbow',
    category: 'CORE',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Core',
    description: 'Hanging movement bringing knees to elbows',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 15,
    foundationMovement: 'Hanging Knee Raise',
    standardAbbreviation: 'K2E',
    difficulty: 'Intermediate',
  },
  {
    name: 'Hanging Knee Raise',
    nameSv: 'Hängande Knälyft',
    nameEn: 'Hanging Knee Raise',
    category: 'CORE',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Core',
    description: 'Raise knees while hanging from bar',
    equipmentTypes: ['PULL_UP_BAR'],
    defaultReps: 15,
    standardAbbreviation: 'HKR',
    difficulty: 'Beginner',
  },
  {
    name: 'Handstand Push-Up',
    nameSv: 'Handstående Armhävning',
    nameEn: 'Handstand Push-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Shoulders',
    description: 'Push-up while inverted against wall',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 10,
    foundationMovement: 'Pike Push-Up',
    standardAbbreviation: 'HSPU',
    difficulty: 'Advanced',
  },
  {
    name: 'Strict Handstand Push-Up',
    nameSv: 'Strikt Handstående Armhävning',
    nameEn: 'Strict Handstand Push-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Shoulders',
    description: 'HSPU without kipping',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 5,
    foundationMovement: 'Pike Push-Up',
    standardAbbreviation: 'SHSPU',
    difficulty: 'Advanced',
  },
  {
    name: 'Handstand Walk',
    nameSv: 'Handstående Gång',
    nameEn: 'Handstand Walk',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Shoulders',
    description: 'Walking on hands while inverted',
    equipmentTypes: ['BODYWEIGHT'],
    foundationMovement: 'Wall Walk',
    standardAbbreviation: 'HSW',
    difficulty: 'Advanced',
  },
  {
    name: 'Wall Walk',
    nameSv: 'Väggklättring',
    nameEn: 'Wall Walk',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Shoulders',
    description: 'Walk hands up wall to handstand position',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 5,
    standardAbbreviation: 'WW',
    difficulty: 'Intermediate',
  },
  {
    name: 'Box Jump',
    nameSv: 'Boxhopp',
    nameEn: 'Box Jump',
    category: 'PLYOMETRIC',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Legs',
    description: 'Jump onto plyo box',
    equipmentTypes: ['BOX'],
    defaultReps: 20,
    standardAbbreviation: 'BJ',
    difficulty: 'Beginner',
  },
  {
    name: 'Box Jump Over',
    nameSv: 'Boxhopp Över',
    nameEn: 'Box Jump Over',
    category: 'PLYOMETRIC',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Legs',
    description: 'Jump over box, landing on other side',
    equipmentTypes: ['BOX'],
    defaultReps: 20,
    standardAbbreviation: 'BJO',
    difficulty: 'Intermediate',
  },
  {
    name: 'Step-Up',
    nameSv: 'Step-Up',
    nameEn: 'Step-Up',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Step onto elevated surface',
    equipmentTypes: ['BOX'],
    defaultReps: 20,
    standardAbbreviation: 'SU',
    difficulty: 'Beginner',
  },
  {
    name: 'Rope Climb',
    nameSv: 'Repklättring',
    nameEn: 'Rope Climb',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Upper Body',
    description: 'Climb 15ft rope using arms and legs',
    equipmentTypes: ['ROPE'],
    defaultReps: 1,
    foundationMovement: 'Rope Pull from Floor',
    standardAbbreviation: 'RC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Legless Rope Climb',
    nameSv: 'Benlös Repklättring',
    nameEn: 'Legless Rope Climb',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Upper Body',
    description: 'Climb rope using only arms',
    equipmentTypes: ['ROPE'],
    defaultReps: 1,
    foundationMovement: 'Rope Climb',
    standardAbbreviation: 'LRC',
    difficulty: 'Advanced',
  },
  {
    name: 'Double Under',
    nameSv: 'Double Under',
    nameEn: 'Double Under',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Jump rope passing twice under feet per jump',
    equipmentTypes: ['JUMP_ROPE'],
    defaultReps: 50,
    foundationMovement: 'Single Under',
    standardAbbreviation: 'DU',
    difficulty: 'Intermediate',
  },
  {
    name: 'Single Under',
    nameSv: 'Single Under',
    nameEn: 'Single Under',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Standard jump rope',
    equipmentTypes: ['JUMP_ROPE'],
    defaultReps: 100,
    standardAbbreviation: 'SU',
    difficulty: 'Beginner',
  },
  {
    name: 'Triple Under',
    nameSv: 'Triple Under',
    nameEn: 'Triple Under',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Jump rope passing three times under feet per jump',
    equipmentTypes: ['JUMP_ROPE'],
    defaultReps: 10,
    foundationMovement: 'Double Under',
    standardAbbreviation: 'TU',
    difficulty: 'Advanced',
  },
  {
    name: 'Pistol Squat',
    nameSv: 'Pistol Squat',
    nameEn: 'Pistol Squat',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Legs',
    description: 'Single-leg squat with other leg extended',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 10,
    foundationMovement: 'Box Pistol',
    standardAbbreviation: 'PS',
    difficulty: 'Advanced',
  },
  {
    name: 'Push-Up',
    nameSv: 'Armhävning',
    nameEn: 'Push-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Chest',
    description: 'Standard push-up',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 20,
    standardAbbreviation: 'PuU',
    difficulty: 'Beginner',
  },
  {
    name: 'Burpee',
    nameSv: 'Burpee',
    nameEn: 'Burpee',
    category: 'OTHER',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Full Body',
    description: 'Squat thrust with push-up and jump',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 15,
    standardAbbreviation: 'BUR',
    difficulty: 'Beginner',
  },
  {
    name: 'Burpee Box Jump Over',
    nameSv: 'Burpee Boxhopp Över',
    nameEn: 'Burpee Box Jump Over',
    category: 'OTHER',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Full Body',
    description: 'Burpee with box jump over at end',
    equipmentTypes: ['BOX', 'BODYWEIGHT'],
    defaultReps: 10,
    standardAbbreviation: 'BBJO',
    difficulty: 'Intermediate',
  },
  {
    name: 'Bar Facing Burpee',
    nameSv: 'Bar Facing Burpee',
    nameEn: 'Bar Facing Burpee',
    category: 'OTHER',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Full Body',
    description: 'Burpee facing barbell with lateral jump over',
    equipmentTypes: ['BARBELL', 'BODYWEIGHT'],
    defaultReps: 15,
    standardAbbreviation: 'BFB',
    difficulty: 'Intermediate',
  },
  {
    name: 'Burpee Pull-Up',
    nameSv: 'Burpee Chins',
    nameEn: 'Burpee Pull-Up',
    category: 'OTHER',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Full Body',
    description: 'Burpee finishing with pull-up',
    equipmentTypes: ['PULL_UP_BAR', 'BODYWEIGHT'],
    defaultReps: 10,
    standardAbbreviation: 'BPU',
    difficulty: 'Intermediate',
  },

  // ==================== MONOSTRUCTURAL (CARDIO) ====================
  {
    name: 'Run',
    nameSv: 'Löpning',
    nameEn: 'Run',
    category: 'RUNNING',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Cardio',
    description: 'Running for distance',
    equipmentTypes: ['RUNNING'],
    standardAbbreviation: 'RUN',
    difficulty: 'Beginner',
  },
  {
    name: 'Row (Calories)',
    nameSv: 'Rodd (Kalorier)',
    nameEn: 'Row (Calories)',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Row for calories on ergometer',
    equipmentTypes: ['MACHINE_ROW'],
    standardAbbreviation: 'ROW',
    difficulty: 'Beginner',
  },
  {
    name: 'Row (Meters)',
    nameSv: 'Rodd (Meter)',
    nameEn: 'Row (Meters)',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Row for distance on ergometer',
    equipmentTypes: ['MACHINE_ROW'],
    standardAbbreviation: 'ROW',
    difficulty: 'Beginner',
  },
  {
    name: 'Bike (Calories)',
    nameSv: 'Cykel (Kalorier)',
    nameEn: 'Bike (Calories)',
    category: 'CYCLING',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Legs',
    description: 'Bike for calories',
    equipmentTypes: ['MACHINE_BIKE'],
    standardAbbreviation: 'BIKE',
    difficulty: 'Beginner',
  },
  {
    name: 'Bike (Meters)',
    nameSv: 'Cykel (Meter)',
    nameEn: 'Bike (Meters)',
    category: 'CYCLING',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Legs',
    description: 'Bike for distance',
    equipmentTypes: ['MACHINE_BIKE'],
    standardAbbreviation: 'BIKE',
    difficulty: 'Beginner',
  },
  {
    name: 'Assault Bike (Calories)',
    nameSv: 'Assault Bike (Kalorier)',
    nameEn: 'Assault Bike (Calories)',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Air bike for calories',
    equipmentTypes: ['ASSAULT_BIKE'],
    standardAbbreviation: 'AB',
    difficulty: 'Intermediate',
  },
  {
    name: 'Ski Erg (Calories)',
    nameSv: 'Ski Erg (Kalorier)',
    nameEn: 'Ski Erg (Calories)',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Upper Body',
    description: 'Ski erg for calories',
    equipmentTypes: ['MACHINE_SKI'],
    standardAbbreviation: 'SKI',
    difficulty: 'Intermediate',
  },
  {
    name: 'Ski Erg (Meters)',
    nameSv: 'Ski Erg (Meter)',
    nameEn: 'Ski Erg (Meters)',
    category: 'OTHER',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Upper Body',
    description: 'Ski erg for distance',
    equipmentTypes: ['MACHINE_SKI'],
    standardAbbreviation: 'SKI',
    difficulty: 'Intermediate',
  },
  {
    name: 'Swim',
    nameSv: 'Simning',
    nameEn: 'Swim',
    category: 'SWIMMING',
    movementCategory: 'MONOSTRUCTURAL',
    muscleGroup: 'Full Body',
    description: 'Swimming for distance',
    equipmentTypes: ['SWIMMING'],
    standardAbbreviation: 'SWIM',
    difficulty: 'Intermediate',
  },

  // ==================== KETTLEBELL ====================
  {
    name: 'Kettlebell Swing',
    nameSv: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Posterior Chain',
    description: 'Russian swing to eye level',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 20,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBS',
    difficulty: 'Beginner',
  },
  {
    name: 'American Kettlebell Swing',
    nameSv: 'Amerikansk Kettlebell Swing',
    nameEn: 'American Kettlebell Swing',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Full Body',
    description: 'Swing to overhead position',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 20,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'AKBS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Turkish Get-Up',
    nameSv: 'Turkish Get-Up',
    nameEn: 'Turkish Get-Up',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Full Body',
    description: 'Stand up from floor while holding KB overhead',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 5,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'TGU',
    difficulty: 'Intermediate',
  },
  {
    name: 'Goblet Squat',
    nameSv: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Legs',
    description: 'Squat holding KB at chest',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 15,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'GS',
    difficulty: 'Beginner',
  },
  {
    name: 'KB Snatch',
    nameSv: 'KB Ryck',
    nameEn: 'Kettlebell Snatch',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Full Body',
    description: 'Single-arm snatch with kettlebell',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 10,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBSN',
    difficulty: 'Intermediate',
  },
  {
    name: 'KB Clean',
    nameSv: 'KB Frivändning',
    nameEn: 'Kettlebell Clean',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Full Body',
    description: 'Single-arm clean with kettlebell',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 10,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBC',
    difficulty: 'Intermediate',
  },
  {
    name: 'KB Thruster',
    nameSv: 'KB Thruster',
    nameEn: 'Kettlebell Thruster',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Full Body',
    description: 'KB front squat to press',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 10,
    defaultWeightMale: 24,
    defaultWeightFemale: 16,
    scaledWeightMale: 16,
    scaledWeightFemale: 12,
    standardAbbreviation: 'KBTH',
    difficulty: 'Intermediate',
  },
  {
    name: 'KB Windmill',
    nameSv: 'KB Windmill',
    nameEn: 'Kettlebell Windmill',
    category: 'STRENGTH',
    movementCategory: 'KETTLEBELL_WORK',
    muscleGroup: 'Core',
    description: 'Hinge to floor while holding KB overhead',
    equipmentTypes: ['KETTLEBELL'],
    defaultReps: 10,
    defaultWeightMale: 16,
    defaultWeightFemale: 12,
    scaledWeightMale: 12,
    scaledWeightFemale: 8,
    standardAbbreviation: 'KBWM',
    difficulty: 'Intermediate',
  },

  // ==================== STRONGMAN ====================
  {
    name: 'Farmers Carry',
    nameSv: 'Farmers Walk',
    nameEn: 'Farmers Carry',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Grip',
    description: 'Walk while holding heavy implements',
    equipmentTypes: ['KETTLEBELL', 'DUMBBELL'],
    defaultWeightMale: 32,
    defaultWeightFemale: 24,
    scaledWeightMale: 24,
    scaledWeightFemale: 16,
    standardAbbreviation: 'FC',
    difficulty: 'Beginner',
  },
  {
    name: 'Sandbag Carry',
    nameSv: 'Sandsäcksbärning',
    nameEn: 'Sandbag Carry',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Full Body',
    description: 'Carry sandbag for distance',
    equipmentTypes: ['SANDBAG'],
    defaultWeightMale: 68,
    defaultWeightFemale: 45,
    scaledWeightMale: 45,
    scaledWeightFemale: 30,
    standardAbbreviation: 'SBC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sandbag Clean',
    nameSv: 'Sandsäck Frivändning',
    nameEn: 'Sandbag Clean',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Full Body',
    description: 'Clean sandbag from floor to shoulder',
    equipmentTypes: ['SANDBAG'],
    defaultReps: 10,
    defaultWeightMale: 68,
    defaultWeightFemale: 45,
    scaledWeightMale: 45,
    scaledWeightFemale: 30,
    standardAbbreviation: 'SBC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sandbag Over Shoulder',
    nameSv: 'Sandsäck Över Axeln',
    nameEn: 'Sandbag Over Shoulder',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Full Body',
    description: 'Throw sandbag over shoulder',
    equipmentTypes: ['SANDBAG'],
    defaultReps: 10,
    defaultWeightMale: 68,
    defaultWeightFemale: 45,
    scaledWeightMale: 45,
    scaledWeightFemale: 30,
    standardAbbreviation: 'SBO',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sled Push',
    nameSv: 'Slädtryckning',
    nameEn: 'Sled Push',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Legs',
    description: 'Push weighted sled for distance',
    equipmentTypes: ['SLED'],
    defaultWeightMale: 113,
    defaultWeightFemale: 79,
    scaledWeightMale: 79,
    scaledWeightFemale: 57,
    standardAbbreviation: 'SLDP',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sled Pull',
    nameSv: 'Slädragning',
    nameEn: 'Sled Pull',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Full Body',
    description: 'Pull weighted sled for distance',
    equipmentTypes: ['SLED'],
    defaultWeightMale: 102,
    defaultWeightFemale: 70,
    scaledWeightMale: 70,
    scaledWeightFemale: 47,
    standardAbbreviation: 'SLDR',
    difficulty: 'Intermediate',
  },
  {
    name: 'Yoke Carry',
    nameSv: 'Yoke Walk',
    nameEn: 'Yoke Carry',
    category: 'STRENGTH',
    movementCategory: 'STRONGMAN',
    muscleGroup: 'Full Body',
    description: 'Walk with yoke on shoulders',
    equipmentTypes: ['YOKE'],
    defaultWeightMale: 181,
    defaultWeightFemale: 120,
    scaledWeightMale: 120,
    scaledWeightFemale: 79,
    standardAbbreviation: 'YC',
    difficulty: 'Advanced',
  },

  // ==================== CORE ====================
  {
    name: 'Sit-Up',
    nameSv: 'Sit-Up',
    nameEn: 'Sit-Up',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Standard sit-up',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 20,
    standardAbbreviation: 'SU',
    difficulty: 'Beginner',
  },
  {
    name: 'GHD Sit-Up',
    nameSv: 'GHD Sit-Up',
    nameEn: 'GHD Sit-Up',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Sit-up on GHD machine',
    equipmentTypes: ['GHD'],
    defaultReps: 20,
    foundationMovement: 'Sit-Up',
    standardAbbreviation: 'GHDS',
    difficulty: 'Intermediate',
  },
  {
    name: 'V-Up',
    nameSv: 'V-Up',
    nameEn: 'V-Up',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Touch toes while raising legs and torso',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 20,
    standardAbbreviation: 'VU',
    difficulty: 'Intermediate',
  },
  {
    name: 'L-Sit',
    nameSv: 'L-Sit',
    nameEn: 'L-Sit',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Hold L position on parallettes or rings',
    equipmentTypes: ['PARALLETTES', 'RINGS'],
    standardAbbreviation: 'LS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Plank',
    nameSv: 'Planka',
    nameEn: 'Plank',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Hold plank position',
    equipmentTypes: ['BODYWEIGHT'],
    standardAbbreviation: 'PLK',
    difficulty: 'Beginner',
  },
  {
    name: 'Russian Twist',
    nameSv: 'Rysk Twist',
    nameEn: 'Russian Twist',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Rotating core exercise',
    equipmentTypes: ['BODYWEIGHT', 'MEDICINE_BALL'],
    defaultReps: 20,
    standardAbbreviation: 'RT',
    difficulty: 'Beginner',
  },
  {
    name: 'Hip Extension',
    nameSv: 'Höftextension',
    nameEn: 'Hip Extension',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Posterior Chain',
    description: 'Hip extension on GHD',
    equipmentTypes: ['GHD'],
    defaultReps: 20,
    standardAbbreviation: 'HE',
    difficulty: 'Intermediate',
  },
  {
    name: 'Back Extension',
    nameSv: 'Ryggextension',
    nameEn: 'Back Extension',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Lower Back',
    description: 'Back extension on GHD',
    equipmentTypes: ['GHD'],
    defaultReps: 20,
    standardAbbreviation: 'BE',
    difficulty: 'Intermediate',
  },

  // ==================== ACCESSORY / DUMBBELL ====================
  {
    name: 'Wall Ball',
    nameSv: 'Wall Ball',
    nameEn: 'Wall Ball',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Squat and throw medicine ball to target',
    equipmentTypes: ['WALL_BALL'],
    defaultReps: 20,
    defaultWeightMale: 9,
    defaultWeightFemale: 6,
    scaledWeightMale: 6,
    scaledWeightFemale: 4,
    standardAbbreviation: 'WB',
    difficulty: 'Beginner',
  },
  {
    name: 'Med Ball Clean',
    nameSv: 'Medicinboll Frivändning',
    nameEn: 'Medicine Ball Clean',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Clean with medicine ball',
    equipmentTypes: ['MEDICINE_BALL'],
    defaultReps: 15,
    defaultWeightMale: 9,
    defaultWeightFemale: 6,
    standardAbbreviation: 'MBC',
    difficulty: 'Beginner',
  },
  {
    name: 'Thruster',
    nameSv: 'Thruster',
    nameEn: 'Thruster',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Front squat to push press',
    equipmentTypes: ['BARBELL'],
    defaultReps: 15,
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'TH',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Thruster',
    nameSv: 'Hantel Thruster',
    nameEn: 'Dumbbell Thruster',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Dumbbell front squat to press',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 15,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBTH',
    difficulty: 'Intermediate',
  },
  {
    name: 'Cluster',
    nameSv: 'Cluster',
    nameEn: 'Cluster',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Squat clean to thruster',
    equipmentTypes: ['BARBELL'],
    defaultReps: 10,
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'CL',
    difficulty: 'Advanced',
  },
  {
    name: 'Lunge',
    nameSv: 'Utfall',
    nameEn: 'Lunge',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Walking or stationary lunge',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 20,
    standardAbbreviation: 'LU',
    difficulty: 'Beginner',
  },
  {
    name: 'Walking Lunge',
    nameSv: 'Gående Utfall',
    nameEn: 'Walking Lunge',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Continuous forward lunges',
    equipmentTypes: ['BODYWEIGHT', 'BARBELL', 'DUMBBELL'],
    defaultReps: 20,
    standardAbbreviation: 'WL',
    difficulty: 'Beginner',
  },
  {
    name: 'Overhead Lunge',
    nameSv: 'Overhead Utfall',
    nameEn: 'Overhead Lunge',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Lunge while holding weight overhead',
    equipmentTypes: ['BARBELL', 'DUMBBELL'],
    defaultReps: 20,
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'OHL',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Squat',
    nameSv: 'Hantel Knäböj',
    nameEn: 'Dumbbell Squat',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Squat holding dumbbells',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 15,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBS',
    difficulty: 'Beginner',
  },
  {
    name: 'DB Push Press',
    nameSv: 'Hantel Pushpress',
    nameEn: 'Dumbbell Push Press',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Shoulders',
    description: 'Dumbbell overhead press with leg drive',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 15,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBPP',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Strict Press',
    nameSv: 'Hantel Militärpress',
    nameEn: 'Dumbbell Strict Press',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Shoulders',
    description: 'Dumbbell overhead press without leg drive',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 10,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBSP',
    difficulty: 'Beginner',
  },
  {
    name: 'DB Row',
    nameSv: 'Hantel Rodd',
    nameEn: 'Dumbbell Row',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Back',
    description: 'Single-arm row with dumbbell',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 10,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBR',
    difficulty: 'Beginner',
  },
  {
    name: 'DB Deadlift',
    nameSv: 'Hantel Marklyft',
    nameEn: 'Dumbbell Deadlift',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Posterior Chain',
    description: 'Deadlift with dumbbells',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 10,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBDL',
    difficulty: 'Beginner',
  },
  {
    name: 'Man Maker',
    nameSv: 'Man Maker',
    nameEn: 'Man Maker',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Push-up, row, clean, thruster with DBs',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 5,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'MM',
    difficulty: 'Advanced',
  },
  {
    name: 'Devil Press',
    nameSv: 'Devil Press',
    nameEn: 'Devil Press',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Full Body',
    description: 'Burpee with DB snatch',
    equipmentTypes: ['DUMBBELL'],
    defaultReps: 10,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DP',
    difficulty: 'Intermediate',
  },
  {
    name: 'DB Box Step-Over',
    nameSv: 'Hantel Box Step-Over',
    nameEn: 'Dumbbell Box Step-Over',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Step over box while holding dumbbells',
    equipmentTypes: ['DUMBBELL', 'BOX'],
    defaultReps: 20,
    defaultWeightMale: 22.5,
    defaultWeightFemale: 15,
    scaledWeightMale: 15,
    scaledWeightFemale: 10,
    standardAbbreviation: 'DBSO',
    difficulty: 'Intermediate',
  },

  // ==================== HYROX STATIONS ====================
  {
    name: 'SkiErg',
    nameSv: 'SkiErg',
    nameEn: 'SkiErg',
    category: 'OTHER',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Upper Body',
    description: 'HYROX station: 1000m ski erg',
    equipmentTypes: ['MACHINE_SKI'],
    standardAbbreviation: 'SKI',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sled Push (HYROX)',
    nameSv: 'Slädtryckning (HYROX)',
    nameEn: 'Sled Push (HYROX)',
    category: 'STRENGTH',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Legs',
    description: 'HYROX station: 50m sled push',
    equipmentTypes: ['SLED'],
    defaultWeightMale: 152,
    defaultWeightFemale: 102,
    scaledWeightMale: 102,
    scaledWeightFemale: 68,
    standardAbbreviation: 'SLDP',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sled Pull (HYROX)',
    nameSv: 'Slädragning (HYROX)',
    nameEn: 'Sled Pull (HYROX)',
    category: 'STRENGTH',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Full Body',
    description: 'HYROX station: 50m sled pull',
    equipmentTypes: ['SLED'],
    defaultWeightMale: 103,
    defaultWeightFemale: 78,
    scaledWeightMale: 78,
    scaledWeightFemale: 53,
    standardAbbreviation: 'SLDR',
    difficulty: 'Intermediate',
  },
  {
    name: 'Burpee Broad Jump',
    nameSv: 'Burpee Längdhopp',
    nameEn: 'Burpee Broad Jump',
    category: 'OTHER',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Full Body',
    description: 'HYROX station: 80m burpee broad jumps',
    equipmentTypes: ['BODYWEIGHT'],
    standardAbbreviation: 'BBJ',
    difficulty: 'Intermediate',
  },
  {
    name: 'Rowing (HYROX)',
    nameSv: 'Rodd (HYROX)',
    nameEn: 'Rowing (HYROX)',
    category: 'OTHER',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Full Body',
    description: 'HYROX station: 1000m row',
    equipmentTypes: ['MACHINE_ROW'],
    standardAbbreviation: 'ROW',
    difficulty: 'Intermediate',
  },
  {
    name: 'Farmers Carry (HYROX)',
    nameSv: 'Farmers Walk (HYROX)',
    nameEn: 'Farmers Carry (HYROX)',
    category: 'STRENGTH',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Grip',
    description: 'HYROX station: 200m farmers carry',
    equipmentTypes: ['KETTLEBELL'],
    defaultWeightMale: 32,
    defaultWeightFemale: 24,
    scaledWeightMale: 24,
    scaledWeightFemale: 16,
    standardAbbreviation: 'FC',
    difficulty: 'Intermediate',
  },
  {
    name: 'Sandbag Lunges (HYROX)',
    nameSv: 'Sandsäck Utfall (HYROX)',
    nameEn: 'Sandbag Lunges (HYROX)',
    category: 'STRENGTH',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Legs',
    description: 'HYROX station: 100m sandbag lunges',
    equipmentTypes: ['SANDBAG'],
    defaultWeightMale: 20,
    defaultWeightFemale: 10,
    scaledWeightMale: 10,
    scaledWeightFemale: 5,
    standardAbbreviation: 'SBL',
    difficulty: 'Intermediate',
  },
  {
    name: 'Wall Balls (HYROX)',
    nameSv: 'Wall Balls (HYROX)',
    nameEn: 'Wall Balls (HYROX)',
    category: 'STRENGTH',
    movementCategory: 'HYROX_STATION',
    muscleGroup: 'Full Body',
    description: 'HYROX station: 100 wall balls',
    equipmentTypes: ['WALL_BALL'],
    defaultReps: 100,
    defaultWeightMale: 9,
    defaultWeightFemale: 6,
    scaledWeightMale: 6,
    scaledWeightFemale: 4,
    standardAbbreviation: 'WB',
    difficulty: 'Intermediate',
  },

  // ==================== ADDITIONAL MOVEMENTS ====================
  {
    name: 'Bar Dip',
    nameSv: 'Dips',
    nameEn: 'Bar Dip',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Triceps',
    description: 'Dip on parallel bars',
    equipmentTypes: ['PARALLETTES'],
    defaultReps: 10,
    standardAbbreviation: 'DIP',
    difficulty: 'Intermediate',
  },
  {
    name: 'Box Dip',
    nameSv: 'Box Dips',
    nameEn: 'Box Dip',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Triceps',
    description: 'Dip using bench or box',
    equipmentTypes: ['BOX'],
    defaultReps: 15,
    standardAbbreviation: 'BDIP',
    difficulty: 'Beginner',
  },
  {
    name: 'Pike Push-Up',
    nameSv: 'Pike Push-Up',
    nameEn: 'Pike Push-Up',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Shoulders',
    description: 'Push-up with hips raised',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 10,
    standardAbbreviation: 'PPU',
    difficulty: 'Intermediate',
  },
  {
    name: 'Box Pistol',
    nameSv: 'Box Pistol',
    nameEn: 'Box Pistol',
    category: 'STRENGTH',
    movementCategory: 'GYMNASTICS',
    muscleGroup: 'Legs',
    description: 'Single-leg squat to box',
    equipmentTypes: ['BOX'],
    defaultReps: 10,
    standardAbbreviation: 'BPS',
    difficulty: 'Intermediate',
  },
  {
    name: 'Air Squat',
    nameSv: 'Luftknäböj',
    nameEn: 'Air Squat',
    category: 'STRENGTH',
    movementCategory: 'ACCESSORY',
    muscleGroup: 'Legs',
    description: 'Bodyweight squat',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 20,
    standardAbbreviation: 'AS',
    difficulty: 'Beginner',
  },
  {
    name: 'Mountain Climber',
    nameSv: 'Mountain Climbers',
    nameEn: 'Mountain Climber',
    category: 'CORE',
    movementCategory: 'CORE_WORK',
    muscleGroup: 'Core',
    description: 'Alternating knee drives in plank position',
    equipmentTypes: ['BODYWEIGHT'],
    defaultReps: 30,
    standardAbbreviation: 'MC',
    difficulty: 'Beginner',
  },
  {
    name: 'Pendlay Row',
    nameSv: 'Pendlay Rodd',
    nameEn: 'Pendlay Row',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Back',
    description: 'Barbell row from dead stop',
    equipmentTypes: ['BARBELL'],
    defaultReps: 10,
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'PR',
    difficulty: 'Intermediate',
  },
  {
    name: 'Bent Over Row',
    nameSv: 'Böjd Rodd',
    nameEn: 'Bent Over Row',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Back',
    description: 'Barbell row in bent over position',
    equipmentTypes: ['BARBELL'],
    defaultReps: 10,
    defaultWeightMale: 61,
    defaultWeightFemale: 43,
    scaledWeightMale: 43,
    scaledWeightFemale: 29,
    standardAbbreviation: 'BOR',
    difficulty: 'Intermediate',
  },
  {
    name: 'Romanian Deadlift',
    nameSv: 'Rumänsk Marklyft',
    nameEn: 'Romanian Deadlift',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Posterior Chain',
    description: 'Hip hinge deadlift variation',
    equipmentTypes: ['BARBELL'],
    defaultReps: 10,
    defaultWeightMale: 70,
    defaultWeightFemale: 47,
    scaledWeightMale: 47,
    scaledWeightFemale: 29,
    standardAbbreviation: 'RDL',
    difficulty: 'Intermediate',
  },
  {
    name: 'Good Morning',
    nameSv: 'Good Morning',
    nameEn: 'Good Morning',
    category: 'STRENGTH',
    movementCategory: 'POWERLIFTING',
    muscleGroup: 'Posterior Chain',
    description: 'Hip hinge with bar on back',
    equipmentTypes: ['BARBELL'],
    defaultReps: 10,
    defaultWeightMale: 43,
    defaultWeightFemale: 29,
    scaledWeightMale: 29,
    scaledWeightFemale: 20,
    standardAbbreviation: 'GM',
    difficulty: 'Intermediate',
  },
];

async function main() {
  console.log('🏋️ Starting Hybrid Studio Movement Seeder...');
  console.log(`📦 Seeding ${hybridMovements.length} movements...`);

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const movement of hybridMovements) {
    // Check if movement already exists by name
    const existing = await prisma.exercise.findFirst({
      where: { name: movement.name },
    });

    if (existing) {
      // Update existing exercise with hybrid fields if it wasn't already a hybrid movement
      if (!existing.isHybridMovement) {
        await prisma.exercise.update({
          where: { id: existing.id },
          data: {
            isHybridMovement: true,
            movementCategory: movement.movementCategory,
            equipmentTypes: movement.equipmentTypes,
            defaultReps: movement.defaultReps,
            defaultWeightMale: movement.defaultWeightMale,
            defaultWeightFemale: movement.defaultWeightFemale,
            scaledWeightMale: movement.scaledWeightMale,
            scaledWeightFemale: movement.scaledWeightFemale,
            foundationMovement: movement.foundationMovement,
            standardAbbreviation: movement.standardAbbreviation,
            nameSv: movement.nameSv,
            nameEn: movement.nameEn,
            description: movement.description,
            difficulty: movement.difficulty,
            muscleGroup: movement.muscleGroup,
          },
        });
        updated++;
        console.log(`  ✏️  Updated: ${movement.name}`);
      } else {
        skipped++;
      }
    } else {
      // Create new exercise
      await prisma.exercise.create({
        data: {
          name: movement.name,
          nameSv: movement.nameSv,
          nameEn: movement.nameEn,
          category: movement.category,
          movementCategory: movement.movementCategory,
          muscleGroup: movement.muscleGroup,
          description: movement.description,
          equipmentTypes: movement.equipmentTypes,
          defaultReps: movement.defaultReps,
          defaultWeightMale: movement.defaultWeightMale,
          defaultWeightFemale: movement.defaultWeightFemale,
          scaledWeightMale: movement.scaledWeightMale,
          scaledWeightFemale: movement.scaledWeightFemale,
          foundationMovement: movement.foundationMovement,
          standardAbbreviation: movement.standardAbbreviation,
          difficulty: movement.difficulty,
          isPublic: true,
          isHybridMovement: true,
        },
      });
      created++;
      console.log(`  ✅ Created: ${movement.name}`);
    }
  }

  console.log('\n📊 Seeding Summary:');
  console.log(`  ✅ Created: ${created}`);
  console.log(`  ✏️  Updated: ${updated}`);
  console.log(`  ⏭️  Skipped: ${skipped}`);
  console.log('\n🎉 Hybrid movements seeding complete!');
}

main()
  .catch((e) => {
    console.error('Error seeding hybrid movements:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
