// prisma/seed-exercises.ts
// Comprehensive exercise library based on scientific strength training framework
// Run with: npx ts-node prisma/seed-exercises.ts

import { PrismaClient, BiomechanicalPillar, ProgressionLevel, PlyometricIntensity } from '@prisma/client'

const prisma = new PrismaClient()

const exercises = [
  // ========================================
  // POSTERIOR CHAIN (Hip Dominance)
  // ========================================
  {
    name: 'HÃ¶ftbrygga',
    nameSv: 'HÃ¶ftbrygga',
    nameEn: 'Glute Bridge',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'GrundlÃ¤ggande gluteus-aktivering',
    instructions: '1. Ligg pÃ¥ rygg med knÃ¤n bÃ¶jda\n2. FÃ¶tterna platt i golvet\n3. Lyft hÃ¶ften uppÃ¥t\n4. SpÃ¤nn skinkor i toppen\n5. SÃ¤nk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Enbensbrygga',
    nameSv: 'Enbensbrygga',
    nameEn: 'Single-Leg Glute Bridge',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig gluteus-styrka',
    instructions: '1. Ligg pÃ¥ rygg med ena benet strÃ¤ckt\n2. Lyft hÃ¶ften pÃ¥ ett ben\n3. HÃ¥ll hÃ¶fterna jÃ¤mna\n4. SpÃ¤nn skinkan\n5. VÃ¤xla ben',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Clamshells med band',
    nameSv: 'Clamshells med band',
    nameEn: 'Clamshells with Band',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Gluteus medius aktivering - fÃ¶rebygger knÃ¤valgus',
    instructions: '1. Ligg pÃ¥ sidan med knÃ¤n bÃ¶jda\n2. Band runt knÃ¤na\n3. Ã–ppna Ã¶versta knÃ¤t\n4. MotstÃ¥ bandet\n5. HÃ¥ll hÃ¶fterna stabila',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Hip hikes',
    nameSv: 'Hip hikes',
    nameEn: 'Hip Hikes',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'FÃ¶rebygger hÃ¶ftdropp under lÃ¶pning',
    instructions: '1. StÃ¥ pÃ¥ en fot pÃ¥ steglÃ¥da\n2. SÃ¤nk motsatt hÃ¶ft\n3. Lyft hÃ¶ften med gluteus medius\n4. Kontrollerad rÃ¶relse',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Fire Hydrants',
    nameSv: 'Fire Hydrants',
    nameEn: 'Fire Hydrants',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'HÃ¶ftabduktion fÃ¶r gluteus medius',
    instructions: '1. PÃ¥ alla fyra\n2. Lyft knÃ¤t ut Ã¥t sidan\n3. HÃ¥ll 90 graders bÃ¶jning i knÃ¤t\n4. SpÃ¤nn glut',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Hip Thrust med skivstÃ¥ng',
    nameSv: 'Hip Thrust med skivstÃ¥ng',
    nameEn: 'Barbell Hip Thrust',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Maximal gluteus-styrka',
    instructions: '1. Rygg mot bÃ¤nk\n2. SkivstÃ¥ng Ã¶ver hÃ¶fterna\n3. Tryck hÃ¶fterna uppÃ¥t\n4. Posteriort pelvis tilt i toppen\n5. SÃ¤nk kontrollerat',
    equipment: 'SkivstÃ¥ng, bÃ¤nk, pad',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'RumÃ¤nsk marklyft',
    nameSv: 'RumÃ¤nsk marklyft',
    nameEn: 'Romanian Deadlift (RDL)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerar hases och gluteus med excentrisk betoning',
    instructions: '1. HÃ¥ll stÃ¥ngen med raka armar\n2. BÃ¶j i hÃ¶ften med lÃ¤tt bÃ¶jda knÃ¤n\n3. KÃ¤nn stretch i hases\n4. Tryck hÃ¶fterna framÃ¥t\n5. BehÃ¥ll neutral rygg',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Enbenig rumÃ¤nsk marklyft',
    nameSv: 'Enbenig rumÃ¤nsk marklyft',
    nameEn: 'Single-Leg Romanian Deadlift',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, Gluteus, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig hases-styrka och proprioception',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. BÃ¶j i hÃ¶ften\n3. StrÃ¤ck fritt ben bakÃ¥t\n4. Balansera\n5. Ã…tergÃ¥ upprÃ¤tt',
    equipment: 'Hantlar eller kettlebell',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Good Mornings',
    nameSv: 'Good Mornings',
    nameEn: 'Good Mornings',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases, LÃ¤ndryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Posterior chain med betoning pÃ¥ excentrisk kontroll',
    instructions: '1. SkivstÃ¥ng pÃ¥ axlarna\n2. BÃ¶j framÃ¥t i hÃ¶ften\n3. Parallell rygg med golvet\n4. Stretch i hases\n5. Ã…tergÃ¥ upprÃ¤tt',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Cable Pull-Through',
    nameSv: 'Cable Pull-Through',
    nameEn: 'Cable Pull-Through',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'HÃ¶ftextension med kabel-motstÃ¥nd',
    instructions: '1. StÃ¥ med ryggen mot kabel\n2. Hantag mellan benen\n3. BÃ¶j i hÃ¶ften\n4. StrÃ¤ck hÃ¶fterna kraftfullt\n5. SpÃ¤nn glut i toppen',
    equipment: 'Kabel',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Kettlebell Swing',
    nameSv: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Explosiv hÃ¶ftextension - power development',
    instructions: '1. Bred stÃ¤llning\n2. Swing kettlebell mellan benen\n3. Explosiv hÃ¶ftstrÃ¤ckning\n4. Armarna passiva\n5. Ballistisk rÃ¶relse',
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Nordic Hamstring',
    nameSv: 'Nordisk hamstring',
    nameEn: 'Nordic Hamstring Curl',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Excentrisk hamstringstyrka - minskar skaderisk med upp till 51%',
    instructions: '1. KnÃ¤ pÃ¥ golvet, anklar fixerade\n2. Partner hÃ¥ller anklarna eller anvÃ¤nd fixering\n3. SÃ¤nk kroppen lÃ¥ngsamt framÃ¥t\n4. HÃ¥ll hÃ¶fterna raka (ingen bÃ¶jning)\n5. FÃ¥nga dig med hÃ¤nderna vid behov\n6. Tryck tillbaka eller gÃ¥ upp med hÃ¤nderna',
    equipment: 'Partner eller fixering',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Marklyft',
    nameSv: 'Marklyft',
    nameEn: 'Deadlift',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp - Posterior Chain',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'HelkroppsÃ¶vning med fokus pÃ¥ bakre kedjan',
    instructions: '1. StÃ¥ med fÃ¶tterna hÃ¶ftbrett\n2. BÃ¶j i hÃ¶ften och grip stÃ¥ngen\n3. Neutral rygg\n4. Lyft genom hÃ¶ft- och knÃ¤extension\n5. LÃ¥s ut i toppen',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Reverse Hyperextension',
    nameSv: 'Reverse Hyperextension',
    nameEn: 'Reverse Hyperextension',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Hases, LÃ¤ndryggen',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Gluteus och hases utan ryggbelastning',
    instructions: '1. Ligg pÃ¥ bÃ¤nk med hÃ¶fterna i kanten\n2. LÃ¥t benen hÃ¤nga\n3. Lyft benen bakÃ¥t och uppÃ¥t\n4. SpÃ¤nn glut\n5. SÃ¤nk kontrollerat',
    equipment: 'BÃ¤nk',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // KNEE DOMINANCE (Quadriceps Strength)
  // ========================================
  {
    name: 'KnÃ¤bÃ¶j',
    nameSv: 'KnÃ¤bÃ¶j',
    nameEn: 'Back Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'GrundlÃ¤ggande bilateral benstyrka',
    instructions: '1. SkivstÃ¥ng pÃ¥ axlarna\n2. FÃ¶tterna axelbrett\n3. SÃ¤nk dig nedÃ¥t\n4. HÃ¶ften under parallell\n5. Tryck upp explosivt',
    equipment: 'SkivstÃ¥ng, rack',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Goblet Squat',
    nameSv: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'LÃ¤r squat-mÃ¶nster med upprÃ¤tt bÃ¥l',
    instructions: '1. HÃ¥ll kettlebell/hantel vid brÃ¶stet\n2. BÃ¶j i knÃ¤n och hÃ¶fter\n3. ArmbÃ¥garna mellan knÃ¤na\n4. Djup squat\n5. Tryck upp',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Wall Sit',
    nameSv: 'VÃ¤ggstol',
    nameEn: 'Wall Sit',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isometrisk quad-styrka',
    instructions: '1. Rygg mot vÃ¤gg\n2. SÃ¤nk till 90 grader\n3. KnÃ¤n Ã¶ver anklar\n4. HÃ¥ll positionen\n5. SpÃ¤nn quads',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Front Squat',
    nameSv: 'Front Squat',
    nameEn: 'Front Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Quad-dominant squat med upprÃ¤tt bÃ¥l',
    instructions: '1. SkivstÃ¥ng pÃ¥ frÃ¤mre deltoider\n2. ArmbÃ¥garna hÃ¶gt\n3. Squat med upprÃ¤tt bÃ¥l\n4. Djup position\n5. Tryck upp',
    equipment: 'SkivstÃ¥ng, rack',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Split Squat',
    nameSv: 'Split Squat',
    nameEn: 'Split Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Statisk split position fÃ¶r quad-styrka',
    instructions: '1. SplitstÃ¤llning\n2. Bakre knÃ¤ sÃ¤nks mot golvet\n3. FrÃ¤mre knÃ¤ Ã¶ver ankel\n4. UpprÃ¤tt bÃ¥l\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Benpress',
    nameSv: 'Benpress',
    nameEn: 'Leg Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Benstyrka utan ryggbelastning',
    instructions: '1. FÃ¶tterna pÃ¥ plattan\n2. SÃ¤nk kontrollerat\n3. KnÃ¤n mot brÃ¶st\n4. Tryck upp kraftfullt\n5. LÃ¥s inte knÃ¤na helt',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Pistol Squat Progression',
    nameSv: 'Pistol Squat Progression',
    nameEn: 'Pistol Squat Progression',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Enbenssquat fÃ¶r avancerad styrka',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. StrÃ¤ck andra benet framÃ¥t\n3. Squat hela vÃ¤gen ner\n4. Balansera\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Cyclist Squat',
    nameSv: 'Cyclist Squat',
    nameEn: 'Cyclist Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerad quad-styrka med hÃ¤llyft',
    instructions: '1. HÃ¤larna pÃ¥ platta (5-10cm)\n2. UpprÃ¤tt bÃ¥l\n3. Smal stÃ¤llning\n4. Djup squat\n5. Quad-dominant',
    equipment: 'Hantlar, platta',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Hoppsquat',
    nameSv: 'Hoppsquat',
    nameEn: 'Jump Squat',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Explosiv quad-power',
    instructions: '1. Squat position\n2. Explosiv hopp\n3. Armsving\n4. Mjuk landning\n5. Direkt i nÃ¤sta rep',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // UNILATERAL (Single-Leg Bias)
  // ========================================
  {
    name: 'Bulgarisk utfallsbÃ¶j',
    nameSv: 'Bulgarisk utfallsbÃ¶j',
    nameEn: 'Bulgarian Split Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig benstyrka - "The Big Three" fÃ¶r lÃ¶pare',
    instructions: '1. Bakre fot pÃ¥ bÃ¤nk\n2. FrÃ¤mre fot framÃ¥t\n3. SÃ¤nk bakre knÃ¤\n4. UpprÃ¤tt bÃ¥l\n5. Tryck upp pÃ¥ frÃ¤mre ben',
    equipment: 'BÃ¤nk, hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Utfallssteg',
    nameSv: 'Utfallssteg',
    nameEn: 'Walking Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk enbensstyrka',
    instructions: '1. Steg framÃ¥t\n2. SÃ¤nk bakre knÃ¤\n3. 90 grader i bÃ¥da knÃ¤na\n4. Tryck upp\n5. Upprepa med annat ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'BakÃ¥tlunges',
    nameSv: 'BakÃ¥tlunges',
    nameEn: 'Reverse Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Mer knÃ¤vÃ¤nlig Ã¤n framÃ¥tlunges',
    instructions: '1. Steg bakÃ¥t\n2. SÃ¤nk bakre knÃ¤\n3. FrÃ¤mre knÃ¤ stabilt Ã¶ver ankel\n4. Tryck upp\n5. VÃ¤xla ben',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Lateral Lunges',
    nameSv: 'Lateral Lunges',
    nameEn: 'Lateral Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Adduktorer, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Frontalplanstyrka',
    instructions: '1. Steg Ã¥t sidan\n2. BÃ¶j i ett knÃ¤\n3. Andra benet rakt\n4. Sitt bakÃ¥t\n5. Tryck upp och tillbaka',
    equipment: 'Ingen eller hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Curtsy Lunges',
    nameSv: 'Curtsy Lunges',
    nameEn: 'Curtsy Lunges',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus Medius, Quadriceps',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Gluteus medius och hÃ¶ftrotation',
    instructions: '1. Steg diagonalt bakÃ¥t\n2. Korsa bakom stÃ¥ende ben\n3. SÃ¤nk i utfallsposition\n4. HÃ¥ll hÃ¶fterna framÃ¥t\n5. Tryck upp',
    equipment: 'Hantlar (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Step-Ups (lÃ¥g)',
    nameSv: 'Step-Ups (lÃ¥g)',
    nameEn: 'Step-Ups (Low Box)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'GrundlÃ¤ggande enbensstyrka',
    instructions: '1. LÃ¥g lÃ¥da (30-40cm)\n2. Placera fot pÃ¥ lÃ¥dan\n3. Tryck upp med det benet\n4. StÃ¥ stadigt\n5. SÃ¤nk kontrollerat',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Step-Ups (hÃ¶g)',
    nameSv: 'Step-Ups (hÃ¶g)',
    nameEn: 'Step-Ups (High Box)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Avancerad enbensstyrka',
    instructions: '1. HÃ¶g lÃ¥da (50-60cm)\n2. Explosiv uppgÃ¥ng\n3. Hela foten pÃ¥ lÃ¥dan\n4. LÃ¥s ut hÃ¶ft och knÃ¤\n5. Kontrollerad nedgÃ¥ng',
    equipment: 'SteglÃ¥da, hantlar',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Step-Ups med knÃ¤drive',
    nameSv: 'Step-Ups med knÃ¤drive',
    nameEn: 'Step-Ups with Knee Drive',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, HÃ¶ftflexorer',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'LÃ¶pspecifik knÃ¤drive',
    instructions: '1. Step-up pÃ¥ lÃ¥da\n2. Svinga fria benet\n3. KnÃ¤ hÃ¶gt (90 grader)\n4. Balansera pÃ¥ stÃ¥ende ben\n5. Kontrollerad nedgÃ¥ng',
    equipment: 'SteglÃ¥da',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Enbenig benpress',
    nameSv: 'Enbenig benpress',
    nameEn: 'Single-Leg Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerad enbensstyrka',
    instructions: '1. En fot pÃ¥ plattan\n2. SÃ¤nk kontrollerat\n3. Djup position\n4. Tryck upp\n5. JÃ¤mfÃ¶r vÃ¤nster/hÃ¶ger',
    equipment: 'Benpress-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Skater Squats',
    nameSv: 'Skater Squats',
    nameEn: 'Skater Squats',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Balans',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad enbenssquat',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. SÃ¤nk dig nedÃ¥t\n3. Bakre ben bakom\n4. Bakre knÃ¤ mot golvet\n5. Tryck upp',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // FOOT & ANKLE COMPLEX
  // ========================================
  {
    name: 'TÃ¥hÃ¤vningar (raka ben)',
    nameSv: 'TÃ¥hÃ¤vningar (raka ben)',
    nameEn: 'Calf Raises (Straight Knee)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gastrocnemius',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Gastrocnemius-styrka',
    instructions: '1. StÃ¥ pÃ¥ kant/steglÃ¥da\n2. Raka ben\n3. Tryck upp pÃ¥ tÃ¥r\n4. Full ROM\n5. Kontrollerad sÃ¤nkning',
    equipment: 'SteglÃ¥da',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'TÃ¥hÃ¤vningar (bÃ¶jda ben)',
    nameSv: 'TÃ¥hÃ¤vningar (bÃ¶jda ben)',
    nameEn: 'Calf Raises (Bent Knee)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Soleus',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Soleus-fokus (viktig fÃ¶r lÃ¶pare)',
    instructions: '1. Sittande eller lÃ¤tt bÃ¶jda knÃ¤n\n2. Tryck upp pÃ¥ tÃ¥r\n3. Isolerar soleus\n4. HÃ¶g volym (15-20 reps)\n5. Kontrollerad tempo',
    equipment: 'Seated calf raise (eller kroppsvikt)',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Enbenig tÃ¥hÃ¤vning',
    nameSv: 'Enbenig tÃ¥hÃ¤vning',
    nameEn: 'Single-Leg Calf Raise',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gastrocnemius, Soleus',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ensidig vader-styrka',
    instructions: '1. Ett ben pÃ¥ kant\n2. Balansera\n3. Full dorsalflexion (sÃ¤nk hÃ¤len)\n4. Explosiv plantarflexion\n5. JÃ¤mfÃ¶r bilateral skillnad',
    equipment: 'SteglÃ¥da',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Ankelhopp',
    nameSv: 'Ankelhopp',
    nameEn: 'Ankle Hops',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vad, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Ankelstyvhet och reaktiv styrka',
    instructions: '1. Minimalt knÃ¤bÃ¶j\n2. Hopp frÃ¥n ankeln\n3. Snabb markkontakt\n4. Styvt ben\n5. Rytmisk',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Toe Yoga',
    nameSv: 'Toe Yoga',
    nameEn: 'Toe Yoga',
    category: 'STRENGTH' as const,
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Intrinsisk fotstyrka',
    instructions: '1. Barfota\n2. Lyft stortÃ¥\n3. Andra tÃ¥r i golvet\n4. VÃ¤xla\n5. StÃ¤rker fotvalv',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Marmor-pickups',
    nameSv: 'Marmor-pickups',
    nameEn: 'Marble/Towel Pickups',
    category: 'STRENGTH' as const,
    muscleGroup: 'Intrinsiska fotmuskler',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Fotvalv-styrka',
    instructions: '1. Barfota\n2. Plocka upp marmelkulor med tÃ¥r\n3. Alternativ: dra handduk\n4. StÃ¤rker fotvalv\n5. FÃ¶rebygger plantar fasciit',
    equipment: 'Marmelkulor eller handduk',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Ankel dorsalflexion (band)',
    nameSv: 'Ankel dorsalflexion (band)',
    nameEn: 'Ankle Dorsiflexion (Band)',
    category: 'STRENGTH' as const,
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'FÃ¶rebygger shin splints',
    instructions: '1. Band runt foten\n2. Dra tÃ¥r mot smalben\n3. Dorsalflexion\n4. Kontrollerad sÃ¤nkning\n5. HÃ¶g volym (20 reps)',
    equipment: 'Resistance band',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'HÃ¤lgÃ¥ng',
    nameSv: 'HÃ¤lgÃ¥ng',
    nameEn: 'Heel Walks',
    category: 'STRENGTH' as const,
    muscleGroup: 'Tibialis anterior',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Tibialis-styrka',
    instructions: '1. GÃ¥ pÃ¥ hÃ¤larna\n2. TÃ¥r uppÃ¥t\n3. Dorsalflexion under gÃ¥ng\n4. 20-30 meter\n5. UppvÃ¤rmning eller rehab',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ANTI-ROTATION CORE
  // ========================================
  {
    name: 'Plank',
    nameSv: 'Plank',
    nameEn: 'Plank',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-extension core',
    instructions: '1. StÃ¶d pÃ¥ underarmar och tÃ¥r\n2. Rak linje\n3. SpÃ¤nn mage och glut\n4. Neutral nacke\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Sidplank',
    nameSv: 'Sidplank',
    nameEn: 'Side Plank',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-lateral flexion',
    instructions: '1. Ligg pÃ¥ sidan\n2. StÃ¶d pÃ¥ underarm\n3. Lyft hÃ¶ften\n4. Rak linje\n5. JÃ¤mfÃ¶r sidor',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Dead Bug',
    nameSv: 'Dead Bug',
    nameEn: 'Dead Bug',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-extension med rÃ¶relse',
    instructions: '1. Rygg pÃ¥ golvet\n2. Armar upp, knÃ¤n 90Â°\n3. StrÃ¤ck motsatt arm/ben\n4. LÃ¤ndryggen i golvet\n5. VÃ¤xla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bird Dog',
    nameSv: 'Bird Dog',
    nameEn: 'Bird Dog',
    category: 'CORE' as const,
    muscleGroup: 'Core, Posterior Chain',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Anti-rotation och posterior chain',
    instructions: '1. PÃ¥ alla fyra\n2. StrÃ¤ck motsatt arm/ben\n3. HÃ¥ll rygg neutral\n4. Balansera\n5. VÃ¤xla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Pallof Press',
    nameSv: 'Pallof Press',
    nameEn: 'Pallof Press (Cable)',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Anti-rotation mot kabel',
    instructions: '1. StÃ¥ sidledes mot kabel\n2. Hantag vid brÃ¶stet\n3. Pressa rakt framÃ¥t\n4. MotstÃ¥ rotation\n5. HÃ¥ll hÃ¶fterna framÃ¥t',
    equipment: 'Kabel eller resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Pallof Press (band)',
    nameSv: 'Pallof Press (band)',
    nameEn: 'Pallof Press (Band)',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Hemversion av pallof press',
    instructions: '1. FÃ¤st band vid stolpe\n2. Sidledes stÃ¤llning\n3. Press framÃ¥t\n4. MotstÃ¥ bandets dragning\n5. Kontrollerad Ã¥tergÃ¥ng',
    equipment: 'Resistance band',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Suitcase Carry',
    nameSv: 'Suitcase Carry',
    nameEn: 'Suitcase Carry',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Quadratus Lumborum',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Anti-lateral flexion dynamisk',
    instructions: '1. Tungt i en hand\n2. GÃ¥ framÃ¥t\n3. MotstÃ¥ lateral flexion\n4. BÃ¥l upprÃ¤tt\n5. 20-40 meter',
    equipment: 'Kettlebell eller hantel',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Farmer\'s Walk',
    nameSv: 'Farmer\'s Walk',
    nameEn: 'Farmer\'s Walk',
    category: 'CORE' as const,
    muscleGroup: 'Core, Trapezius, Grip',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Totalstyrka och stabilitet',
    instructions: '1. Tungt i bÃ¥da hÃ¤nderna\n2. GÃ¥ framÃ¥t\n3. UpprÃ¤tt hÃ¥llning\n4. Axlarna tillbaka\n5. 30-50 meter',
    equipment: 'Hantlar eller kettlebells',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Ab Wheel Rollouts',
    nameSv: 'Ab Wheel Rollouts',
    nameEn: 'Ab Wheel Rollouts',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad anti-extension',
    instructions: '1. KnÃ¤ pÃ¥ golvet\n2. Rulla hjulet framÃ¥t\n3. StrÃ¤ck ut kroppen\n4. BehÃ¥ll neutral lÃ¤ndrygen\n5. Dra tillbaka med core',
    equipment: 'Ab wheel',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Copenhagen Plank',
    nameSv: 'Copenhagen Plank',
    nameEn: 'Copenhagen Plank',
    category: 'CORE' as const,
    muscleGroup: 'Adduktorer, Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Adduktor-styrka (41% minskning groin injury)',
    instructions: '1. Sidplank position\n2. Ã–vre ben pÃ¥ bÃ¤nk\n3. Lyft hÃ¶ften\n4. Adduktor-kontraktion\n5. SvÃ¥r Ã¶vning - bÃ¶rja med kort hold',
    equipment: 'BÃ¤nk',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Stir the Pot',
    nameSv: 'Stir the Pot',
    nameEn: 'Stir the Pot',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Instabil plank variation',
    instructions: '1. Underarmar pÃ¥ gymnastikboll\n2. Plank position\n3. Cirkla armarna (som att rÃ¶ra gryta)\n4. SmÃ¥cirklar\n5. VÃ¤xla riktning',
    equipment: 'Gymnastikboll',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Russian Twist',
    nameSv: 'Russian Twist',
    nameEn: 'Russian Twist',
    category: 'CORE' as const,
    muscleGroup: 'Obliques',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Rotation med kontroll',
    instructions: '1. Sitt med fÃ¶tterna upp\n2. Luta bakÃ¥t\n3. Rotera sida till sida\n4. Touch golvet\n5. Kontrollerad rÃ¶relse',
    equipment: 'Viktskiva (valfritt)',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - LOW INTENSITY (Extensive)
  // ========================================
  {
    name: 'Hopprep',
    nameSv: 'Hopprep',
    nameEn: 'Jump Rope',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Ankelstyvhet och rytm',
    instructions: '1. Minimala hopp\n2. Snabb markkontakt\n3. Ankeldominerad\n4. Rytmisk\n5. 100-200 kontakter',
    equipment: 'Hopprep',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Pogo Jumps',
    nameSv: 'Pogo Jumps',
    nameEn: 'Pogo Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Vader, Ankel',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: '>250ms ground contact, styvhet',
    instructions: '1. Styvt ben\n2. Minimal knÃ¤bÃ¶j\n3. Hopp frÃ¥n ankel\n4. Snabb kontakt\n5. Sets om 15-20 reps',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'LÃ¥ga lÃ¥dhopp',
    nameSv: 'LÃ¥ga lÃ¥dhopp',
    nameEn: 'Low Box Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'LÃ¥g lÃ¥da (30-40cm) fÃ¶r nybÃ¶rjare',
    instructions: '1. LÃ¥g lÃ¥da\n2. Hopp upp\n3. Mjuk landning\n4. Kliv ner (inte hoppa)\n5. 8-10 reps',
    equipment: 'LÃ¥g plyobox',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Lateral Hops',
    nameEn: 'Lateral Hops (Side to Side)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Lateral styvhet',
    instructions: '1. Hopp sida till sida\n2. Linje pÃ¥ golvet\n3. Snabb kontakt\n4. Rytmisk\n5. 20-30 kontakter',
    equipment: 'Ingen eller lÃ¥g kon',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Skipping',
    nameSv: 'Skipping',
    nameEn: 'Skipping',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Vader',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Koordination och ankelstyvhet',
    instructions: '1. Exaggererad lÃ¶prÃ¶relse\n2. KnÃ¤drive\n3. Hopp pÃ¥ varje steg\n4. Rytmisk\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - MODERATE INTENSITY
  // ========================================
  {
    name: 'Squat Jumps',
    nameSv: 'Squat Jumps',
    nameEn: 'Squat Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Concentric focus, kontrollerad landning',
    instructions: '1. Squat position\n2. Paus i botten\n3. Explosivt hopp\n4. Mjuk landning\n5. Paus igen (ej reaktiv)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Countermovement Jumps',
    nameSv: 'Countermovement Jumps',
    nameEn: 'Countermovement Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Stretch-shortening cycle trÃ¤ning',
    instructions: '1. StÃ¥ende position\n2. Snabb countermovement (bÃ¶j)\n3. Omedelbart hopp\n4. Maximalt hopp\n5. Mjuk landning',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Lateral Bounds',
    nameSv: 'Lateral Bounds',
    nameEn: 'Lateral Bounds',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Gluteus Medius',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Lateral power och stabilitet',
    instructions: '1. Hoppa lateral frÃ¥n ett ben\n2. Landa pÃ¥ andra benet\n3. Stabilisera\n4. Hopp tillbaka\n5. 10-12 reps per sida',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Tuck Jumps',
    nameEn: 'Tuck Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben, Core',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal hÃ¶jd med knÃ¤drive',
    instructions: '1. Hopp rakt upp\n2. Dra knÃ¤n mot brÃ¶stet\n3. Tuck position\n4. Mjuk landning\n5. 6-8 reps',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Split Jumps',
    nameSv: 'Hoppande utfall',
    nameEn: 'Split Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 2,
    description: 'Ensidig explosivitet',
    instructions: '1. Utfallsposition\n2. Hopp och byt ben\n3. Landa i utfall\n4. Mjuk landning\n5. 10-12 totala hopp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - HIGH INTENSITY (Intensive)
  // ========================================
  {
    name: 'LÃ¥dhopp (18-24")',
    nameSv: 'LÃ¥dhopp (18-24")',
    nameEn: 'Box Jumps (18-24")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'MedelhÃ¶g lÃ¥da fÃ¶r power',
    instructions: '1. LÃ¥da 46-61cm\n2. Explosivt hopp\n3. Landa mjukt\n4. Kliv ner\n5. 8-10 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Enbenhopp (Bounds)',
    nameSv: 'Enbenhopp (Bounds)',
    nameEn: 'Single-Leg Bounds',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'LÃ¶pspecifik horizontal power',
    instructions: '1. Hoppa framÃ¥t pÃ¥ ett ben\n2. Maximalt avstÃ¥nd\n3. Mjuk landning\n4. Upprepa samma ben\n5. 20-30 meter per ben',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Hurdle Hops',
    nameSv: 'Hurdle Hops',
    nameEn: 'Hurdle Hops',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Seriella hopp Ã¶ver hÃ¤ckar',
    instructions: '1. Rad av hÃ¤ckar\n2. Hopp Ã¶ver varje hÃ¤ck\n3. Minimal markkontakt\n4. Rytmisk\n5. 6-10 hÃ¤ckar',
    equipment: 'HÃ¤ckar (30-46cm)',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Bred hopp (max)',
    nameSv: 'Bred hopp (max)',
    nameEn: 'Broad Jump (Maximal)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal horizontal power',
    instructions: '1. Armsving\n2. Explosiv hopp framÃ¥t\n3. Maximalt avstÃ¥nd\n4. Mjuk landning\n5. MÃ¤t avstÃ¥nd (test)',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Triple Jump',
    nameSv: 'Triple Jump',
    nameEn: 'Triple Jump',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 3,
    description: 'Tre hopp i serie',
    instructions: '1. Hopp pÃ¥ hÃ¶ger ben\n2. Hopp pÃ¥ vÃ¤nster ben\n3. Bred hopp med bÃ¥da ben\n4. Maximalt avstÃ¥nd\n5. 3-5 fÃ¶rsÃ¶k',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // PLYOMETRIC - ADVANCED (Depth Jumps)
  // ========================================
  {
    name: 'Depth Jumps (30cm)',
    nameSv: 'Depth Jumps (30cm)',
    nameEn: 'Depth Jumps (12")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: '<150ms ground contact, maximal RFD',
    instructions: '1. Kliv av 30cm lÃ¥da\n2. Mjuk landning\n3. Omedelbart maxhopp\n4. Minimal markkontakt\n5. MAX 27 kontakter per session',
    equipment: 'Plyobox 30cm',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Depth Jumps (40cm)',
    nameSv: 'Depth Jumps (40cm)',
    nameEn: 'Depth Jumps (16")',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Elite-level depth jump',
    instructions: '1. Kliv av 40cm lÃ¥da\n2. Absorb impact\n3. Explosiv rebound\n4. Maximal hÃ¶jd\n5. ENDAST fÃ¶r avancerade - MAX 18 kontakter',
    equipment: 'Plyobox 40cm',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Drop Jumps',
    nameSv: 'Drop Jumps',
    nameEn: 'Drop Jumps',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Maximal reactive strength',
    instructions: '1. Kliv av lÃ¥da\n2. Landa\n3. Omedelbart maxhopp uppÃ¥t\n4. <200ms contact\n5. KrÃ¤ver styrka: 1.5x BW squat',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Repeated Bounds',
    nameSv: 'Repeated Bounds',
    nameEn: 'Repeated Bounds (Continuous)',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'UNILATERAL' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Seriella enbenhopp',
    instructions: '1. Kontinuerliga enbenhopp\n2. Samma ben\n3. Snabb markkontakt\n4. Maximalt avstÃ¥nd per hopp\n5. 30-50 meter',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Depth to Broad Jump',
    nameSv: 'Depth to Broad Jump',
    nameEn: 'Depth to Broad Jump',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Ben',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    plyometricIntensity: 'HIGH' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Vertical to horizontal power',
    instructions: '1. Kliv av lÃ¥da\n2. Landa\n3. Omedelbart bred hopp framÃ¥t\n4. Maximalt horisontellt avstÃ¥nd\n5. 5-8 reps',
    equipment: 'Plyobox',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // UPPER BODY (Optional for runners)
  // ========================================
  {
    name: 'BÃ¤nkpress',
    nameSv: 'BÃ¤nkpress',
    nameEn: 'Bench Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'BrÃ¶st, Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ã–verkroppsstyrka (valfritt fÃ¶r lÃ¶pare)',
    instructions: '1. Ligg pÃ¥ bÃ¤nk\n2. Grip nÃ¥got bredare Ã¤n axlar\n3. SÃ¤nk till brÃ¶stet\n4. Pressa upp\n5. LÃ¥s ut',
    equipment: 'SkivstÃ¥ng, bÃ¤nk',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Rodd',
    nameSv: 'Rodd',
    nameEn: 'Barbell Row',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ryggstyrkavs',
    instructions: '1. BÃ¶j framÃ¥t i hÃ¶ften\n2. Grip stÃ¥ngen\n3. Dra mot mage\n4. ArmbÃ¥gar nÃ¤ra kroppen\n5. Squee ze shoulder blades',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Chins',
    nameSv: 'Chins',
    nameEn: 'Pull-ups/Chin-ups',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Ryggstyrkavs med kroppsvikt',
    instructions: '1. HÃ¤ng i stÃ¥ng\n2. Dra dig upp\n3. Hakan Ã¶ver stÃ¥ngen\n4. Kontrollerad nedgÃ¥ng\n5. Full ROM',
    equipment: 'Chin-up bar',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Axelpress',
    nameSv: 'Axelpress',
    nameEn: 'Overhead Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Axelstyrka',
    instructions: '1. StÃ¥ng vid axelhÃ¶jd\n2. Pressa rakt uppÃ¥t\n3. LÃ¥s ut armarna\n4. SÃ¤nk kontrollerat\n5. Neutral rygg',
    equipment: 'SkivstÃ¥ng',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL CORE EXERCISES
  // ========================================
  {
    name: 'Mountain Climbers',
    nameSv: 'BergsklÃ¤ttrare',
    nameEn: 'Mountain Climbers',
    category: 'CORE' as const,
    muscleGroup: 'Core, HÃ¶ftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk core-Ã¶vning som hÃ¶jer pulsen',
    instructions: '1. BÃ¶rja i armhÃ¤vningsposition\n2. Dra ett knÃ¤ mot brÃ¶stet\n3. Byt snabbt ben\n4. HÃ¥ll hÃ¶fterna lÃ¥ga\n5. FortsÃ¤tt i angivet tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bicycle Crunches',
    nameSv: 'Cykelcrunches',
    nameEn: 'Bicycle Crunches',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Roterande core-Ã¶vning fÃ¶r obliques',
    instructions: '1. Ligg pÃ¥ rygg med hÃ¤nderna bakom huvudet\n2. Lyft axlarna frÃ¥n golvet\n3. FÃ¶r motsatt armbÃ¥ge mot knÃ¤\n4. VÃ¤xla sida i cykelrÃ¶relse\n5. HÃ¥ll nedre ryggen i golvet',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Leg Raises',
    nameSv: 'Benlyft',
    nameEn: 'Leg Raises',
    category: 'CORE' as const,
    muscleGroup: 'Nedre Magmuskler, HÃ¶ftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Fokuserar pÃ¥ nedre magmusklerna',
    instructions: '1. Ligg pÃ¥ rygg med benen raka\n2. HÃ¤nder under sÃ¤tet fÃ¶r stÃ¶d\n3. Lyft benen rakt upp till 90 grader\n4. SÃ¤nk lÃ¥ngsamt tillbaka\n5. LÃ¥t inte ryggen lyfta frÃ¥n golvet',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'V-ups',
    nameSv: 'V-ups',
    nameEn: 'V-ups',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis, HÃ¶ftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad core-Ã¶vning i V-form',
    instructions: '1. Ligg pÃ¥ rygg med armar och ben strÃ¤ckta\n2. Lyft Ã¶verkropp och ben samtidigt\n3. FÃ¶rsÃ¶k rÃ¶ra tÃ¥rna med hÃ¤nderna\n4. Bilda en V-form\n5. SÃ¤nk kontrollerat tillbaka',
    equipment: 'Ingen',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Hollow Hold',
    nameSv: 'Hollow Hold',
    nameEn: 'Hollow Body Hold',
    category: 'CORE' as const,
    muscleGroup: 'Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isometrisk core-Ã¶vning fÃ¶r helkroppsspÃ¤nning',
    instructions: '1. Ligg pÃ¥ rygg\n2. Pressa lÃ¤ndryggen i golvet\n3. Lyft armar, axlar och ben\n4. Bananform - hÃ¥ll kvar\n5. Andas normalt',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Sit-ups',
    nameSv: 'Sit-ups',
    nameEn: 'Sit-ups',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Klassisk magÃ¶vning',
    instructions: '1. Ligg pÃ¥ rygg med knÃ¤n bÃ¶jda\n2. FÃ¶tterna i golvet\n3. HÃ¤nder vid Ã¶ronen eller Ã¶ver brÃ¶stet\n4. Lyft Ã¶verkroppen mot knÃ¤na\n5. SÃ¤nk kontrollerat tillbaka',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Crunches',
    nameSv: 'Crunches',
    nameEn: 'Crunches',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad magmuskel-aktivering',
    instructions: '1. Ligg pÃ¥ rygg med knÃ¤n bÃ¶jda\n2. HÃ¤nder vid Ã¶ronen\n3. Lyft endast axlarna frÃ¥n golvet\n4. SpÃ¤nn magmusklerna i toppen\n5. SÃ¤nk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL UPPER BODY
  // ========================================
  {
    name: 'ArmhÃ¤vningar',
    nameSv: 'ArmhÃ¤vningar',
    nameEn: 'Push-ups',
    category: 'STRENGTH' as const,
    muscleGroup: 'BrÃ¶st, Triceps, Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'GrundlÃ¤ggande Ã¶verkroppsÃ¶vning med kroppsvikt',
    instructions: '1. HÃ¤nder axelbrett pÃ¥ golvet\n2. Kroppen i rak linje\n3. SÃ¤nk brÃ¶stet mot golvet\n4. Pressa upp till raka armar\n5. HÃ¥ll core spÃ¤nd hela tiden',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Dips',
    nameSv: 'Dips',
    nameEn: 'Dips',
    category: 'STRENGTH' as const,
    muscleGroup: 'Triceps, BrÃ¶st',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Triceps och brÃ¶sttrÃ¤ning',
    instructions: '1. Grip tag om bÃ¤nk/barr bakom dig\n2. SÃ¤nk kroppen genom att bÃ¶ja armarna\n3. ArmbÃ¥garna 90 grader\n4. Pressa upp till raka armar\n5. Undvik att sjunka fÃ¶r djupt',
    equipment: 'BÃ¤nk eller dipbarr',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Inverterad rodd',
    nameSv: 'Inverterad rodd',
    nameEn: 'Inverted Row',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'RyggÃ¶vning med kroppsvikt',
    instructions: '1. HÃ¤ng under en stÃ¥ng\n2. Kroppen rak\n3. Dra brÃ¶stet mot stÃ¥ngen\n4. KlÃ¤m ihop skulderbladen\n5. SÃ¤nk kontrollerat',
    equipment: 'StÃ¥ng pÃ¥ lÃ¥g hÃ¶jd',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Face Pulls',
    nameSv: 'Face Pulls',
    nameEn: 'Face Pulls',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bakre Axlar, Rotator Cuff',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Bakre axlar och hÃ¥llning',
    instructions: '1. Kabel eller band i ansiktshÃ¶jd\n2. Dra mot ansiktet\n3. HÃ¤nder gÃ¥r ut och bakÃ¥t\n4. KlÃ¤m ihop skulderbladen\n5. Kontrollerad Ã¥tergÃ¥ng',
    equipment: 'Kabel eller band',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Latsdrag',
    nameSv: 'Latsdrag',
    nameEn: 'Lat Pulldown',
    category: 'STRENGTH' as const,
    muscleGroup: 'Latissimus Dorsi, Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ryggens stora muskel',
    instructions: '1. Grip stÃ¥ngen bredare Ã¤n axlar\n2. Luta lÃ¤tt bakÃ¥t\n3. Dra stÃ¥ngen mot Ã¶vre brÃ¶stet\n4. KlÃ¤m ihop skulderbladen\n5. StrÃ¤ck ut armarna kontrollerat',
    equipment: 'Latsdragsmaskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // MOBILITY & WARMUP
  // ========================================
  {
    name: 'HÃ¶ftcirklar',
    nameSv: 'HÃ¶ftcirklar',
    nameEn: 'Hip Circles',
    category: 'STRENGTH' as const,
    muscleGroup: 'HÃ¶fter',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk hÃ¶ftmobilisering',
    instructions: '1. StÃ¥ pÃ¥ ett ben\n2. Lyft andra knÃ¤t\n3. Rita cirklar med knÃ¤t\n4. Stora, kontrollerade rÃ¶relser\n5. GÃ¶r bÃ¥da riktningarna',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bensving',
    nameSv: 'Bensving',
    nameEn: 'Leg Swings',
    category: 'STRENGTH' as const,
    muscleGroup: 'HÃ¶fter, Hases',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk stretch fÃ¶r bakre lÃ¥rmuskel',
    instructions: '1. HÃ¥ll i ett stÃ¶d\n2. Svinga benet framÃ¥t och bakÃ¥t\n3. HÃ¥ll benet rakt\n4. Kontrollerad sving\n5. Ã–ka rÃ¶relseomfÃ¥nget gradvis',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'VÃ¤rldens bÃ¤sta stretch',
    nameSv: 'VÃ¤rldens bÃ¤sta stretch',
    nameEn: 'Worlds Greatest Stretch',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp mobilitet',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Komplett dynamisk stretch fÃ¶r hela kroppen',
    instructions: '1. Utfallsposition\n2. Rotera Ã¶vre kroppen mot frÃ¤mre benet\n3. StrÃ¤ck armen mot taket\n4. SÃ¤nk armbÃ¥gen mot foten\n5. VÃ¤xla sida',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Katt-Ko',
    nameSv: 'Katt-Ko',
    nameEn: 'Cat-Cow',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg mobilitet',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'RyggradsrÃ¶rlighet',
    instructions: '1. PÃ¥ alla fyra\n2. Runda ryggen uppÃ¥t (katt)\n3. BÃ¶j ryggen nedÃ¥t (ko)\n4. Flytande rÃ¶relser\n5. Andas djupt',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Foam Rolling',
    nameSv: 'Foam Rolling',
    nameEn: 'Foam Rolling',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'MjukvÃ¤vnadsmobilisering',
    instructions: '1. Placera foam roller under mÃ¥lomrÃ¥det\n2. Rulla lÃ¥ngsamt Ã¶ver muskeln\n3. Stanna pÃ¥ Ã¶mma punkter\n4. 30-60 sekunder per omrÃ¥de\n5. Andas avslappnat',
    equipment: 'Foam roller',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'AnkelrÃ¶rlighet',
    nameSv: 'AnkelrÃ¶rlighet',
    nameEn: 'Ankle Mobility',
    category: 'STRENGTH' as const,
    muscleGroup: 'Anklar',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ã–kar dorsalflexion i ankeln',
    instructions: '1. StÃ¥ med en fot framfÃ¶r\n2. Pressa knÃ¤t framÃ¥t Ã¶ver tÃ¥rna\n3. HÃ¥ll hÃ¤len i golvet\n4. KÃ¤nn stretch i vaden\n5. Upprepa pÃ¥ bÃ¥da sidor',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },

  // ========================================
  // ADDITIONAL STRENGTH
  // ========================================
  {
    name: 'Sumo Squats',
    nameSv: 'SumoknÃ¤bÃ¶j',
    nameEn: 'Sumo Squats',
    category: 'STRENGTH' as const,
    muscleGroup: 'Adduktorer, Gluteus, Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Bred stÃ¤llning fÃ¶r adduktorer och gluteus',
    instructions: '1. Bred stÃ¤llning med tÃ¥r utÃ¥t\n2. SÃ¤nk hÃ¶fterna rakt nedÃ¥t\n3. KnÃ¤n i linje med tÃ¥rna\n4. UpprÃ¤tt bÃ¥l\n5. Tryck upp genom hÃ¤larna',
    equipment: 'Ingen eller kettlebell',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Glute Kickbacks',
    nameSv: 'Sparkbaksparkar',
    nameEn: 'Glute Kickbacks',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad gluteus-aktivering',
    instructions: '1. PÃ¥ alla fyra\n2. Sparka ett ben bakÃ¥t och uppÃ¥t\n3. SpÃ¤nn skinkan i toppen\n4. Kontrollerad Ã¥tergÃ¥ng\n5. HÃ¥ll hÃ¶fterna stabila',
    equipment: 'Ingen eller band',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Wall Angels',
    nameSv: 'VÃ¤ggÃ¤nglar',
    nameEn: 'Wall Angels',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar, Ã–vre rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'AxelrÃ¶rlighet och hÃ¥llning',
    instructions: '1. StÃ¥ med ryggen mot vÃ¤ggen\n2. Armar i 90 grader mot vÃ¤ggen\n3. Glid armarna upp och ner\n4. HÃ¥ll kontakt med vÃ¤ggen\n5. Kontrollerad rÃ¶relse',
    equipment: 'VÃ¤gg',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Prone Y-raise',
    nameSv: 'Y-lyft liggande',
    nameEn: 'Prone Y-Raise',
    category: 'STRENGTH' as const,
    muscleGroup: 'Nedre Trapezius, Bakre Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Skulderbladsaktivering och stabilitet',
    instructions: '1. Ligg pÃ¥ mage\n2. Lyft armarna i Y-form\n3. Tummar pekar uppÃ¥t\n4. KlÃ¤m ihop skulderbladen\n5. HÃ¥ll i toppen',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Superman',
    nameSv: 'Superman',
    nameEn: 'Superman',
    category: 'STRENGTH' as const,
    muscleGroup: 'LÃ¤ndryggen, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Ryggextension och bakre kedjan',
    instructions: '1. Ligg pÃ¥ mage med armar strÃ¤ckta\n2. Lyft armar och ben samtidigt\n3. HÃ¥ll i toppen\n4. SpÃ¤nn gluteus\n5. SÃ¤nk kontrollerat',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Inchworm',
    nameSv: 'Inchworm',
    nameEn: 'Inchworm',
    category: 'STRENGTH' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Dynamisk helkroppsrÃ¶rlighet',
    instructions: '1. StÃ¥ med raka ben\n2. BÃ¶j framÃ¥t och sÃ¤tt hÃ¤nderna i golvet\n3. GÃ¥ ut med hÃ¤nderna till planka\n4. GÃ¥ tillbaka med hÃ¤nderna\n5. Res dig upp',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'High Knees',
    nameSv: 'HÃ¶ga knÃ¤n',
    nameEn: 'High Knees',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'HÃ¶ftflexorer, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Dynamisk uppvÃ¤rmning och knÃ¤lyft',
    instructions: '1. Jogga pÃ¥ stÃ¤llet\n2. Lyft knÃ¤na hÃ¶gt (Ã¶ver hÃ¶ften)\n3. Snabb armrÃ¶relse\n4. Landa mjukt pÃ¥ framfoten\n5. HÃ¥ll hÃ¶gt tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Butt Kicks',
    nameSv: 'HÃ¤larmar',
    nameEn: 'Butt Kicks',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Hases, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'LÃ¶pspecifik uppvÃ¤rmning',
    instructions: '1. Jogga pÃ¥ stÃ¤llet\n2. Sparka hÃ¤larna mot rumpan\n3. Snabb vÃ¤xling\n4. LÃ¤tt framÃ¥tlutning\n5. HÃ¥ll hÃ¶gt tempo',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Jumping Jacks',
    nameSv: 'Hampelmannhopp',
    nameEn: 'Jumping Jacks',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Helkropp, Kondition',
    biomechanicalPillar: 'FOOT_ANKLE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    plyometricIntensity: 'LOW' as PlyometricIntensity,
    contactsPerRep: 1,
    description: 'Klassisk uppvÃ¤rmningsÃ¶vning',
    instructions: '1. BÃ¶rja med fÃ¶tterna ihop\n2. Hoppa ut med fÃ¶tterna\n3. Samtidigt lyft armarna Ã¶ver huvudet\n4. Hoppa tillbaka till start\n5. Rytmisk rÃ¶relse',
    equipment: 'Ingen',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Burpees',
    nameSv: 'Burpees',
    nameEn: 'Burpees',
    category: 'PLYOMETRIC' as const,
    muscleGroup: 'Helkropp',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    plyometricIntensity: 'MODERATE' as PlyometricIntensity,
    contactsPerRep: 2,
    description: 'Helkropps konditions- och styrkeÃ¶vning',
    instructions: '1. StÃ¥ upprÃ¤tt\n2. GÃ¥ ner i squat och sÃ¤tt hÃ¤nderna i golvet\n3. Hoppa fÃ¶tterna bakÃ¥t till planka\n4. GÃ¶r en armhÃ¤vning (valfritt)\n5. Hoppa fÃ¶tterna framÃ¥t och hopp upp',
    equipment: 'Ingen',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // UPPER_BODY - Additional Exercises
  // ========================================
  {
    name: 'Lutande bänkpress',
    nameSv: 'Lutande bänkpress',
    nameEn: 'Incline Bench Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bröst, Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Övre bröstmuskelstyrka med lutande bänk',
    instructions: '1. Ställ bänken i 30-45 grader\n2. Grip strax utanför axelbredd\n3. Sänk stången till övre bröst\n4. Pressa upp explosivt\n5. Lås ut i toppen',
    equipment: 'Skivstång, bänk',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Lutande hantelpress',
    nameSv: 'Lutande hantelpress',
    nameEn: 'Incline Dumbbell Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bröst, Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Övre bröst med fritt ROM och hantlar',
    instructions: '1. Bänk i 30-45 grader\n2. Hantlar vid axlarna\n3. Pressa uppåt\n4. Kontrollerad sänkning\n5. Större ROM än skivstång',
    equipment: 'Hantlar, bänk',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Trångfattad bänkpress',
    nameSv: 'Trångfattad bänkpress',
    nameEn: 'Close-Grip Bench Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Triceps, Bröst',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Triceps-dominant pressövning',
    instructions: '1. Ligg på bänk\n2. Smal grip (axelbredd)\n3. Sänk till bröstet\n4. Armbågar nära kroppen\n5. Pressa upp',
    equipment: 'Skivstång, bänk',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Skull Crushers',
    nameSv: 'Skull Crushers',
    nameEn: 'Skull Crushers',
    category: 'STRENGTH' as const,
    muscleGroup: 'Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Isolerad triceps med EZ-stång',
    instructions: '1. Ligg på bänk med EZ-stång\n2. Armar rakt upp\n3. Böj i armbågen\n4. Sänk mot pannan\n5. Sträck armarna tillbaka',
    equipment: 'EZ-stång, bänk',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Tricepspress över huvudet',
    nameSv: 'Tricepspress över huvudet',
    nameEn: 'Overhead Tricep Extension',
    category: 'STRENGTH' as const,
    muscleGroup: 'Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Triceps med stretch i lång position',
    instructions: '1. Håll hantel bakom huvudet\n2. Armbågar pekar uppåt\n3. Sträck armarna\n4. Kontrollerad sänkning\n5. Full stretch i botten',
    equipment: 'Hantel',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bicepscurl med skivstång',
    nameSv: 'Bicepscurl med skivstång',
    nameEn: 'Barbell Bicep Curl',
    category: 'STRENGTH' as const,
    muscleGroup: 'Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Klassisk bicepsövning med skivstång',
    instructions: '1. Stå upprätt med skivstång\n2. Armar hängande\n3. Curl uppåt\n4. Kläm i toppen\n5. Sänk kontrollerat',
    equipment: 'Skivstång',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bicepscurl med hantlar',
    nameSv: 'Bicepscurl med hantlar',
    nameEn: 'Dumbbell Bicep Curl',
    category: 'STRENGTH' as const,
    muscleGroup: 'Biceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Grundläggande bicepsövning',
    instructions: '1. Hantlar i varje hand\n2. Curl en åt gången eller båda\n3. Supinera i toppen\n4. Kläm biceps\n5. Sänk kontrollerat',
    equipment: 'Hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Hammarcurl',
    nameSv: 'Hammarcurl',
    nameEn: 'Hammer Curl',
    category: 'STRENGTH' as const,
    muscleGroup: 'Biceps, Underarmar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Biceps och brachioradialis',
    instructions: '1. Hantlar med neutralt grepp\n2. Tummar pekar uppåt\n3. Curl uppåt\n4. Håll neutralt grepp\n5. Sänk kontrollerat',
    equipment: 'Hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Sidolyft',
    nameSv: 'Sidolyft',
    nameEn: 'Lateral Raises',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar (Medial Deltoid)',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad medial deltoid',
    instructions: '1. Hantlar vid sidorna\n2. Lyft armarna ut åt sidan\n3. Till axelhöjd\n4. Kontrollerad sänkning\n5. Lätt böjda armbågar',
    equipment: 'Hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Frontlyft',
    nameSv: 'Frontlyft',
    nameEn: 'Front Raises',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar (Anterior Deltoid)',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad främre deltoid',
    instructions: '1. Hantlar framför kroppen\n2. Lyft rakt framåt\n3. Till axelhöjd\n4. Kontrollerad sänkning\n5. Alternera armar eller båda',
    equipment: 'Hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Bakre axellyft',
    nameSv: 'Bakre axellyft',
    nameEn: 'Rear Delt Flys',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bakre Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Bakre deltoid och hållning',
    instructions: '1. Böj framåt i höften\n2. Hantlar hängande\n3. Lyft ut åt sidan\n4. Kläm ihop skulderbladen\n5. Kontrollerad sänkning',
    equipment: 'Hantlar',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Kabelflyes',
    nameSv: 'Kabelflyes',
    nameEn: 'Cable Flyes',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bröst',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Bröstträning med konstant spänning',
    instructions: '1. Ställ kablar i brösthöjd\n2. Steg framåt\n3. För armarna ihop framför bröstet\n4. Kläm bröstmusklerna\n5. Kontrollerad tillbaka',
    equipment: 'Kabelmaskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Upprätt rodd',
    nameSv: 'Upprätt rodd',
    nameEn: 'Upright Rows',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar, Trapezius',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Axlar och trapezius',
    instructions: '1. Grip skivstång i smal grip\n2. Dra uppåt mot hakan\n3. Armbågar leder rörelsen\n4. Sänk kontrollerat\n5. Undvik för hög lyft om axelproblem',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Axelryckningar',
    nameSv: 'Axelryckningar',
    nameEn: 'Shrugs',
    category: 'STRENGTH' as const,
    muscleGroup: 'Trapezius',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Trapezius-styrka',
    instructions: '1. Hantlar eller skivstång i händerna\n2. Lyft axlarna rakt upp\n3. Kläm i toppen\n4. Sänk kontrollerat\n5. Raka armar hela tiden',
    equipment: 'Hantlar eller skivstång',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Arnold Press',
    nameSv: 'Arnold Press',
    nameEn: 'Arnold Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Komplett axelövning med rotation',
    instructions: '1. Hantlar vid axlarna, handflatorna mot dig\n2. Pressa uppåt\n3. Rotera under pressning\n4. Handflatorna framåt i toppen\n5. Reversera',
    equipment: 'Hantlar',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Push Press',
    nameSv: 'Push Press',
    nameEn: 'Push Press',
    category: 'STRENGTH' as const,
    muscleGroup: 'Axlar, Triceps',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Explosiv axelpress med bendrive',
    instructions: '1. Skivstång vid axlarna\n2. Lätt böj i knäna\n3. Explosiv bensträckning\n4. Pressa stången över huvudet\n5. Lås ut i toppen',
    equipment: 'Skivstång',
    difficulty: 'Advanced',
    isPublic: true,
  },
  {
    name: 'Band Pull-Aparts',
    nameSv: 'Band Pull-Aparts',
    nameEn: 'Band Pull-Aparts',
    category: 'STRENGTH' as const,
    muscleGroup: 'Bakre Axlar, Övre rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Bakre axlar och hållningskorrigering',
    instructions: '1. Håll band framför dig\n2. Armar raka\n3. Dra isär bandet\n4. Kläm skulderbladen\n5. Kontrollerad tillbaka',
    equipment: 'Motståndsband',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Kabelrodd',
    nameSv: 'Kabelrodd',
    nameEn: 'Cable Rows',
    category: 'STRENGTH' as const,
    muscleGroup: 'Rygg',
    biomechanicalPillar: 'UPPER_BODY' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Ryggstyrka med konstant kabelmotstånd',
    instructions: '1. Sitt med fötterna på plattan\n2. Dra handtaget mot magen\n3. Kläm ihop skulderbladen\n4. Kontrollerad tillbaka\n5. Håll upprätt bål',
    equipment: 'Kabelmaskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // KNEE DOMINANCE - Machine Exercises
  // ========================================
  {
    name: 'Hack Squat',
    nameSv: 'Hack Squat',
    nameEn: 'Hack Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Maskinsquat med ryggstöd',
    instructions: '1. Rygg mot plattan\n2. Fötter axelbrett\n3. Sänk kontrollerat\n4. Tryck upp genom hälarna\n5. Lås inte knäna helt',
    equipment: 'Hack squat-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Benextension',
    nameSv: 'Benextension',
    nameEn: 'Leg Extension',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad quadriceps-träning',
    instructions: '1. Sitt i maskinen\n2. Kudden mot smalbenen\n3. Sträck benen\n4. Kläm quads i toppen\n5. Sänk kontrollerat',
    equipment: 'Benextensionsmaskin',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Belt Squat',
    nameSv: 'Belt Squat',
    nameEn: 'Belt Squat',
    category: 'STRENGTH' as const,
    muscleGroup: 'Quadriceps, Gluteus',
    biomechanicalPillar: 'KNEE_DOMINANCE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Squat utan ryggbelastning via bälte',
    instructions: '1. Bälte runt höften\n2. Stå på plattformarna\n3. Squat som vanligt\n4. Ingen belastning på ryggen\n5. Bra för rehab',
    equipment: 'Belt squat-maskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },

  // ========================================
  // POSTERIOR CHAIN - Additional Exercises
  // ========================================
  {
    name: 'Bencurl',
    nameSv: 'Bencurl',
    nameEn: 'Leg Curl',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hamstrings',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_1' as ProgressionLevel,
    description: 'Isolerad hamstring-träning',
    instructions: '1. Ligg eller sitt i maskin\n2. Kudden mot hälsenorna\n3. Böj benen\n4. Kläm hamstrings\n5. Sänk kontrollerat',
    equipment: 'Bencurlmaskin',
    difficulty: 'Beginner',
    isPublic: true,
  },
  {
    name: 'Sumomarklyft',
    nameSv: 'Sumomarklyft',
    nameEn: 'Sumo Deadlift',
    category: 'STRENGTH' as const,
    muscleGroup: 'Gluteus, Adduktorer, Hamstrings',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Marklyft med bred ställning',
    instructions: '1. Bred ställning, tår utåt\n2. Grip stången innanför benen\n3. Neutral rygg\n4. Tryck golvet ifrån dig\n5. Lås ut i toppen',
    equipment: 'Skivstång',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Glute-Ham Raise',
    nameSv: 'Glute-Ham Raise',
    nameEn: 'Glute-Ham Raise',
    category: 'STRENGTH' as const,
    muscleGroup: 'Hamstrings, Gluteus',
    biomechanicalPillar: 'POSTERIOR_CHAIN' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_3' as ProgressionLevel,
    description: 'Avancerad hamstring/gluteus med GHD',
    instructions: '1. Placera dig i GHD-maskinen\n2. Sänk överkroppen framåt\n3. Dra tillbaka med hamstrings\n4. Sträck höften i toppen\n5. Kontrollerad excentrisk',
    equipment: 'GHD',
    difficulty: 'Advanced',
    isPublic: true,
  },

  // ========================================
  // ANTI_ROTATION_CORE - Additional Exercises
  // ========================================
  {
    name: 'Hängande benlyft',
    nameSv: 'Hängande benlyft',
    nameEn: 'Hanging Leg Raises',
    category: 'CORE' as const,
    muscleGroup: 'Core, Höftflexorer',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Avancerad core med hängande position',
    instructions: '1. Häng i chinsstång\n2. Lyft raka ben\n3. Till 90 grader eller högre\n4. Kontrollerad sänkning\n5. Undvik sväng',
    equipment: 'Chinsstång',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Kabel Woodchops',
    nameSv: 'Kabel Woodchops',
    nameEn: 'Cable Woodchops',
    category: 'CORE' as const,
    muscleGroup: 'Obliques, Core',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Rotationsstyrka med kabel',
    instructions: '1. Ställ kabeln högt eller lågt\n2. Stå sidledes\n3. Dra diagonalt över kroppen\n4. Rotera genom bålen\n5. Kontrollerad tillbaka',
    equipment: 'Kabelmaskin',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Overhead Carry',
    nameSv: 'Overhead Carry',
    nameEn: 'Overhead Carry',
    category: 'CORE' as const,
    muscleGroup: 'Core, Axlar, Stabilitet',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Helkroppsstabilitet med vikt över huvudet',
    instructions: '1. Lyft vikt/vikter över huvudet\n2. Lås ut armarna\n3. Gå framåt\n4. Håll core aktiverat\n5. 20-40 meter',
    equipment: 'Hantlar eller kettlebell',
    difficulty: 'Intermediate',
    isPublic: true,
  },
  {
    name: 'Kabel Crunches',
    nameSv: 'Kabel Crunches',
    nameEn: 'Cable Crunches',
    category: 'CORE' as const,
    muscleGroup: 'Rectus Abdominis',
    biomechanicalPillar: 'ANTI_ROTATION_CORE' as BiomechanicalPillar,
    progressionLevel: 'LEVEL_2' as ProgressionLevel,
    description: 'Core med justerbart kabelmotstånd',
    instructions: '1. Knäböjande under kabeln\n2. Rep bakom huvudet\n3. Crunch nedåt\n4. Kläm magen\n5. Kontrollerad tillbaka',
    equipment: 'Kabelmaskin',
    difficulty: 'Beginner',
    isPublic: true,
  },
]

async function main() {
  console.log('ðŸ‹ï¸ Seeding comprehensive exercise library based on scientific framework...\n')

  let created = 0
  let skipped = 0

  for (const exercise of exercises) {
    // Check if exercise already exists (by name and coachId=null for system exercises)
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name, coachId: null },
    })

    if (existing) {
      console.log(`â­ï¸  Skipped (exists): ${exercise.name}`)
      skipped++
      continue
    }

    const createdExercise = await prisma.exercise.create({
      data: {
        ...exercise,
        nameSv: exercise.nameSv || exercise.name,
      },
    })
    console.log(`âœ… Created: ${createdExercise.name} (${createdExercise.biomechanicalPillar || createdExercise.category})`)
    created++
  }

  console.log('\n' + '='.repeat(60))
  console.log('ðŸ“Š Exercise Library Seeding Summary')
  console.log('='.repeat(60))
  console.log(`âœ… Created: ${created} exercises`)
  console.log(`â­ï¸  Skipped: ${skipped} exercises (already existed)`)
  console.log(`ðŸ“š Total in library: ${created + skipped} exercises`)
  console.log('='.repeat(60))

  // Summary by category
  const summary = exercises.reduce((acc: any, ex) => {
    const pillar = ex.biomechanicalPillar || 'OTHER'
    acc[pillar] = (acc[pillar] || 0) + 1
    return acc
  }, {})

  console.log('\nðŸ“‹ Breakdown by Biomechanical Pillar:')
  Object.entries(summary).forEach(([pillar, count]) => {
    console.log(`   ${pillar}: ${count} exercises`)
  })

  console.log('\nâœ¨ Exercise library ready for Norwegian Singles integration!')
}

main()
  .catch((e) => {
    console.error('âŒ Error seeding exercises:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
