// prisma/seed-agility-drills.ts
// Seed file for Agility Studio drill library
// Run with: npx ts-node prisma/seed-agility-drills.ts

import { PrismaClient, AgilityDrillCategory, DevelopmentStage, SportType } from '@prisma/client'

const prisma = new PrismaClient()

interface AgilityDrillSeed {
  name: string
  nameSv: string
  description: string
  descriptionSv: string
  category: AgilityDrillCategory
  requiredEquipment: string[]
  optionalEquipment: string[]
  distanceMeters?: number
  durationSeconds?: number
  defaultReps?: number
  defaultSets?: number
  restSeconds?: number
  minDevelopmentStage: DevelopmentStage
  maxDevelopmentStage: DevelopmentStage
  primarySports: SportType[]
  difficultyLevel: number
  setupInstructions: string
  executionCues: string[]
}

const agilityDrills: AgilityDrillSeed[] = [
  // ==================== CHANGE OF DIRECTION (COD) ====================
  {
    name: '5-10-5 Pro Agility',
    nameSv: '5-10-5 Pro Agility',
    description: 'Start in 3-point stance, sprint 5 yards to one side, touch line, sprint 10 yards to opposite side, touch line, sprint 5 yards back through start.',
    descriptionSv: 'Starta i 3-punktsställning, sprinta 5 yards åt ena hållet, rör linjen, sprinta 10 yards åt motsatt håll, rör linjen, sprinta 5 yards tillbaka genom start.',
    category: 'COD',
    requiredEquipment: ['cones', 'timing_gates'],
    optionalEquipment: [],
    distanceMeters: 18.3,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up 3 cones 5 yards apart in a straight line. Start position is at middle cone in 3-point stance.',
    executionCues: ['Stay low through turns', 'Push off outside foot', 'Eyes up', 'Accelerate out of turns']
  },
  {
    name: 'T-Test',
    nameSv: 'T-Test',
    description: 'Sprint forward 10m to center cone, shuffle left 5m, shuffle right 10m, shuffle left 5m back to center, backpedal to start.',
    descriptionSv: 'Sprinta framåt 10m till mittkonen, sidosteg vänster 5m, sidosteg höger 10m, sidosteg vänster 5m tillbaka till mitten, backa till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 40,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up cones in T-shape: start cone, center cone 10m away, left and right cones 5m from center.',
    executionCues: ['Face forward entire drill', 'Stay in athletic stance', 'Touch cones with hand', 'Quick feet on direction changes']
  },
  {
    name: 'Illinois Agility Test',
    nameSv: 'Illinois-testet',
    description: 'Lie face down at start, sprint 10m, weave through 4 cones, sprint 10m, turn and repeat pattern back to start.',
    descriptionSv: 'Ligg på magen vid start, sprinta 10m, väva genom 4 koner, sprinta 10m, vänd och upprepa mönstret tillbaka till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 60,
    defaultReps: 2,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Set up 10m x 5m rectangle with 4 cones in center spaced 3.3m apart for weaving.',
    executionCues: ['Explosive start from prone', 'Stay low through cones', 'Tight turns around cones', 'Accelerate on straights']
  },
  {
    name: 'L-Drill (3 Cone Drill)',
    nameSv: 'L-Drill (3-konövning)',
    description: 'Sprint 5 yards, touch line, return to start, sprint 5 yards again, turn left around cone, weave figure-8 around second cone, return.',
    descriptionSv: 'Sprinta 5 yards, rör linjen, återvänd till start, sprinta 5 yards igen, sväng vänster runt konen, väv figur-8 runt andra konen, återvänd.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 27,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Set up 3 cones in L-shape, each 5 yards apart.',
    executionCues: ['Plant and drive', 'Low center of gravity', 'Quick hip rotation', 'Eyes forward']
  },
  {
    name: 'Arrowhead Agility Test',
    nameSv: 'Pilspets-agilitytest',
    description: 'Sprint forward to center cone, angle left to outer cone, return through center, angle right to outer cone, return through start.',
    descriptionSv: 'Sprinta framåt till mittkonen, vinkla vänster till yttre konen, återvänd genom mitten, vinkla höger till yttre konen, återvänd genom start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 24,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_FLOORBALL', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set cones in arrowhead pattern: start, center 10m away, left and right cones at 45-degree angles from center.',
    executionCues: ['Approach cone at angle', 'Plant outside foot', 'Drive off planted foot', 'Maintain speed through turns']
  },
  {
    name: '180-Degree Turns',
    nameSv: '180-graders vändningar',
    description: 'Sprint 10m, perform 180-degree turn around cone, sprint back. Alternate left and right turn directions.',
    descriptionSv: 'Sprinta 10m, utför 180-graders vändning runt konen, sprinta tillbaka. Alternera vänster och höger vändningsriktning.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Place single cone 10m from start line.',
    executionCues: ['Decelerate efficiently', 'Drop hips to turn', 'Push off outside foot', 'Accelerate immediately']
  },
  {
    name: 'Box Drill',
    nameSv: 'Rutövning',
    description: 'Navigate a 5m x 5m box pattern: sprint forward, shuffle right, backpedal, shuffle left back to start.',
    descriptionSv: 'Navigera ett 5m x 5m rutmönster: sprinta framåt, sidosteg höger, backa, sidosteg vänster tillbaka till start.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up 4 cones in 5m x 5m square.',
    executionCues: ['Stay in athletic stance', 'Face forward throughout', 'Quick direction changes', 'Touch each cone']
  },
  {
    name: 'Star Drill',
    nameSv: 'Stjärnövning',
    description: 'From center, sprint to each of 5 outer cones and back, covering all points of a star pattern.',
    descriptionSv: 'Från mitten, sprinta till var och en av 5 yttre koner och tillbaka, täck alla punkter i ett stjärnmönster.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 50,
    defaultReps: 2,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_BASKETBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set center cone with 5 outer cones at 5m distance in star pattern (like points on a star).',
    executionCues: ['Sprint to outer cone', 'Touch and return', 'Quick feet at center', 'Maintain intensity throughout']
  },
  {
    name: 'W-Drill',
    nameSv: 'W-övning',
    description: 'Sprint diagonally between cones set in W pattern, combining forward sprints with angle cuts.',
    descriptionSv: 'Sprinta diagonalt mellan koner placerade i W-mönster, kombinera framåtsprintar med vinkelbyten.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 25,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set 5 cones in W pattern with 5m between each cone.',
    executionCues: ['Plant and cut at each cone', 'Stay low', 'Quick direction change', 'Accelerate between cones']
  },
  {
    name: 'Lane Agility (Basketball)',
    nameSv: 'Lane Agility (Basketball)',
    description: 'Navigate basketball key area: sprint forward, defensive slide left, backpedal, defensive slide right, sprint to finish.',
    descriptionSv: 'Navigera basketplanens målområde: sprinta framåt, försvarsrörelse vänster, backa, försvarsrörelse höger, sprinta i mål.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 28,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set cones to match basketball key dimensions (4.9m x 5.8m).',
    executionCues: ['Stay low in defensive slides', 'Quick hip transitions', 'Face baseline throughout', 'Explosive starts']
  },

  // ==================== REACTIVE AGILITY ====================
  {
    name: 'Mirror Drill (Partner)',
    nameSv: 'Spegelövning (partner)',
    description: 'Face partner 2m apart. Leader moves laterally, follower mirrors movements. React to sudden direction changes.',
    descriptionSv: 'Stå mittemot partner 2m ifrån varandra. Ledaren rör sig i sidled, följaren speglar rörelserna. Reagera på plötsliga riktningsändringar.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    durationSeconds: 20,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 40,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark 5m wide zone. Partners face each other 2m apart.',
    executionCues: ['Stay in athletic stance', 'React to hips not shoulders', 'Quick first step', 'Stay balanced']
  },
  {
    name: 'Reaction Ball Catches',
    nameSv: 'Reaktionsboll fångningar',
    description: 'Drop or throw reaction ball (hexagonal ball) and catch on unpredictable bounce.',
    descriptionSv: 'Släpp eller kasta reaktionsboll (hexagonal boll) och fånga vid oförutsägbar studs.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['reaction_ball'],
    optionalEquipment: ['wall'],
    durationSeconds: 30,
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL', 'TEAM_VOLLEYBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Use against wall or partner throws. Start 2-3m from wall.',
    executionCues: ['Stay ready position', 'React quickly', 'Use peripheral vision', 'Soft hands on catch']
  },
  {
    name: 'Blazepod Reaction Lights',
    nameSv: 'Blazepod reaktionsljus',
    description: 'React to randomly illuminating light pods, touching each as quickly as possible.',
    descriptionSv: 'Reagera på slumpmässigt tändande ljuspods, rör varje så snabbt som möjligt.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['reaction_lights'],
    optionalEquipment: ['cones'],
    durationSeconds: 30,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_ICE_HOCKEY', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Place 4-6 light pods in pattern appropriate for sport. Set reaction time and sequence in app.',
    executionCues: ['Central starting position', 'Use peripheral vision', 'Quick first step', 'Return to center']
  },
  {
    name: 'Coach Signal Reaction',
    nameSv: 'Coachsignal reaktion',
    description: 'React to visual or audio signals from coach indicating direction of movement.',
    descriptionSv: 'Reagera på visuella eller ljudsignaler från coach som indikerar rörelseriktning.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: [],
    optionalEquipment: ['cones', 'whistle'],
    durationSeconds: 30,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up movement area with cones. Coach stands visible to athletes.',
    executionCues: ['Watch coach peripherally', 'React to first cue', 'Explosive start', 'Commit to direction']
  },
  {
    name: 'Random Sprint Directions',
    nameSv: 'Slumpmässiga sprintriktningar',
    description: 'From center, sprint to randomly called numbered cones (1-4 or 1-6 pattern).',
    descriptionSv: 'Från mitten, sprinta till slumpmässigt kallade numrerade koner (1-4 eller 1-6 mönster).',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set numbered cones in circle or diamond pattern around center position, 5m from center.',
    executionCues: ['Stay ready', 'React immediately to call', 'Sprint to cone and back', 'Quick recovery to center']
  },
  {
    name: 'Tennis Ball Drop',
    nameSv: 'Tennisbollssläpp',
    description: 'Partner holds tennis ball at shoulder height, drops randomly. Catch before second bounce.',
    descriptionSv: 'Partner håller tennisboll i axelhöjd, släpper slumpmässigt. Fånga före andra studsen.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['tennis_ball'],
    optionalEquipment: [],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand 2m from partner who holds ball at shoulder height.',
    executionCues: ['Watch the ball', 'Explosive first step', 'Low catch position', 'Soft hands']
  },
  {
    name: 'Y-Test with Decision',
    nameSv: 'Y-test med beslut',
    description: 'Sprint forward, at decision point react to signal and cut left or right to finish.',
    descriptionSv: 'Sprinta framåt, vid beslutspunkten reagera på signal och sväng vänster eller höger till mål.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['reaction_lights'],
    distanceMeters: 15,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set up Y-pattern: start cone, decision cone 10m away, finish cones 5m at 45-degree angles.',
    executionCues: ['Full speed to decision point', 'React late', 'Plant and cut sharply', 'Accelerate through finish']
  },
  {
    name: 'Agility Ladder with Random Exits',
    nameSv: 'Stege med slumpmässiga utgångar',
    description: 'Navigate agility ladder, on signal exit and sprint to designated side cone.',
    descriptionSv: 'Navigera agilitetsstege, på signal avsluta och sprinta till angiven sidokägle.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['agility_ladder', 'cones'],
    optionalEquipment: ['whistle'],
    distanceMeters: 10,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Place agility ladder with cones 3m to each side for sprint exits.',
    executionCues: ['Maintain ladder rhythm', 'Listen for signal', 'Explosive lateral exit', 'Sprint through cone']
  },

  // ==================== SPEED & ACCELERATION ====================
  {
    name: '10m Sprint',
    nameSv: '10m sprint',
    description: 'Maximal acceleration sprint over 10 meters from standing or 3-point stance.',
    descriptionSv: 'Maximal accelerationssprint över 10 meter från stående eller 3-punktsställning.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark start and finish lines 10m apart. Optional timing gates at both ends.',
    executionCues: ['Explosive first step', 'Forward lean', 'Drive knees high', 'Pump arms hard']
  },
  {
    name: '20m Sprint',
    nameSv: '20m sprint',
    description: 'Acceleration sprint developing into max velocity over 20 meters.',
    descriptionSv: 'Accelerationssprint som utvecklas till maxhastighet över 20 meter.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL', 'RUNNING'],
    difficultyLevel: 2,
    setupInstructions: 'Mark start and finish lines 20m apart.',
    executionCues: ['Strong start', 'Gradual rise to upright', 'Drive through finish', 'Relax face and shoulders']
  },
  {
    name: '40m Sprint',
    nameSv: '40m sprint',
    description: 'Full acceleration and max velocity sprint over 40 meters.',
    descriptionSv: 'Full acceleration och maxhastighetssprint över 40 meter.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 40,
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING'],
    difficultyLevel: 3,
    setupInstructions: 'Mark start and finish lines 40m apart. Split timing at 10m and 20m optional.',
    executionCues: ['Powerful drive phase', 'Rise gradually', 'Maintain mechanics at max velocity', 'Run through finish']
  },
  {
    name: 'Flying 10m',
    nameSv: 'Flygande 10m',
    description: 'Build-up zone followed by timed 10m at maximum velocity.',
    descriptionSv: 'Uppbyggnadszon följt av tidtagning på 10m med maximal hastighet.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones', 'timing_gates'],
    optionalEquipment: [],
    distanceMeters: 30,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 180,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark 20m build-up zone, then 10m timed section.',
    executionCues: ['Build to max speed in zone', 'Maintain velocity through timing', 'Relaxed at top speed', 'Tall posture']
  },
  {
    name: 'Acceleration Ladder',
    nameSv: 'Accelerationsstege',
    description: 'Progressive sprints: 5m, 10m, 15m, 20m with walk-back recovery.',
    descriptionSv: 'Progressiva sprinter: 5m, 10m, 15m, 20m med gång-tillbaka återhämtning.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 50,
    defaultReps: 1,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark cones at 5m, 10m, 15m, and 20m from start.',
    executionCues: ['Max effort each sprint', 'Walk back for recovery', 'Focus on technique', 'Maintain quality']
  },
  {
    name: 'Sprint with Resistance Band',
    nameSv: 'Sprint med motståndsband',
    description: 'Partner-resisted sprints using resistance band for overspeed training effect.',
    descriptionSv: 'Partnermotståndssprinter med motståndsband för överhastighetstränande effekt.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['resistance_band'],
    optionalEquipment: ['cones'],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Attach band around waist. Partner provides resistance from behind.',
    executionCues: ['Drive against resistance', 'Forward lean', 'Powerful arm action', 'Quick foot contacts']
  },
  {
    name: 'Hill Sprints',
    nameSv: 'Backsprinter',
    description: 'Sprint up moderate incline (5-10%) to develop acceleration power.',
    descriptionSv: 'Sprinta uppför moderat lutning (5-10%) för att utveckla accelerationskraft.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 30,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING'],
    difficultyLevel: 4,
    setupInstructions: 'Find grassy hill with 5-10% gradient. Mark 20-30m sprint distance.',
    executionCues: ['Drive knees high', 'Pump arms powerfully', 'Lean into hill', 'Walk down for recovery']
  },
  {
    name: 'Standing Triple Jump for Distance',
    nameSv: 'Stående tresteg för längd',
    description: 'Horizontal plyometric: hop, step, jump for maximum distance.',
    descriptionSv: 'Horisontell plyometrisk: hopp, steg, hopp för maximal distans.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: [],
    optionalEquipment: ['measuring_tape'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark starting line. Ensure soft landing surface. Mark best distance.',
    executionCues: ['Explosive takeoff', 'Drive knee forward', 'Swing arms', 'Land balanced']
  },

  // ==================== PLYOMETRICS ====================
  {
    name: 'Box Jumps',
    nameSv: 'Lådhopp',
    description: 'Jump onto box from standing position, step down, repeat.',
    descriptionSv: 'Hoppa upp på låda från stående position, steg ner, upprepa.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Place box on stable surface. Start with 12-18 inch height and progress.',
    executionCues: ['Arms back to start', 'Swing arms up', 'Drive knees up', 'Land softly on box', 'Step down']
  },
  {
    name: 'Broad Jump',
    nameSv: 'Längdhopp från stående',
    description: 'Maximum distance horizontal jump from standing position.',
    descriptionSv: 'Maximal distans horisontellt hopp från stående position.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['measuring_tape'],
    distanceMeters: 3,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'RUNNING'],
    difficultyLevel: 2,
    setupInstructions: 'Mark starting line. Ensure clear landing area with good surface.',
    executionCues: ['Load hips back', 'Swing arms', 'Explode forward', 'Reach forward on landing']
  },
  {
    name: 'Lateral Hops',
    nameSv: 'Sidohopp',
    description: 'Continuous lateral hops over line or mini hurdle, single or double leg.',
    descriptionSv: 'Kontinuerliga sidohopp över linje eller minihäck, ett eller två ben.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['mini_hurdles'],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Mark line or place mini hurdle. Progress from line to higher obstacles.',
    executionCues: ['Stay in athletic stance', 'Push off outside leg', 'Quick ground contact', 'Arms for balance']
  },
  {
    name: 'Single-Leg Bounds',
    nameSv: 'Enkelbenhopp',
    description: 'Continuous forward bounds on single leg, focusing on distance and height.',
    descriptionSv: 'Kontinuerliga framåthopp på ett ben, fokus på distans och höjd.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 30,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Mark 30m distance. Ensure flat, even surface.',
    executionCues: ['Drive knee forward', 'Extend hip fully', 'Swing opposite arm', 'Active landing']
  },
  {
    name: 'Depth Jumps',
    nameSv: 'Djuphopp',
    description: 'Step off box, absorb landing, immediately jump up. Develops reactive strength.',
    descriptionSv: 'Kliv av låda, absorbera landning, hoppa omedelbart upp. Utvecklar reaktiv styrka.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_FOOTBALL'],
    difficultyLevel: 5,
    setupInstructions: 'Start with 12 inch box. Progress height gradually. Maximum 27 contacts per session.',
    executionCues: ['Step off, dont jump off', 'Minimal ground time', 'Explode upward', 'Land softly on box']
  },
  {
    name: 'Tuck Jumps',
    nameSv: 'Knälyft-hopp',
    description: 'Jump and bring knees to chest at peak height, land softly and repeat.',
    descriptionSv: 'Hoppa och för knäna till bröstet på topphöjden, landa mjukt och upprepa.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_VOLLEYBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Clear area required. Ensure good footing surface.',
    executionCues: ['Drive arms up', 'Pull knees high', 'Quick hip flexion', 'Extend before landing']
  },
  {
    name: 'Pogo Hops',
    nameSv: 'Pogo-hopp',
    description: 'Continuous small hops with minimal knee bend, focus on ankle stiffness.',
    descriptionSv: 'Kontinuerliga små hopp med minimal knäböjning, fokus på fotledsstyvhet.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 20,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['RUNNING', 'TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS'],
    difficultyLevel: 1,
    setupInstructions: 'Stand in place on firm surface.',
    executionCues: ['Stiff ankles', 'Minimal knee bend', 'Quick ground contact', 'Stay tall']
  },
  {
    name: 'Hurdle Hops (Continuous)',
    nameSv: 'Häckhopp (kontinuerliga)',
    description: 'Continuous forward hops over series of mini hurdles.',
    descriptionSv: 'Kontinuerliga framåthopp över serie av minihäckar.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['mini_hurdles'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'RUNNING', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set 5-6 hurdles in line, spacing 1m apart. Height 6-18 inches based on ability.',
    executionCues: ['Arms drive upward', 'Quick feet over hurdles', 'Land softly', 'Immediately spring up']
  },
  {
    name: 'Split Squat Jumps',
    nameSv: 'Splithopp',
    description: 'Jump from lunge position, switch legs in air, land in lunge position.',
    descriptionSv: 'Hoppa från utfallsposition, byt ben i luften, landa i utfallsposition.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: [],
    defaultReps: 10,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 3,
    setupInstructions: 'Clear area required. Start in lunge position.',
    executionCues: ['Drive through front leg', 'Get height', 'Switch legs quickly', 'Land softly in lunge']
  },
  {
    name: 'Rotational Box Jump',
    nameSv: 'Rotationshopp',
    description: 'Jump onto box with 90 or 180 degree rotation.',
    descriptionSv: 'Hoppa upp på låda med 90 eller 180 graders rotation.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['plyo_box'],
    optionalEquipment: [],
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Place lower box than normal box jumps. Start with 90-degree rotations.',
    executionCues: ['Swing arms for rotation', 'Turn head first', 'Land stable', 'Step down controlled']
  },

  // ==================== FOOTWORK ====================
  {
    name: 'Ladder - In-In-Out-Out (Icky Shuffle)',
    nameSv: 'Stege - In-In-Ut-Ut',
    description: 'Classic ladder pattern: both feet in square, both feet out sides, repeat down ladder.',
    descriptionSv: 'Klassiskt stegemönster: båda fötterna i rutan, båda fötterna ut på sidorna, upprepa nedför stegen.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Lay ladder flat on ground. Stand at one end.',
    executionCues: ['Stay on balls of feet', 'Quick feet', 'Arms bent at 90 degrees', 'Eyes up']
  },
  {
    name: 'Ladder - Lateral Shuffle',
    nameSv: 'Stege - Sidosteg',
    description: 'Move laterally through ladder, two feet in each square.',
    descriptionSv: 'Rör dig i sidled genom stegen, två fötter i varje ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL', 'TEAM_HANDBALL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand beside ladder at one end.',
    executionCues: ['Stay low', 'Quick shuffle', 'Dont cross feet', 'Face forward']
  },
  {
    name: 'Ladder - Single Leg Hops',
    nameSv: 'Stege - Enkelbenhopp',
    description: 'Hop through ladder on single leg, one foot per square.',
    descriptionSv: 'Hoppa genom stegen på ett ben, en fot per ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Lay ladder flat. Do both legs each set.',
    executionCues: ['Stay balanced', 'Quick hops', 'Use arms', 'Land softly']
  },
  {
    name: 'Ladder - High Knees',
    nameSv: 'Stege - Höga knän',
    description: 'Run through ladder with high knee drive, one foot per square.',
    descriptionSv: 'Spring genom stegen med höga knälyft, en fot per ruta.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder'],
    optionalEquipment: [],
    distanceMeters: 5,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Stand at ladder end. Focus on knee height.',
    executionCues: ['Drive knees up', 'Quick contacts', 'Stay tall', 'Pump arms']
  },
  {
    name: 'Cone Zig-Zag',
    nameSv: 'Kon zigzag',
    description: 'Sprint diagonally between staggered cones, cutting at each cone.',
    descriptionSv: 'Sprinta diagonalt mellan förskjutna koner, sväng vid varje kon.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Set 6-8 cones in zigzag pattern, 2-3m apart.',
    executionCues: ['Plant outside foot', 'Stay low', 'Quick direction change', 'Accelerate between cones']
  },
  {
    name: 'Quick Feet Drill',
    nameSv: 'Snabba fötter-övning',
    description: 'Rapid foot movement in place or over line, maximum speed footwork.',
    descriptionSv: 'Snabba fotrörelsen på stället eller över linje, maximal hastighet.',
    category: 'FOOTWORK',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    durationSeconds: 10,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand in athletic stance. Optional line or cone as reference.',
    executionCues: ['Balls of feet only', 'Maximum turnover', 'Stay light', 'Arms at 90 degrees']
  },
  {
    name: 'Figure 8 Around Cones',
    nameSv: 'Figur-8 runt koner',
    description: 'Navigate figure 8 pattern around two cones with continuous movement.',
    descriptionSv: 'Navigera figur-8 mönster runt två koner med kontinuerlig rörelse.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 2,
    setupInstructions: 'Place two cones 3-4m apart.',
    executionCues: ['Stay low', 'Tight turns', 'Push off outside foot', 'Control through curves']
  },
  {
    name: 'Ali Shuffle',
    nameSv: 'Ali-shuffle',
    description: 'Quick alternating forward-back foot pattern in place.',
    descriptionSv: 'Snabbt alternerande fram-bak fotmönster på stället.',
    category: 'FOOTWORK',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 15,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Stand in place, athletic stance.',
    executionCues: ['Light on feet', 'Quick switches', 'Stay centered', 'Relaxed upper body']
  },

  // ==================== BALANCE ====================
  {
    name: 'Single-Leg Balance',
    nameSv: 'Enkelbenbalans',
    description: 'Stand on single leg maintaining balance for specified time.',
    descriptionSv: 'Stå på ett ben och håll balansen under angiven tid.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 30,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 15,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING', 'TENNIS', 'PADEL'],
    difficultyLevel: 1,
    setupInstructions: 'Stand on flat surface. Progress to unstable surfaces.',
    executionCues: ['Eyes forward', 'Slight knee bend', 'Core engaged', 'Arms for balance']
  },
  {
    name: 'Single-Leg Balance with Eyes Closed',
    nameSv: 'Enkelbenbalans med slutna ögon',
    description: 'Single-leg balance with eyes closed to challenge proprioception.',
    descriptionSv: 'Enkelbenbalans med slutna ögon för att utmana proprioception.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: [],
    durationSeconds: 20,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 15,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING'],
    difficultyLevel: 2,
    setupInstructions: 'Ensure safe area. Progress from firm to unstable surface.',
    executionCues: ['Close eyes smoothly', 'Micro-adjustments', 'Core tight', 'Relax breathing']
  },
  {
    name: 'BOSU Single-Leg Balance',
    nameSv: 'BOSU enkelbenbalans',
    description: 'Single-leg balance on BOSU ball surface.',
    descriptionSv: 'Enkelbenbalans på BOSU-bollens yta.',
    category: 'BALANCE',
    requiredEquipment: ['bosu_ball'],
    optionalEquipment: [],
    durationSeconds: 30,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 20,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'SKIING', 'TEAM_BASKETBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Place BOSU flat side down. Stand on dome side.',
    executionCues: ['Find center', 'Engage core', 'Micro-adjust ankle', 'Use arms if needed']
  },
  {
    name: 'Y-Balance Test Drill',
    nameSv: 'Y-balanstestövning',
    description: 'Reach in three directions (anterior, posterolateral, posteromedial) while standing on single leg.',
    descriptionSv: 'Nå i tre riktningar (framåt, posterolateral, posteromedial) medan du står på ett ben.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['y_balance_kit'],
    defaultReps: 3,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'RUNNING'],
    difficultyLevel: 3,
    setupInstructions: 'Mark Y-pattern on floor or use Y-balance kit.',
    executionCues: ['Control throughout', 'Reach as far as possible', 'Return to start', 'Maintain balance']
  },
  {
    name: 'Dynamic Balance Reaches',
    nameSv: 'Dynamiska balansnådder',
    description: 'Single-leg stance with reaches in multiple directions for dynamic stability.',
    descriptionSv: 'Enstående ställning med nådder i flera riktningar för dynamisk stabilitet.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    defaultReps: 8,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TENNIS', 'PADEL'],
    difficultyLevel: 2,
    setupInstructions: 'Set up cones in arc around standing position.',
    executionCues: ['Stable stance leg', 'Controlled reaches', 'Return to center', 'Progress speed']
  },
  {
    name: 'Perturbation Training',
    nameSv: 'Perturbationsträning',
    description: 'Partner provides random pushes while athlete maintains single-leg balance.',
    descriptionSv: 'Partner ger slumpmässiga skuff medan atleten håller enkelbenbalans.',
    category: 'BALANCE',
    requiredEquipment: [],
    optionalEquipment: ['stability_pad'],
    durationSeconds: 20,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Partner stands ready to apply light, random pushes to hips and shoulders.',
    executionCues: ['Stay reactive', 'Quick recovery', 'Use core', 'Anticipate in game-like way']
  },

  // ==================== ADDITIONAL SPEED & ACCELERATION ====================
  {
    name: 'Repeated Sprint Ability (RSA) Test',
    nameSv: 'Upprepat sprinttest (RSA)',
    description: '6-10 repeated maximal sprints (20-40m) with short rest (20-25s). Measures ability to maintain sprint speed under fatigue.',
    descriptionSv: '6-10 upprepade maximala sprinter (20-40m) med kort vila (20-25s). Mäter förmågan att bibehålla sprinthastighet under trötthet.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['timing_gates', 'cones'],
    optionalEquipment: ['heart_rate_monitor'],
    distanceMeters: 30,
    defaultReps: 8,
    defaultSets: 1,
    restSeconds: 25,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_BASKETBALL', 'TEAM_ICE_HOCKEY'],
    difficultyLevel: 5,
    setupInstructions: 'Mark 30m sprint distance with timing gates at start and finish. Set timer for 25s recovery.',
    executionCues: ['Maximal effort every sprint', 'Walk back quickly', 'Ready position before each sprint', 'Focus on first 3 steps']
  },
  {
    name: 'Deceleration Stop Drill',
    nameSv: 'Inbromsningsövning',
    description: 'Sprint 20m at max speed, then decelerate and stop as quickly as possible within a 5m zone. Focus on braking mechanics.',
    descriptionSv: 'Sprinta 20m med maxfart, bromsa in och stanna så snabbt som möjligt inom en 5m zon. Fokus på bromsningsteknik.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 25,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Mark start line, 20m sprint zone, then 5m deceleration zone with final stop line.',
    executionCues: ['Lower center of gravity to stop', 'Short choppy steps', 'Lean back slightly', 'Arms out for balance']
  },

  // ==================== ADDITIONAL COD ====================
  {
    name: 'Deceleration to Cut',
    nameSv: 'Inbromsning till riktningsbyte',
    description: 'Sprint 15m, decelerate, plant foot and cut 45-90 degrees, accelerate 10m to finish.',
    descriptionSv: 'Sprinta 15m, bromsa in, plantera foten och sväng 45-90 grader, accelerera 10m till mål.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 25,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_HANDBALL', 'TEAM_FLOORBALL', 'TEAM_BASKETBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Set start cone, decision cone at 15m, and finish cone at 45/90 degree angle 10m from decision point.',
    executionCues: ['Decelerate with control', 'Plant outside foot hard', 'Low center of gravity at cut', 'Explode out of cut']
  },
  {
    name: 'Zig-Zag Sprint with Deceleration',
    nameSv: 'Zigzag-sprint med inbromsning',
    description: 'Sprint through zig-zag cone pattern with forced deceleration at each change of direction.',
    descriptionSv: 'Sprinta genom zigzag-konmönster med tvingad inbromsning vid varje riktningsbyte.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 30,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 3,
    setupInstructions: 'Set 6-8 cones in zig-zag pattern, 5m apart, with 3m offset.',
    executionCues: ['Decelerate before each cone', 'Plant and drive', 'Stay low through cuts', 'Accelerate between cones']
  },

  // ==================== ADDITIONAL FOOTWORK ====================
  {
    name: 'Carioca / Karaoke Drill',
    nameSv: 'Carioca / Karaoke',
    description: 'Lateral movement crossing feet alternately in front and behind. Develops hip mobility and coordination.',
    descriptionSv: 'Sidledes rörelse med korsande fötter omväxlande framför och bakom. Utvecklar höftrörlighet och koordination.',
    category: 'FOOTWORK',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'RUNNING', 'TENNIS', 'TEAM_HANDBALL', 'TEAM_ICE_HOCKEY'],
    difficultyLevel: 2,
    setupInstructions: 'Mark 20m distance. Perform in both directions each set.',
    executionCues: ['Cross over in front', 'Cross behind', 'Stay on balls of feet', 'Quick hip rotation']
  },
  {
    name: 'Multi-Directional Sprint Pattern',
    nameSv: 'Multiriktad sprintövning',
    description: 'From center cone, sprint to cones placed at 0, 45, 90, 135, and 180 degrees. Coach or signal calls direction.',
    descriptionSv: 'Från mittkonen, sprinta till koner placerade vid 0, 45, 90, 135 och 180 grader. Coach eller signal ropar riktning.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones', 'timing_gates'],
    optionalEquipment: ['reaction_lights'],
    distanceMeters: 10,
    defaultReps: 8,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_FOOTBALL', 'TEAM_ICE_HOCKEY', 'TEAM_BASKETBALL', 'TEAM_HANDBALL'],
    difficultyLevel: 4,
    setupInstructions: 'Place center cone with 5 outer cones at 10m distance in semi-circle pattern at 0, 45, 90, 135, 180 degrees.',
    executionCues: ['Explosive first step', 'Open hips to target direction', 'Sprint through cone', 'Quick return to center']
  }
]

const hockeyAgilityDrills: AgilityDrillSeed[] = [
  // ==================== HOCKEY-SPECIFIC OFF-ICE PACK ====================
  // Derived from the de-identified 2020-2026 hockey program corpus:
  // hurdle prep, cone touch, lateral shuffle, short shuttle repeats,
  // speed-course/L-drill work, reactive signals, sled drive, and late-summer speed progression.
  {
    name: 'Hockey Hurdle Walkover with Medicine Ball',
    nameSv: 'Hockey häckgång med medicinboll',
    description: 'Controlled hurdle walkover holding a medicine ball to prepare hips, trunk, and groin before higher-speed hockey agility.',
    descriptionSv: 'Kontrollerad häckgång med medicinboll för att förbereda höft, bål och ljumske inför snabbare hockeyagility.',
    category: 'FOOTWORK',
    requiredEquipment: ['mini_hurdles', 'medicine_ball'],
    optionalEquipment: [],
    distanceMeters: 8,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 2,
    setupInstructions: 'Place 5-6 low hurdles in a straight line. Hold medicine ball at chest height.',
    executionCues: ['Tall posture', 'Own the hip position', 'Quiet trunk', 'Step over without swinging the leg']
  },
  {
    name: 'Hockey Zig-Zag Hurdle Hop',
    nameSv: 'Hockey zick-zack-hopp över häck',
    description: 'Diagonal low hurdle hops emphasizing lateral stiffness, rhythm, and controlled landing angles.',
    descriptionSv: 'Diagonala låga häckhopp med fokus på lateral styvhet, rytm och kontrollerade landningsvinklar.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['mini_hurdles'],
    optionalEquipment: [],
    distanceMeters: 8,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Place 5-6 mini hurdles in a slight zig-zag line with 1-1.5m spacing.',
    executionCues: ['Push side-to-side', 'Land over mid-foot', 'Keep knees tracking toes', 'Stop before landings get noisy']
  },
  {
    name: 'Hockey Figure-8 Ball Catch',
    nameSv: 'Hockey åttan med bollfång',
    description: 'Figure-8 cone movement with a partner ball toss to combine curved footwork, vision, and hand reaction.',
    descriptionSv: 'Figur-8 runt koner med bollkast från partner för att kombinera kurvtagning, blick och handreaktion.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones', 'tennis_ball'],
    optionalEquipment: ['medicine_ball'],
    distanceMeters: 10,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 40,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Place two cones 4m apart. Athlete moves in figure-8 while partner tosses ball from changing angles.',
    executionCues: ['Keep eyes available', 'Stay low through curves', 'Catch outside the body line', 'Accelerate out of each turn']
  },
  {
    name: 'Hockey Dice Five Cone Touch',
    nameSv: 'Hockey kontouch femman',
    description: 'Max-speed cone touch pattern using a dice-five setup: center cone plus four outside cones.',
    descriptionSv: 'Kontouch i maxhastighet med tärningens femma: mittkon plus fyra ytterkoner.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 24,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Set four cones in a 5m square and one cone in the center. Start and return through center between touches.',
    executionCues: ['Low hips into touch', 'Push away from the cone', 'Short brake steps', 'Sprint the first two steps out']
  },
  {
    name: 'Hockey Reactive Cone Touch',
    nameSv: 'Hockey reaktiv kontouch',
    description: 'Cone touch pattern where coach calls the next cone late to train decision making under speed.',
    descriptionSv: 'Kontouch där coachen ropar nästa kon sent för att träna beslut under fart.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['reaction_lights', 'whistle'],
    durationSeconds: 15,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Use dice-five cone setup. Coach calls color/number only after athlete returns toward center.',
    executionCues: ['React late', 'No guessing', 'Brake before the cone', 'Explode out of every touch']
  },
  {
    name: 'Hockey Lateral Run Hurdle Combo',
    nameSv: 'Hockey sidledslöp med häck',
    description: 'Lateral shuffle into low hurdle contacts and short acceleration, matching common off-ice hockey agility blocks.',
    descriptionSv: 'Sidledslöp in i låga häckkontakter och kort acceleration enligt återkommande hockeyagilityblock.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones', 'mini_hurdles'],
    optionalEquipment: [],
    distanceMeters: 12,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Mark 4m lateral shuffle lane, then place 3 mini hurdles and a 5m sprint finish.',
    executionCues: ['Stay square during shuffle', 'Fast feet over hurdles', 'Open hips cleanly', 'Sprint through the finish']
  },
  {
    name: 'Hockey L-Run 2-4-2-4-2',
    nameSv: 'Hockey L-löpning 2-4-2-4-2',
    description: 'Short L-pattern shuttle with 2m and 4m changes, built for tight hockey-style re-acceleration.',
    descriptionSv: 'Kort L-format shuttle med 2m och 4m riktningsbyten för tät hockeylik re-acceleration.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 14,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Create an L with cones at 0m, 2m, 6m, 8m, and 12m. Athlete changes direction at every cone.',
    executionCues: ['Own the braking step', 'Stay compact', 'Punch the ground away', 'No upright turns']
  },
  {
    name: 'Hockey Short Idioten 5-10-5-10',
    nameSv: 'Hockey korta idioten 5-10-5-10',
    description: 'Short shuttle repeat using 5m and 10m touches for hockey repeat-acceleration and braking quality.',
    descriptionSv: 'Kort idioten med 5m och 10m touch för upprepad acceleration och bromskvalitet i hockey.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 30,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 75,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Mark start, 5m, and 10m lines. Run 5-out/back, 10-out/back, then repeat if prescribed.',
    executionCues: ['Touch low', 'Turn both directions', 'Keep first steps powerful', 'Stop if braking gets sloppy']
  },
  {
    name: 'Hockey Long Idioten 5-10-15-20-25',
    nameSv: 'Hockey långa idioten 5-10-15-20-25',
    description: 'Longer shuttle ladder used for late-block conditioning, COD tolerance, and fatigue-resistant mechanics.',
    descriptionSv: 'Längre idiotstege för sen blockkondition, COD-tolerans och teknik under trötthet.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 150,
    defaultReps: 2,
    defaultSets: 2,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 5,
    setupInstructions: 'Mark start plus 5m, 10m, 15m, 20m, and 25m lines. Return to start after each distance.',
    executionCues: ['Pace the first half', 'Touch and exit cleanly', 'Hold posture late', 'Track quality drop']
  },
  {
    name: 'Hockey Repeated Sprint 6-6-44',
    nameSv: 'Hockey upprepad sprint 6x6/44',
    description: 'Six-second maximal sprint repeated with 44 seconds recovery, reflecting hockey repeated-sprint programming.',
    descriptionSv: 'Sex sekunders maxsprint med 44 sekunders vila, enligt återkommande hockey-RSA-upplägg.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates', 'heart_rate_monitor'],
    durationSeconds: 6,
    defaultReps: 6,
    defaultSets: 2,
    restSeconds: 44,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 5,
    setupInstructions: 'Mark a 30-40m lane. Sprint maximally for 6 seconds, then recover for 44 seconds.',
    executionCues: ['Max intent every rep', 'Reset breathing fast', 'Track distance or time', 'Stop if output collapses']
  },
  {
    name: 'Hockey Repeated Sprint 4-16',
    nameSv: 'Hockey upprepad sprint 4/16',
    description: 'Four-second sprint bursts with 16 seconds recovery for short shift-quality acceleration repeats.',
    descriptionSv: 'Fyra sekunders sprintar med 16 sekunders vila för korta shift-lika accelerationer.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    durationSeconds: 4,
    defaultReps: 10,
    defaultSets: 2,
    restSeconds: 16,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Use a 20-30m lane. Sprint for 4 seconds, walk/reset for 16 seconds.',
    executionCues: ['Explosive first three steps', 'Stay low early', 'Reset quickly', 'Keep every rep sharp']
  },
  {
    name: 'Hockey Repeated Sprint 3-7',
    nameSv: 'Hockey upprepad sprint 3/7',
    description: 'Very short acceleration repeats with incomplete recovery for first-step repeatability.',
    descriptionSv: 'Mycket korta accelerationsrepetitioner med ofullständig vila för upprepad förstastegskvalitet.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    durationSeconds: 3,
    defaultReps: 12,
    defaultSets: 2,
    restSeconds: 7,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Use 10-15m acceleration zone. Sprint 3 seconds, reset 7 seconds.',
    executionCues: ['Win the first step', 'Stay compact', 'No wasted step', 'Keep posture under fatigue']
  },
  {
    name: 'Hockey Lateral Start to 10m Sprint',
    nameSv: 'Hockey sidostart till 10m sprint',
    description: 'Start facing sideways, open hips, and sprint 10m to train lateral-to-forward transfer.',
    descriptionSv: 'Starta sidvänd, öppna höften och sprinta 10m för överföring från sidled till framåt.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Mark a 10m lane. Athlete begins side-on to finish line and alternates opening left/right.',
    executionCues: ['Open hip violently', 'No false step', 'Drive inside arm', 'Sprint through line']
  },
  {
    name: 'Hockey Crossover Step-Up Sprint',
    nameSv: 'Hockey crossover step-up sprint',
    description: 'Crossover step or low box step-up immediately into a short sprint, bridging gym crossover strength to acceleration.',
    descriptionSv: 'Crossoversteg eller låg step-up direkt till kort sprint som brygga från gymstyrka till acceleration.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['plyo_box', 'cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Use a low stable box or marked crossover start. Step across, drive up, then sprint 10m.',
    executionCues: ['Push through whole foot', 'Snap hips forward', 'Tall exit', 'Alternate sides']
  },
  {
    name: 'Hockey Sprint-Float-Sprint',
    nameSv: 'Hockey sprint-flyt-sprint',
    description: 'Short acceleration, relaxed float, then re-acceleration to develop speed rhythm without excess volume.',
    descriptionSv: 'Kort acceleration, avslappnat flyt och ny acceleration för fartkänsla utan onödig volym.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 25,
    defaultReps: 4,
    defaultSets: 2,
    restSeconds: 120,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Mark 5m sprint, 10m float, and 10m sprint zones.',
    executionCues: ['Accelerate hard first zone', 'Relax in float', 'Re-accelerate smoothly', 'Keep shoulders quiet']
  },
  {
    name: 'Hockey Sled Push Repeat 2x20m',
    nameSv: 'Hockey slädpush 2x20m',
    description: 'Two hard 20m sled pushes per rep for skating drive, trunk stiffness, and repeat-power conditioning.',
    descriptionSv: 'Två hårda 20m slädpushar per rep för skridskodriv, bålstyvhet och repeat-power.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['sled'],
    optionalEquipment: ['cones'],
    distanceMeters: 40,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Mark 20m lane. Push out and back or perform two separate 20m pushes.',
    executionCues: ['Low drive angle', 'Long powerful pushes', 'Brace trunk', 'Keep output repeatable']
  },
  {
    name: 'Hockey Sled Push 2x25m',
    nameSv: 'Hockey slädpush 2x25m',
    description: 'Longer sled push repeat used for heavy skating-drive conditioning blocks.',
    descriptionSv: 'Längre slädpushrepetition för tyngre skridskodriv och konditionsblock.',
    category: 'SPEED_ACCELERATION',
    requiredEquipment: ['sled'],
    optionalEquipment: ['cones'],
    distanceMeters: 50,
    defaultReps: 2,
    defaultSets: 3,
    restSeconds: 90,
    minDevelopmentStage: 'TRAINING_TO_COMPETE',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 5,
    setupInstructions: 'Mark 25m lane. Use load that allows forceful but continuous movement.',
    executionCues: ['Drive through hips', 'Avoid rounded back', 'Finish the lane', 'Rest enough to keep quality']
  },
  {
    name: 'Hockey G-Band Lateral Cone Touch',
    nameSv: 'Hockey G-band sidled kontouch',
    description: 'Band-resisted lateral cone touch for groin, hip, and skating push-off control.',
    descriptionSv: 'Bandmotstånd i sidled med kontouch för ljumske, höft och skridskofrånslag.',
    category: 'COD',
    requiredEquipment: ['resistance_band', 'cones'],
    optionalEquipment: [],
    distanceMeters: 8,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Anchor band at hip height. Place two cones 3-4m apart laterally. Move against band and touch cone.',
    executionCues: ['Control knee line', 'Push from outside hip', 'Do not collapse trunk', 'Return with control']
  },
  {
    name: 'Hockey G-Band Half-Moon Cone Touch',
    nameSv: 'Hockey G-band halvmåne kontouch',
    description: 'Band-resisted half-moon cone touches to train multi-angle hip control and re-acceleration.',
    descriptionSv: 'Bandmotstånd i halvmåne för multi-vinkel höftkontroll och re-acceleration.',
    category: 'COD',
    requiredEquipment: ['resistance_band', 'cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Place 3-5 cones in a half-moon around the athlete while band is anchored behind or to the side.',
    executionCues: ['Reach with hips loaded', 'Keep chest over base', 'Push out of each touch', 'Alternate directions']
  },
  {
    name: 'Hockey VIPR Gate Run',
    nameSv: 'Hockey gatlopp med ViPR',
    description: 'Carry or hold ViPR through a cone gate pattern to combine contact posture, trunk stiffness, and COD.',
    descriptionSv: 'Bär eller håll ViPR genom ett kon-gatlopp för kontaktposition, bålstyvhet och riktningsbyte.',
    category: 'COD',
    requiredEquipment: ['cones', 'vipr'],
    optionalEquipment: [],
    distanceMeters: 20,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Set 5-6 cone gates in a staggered line. Carry ViPR at chest or bear-hug position.',
    executionCues: ['Brace before cut', 'Stay low through gates', 'Do not let load rotate you', 'Accelerate between gates']
  },
  {
    name: 'Hockey Quick Feet Broad Jump Exit',
    nameSv: 'Hockey frekvensstege till bredhopp och exit',
    description: 'Fast ladder pattern into three broad jumps, six quick hops, then sprint exit.',
    descriptionSv: 'Frekvensstege in i tre bredhopp, sex snabba omhopp och därefter sprint ut.',
    category: 'FOOTWORK',
    requiredEquipment: ['agility_ladder', 'cones'],
    optionalEquipment: [],
    distanceMeters: 15,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Lay ladder, mark broad-jump zone after ladder, then 5m sprint exit.',
    executionCues: ['Fast feet first', 'Stick broad jumps', 'Quick rebound hops', 'Sprint out clean']
  },
  {
    name: 'Hockey Low Pogo to Sprint',
    nameSv: 'Hockey låga pogos till sprint',
    description: 'Low ankle stiffness pogo hops immediately into a short sprint for first-step pop.',
    descriptionSv: 'Låga pogohopp för fotledsstyvhet direkt till kort sprint för förstastegspop.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'FUNDAMENTALS',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 2,
    setupInstructions: 'Perform 6-8 low pogos in place, then sprint 10m.',
    executionCues: ['Stiff ankles', 'Quiet upper body', 'Pop into first step', 'No deep countermovement']
  },
  {
    name: 'Hockey Skater Jump Stick',
    nameSv: 'Hockey skridskohopp med stopp',
    description: 'Lateral skater jump with a clean stick landing to build edge-control analogs off ice.',
    descriptionSv: 'Lateralt skridskohopp med kontrollerad landning som off-ice-analog till edge control.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Mark lateral distance with cones if needed. Jump side-to-side and hold each landing 1 second.',
    executionCues: ['Push the floor away', 'Land on one leg', 'Knee tracks toes', 'Quiet upper body']
  },
  {
    name: 'Hockey Skater Jump Three-Beat',
    nameSv: 'Hockey skridskohopp 3-takt',
    description: 'Rhythmic three-beat skater jump sequence for lateral power and transition timing.',
    descriptionSv: 'Rytmisk 3-taktssekvens av skridskohopp för lateral kraft och övergångstiming.',
    category: 'PLYOMETRICS',
    requiredEquipment: [],
    optionalEquipment: ['cones'],
    distanceMeters: 20,
    defaultReps: 3,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Move laterally down a 20m lane using a three-beat rhythm before switching direction.',
    executionCues: ['Find rhythm', 'Push laterally not vertically', 'Control pelvis', 'Reset if rhythm breaks']
  },
  {
    name: 'Hockey Lateral Bound to Sprint',
    nameSv: 'Hockey sidohopp till sprint',
    description: 'Single lateral bound into a 10m sprint, training force transfer from side push to forward acceleration.',
    descriptionSv: 'Ett lateralt hopp direkt till 10m sprint för kraftöverföring från sidofrånslag till acceleration.',
    category: 'PLYOMETRICS',
    requiredEquipment: ['cones'],
    optionalEquipment: ['timing_gates'],
    distanceMeters: 10,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Start side-on. Perform one lateral bound, land, then sprint 10m forward.',
    executionCues: ['Stick the landing fast', 'Open hips', 'No extra gather step', 'Sprint through line']
  },
  {
    name: 'Hockey Side Step with Stop',
    nameSv: 'Hockey sidostep med stopp',
    description: 'Side-step across mini hurdles with a deliberate stop and medicine-ball hold to reinforce braking and trunk control.',
    descriptionSv: 'Sidosteg över små häckar med markerat stopp och medicinboll för bromsning och bålposition.',
    category: 'FOOTWORK',
    requiredEquipment: ['mini_hurdles', 'medicine_ball'],
    optionalEquipment: ['cones'],
    distanceMeters: 8,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Place 4 mini hurdles laterally. Hold medicine ball and stop hard after final hurdle.',
    executionCues: ['Stay low', 'Fast side steps', 'Freeze the stop', 'No knee collapse']
  },
  {
    name: 'Hockey Forward-Back Cone Round',
    nameSv: 'Hockey fram-bak runt bakre kon',
    description: 'Forward-backward cone pattern rounding the rear cone to train hip turns and transition control.',
    descriptionSv: 'Fram-bak-koner med rundning av bakre kon för höftvändning och övergångskontroll.',
    category: 'COD',
    requiredEquipment: ['cones'],
    optionalEquipment: [],
    distanceMeters: 16,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Place front cone, rear cone 4m behind, and finish cone 4m forward. Move forward-back-round-forward.',
    executionCues: ['Keep feet under hips', 'Round rear cone tight', 'Open hips before sprint', 'Stay balanced backward']
  },
  {
    name: 'Hockey Mirror Shuffle to Sprint',
    nameSv: 'Hockey spegel sidled till sprint',
    description: 'Partner mirror shuffle that finishes with a sprint cue to blend reaction, lateral movement, and acceleration.',
    descriptionSv: 'Partnerspegel i sidled som avslutas med sprintsignal för reaktion, sidled och acceleration.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['whistle'],
    durationSeconds: 20,
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 60,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Mark 5m lateral lane and 10m sprint finish. Mirror partner until coach cues sprint.',
    executionCues: ['React to hips', 'Stay low', 'Do not cross feet unless cued', 'Win the sprint exit']
  },
  {
    name: 'Hockey Color Call Lateral Cut',
    nameSv: 'Hockey färgrop sidledscut',
    description: 'Coach calls cone color or number and athlete cuts laterally before sprinting through the called gate.',
    descriptionSv: 'Coach ropar färg eller nummer och atleten cuttar i sidled innan sprint genom kallad gate.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['reaction_lights'],
    distanceMeters: 12,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Place 3-4 colored or numbered gates in a shallow arc 6-8m away.',
    executionCues: ['Read then go', 'Cut under control', 'Accelerate through gate', 'Recover to ready position']
  },
  {
    name: 'Hockey Reactive Hurdle Hop on Signal',
    nameSv: 'Hockey reaktivt häckhopp på signal',
    description: 'Cone touch followed by a reactive hurdle hop direction on coach signal.',
    descriptionSv: 'Kontouch följt av reaktivt häckhopp i riktning på coachsignal.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones', 'mini_hurdles'],
    optionalEquipment: ['whistle', 'reaction_lights'],
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Set one touch cone and hurdles left/right. Athlete touches cone, then hops the signaled hurdle.',
    executionCues: ['Wait for cue', 'Fast but clean hop', 'Stick the landing', 'Return to ready stance']
  },
  {
    name: 'Hockey Battle Rope Lunge Lateral Signal',
    nameSv: 'Hockey battlerope utfall sidled på signal',
    description: 'Battle rope or snake rope waves with alternating lunge, then lateral shuffle on coach signal.',
    descriptionSv: 'Battlerope/snakerope med växlande utfall och sidledslöp på signal.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['battle_rope', 'cones'],
    optionalEquipment: ['whistle'],
    durationSeconds: 15,
    defaultReps: 4,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'TRAINING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 4,
    setupInstructions: 'Athlete performs rope waves with alternating lunge. On signal, releases rope and shuffles to called cone.',
    executionCues: ['Brace while using rope', 'React instantly', 'Stay low in shuffle', 'Reset rope under control']
  },
  {
    name: 'Hockey Goalie Crease Lateral Push',
    nameSv: 'Hockey målvakt sidledspush',
    description: 'Goalie-oriented lateral push between crease-width cones with stick landing and visual cue.',
    descriptionSv: 'Målvaktsinriktad sidledspush mellan koner i crease-bredd med kontrollerad landning och visuell cue.',
    category: 'REACTIVE_AGILITY',
    requiredEquipment: ['cones'],
    optionalEquipment: ['reaction_lights', 'tennis_ball'],
    distanceMeters: 6,
    defaultReps: 6,
    defaultSets: 3,
    restSeconds: 45,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Place two cones 3-4m apart. Coach points, calls, or tosses ball to trigger direction.',
    executionCues: ['Push from inside edge analog', 'Stay square', 'Stick the stop', 'Recover eyes before next cue']
  },
  {
    name: 'Hockey Single-Leg Lateral Catch',
    nameSv: 'Hockey enbens sidofång',
    description: 'Single-leg lateral hop or reach with partner catch to blend balance, groin control, and reaction.',
    descriptionSv: 'Enbens sidohopp eller reach med partnerfång för balans, ljumske och reaktion.',
    category: 'BALANCE',
    requiredEquipment: ['tennis_ball'],
    optionalEquipment: ['stability_pad'],
    defaultReps: 5,
    defaultSets: 3,
    restSeconds: 30,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Stand on one leg. Partner tosses ball slightly outside body line after each small lateral hop/reach.',
    executionCues: ['Quiet landing', 'Reach without collapsing', 'Catch with eyes up', 'Alternate sides']
  },
  {
    name: 'Hockey BOSU Clock Reach',
    nameSv: 'Hockey klockan på BOSU',
    description: 'Single-leg clock reach on BOSU or stable surface for ankle, hip, and trunk control.',
    descriptionSv: 'Enbens klockreach på BOSU eller plant underlag för fotled, höft och bål.',
    category: 'BALANCE',
    requiredEquipment: ['bosu_ball'],
    optionalEquipment: ['cones'],
    durationSeconds: 90,
    defaultReps: 1,
    defaultSets: 2,
    restSeconds: 30,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 3,
    setupInstructions: 'Stand on one leg on BOSU. Reach free foot or hand toward clock positions around the body.',
    executionCues: ['Keep stance knee aligned', 'Reach from hip', 'Move slowly', 'Do both legs']
  },
  {
    name: 'Hockey Low Agility Return-to-Ice',
    nameSv: 'Hockey lätt agility inför isfys',
    description: 'Low-intensity return-to-speed sequence for athletes reintroducing agility before heavier ice or camp work.',
    descriptionSv: 'Lågintensiv återgång till fart/agility inför tyngre isfys eller camp.',
    category: 'FOOTWORK',
    requiredEquipment: ['cones'],
    optionalEquipment: ['mini_hurdles'],
    durationSeconds: 20,
    defaultReps: 5,
    defaultSets: 2,
    restSeconds: 40,
    minDevelopmentStage: 'LEARNING_TO_TRAIN',
    maxDevelopmentStage: 'ELITE',
    primarySports: ['TEAM_ICE_HOCKEY'],
    difficultyLevel: 2,
    setupInstructions: 'Use 3-4 simple cones and optional low hurdles. Keep work submaximal and clean.',
    executionCues: ['Move at 70-85 percent', 'No pain response', 'Clean stops', 'Progress speed only if quality is high']
  }
]

const allAgilityDrills = [...agilityDrills, ...hockeyAgilityDrills]

async function main() {
  console.log('Seeding agility drills...')

  let created = 0
  let skipped = 0

  for (const drill of allAgilityDrills) {
    // Check if drill already exists
    const existing = await prisma.agilityDrill.findFirst({
      where: {
        name: drill.name,
        isSystemDrill: true
      }
    })

    if (existing) {
      console.log(`Skipping existing drill: ${drill.name}`)
      skipped++
      continue
    }

    await prisma.agilityDrill.create({
      data: {
        name: drill.name,
        nameSv: drill.nameSv,
        description: drill.description,
        descriptionSv: drill.descriptionSv,
        category: drill.category,
        requiredEquipment: drill.requiredEquipment,
        optionalEquipment: drill.optionalEquipment,
        distanceMeters: drill.distanceMeters,
        durationSeconds: drill.durationSeconds,
        defaultReps: drill.defaultReps,
        defaultSets: drill.defaultSets,
        restSeconds: drill.restSeconds,
        minDevelopmentStage: drill.minDevelopmentStage,
        maxDevelopmentStage: drill.maxDevelopmentStage,
        primarySports: drill.primarySports,
        difficultyLevel: drill.difficultyLevel,
        setupInstructions: drill.setupInstructions,
        executionCues: drill.executionCues,
        isSystemDrill: true
      }
    })

    console.log(`Created drill: ${drill.name}`)
    created++
  }

  console.log(`\nSeeding complete!`)
  console.log(`Created: ${created} drills`)
  console.log(`Skipped: ${skipped} existing drills`)
  console.log(`Total in library: ${allAgilityDrills.length}`)
  console.log(`Hockey drill pack: ${hockeyAgilityDrills.length}`)
}

main()
  .catch((e) => {
    console.error('Error seeding drills:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
