import type { Metadata } from 'next'
import { LandingHeader } from '@/components/landing/LandingHeader'
import { LandingFooter } from '@/components/landing/LandingFooter'

export const metadata: Metadata = {
  title: 'Terms of Service | Trainomics',
  description:
    'Trainomics terms of service. The agreement between you and Trainomics governing use of our training and physiological testing platform.',
}

export default function TermsOfServicePage() {
  const lastUpdated = '2026-05-06'

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <LandingHeader />

      <main className="flex-1">
        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto">
              <h1 className="text-4xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
              <p className="text-muted-foreground mb-12">Last updated: {lastUpdated}</p>

              <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
                {/* 1. Introduction */}
                <Section title="1. Introduction and Acceptance">
                  <p>
                    These Terms of Service (&quot;Terms&quot;) form a binding agreement between you (&quot;you&quot;,
                    &quot;your&quot;, or &quot;User&quot;) and Trainomics (&quot;Trainomics&quot;, &quot;we&quot;,
                    &quot;us&quot;, or &quot;our&quot;) governing your access to and use of the Trainomics platform
                    available at trainomics.app and any related services, applications, or features
                    (collectively, the &quot;Service&quot;).
                  </p>
                  <p>
                    By creating an account, accessing, or using the Service, you confirm that you have read,
                    understood, and agree to be bound by these Terms and by our{' '}
                    <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.
                    If you do not agree, do not use the Service.
                  </p>
                </Section>

                {/* 2. Definitions */}
                <Section title="2. Definitions">
                  <ul className="list-disc pl-6 space-y-1">
                    <li><strong>Athlete</strong> &mdash; A user who logs training, tests, and health data for their own performance.</li>
                    <li><strong>Coach</strong> &mdash; A user who manages athletes, prescribes programs, and reviews data.</li>
                    <li><strong>Physiotherapist</strong> &mdash; A user with the physiotherapist role who manages rehabilitation cases.</li>
                    <li><strong>Business</strong> &mdash; The organization or coaching practice a Coach or Physiotherapist operates within.</li>
                    <li><strong>Content</strong> &mdash; Any data, text, files, training plans, test results, notes, or other material uploaded to or generated within the Service.</li>
                    <li><strong>AI Output</strong> &mdash; Suggestions, programs, summaries, or insights generated by AI systems integrated into the Service.</li>
                  </ul>
                </Section>

                {/* 3. Eligibility */}
                <Section title="3. Eligibility and Account Registration">
                  <p>
                    You must be at least 16 years old to create an account. If you are under 18, you confirm
                    that a parent or legal guardian has reviewed and accepted these Terms on your behalf.
                  </p>
                  <p>
                    You agree to provide accurate, current, and complete information during registration and
                    to keep that information up to date. You are responsible for safeguarding your login
                    credentials and for all activity that occurs under your account. Notify us promptly at{' '}
                    <a href="mailto:privacy@trainomics.app" className="text-primary hover:underline">
                      privacy@trainomics.app
                    </a>{' '}
                    if you suspect unauthorized access.
                  </p>
                </Section>

                {/* 4. Description of Service */}
                <Section title="4. Description of the Service">
                  <p>
                    Trainomics provides software tools for athletes, coaches, and physiotherapists to plan
                    training, conduct physiological testing, monitor recovery, and analyze performance.
                    Features include, without limitation:
                  </p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Threshold detection and training-zone calculations</li>
                    <li>Periodized training program generation</li>
                    <li>Daily workout (WOD) recommendations and readiness scoring</li>
                    <li>Injury and rehabilitation tracking, including ACWR monitoring</li>
                    <li>Integrations with third-party services (e.g.&nbsp;Garmin, Strava, Oura, WHOOP, Concept2)</li>
                    <li>AI-assisted coaching, video analysis, and conversational features</li>
                  </ul>
                  <p>
                    The features available to you depend on your role and subscription tier and may change
                    over time as we develop the Service.
                  </p>
                </Section>

                {/* 5. Subscriptions, Trials & Billing */}
                <Section title="5. Subscriptions, Trials, and Billing">
                  <h3 className="text-lg font-semibold mt-4 mb-2">5.1 Plans</h3>
                  <p>
                    The Service is offered through a free tier and several paid subscription tiers. Each tier
                    has feature limits that are described on our pricing page and inside the application.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">5.2 Trials</h3>
                  <p>
                    We may offer free trial periods. Unless cancelled before the trial ends, the trial
                    converts into a paid subscription at the price displayed at sign-up.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">5.3 Billing and Payment</h3>
                  <p>
                    Paid subscriptions are billed in advance on a recurring basis (monthly or annually) via
                    our payment processor, Stripe. By providing payment details, you authorize recurring
                    charges to your chosen payment method until you cancel. All fees are stated in the
                    currency shown at checkout and are exclusive of applicable taxes unless stated otherwise.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">5.4 Cancellation</h3>
                  <p>
                    You may cancel your subscription at any time from your account settings or by contacting
                    support. Cancellation takes effect at the end of the current billing period; you retain
                    access until that date. Except where required by law, fees already paid are non-refundable.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">5.5 Right of Withdrawal (EU/Swedish Consumers)</h3>
                  <p>
                    If you are a consumer in the EU/EEA, you ordinarily have a 14-day right of withdrawal
                    under the Swedish Distance Contracts Act (Distansavtalslagen) for distance contracts.
                    By starting to use the Service immediately after purchase, you expressly request immediate
                    delivery and acknowledge that your right of withdrawal is forfeited once full performance
                    of the digital service has begun, in accordance with applicable consumer-protection law.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">5.6 Price Changes</h3>
                  <p>
                    We may change subscription prices. Material price increases will take effect on your next
                    renewal and will be communicated to you at least 30 days in advance. If you do not accept
                    the change, you may cancel before it takes effect.
                  </p>
                </Section>

                {/* 6. User Content */}
                <Section title="6. User Content and Data Ownership">
                  <p>
                    You retain ownership of all Content you submit, upload, or generate while using the
                    Service. You grant Trainomics a worldwide, non-exclusive, royalty-free licence to host,
                    store, copy, transmit, display, and process your Content solely for the purpose of
                    operating, securing, and improving the Service for you.
                  </p>
                  <p>
                    You are solely responsible for the accuracy, legality, and appropriateness of the Content
                    you submit. You confirm that you have the rights and consents necessary to submit any
                    third-party data (for example, athlete data uploaded by a Coach).
                  </p>
                </Section>

                {/* 7. Acceptable Use */}
                <Section title="7. Acceptable Use">
                  <p>You agree not to:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Use the Service in violation of any applicable law or regulation</li>
                    <li>Upload data of any person without their consent or lawful basis</li>
                    <li>Attempt to access, probe, or interfere with the Service&apos;s underlying infrastructure or with other users&apos; accounts</li>
                    <li>Reverse-engineer, decompile, or scrape the Service except as expressly permitted by law</li>
                    <li>Use the Service to develop or train competing products without prior written permission</li>
                    <li>Use the Service to transmit malware, spam, harassing content, or content that infringes the rights of others</li>
                    <li>Resell, sublicense, or commercially exploit the Service or its outputs except as part of your authorized coaching activities</li>
                  </ul>
                  <p>
                    We may suspend or terminate accounts that violate this section or otherwise put the
                    Service or its users at risk.
                  </p>
                </Section>

                {/* 8. Health, Training, and Medical Disclaimer */}
                <Section title="8. Health, Training, and Medical Disclaimer">
                  <p>
                    <strong>The Service is not a medical device and does not provide medical advice,
                    diagnosis, or treatment.</strong> Trainomics is a software tool intended to support
                    training and physiological testing decisions; it is not a substitute for professional
                    medical advice, examination, or care.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">8.1 Consult a Qualified Professional</h3>
                  <p>
                    Before beginning, modifying, or intensifying any training or rehabilitation program,
                    consult a qualified medical professional, especially if you have any pre-existing
                    medical condition, are pregnant, are recovering from injury or illness, or experience any
                    symptoms during exercise. Stop training and seek medical attention immediately if you
                    experience pain, dizziness, shortness of breath, or any unusual symptom.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">8.2 Assumption of Risk</h3>
                  <p>
                    Physical exercise and physiological testing carry an inherent risk of injury, illness,
                    and, in rare cases, serious harm. By using the Service you knowingly and voluntarily
                    assume those risks and accept full responsibility for your decisions to act on training,
                    test, or recovery information presented within the Service.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">8.3 Data Accuracy</h3>
                  <p>
                    Calculations such as VO2max estimates, lactate-threshold detection, training zones,
                    one-rep-max projections, ACWR, and readiness scores are based on standard sport-science
                    formulas and on data you or third-party services provide. Inputs may contain errors,
                    sensor noise, or device-specific quirks. Treat all numbers as informational guidance and
                    confirm important decisions with a qualified professional.
                  </p>

                  <h3 className="text-lg font-semibold mt-4 mb-2">8.4 Physiotherapy Features</h3>
                  <p>
                    Rehabilitation tools, pain logs, ACWR alerts, and physio-prescribed programs inside the
                    Service are intended to support, not replace, in-person assessment and care by a licensed
                    physiotherapist or physician.
                  </p>
                </Section>

                {/* 9. Coach–Athlete Relationship */}
                <Section title="9. Coach–Athlete Relationship">
                  <p>
                    Coaches and Businesses use the Service to manage their own athletes. Trainomics provides
                    the platform but is not a party to the coaching, training, or care relationship between
                    a Coach (or Business) and an Athlete. We are not responsible for the content of programs,
                    advice, messages, or decisions exchanged between users.
                  </p>
                  <p>
                    Coaches and Businesses are responsible for obtaining appropriate consents from their
                    athletes before uploading personal or health data, for compliance with any professional
                    or regulatory obligations applicable to their practice, and for the agreements they enter
                    into with their own clients.
                  </p>
                </Section>

                {/* 10. Third-Party Integrations */}
                <Section title="10. Third-Party Integrations">
                  <p>
                    The Service connects to third-party services such as Garmin, Strava, Oura, WHOOP, Concept2,
                    Stripe, and AI providers (e.g.&nbsp;Anthropic, Google, OpenAI). When you connect a
                    third-party account, your use of that service is also governed by the third party&apos;s
                    own terms and privacy policy.
                  </p>
                  <p>
                    Third-party services are operated independently. Trainomics is not responsible for the
                    availability, accuracy, content, or behaviour of any third-party service, nor for the
                    consequences of changes to their APIs. You can disconnect any integration at any time
                    from your account settings, which stops further data exchange with that provider.
                  </p>
                </Section>

                {/* 11. AI-Generated Content */}
                <Section title="11. AI-Generated Content">
                  <p>
                    Several features rely on artificial-intelligence systems to generate text, programs,
                    summaries, and other AI Output. AI Output may be inaccurate, incomplete, or outdated, and
                    may not reflect current scientific consensus. You are responsible for reviewing AI Output
                    before acting on it. AI Output is not medical, legal, or other professional advice.
                  </p>
                  <p>
                    AI providers process the inputs we send them in accordance with their own terms; we send
                    only what is necessary to deliver the requested feature.
                  </p>
                </Section>

                {/* 12. Intellectual Property */}
                <Section title="12. Intellectual Property">
                  <p>
                    The Service, including its software, design, branding, text, graphics, and underlying
                    algorithms, is owned by Trainomics and protected by intellectual-property laws. Subject to
                    your compliance with these Terms, we grant you a limited, revocable, non-transferable,
                    non-exclusive licence to access and use the Service for its intended purpose.
                  </p>
                  <p>
                    Nothing in these Terms transfers ownership of the Service to you. You may not remove
                    proprietary notices, copy substantial portions of the Service, or use our trademarks
                    without prior written permission.
                  </p>
                </Section>

                {/* 13. Privacy */}
                <Section title="13. Privacy">
                  <p>
                    Our collection and use of personal data is described in the{' '}
                    <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>, which
                    forms part of these Terms. Health and training data is special-category data under the
                    GDPR and is processed only with your explicit consent.
                  </p>
                </Section>

                {/* 14. Service Availability */}
                <Section title="14. Service Availability and Modifications">
                  <p>
                    We aim to keep the Service available, but we do not guarantee uninterrupted, error-free,
                    or secure operation. We may add, change, suspend, or remove features at any time, and we
                    may schedule maintenance windows. We will give reasonable notice of changes that
                    materially reduce the functionality you have paid for.
                  </p>
                </Section>

                {/* 15. Termination */}
                <Section title="15. Termination">
                  <p>
                    You may stop using and delete your account at any time. We may suspend or terminate your
                    access to the Service if you breach these Terms, if your use puts the Service or other
                    users at risk, if required by law, or if we discontinue the Service.
                  </p>
                  <p>
                    On termination, your right to use the Service ends immediately. Data deletion follows the
                    Data Retention section of the Privacy Policy. Sections that by their nature should
                    survive termination (including ownership, disclaimers, liability limits, and governing
                    law) will continue in force.
                  </p>
                </Section>

                {/* 16. Disclaimers */}
                <Section title="16. Disclaimers">
                  <p>
                    To the fullest extent permitted by law, the Service and AI Output are provided
                    &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind, whether
                    express, implied, or statutory, including warranties of merchantability, fitness for a
                    particular purpose, accuracy, and non-infringement. We do not warrant that the Service
                    will meet your requirements, be uninterrupted, secure, or free of errors, or that
                    calculations or recommendations will be appropriate for your individual situation.
                  </p>
                  <p>
                    Nothing in these Terms excludes or limits liability that cannot be excluded or limited
                    under mandatory applicable law, including statutory rights of consumers under Swedish
                    or EU law.
                  </p>
                </Section>

                {/* 17. Limitation of Liability */}
                <Section title="17. Limitation of Liability">
                  <p>
                    To the fullest extent permitted by law, Trainomics, its officers, employees, and
                    affiliates shall not be liable for any indirect, incidental, special, consequential, or
                    punitive damages, including loss of profits, revenue, data, goodwill, or training
                    progress, arising out of or in connection with your use of the Service, even if advised
                    of the possibility of such damages.
                  </p>
                  <p>
                    Our total aggregate liability arising out of or relating to the Service or these Terms,
                    regardless of the form of action, will not exceed the greater of (a) the fees you paid
                    to Trainomics in the twelve (12) months preceding the event giving rise to the claim, or
                    (b) one hundred euros (€100).
                  </p>
                  <p>
                    Nothing in this section limits liability for death or personal injury caused by our
                    negligence, for fraud or fraudulent misrepresentation, or for any other liability that
                    cannot be excluded or limited under mandatory applicable law.
                  </p>
                </Section>

                {/* 18. Indemnification */}
                <Section title="18. Indemnification">
                  <p>
                    You agree to defend, indemnify, and hold Trainomics harmless from and against any
                    claims, liabilities, damages, losses, and expenses (including reasonable legal fees)
                    arising out of or in any way connected with (a) your Content, (b) your use of the
                    Service in breach of these Terms, (c) your violation of any law or third-party right,
                    or (d) your provision of training, coaching, or healthcare services to others using the
                    Service.
                  </p>
                </Section>

                {/* 19. Consumer Rights */}
                <Section title="19. Consumer Rights">
                  <p>
                    If you are a consumer in Sweden or the EU/EEA, mandatory consumer-protection laws apply
                    in addition to these Terms and prevail to the extent of any conflict. Nothing in these
                    Terms restricts non-waivable statutory rights you have as a consumer.
                  </p>
                  <p>
                    EU consumers can also use the European Commission&apos;s Online Dispute Resolution
                    platform at{' '}
                    <a
                      href="https://ec.europa.eu/consumers/odr"
                      className="text-primary hover:underline"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      ec.europa.eu/consumers/odr
                    </a>.
                  </p>
                </Section>

                {/* 20. Governing Law */}
                <Section title="20. Governing Law and Jurisdiction">
                  <p>
                    These Terms are governed by the laws of Sweden, without regard to its conflict-of-laws
                    rules. Disputes arising out of or relating to these Terms or the Service shall be
                    submitted to the exclusive jurisdiction of the Swedish courts, with Stockholm District
                    Court as the court of first instance, except that consumers may bring proceedings in
                    the courts of their place of residence as required by mandatory consumer-protection law.
                  </p>
                </Section>

                {/* 21. Changes to Terms */}
                <Section title="21. Changes to These Terms">
                  <p>
                    We may update these Terms from time to time. Material changes will be communicated by
                    email or by an in-app notice at least 30 days before they take effect. Continued use of
                    the Service after the effective date constitutes acceptance of the updated Terms. The
                    &quot;Last updated&quot; date at the top of this page reflects the most recent revision.
                  </p>
                </Section>

                {/* 22. Miscellaneous */}
                <Section title="22. Miscellaneous">
                  <p>
                    These Terms, together with the Privacy Policy and any additional terms that apply to
                    specific features, constitute the entire agreement between you and Trainomics regarding
                    the Service. If any provision is held invalid or unenforceable, the remaining provisions
                    will remain in full effect. Our failure to enforce any provision is not a waiver of our
                    right to enforce it later. You may not assign these Terms without our prior written
                    consent; we may assign these Terms in connection with a merger, acquisition, or sale of
                    assets.
                  </p>
                </Section>

                {/* 23. Contact */}
                <Section title="23. Contact Us">
                  <p>
                    Questions about these Terms or the Service can be sent to:
                  </p>
                  <address className="not-italic bg-muted/50 rounded-lg p-4 text-sm">
                    Trainomics<br />
                    Email: <a href="mailto:privacy@trainomics.app" className="text-primary hover:underline">privacy@trainomics.app</a><br />
                    Website: trainomics.app
                  </address>
                </Section>
              </div>
            </div>
          </div>
        </section>
      </main>

      <LandingFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-2xl font-bold tracking-tight mb-4">{title}</h2>
      <div className="space-y-3 text-muted-foreground leading-relaxed">{children}</div>
    </section>
  )
}
