/**
 * Seed public hockey movement-library entries from the de-identified
 * off-season hockey program corpus.
 *
 * Run with:
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/seed-hockey-movement-library.ts
 */

import {
  BiomechanicalPillar,
  EquipmentType,
  MovementCategory,
  PlyometricIntensity,
  Prisma,
  PrismaClient,
  ProgressionLevel,
  RehabPhase,
  WorkoutType,
} from '@prisma/client'

const prisma = new PrismaClient()

type HockeyExerciseSeed = Prisma.ExerciseCreateInput & {
  aliases?: string[]
}

const hockeyExercises: HockeyExerciseSeed[] = [
  {
    name: '90-90 Hip Bridge',
    nameSv: '90-90 höftbrygga',
    nameEn: '90-90 Hip Bridge',
    category: WorkoutType.CORE,
    muscleGroup: 'Höft, säte, ljumske',
    biomechanicalPillar: BiomechanicalPillar.POSTERIOR_CHAIN,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Lågintensiv höft- och sätesaktivering för hockeyspelare med fokus på bäckenkontroll.',
    instructions: 'Ligg på rygg med höft och knä nära 90 grader. Pressa hälarna lätt i underlaget, lyft bäckenet kontrollerat och håll revbenen nere. Pausa i toppläget utan att svanka.',
    equipment: 'Kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.SUBACUTE, RehabPhase.REMODELING, RehabPhase.FUNCTIONAL],
    targetBodyParts: ['hip', 'groin', 'glute'],
    contraindications: ['acute hip pain', 'acute groin pain'],
    iconCategory: 'core',
    aliases: ['90/90 höftbrygga', '90-90 brygga'],
  },
  {
    name: 'Bench Bird Dog Hip Extension',
    nameSv: 'Hunden på bänk',
    nameEn: 'Bench Bird Dog Hip Extension',
    category: WorkoutType.CORE,
    muscleGroup: 'Höft, bål, säte',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Bål- och höftstabilitet med liten belastning, användbar före tyngre underkroppsarbete.',
    instructions: 'Stå med knä eller underben på bänk. Håll bäckenet stilla, sträck ett ben bakåt och pausa utan att rotera höften. Byt sida med samma kontroll.',
    equipment: 'Bänk',
    equipmentTypes: [EquipmentType.BODYWEIGHT, EquipmentType.BOX],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.SUBACUTE, RehabPhase.REMODELING, RehabPhase.FUNCTIONAL],
    targetBodyParts: ['trunk', 'hip', 'glute'],
    contraindications: ['acute lumbar pain'],
    iconCategory: 'core',
    aliases: ['Hunden pa bank', 'bench dog', 'hund på bänk'],
  },
  {
    name: 'Bomben Step 1',
    nameSv: 'Bomben steg 1',
    nameEn: 'Bomben Step 1',
    category: WorkoutType.CORE,
    muscleGroup: 'Ljumske, höft, bål',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Kontrollerad hockeyprehab för ljumske och höft där position och långsam kontroll prioriteras före belastning.',
    instructions: 'Arbeta långsamt i den förutbestämda positionen. Håll bäckenet plant, skapa lätt tryck genom stödbenet och avbryt om ljumsken smärtar mer än lätt obehag.',
    equipment: 'Kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.SUBACUTE, RehabPhase.REMODELING],
    targetBodyParts: ['groin', 'hip', 'adductor'],
    contraindications: ['acute groin strain', 'pain above 3/10'],
    iconCategory: 'core',
    aliases: ['Bomben', 'Bomben 1'],
  },
  {
    name: 'Single-Leg RDL 3-Point Rotation',
    nameSv: 'Draken med 3-punktsrotation',
    nameEn: 'Single-Leg RDL 3-Point Rotation',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Höft, hamstrings, fotled, bål',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Enbens höftfällning med rotationskontroll för skridskoposition, balans och höftstabilitet.',
    instructions: 'Stå på ett ben och fäll i höften. Nå mot tre punkter framför kroppen utan att knät faller in. Håll höften parallell och återgå kontrollerat.',
    equipment: 'Kroppsvikt eller hantel',
    equipmentTypes: [EquipmentType.BODYWEIGHT, EquipmentType.DUMBBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['hamstring', 'hip', 'ankle', 'trunk'],
    contraindications: ['acute hamstring pain', 'poor single-leg balance'],
    iconCategory: 'strength',
    aliases: ['Draken 3 punkt', '3-punktsdraken'],
  },
  {
    name: 'Two-Step Side Lift',
    nameSv: 'Sidlyft 2-steg',
    nameEn: 'Two-Step Side Lift',
    category: WorkoutType.CORE,
    muscleGroup: 'Sidobål, höft, ljumske',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Sidobåls- och höftkontroll som passar i prehabdelen före is- eller gympass.',
    instructions: 'Ligg på sidan och bygg upp positionen i två steg: först kort hävarm, sedan längre hävarm. Håll kroppen rak och undvik rotation framåt.',
    equipment: 'Kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.REMODELING, RehabPhase.FUNCTIONAL],
    targetBodyParts: ['trunk', 'hip', 'groin'],
    contraindications: ['shoulder pain in side support'],
    iconCategory: 'core',
    aliases: ['Sidolyft två steg', 'side lift 2 step'],
  },
  {
    name: 'Copenhagen Plank',
    nameSv: 'Copenhagen plank',
    nameEn: 'Copenhagen Plank',
    category: WorkoutType.CORE,
    muscleGroup: 'Ljumske, adduktorer, sidobål',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Adduktorstyrka och sidobålsstabilitet för att tåla skridskoskär och riktningsförändringar.',
    instructions: 'Placera övre benet på bänk och lyft kroppen till en rak sidoplanka. Börja med böjt knä och kort hålltid. Öka hävarm eller tid när smärtfritt.',
    equipment: 'Bänk',
    equipmentTypes: [EquipmentType.BODYWEIGHT, EquipmentType.BOX],
    difficulty: 'Intermediate',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.REMODELING, RehabPhase.FUNCTIONAL, RehabPhase.RETURN_TO_SPORT],
    targetBodyParts: ['adductor', 'groin', 'trunk'],
    contraindications: ['acute adductor strain', 'pain above 3/10'],
    iconCategory: 'core',
    aliases: ['Köpenhamnsplanka', 'Copenhagen adductor'],
  },
  {
    name: 'Dead Bug with Lateral Band',
    nameSv: 'Dead bug med sidoband',
    nameEn: 'Dead Bug with Lateral Band',
    category: WorkoutType.CORE,
    muscleGroup: 'Bål, höftböjare, skulderstabilitet',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Anti-extension och anti-rotation med banddrag från sidan.',
    instructions: 'Fäst ett band från sidan. Håll bandet över bröstet, pressa ländryggen lätt mot golvet och sänk motsatt arm/ben långsamt utan att tappa bäckenposition.',
    equipment: 'Gummiband',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Beginner',
    isPublic: true,
    targetBodyParts: ['trunk', 'hip flexor', 'shoulder'],
    iconCategory: 'core',
    aliases: ['Deadbug sidoband', 'lateral band dead bug'],
  },
  {
    name: 'Bear Crawl Kettlebell Drag',
    nameSv: 'Bear crawl KB-drag',
    nameEn: 'Bear Crawl Kettlebell Drag',
    category: WorkoutType.CORE,
    muscleGroup: 'Bål, axlar, höft',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Anti-rotation under krypposition, bra för kontaktstyrka och bålstabilitet.',
    instructions: 'Stå i bear-position med knäna nära golvet. Dra kettlebellen långsamt under kroppen utan att vrida bäckenet eller flytta fötterna.',
    equipment: 'Kettlebell',
    equipmentTypes: [EquipmentType.KETTLEBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['trunk', 'shoulder', 'hip'],
    contraindications: ['wrist pain', 'shoulder pain under load'],
    iconCategory: 'core',
    aliases: ['KB drag bear crawl', 'björngång kettlebell drag'],
  },
  {
    name: 'Barbell Rollout',
    nameSv: 'Rollout med stång',
    nameEn: 'Barbell Rollout',
    category: WorkoutType.CORE,
    muscleGroup: 'Bål, skuldror',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Anti-extension för bål och skuldror, ofta använd i hockeyns styrke- och prehabblock.',
    instructions: 'Starta på knä med stången under axlarna. Rulla fram bara så långt du kan hålla revbenen nere och bäckenet stabilt. Dra tillbaka utan att svanka.',
    equipment: 'Skivstång',
    equipmentTypes: [EquipmentType.BARBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['trunk', 'shoulder'],
    contraindications: ['acute low back pain', 'shoulder impingement'],
    iconCategory: 'core',
    aliases: ['Stångrollout', 'rollout stång'],
  },
  {
    name: 'Shoulder Internal External Rotation',
    nameSv: 'Liggande in- och utrotation axel',
    nameEn: 'Shoulder Internal External Rotation',
    category: WorkoutType.WARMUP,
    muscleGroup: 'Rotatorkuff, skuldra',
    biomechanicalPillar: BiomechanicalPillar.UPPER_BODY,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Lågdos rotatorkuffarbete för skott, närkamper och tung överkroppsträning.',
    instructions: 'Ligg eller stå stabilt med armbågen fixerad. Rotera kontrollerat inåt och utåt med lätt vikt eller band. Håll skulderbladet lugnt.',
    equipment: 'Miniband eller lätt hantel',
    equipmentTypes: [EquipmentType.BODYWEIGHT, EquipmentType.DUMBBELL],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.SUBACUTE, RehabPhase.REMODELING, RehabPhase.FUNCTIONAL],
    targetBodyParts: ['shoulder', 'rotator cuff'],
    contraindications: ['acute shoulder pain'],
    iconCategory: 'strength',
    aliases: ['Axel in ut rotation', 'rotatorkuff rotation'],
  },
  {
    name: 'Band Pull-Apart to External Rotation',
    nameSv: 'Band pull-apart till utrotation',
    nameEn: 'Band Pull-Apart to External Rotation',
    category: WorkoutType.WARMUP,
    muscleGroup: 'Övre rygg, rotatorkuff, skuldra',
    biomechanicalPillar: BiomechanicalPillar.UPPER_BODY,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Skulderaktivering före pressar, rodd och kontaktarbete.',
    instructions: 'Dra bandet isär med raka armar, böj sedan armbågarna och rotera utåt. Håll revbenen nere och skuldrorna låga.',
    equipment: 'Gummiband',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Beginner',
    isPublic: true,
    targetBodyParts: ['shoulder', 'upper back'],
    iconCategory: 'strength',
    aliases: ['Pull apart utrotation', 'band external rotation pull apart'],
  },
  {
    name: 'Single-Leg Calf Raise Iso Hold',
    nameSv: 'Enbens tåhävning isohåll',
    nameEn: 'Single-Leg Calf Raise Iso Hold',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Vad, fot, fotled',
    biomechanicalPillar: BiomechanicalPillar.FOOT_ANKLE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Isometrisk fot- och vadstyrka för acceleration, riktningsförändring och skridskostyvhet.',
    instructions: 'Stå på ett ben och pressa upp till tå. Håll toppläget med rak fotled, tung stortåkontakt och kontrollerat bäcken.',
    equipment: 'Kroppsvikt eller hantel',
    equipmentTypes: [EquipmentType.BODYWEIGHT, EquipmentType.DUMBBELL],
    difficulty: 'Beginner',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.REMODELING, RehabPhase.FUNCTIONAL, RehabPhase.RETURN_TO_SPORT],
    targetBodyParts: ['calf', 'ankle', 'foot'],
    contraindications: ['acute achilles pain'],
    iconCategory: 'strength',
    aliases: ['Tåhävning iso', 'calf iso hold'],
  },
  {
    name: 'Kbox Bilateral Squat',
    nameSv: 'Kbox bilateral knäböj',
    nameEn: 'Kbox Bilateral Squat',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Quadriceps, säte',
    biomechanicalPillar: BiomechanicalPillar.KNEE_DOMINANCE,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Flywheel-knäböj för styrka och excentrisk kontroll i hockeyns underkroppsblock.',
    instructions: 'Stå stabilt på Kbox-plattan. Sänk kontrollerat, vänd kraftfullt och bromsa excentriskt utan att knäna faller in.',
    equipment: 'Kbox / flywheel',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['quadriceps', 'glute', 'knee'],
    contraindications: ['uncontrolled knee pain'],
    iconCategory: 'strength',
    aliases: ['Kbox knäböj', 'Flywheel squat'],
  },
  {
    name: 'Kbox Unilateral Squat',
    nameSv: 'Kbox unilateral knäböj',
    nameEn: 'Kbox Unilateral Squat',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Quadriceps, säte, höft',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Unilateral flywheel-styrka för skridskospecifik kraft och sidobalans.',
    instructions: 'Använd en split- eller enbensposition. Håll knät över foten, bromsa excentriskt och tryck upp med kontrollerad höftlinje.',
    equipment: 'Kbox / flywheel',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Advanced',
    isPublic: true,
    targetBodyParts: ['quadriceps', 'glute', 'hip', 'knee'],
    contraindications: ['uncontrolled knee valgus', 'acute knee pain'],
    iconCategory: 'strength',
    aliases: ['Kbox enbensknäböj', 'Flywheel unilateral squat'],
  },
  {
    name: 'Kbox Iso Squat Hold',
    nameSv: 'Kbox ISO-håll knäböj',
    nameEn: 'Kbox Iso Squat Hold',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Quadriceps, säte, bål',
    biomechanicalPillar: BiomechanicalPillar.KNEE_DOMINANCE,
    progressionLevel: ProgressionLevel.LEVEL_1,
    description: 'Isometriskt håll i hockeyrelevant knävinkel, ofta som kontroll- eller kapacitetsblock.',
    instructions: 'Sänk till ordinerad knävinkel och håll positionen. Håll hela foten i kontakt, aktiv bål och jämnt tryck genom båda benen.',
    equipment: 'Kbox / flywheel eller kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['quadriceps', 'knee', 'glute'],
    iconCategory: 'strength',
    aliases: ['Kbox isohåll', 'Flywheel squat iso'],
  },
  {
    name: 'Flywheel Lateral Squat',
    nameSv: 'Flywheel sidoknäböj',
    nameEn: 'Flywheel Lateral Squat',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Adduktorer, säte, quadriceps',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Sidoplanstyrka och excentrisk broms för skridskoskär och riktningsförändring.',
    instructions: 'Kliva ut i sidoknäböj mot flywheel-linan. Håll höften bak, knät stabilt och bromsa vägen tillbaka med kontroll.',
    equipment: 'Flywheel',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Advanced',
    isPublic: true,
    targetBodyParts: ['adductor', 'glute', 'quadriceps'],
    contraindications: ['acute groin strain'],
    iconCategory: 'strength',
    aliases: ['Kbox sidoknäböj', 'lateral flywheel squat'],
  },
  {
    name: 'Landmine Lateral Squat',
    nameSv: 'Landmine sidoknäböj',
    nameEn: 'Landmine Lateral Squat',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Adduktorer, säte, quadriceps',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Lateral underkroppsstyrka med guidat redskap för hockeyspelare.',
    instructions: 'Håll landmine i brösthöjd, kliv ut åt sidan och sitt bak i höften. Tryck tillbaka explosivt utan att tappa fot- och knälinje.',
    equipment: 'Skivstång landmine',
    equipmentTypes: [EquipmentType.BARBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['adductor', 'glute', 'quadriceps'],
    contraindications: ['acute groin pain'],
    iconCategory: 'strength',
    aliases: ['Landmine lateral squat', 'sidoknäböj landmine'],
  },
  {
    name: 'Landmine Skate Squat',
    nameSv: 'Landmine skate squat',
    nameEn: 'Landmine Skate Squat',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Quadriceps, säte, höft',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Assisterad enbensstyrka med skridskolik knä- och höftkontroll.',
    instructions: 'Håll landmine som motvikt. Sänk på ett ben med fria benet bakom kroppen. Håll bäckenet stabilt och tryck upp genom hela foten.',
    equipment: 'Skivstång landmine',
    equipmentTypes: [EquipmentType.BARBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['quadriceps', 'glute', 'hip'],
    contraindications: ['acute knee pain', 'uncontrolled knee valgus'],
    iconCategory: 'strength',
    aliases: ['Skate squat landmine', 'skridskoknäböj landmine'],
  },
  {
    name: 'Kickstand Romanian Deadlift',
    nameSv: 'Kickstand RDL',
    nameEn: 'Kickstand Romanian Deadlift',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Hamstrings, säte, höft',
    biomechanicalPillar: BiomechanicalPillar.POSTERIOR_CHAIN,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Bakre kedjan med liten stödfot, bra mellan bilateral RDL och full enbens-RDL.',
    instructions: 'Placera stödfoten lätt bakom arbetsbenet. Fäll i höften, håll ryggen neutral och låt bakre benet bara hjälpa balansen.',
    equipment: 'Hantlar eller skivstång',
    equipmentTypes: [EquipmentType.DUMBBELL, EquipmentType.BARBELL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['hamstring', 'glute', 'hip'],
    contraindications: ['acute hamstring strain'],
    iconCategory: 'strength',
    aliases: ['B-stance RDL', 'kickstand marklyft'],
  },
  {
    name: 'Slider Hamstring Curl',
    nameSv: 'Hamstring curl med glid',
    nameEn: 'Slider Hamstring Curl',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Hamstrings, säte',
    biomechanicalPillar: BiomechanicalPillar.POSTERIOR_CHAIN,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Hamstringstyrka och höftkontroll med glidplattor eller Flowin.',
    instructions: 'Ligg på rygg med hälarna på glidplattor. Lyft höften och dra hälarna in mot kroppen utan att tappa höftlinjen.',
    equipment: 'Glidplattor / Flowin',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Intermediate',
    isPublic: true,
    isRehabExercise: true,
    rehabPhases: [RehabPhase.REMODELING, RehabPhase.FUNCTIONAL, RehabPhase.RETURN_TO_SPORT],
    targetBodyParts: ['hamstring', 'glute'],
    contraindications: ['acute hamstring strain'],
    iconCategory: 'strength',
    aliases: ['Flowin hamstring curl', 'hamstringcurl glid'],
  },
  {
    name: 'Heavy Sled Acceleration',
    nameSv: 'Tung släde acceleration',
    nameEn: 'Heavy Sled Acceleration',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Höft, quadriceps, vad',
    biomechanicalPillar: BiomechanicalPillar.KNEE_DOMINANCE,
    progressionLevel: ProgressionLevel.LEVEL_3,
    description: 'Kort acceleration med tung släde för första skär, startstyrka och horisontell kraft.',
    instructions: 'Luta kroppen framåt med stabil bål. Driv kraftfullt med korta steg och full fotkontakt. Håll kvaliteten hög, vila generöst.',
    equipment: 'Släde',
    equipmentTypes: [EquipmentType.SLED],
    difficulty: 'Advanced',
    isPublic: true,
    isHybridMovement: true,
    movementCategory: MovementCategory.STRONGMAN,
    targetBodyParts: ['hip', 'quadriceps', 'calf'],
    contraindications: ['acute achilles pain', 'acute knee pain'],
    iconCategory: 'strength',
    aliases: ['Sled acceleration', 'tung släde sprint'],
  },
  {
    name: 'Sled Push March',
    nameSv: 'Släde push march',
    nameEn: 'Sled Push March',
    category: WorkoutType.STRENGTH,
    muscleGroup: 'Höft, quadriceps, bål',
    biomechanicalPillar: BiomechanicalPillar.KNEE_DOMINANCE,
    progressionLevel: ProgressionLevel.LEVEL_2,
    description: 'Kontrollerad slädgång för accelerationsteknik, bålposition och underkroppskapacitet.',
    instructions: 'Håll raka armar och stark bål. Marschera med tydlig knädrive och jämnt tryck genom marken. Stoppa innan tekniken faller.',
    equipment: 'Släde',
    equipmentTypes: [EquipmentType.SLED],
    difficulty: 'Intermediate',
    isPublic: true,
    isHybridMovement: true,
    movementCategory: MovementCategory.STRONGMAN,
    targetBodyParts: ['hip', 'quadriceps', 'trunk'],
    iconCategory: 'strength',
    aliases: ['Sled march', 'slädmarsch'],
  },
  {
    name: 'Rotational Medicine Ball Throw',
    nameSv: 'Rotationskast med medicinboll',
    nameEn: 'Rotational Medicine Ball Throw',
    category: WorkoutType.PLYOMETRIC,
    muscleGroup: 'Bål, höft, överkropp',
    biomechanicalPillar: BiomechanicalPillar.ANTI_ROTATION_CORE,
    progressionLevel: ProgressionLevel.LEVEL_3,
    plyometricIntensity: PlyometricIntensity.MODERATE,
    description: 'Rotationspower för skott, tacklingar och riktningsförändring.',
    instructions: 'Stå atletiskt med bollen vid höften. Rotera genom höft och bål, kasta explosivt mot vägg eller partner och fånga kontrollerat.',
    equipment: 'Medicinboll',
    equipmentTypes: [EquipmentType.MEDICINE_BALL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['trunk', 'hip', 'shoulder'],
    contraindications: ['acute back pain', 'acute shoulder pain'],
    iconCategory: 'plyometric',
    aliases: ['MB rotational throw', 'medicinboll rotationskast'],
  },
  {
    name: 'Medicine Ball Chest Pass',
    nameSv: 'Medicinboll bröstpass',
    nameEn: 'Medicine Ball Chest Pass',
    category: WorkoutType.PLYOMETRIC,
    muscleGroup: 'Bröst, triceps, skuldra, bål',
    biomechanicalPillar: BiomechanicalPillar.UPPER_BODY,
    progressionLevel: ProgressionLevel.LEVEL_3,
    plyometricIntensity: PlyometricIntensity.MODERATE,
    description: 'Överkroppspower med låg teknisk tröskel.',
    instructions: 'Håll bollen vid bröstet, spänn bålen och kasta explosivt rakt fram. Fånga eller låt bollen studsa tillbaka med bra hållning.',
    equipment: 'Medicinboll',
    equipmentTypes: [EquipmentType.MEDICINE_BALL],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['chest', 'shoulder', 'trunk'],
    contraindications: ['acute shoulder pain'],
    iconCategory: 'plyometric',
    aliases: ['MB chest pass', 'bröstkast medicinboll'],
  },
  {
    name: 'Skater Jump Stick',
    nameSv: 'Skater jump med stopp',
    nameEn: 'Skater Jump Stick',
    category: WorkoutType.PLYOMETRIC,
    muscleGroup: 'Höft, fotled, quadriceps',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_2,
    plyometricIntensity: PlyometricIntensity.MODERATE,
    contactsPerRep: 1,
    description: 'Lateral power med landningskontroll för skridskolik kraft.',
    instructions: 'Hoppa i sidled från ett ben till det andra. Landa tyst, håll knä över fot och pausa två sekunder innan nästa repetition.',
    equipment: 'Kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Intermediate',
    isPublic: true,
    targetBodyParts: ['hip', 'knee', 'ankle'],
    contraindications: ['acute knee pain', 'uncontrolled landing mechanics'],
    iconCategory: 'plyometric',
    aliases: ['Skater hopp stopp', 'lateral bound stick'],
  },
  {
    name: 'Seated Box Jump',
    nameSv: 'Sittande lådhopp',
    nameEn: 'Seated Box Jump',
    category: WorkoutType.PLYOMETRIC,
    muscleGroup: 'Höft, quadriceps, vad',
    biomechanicalPillar: BiomechanicalPillar.KNEE_DOMINANCE,
    progressionLevel: ProgressionLevel.LEVEL_3,
    plyometricIntensity: PlyometricIntensity.HIGH,
    contactsPerRep: 1,
    description: 'Startpower från statisk position, användbar för acceleration och explosivitet.',
    instructions: 'Sitt på bänk eller box. Starta utan gung, hoppa explosivt upp på boxen och landa stabilt. Kliv ner kontrollerat.',
    equipment: 'Box eller bänk',
    equipmentTypes: [EquipmentType.BOX],
    difficulty: 'Advanced',
    isPublic: true,
    targetBodyParts: ['hip', 'quadriceps', 'calf'],
    contraindications: ['poor landing control', 'acute knee pain'],
    iconCategory: 'plyometric',
    aliases: ['Sittande box jump', 'seated jump to box'],
  },
  {
    name: 'Lateral Bound Continuous',
    nameSv: 'Lateral bound kontinuerlig',
    nameEn: 'Lateral Bound Continuous',
    category: WorkoutType.PLYOMETRIC,
    muscleGroup: 'Höft, fotled, quadriceps',
    biomechanicalPillar: BiomechanicalPillar.UNILATERAL,
    progressionLevel: ProgressionLevel.LEVEL_3,
    plyometricIntensity: PlyometricIntensity.HIGH,
    contactsPerRep: 1,
    description: 'Reaktiv lateral power när landningskontrollen redan är stabil.',
    instructions: 'Hoppa rytmiskt från sida till sida med kort markkontakt. Håll bäckenet stabilt och stoppa serien om landningen tappar kvalitet.',
    equipment: 'Kroppsvikt',
    equipmentTypes: [EquipmentType.BODYWEIGHT],
    difficulty: 'Advanced',
    isPublic: true,
    targetBodyParts: ['hip', 'ankle', 'knee'],
    contraindications: ['acute knee pain', 'poor landing control'],
    iconCategory: 'plyometric',
    aliases: ['Kontinuerliga skater jumps', 'continuous lateral bounds'],
  },
]

async function seedAlias(alias: string, exerciseId: string) {
  const existing = await prisma.exerciseNameAlias.findFirst({
    where: { coachId: null, alias },
    select: { id: true },
  })

  if (existing) return false

  await prisma.exerciseNameAlias.create({
    data: {
      coachId: null,
      alias,
      exerciseId,
      createdBy: 'system:hockey-movement-library',
    },
  })

  return true
}

async function main() {
  let created = 0
  let updated = 0
  let aliasesCreated = 0

  for (const { aliases = [], ...exercise } of hockeyExercises) {
    const existing = await prisma.exercise.findFirst({
      where: {
        coachId: null,
        OR: [
          { name: exercise.name },
          { nameSv: exercise.nameSv ?? exercise.name },
          { nameEn: exercise.nameEn ?? exercise.name },
        ],
      },
      select: { id: true },
    })

    const saved = existing
      ? await prisma.exercise.update({
          where: { id: existing.id },
          data: exercise,
        })
      : await prisma.exercise.create({
          data: exercise,
        })

    if (existing) updated++
    else created++

    for (const alias of aliases) {
      if (await seedAlias(alias, saved.id)) aliasesCreated++
    }
  }

  console.log('Hockey movement library seeded.')
  console.log(`Created: ${created}`)
  console.log(`Updated: ${updated}`)
  console.log(`Aliases created: ${aliasesCreated}`)
}

main()
  .catch((error) => {
    console.error('Failed to seed hockey movement library:', error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
