// Bilingual UI copy for the floating AI chat. Keep en/sv keys in sync.

export type AppLocale = 'en' | 'sv'

export const FLOATING_CHAT_COPY = {
  en: {
    assistant: 'AI assistant',
    browserVoice: 'Using the browser voice.',
    generatingVoice: 'Creating AI voice...',
    playingVoice: 'Playing AI voice...',
    spokenRepliesUnavailable: 'Voice replies could not be played in this browser.',
    spokenRepliesUnsupported: 'Voice replies are not supported in this browser.',
    modernBrowser: 'Try a modern version of Safari, Chrome, or Edge.',
    voiceOperatorNeedsSpeech: 'Voice operator mode needs voice replies, but this browser does not support speech playback.',
    voiceOperatorCannotStart: 'Voice operator cannot start',
    voiceOperatorActiveNotice: 'Voice operator mode is active. I listen through the microphone, send after a short pause, and speak my replies out loud. Actions that send or change anything still require confirmation.',
    voiceOperatorActiveTitle: 'Voice operator active',
    voiceOperatorActiveDescription: 'Voice replies and automatic voice sending are on.',
    voiceOperatorOffNotice: 'Voice operator mode is off. You can still use the microphone manually.',
    voiceOperatorOffTitle: 'Voice operator off',
    voiceOperatorOffDescription: 'Voice settings can still be controlled separately.',
    liveVoiceUnsupported: 'Live voice is not supported in this browser.',
    missingMicrophone: 'I cannot start live voice because microphone access is missing.',
    missingMicrophoneTitle: 'Microphone missing',
    allowMicrophone: 'Allow microphone access and try again.',
    startingLiveVoice: 'Starting live voice...',
    liveVoiceActiveConfirm: 'Live voice active. Actions still require confirmation in chat.',
    liveVoiceDisconnected: 'Live voice is disconnected.',
    liveVoiceListening: 'Live voice is listening.',
    liveVoiceUnknownError: 'Live voice received an unknown error.',
    liveVoiceCouldNotContinue: (message: string) => `Live voice could not continue: ${message}`,
    liveVoiceAnswered: 'Live voice answered.',
    liveVoiceListeningEllipsis: 'Live voice listening...',
    processingLiveVoice: 'Processing live voice...',
    webRtcOfferFailed: 'Could not create WebRTC offer.',
    openAiLiveVoiceFailed: 'Could not start OpenAI live voice.',
    connectingLiveVoice: 'Connecting live voice...',
    liveVoiceStartFailed: 'Could not start live voice.',
    liveVoiceStartNotice: (message: string) => `I could not start live voice: ${message}`,
    liveVoiceStartToastTitle: 'Live voice could not start',
    liveVoiceOff: 'Live voice is off.',
    requestFailedNotice: (message: string) => `I could not complete the request: ${message}`,
    sendErrorTitle: 'Could not send message',
    noAthleteTitle: 'No athlete selected',
    noAthleteDescription: 'Select an athlete to save the program.',
    programSavedTitle: 'Program saved!',
    programSavedDescription: (name: string) => `"${name}" has been saved.`,
    saveProgramErrorTitle: 'Could not save program',
    tryAgainLater: 'Try again later.',
    saveErrorTitle: 'Save failed',
    unexpectedError: 'An unexpected error occurred.',
    modelLoadingNotice: 'I cannot send right now because the AI model is still loading. Wait a few seconds and try again.',
    transcribeError: 'Could not transcribe the voice message.',
    noSpeechHeard: 'I did not hear anything clear in the voice message.',
    voiceInputUnsupported: 'Voice input is not supported in this browser.',
    noMicrophoneAudio: 'I did not receive any audio data from the microphone.',
    voiceTranscribedTitle: 'Voice transcribed',
    voiceAutoSendDescription: 'I will send the message automatically in a moment.',
    voicePlacedDescription: 'The text is in the message field.',
    voiceHandlingError: 'Could not handle the voice message.',
    voiceUseErrorNotice: (message: string) => `I could not use the voice message: ${message}`,
    voiceUseErrorTitle: 'Could not use voice',
    contextAthlete: (name: string) => `Athlete: ${name}`,
    athleteContext: 'Athlete context',
    programContext: 'Program context',
    testContext: 'Test context',
    videoContextTotal: (total?: number, done?: number) => `**Total**: ${total} video analyses (${done} complete)`,
    athletePseudonym: 'Athlete',
    type: 'Type',
    status: 'Status',
    score: 'Score',
    issues: 'Issues',
    recommendations: 'Recommendations',
    exercise: 'Exercise',
    identifiedIssues: 'Identified issues',
    poseAnalysis: 'MediaPipe pose analysis',
    aiScore: 'AI score',
    interpretation: 'Interpretation',
    technicalFeedback: 'Technical feedback',
    patterns: 'Patterns',
    overallAssessment: 'Overall assessment',
    currentPageContext: (title: string) => `\n\n## CURRENT PAGE CONTEXT: ${title}\n`,
    newConversation: 'New conversation',
    chatHistory: 'Chat history',
    loadConversationErrorTitle: 'Could not load conversation',
    selectAthlete: 'Select athlete',
    searchAthletes: 'Search athletes...',
    noAthletesFound: 'No athletes found',
    clearAthleteContext: 'Chat without athlete context',
    athletesLoadError: 'Could not load athletes',
    minimizeChat: 'Minimize chat',
    expandChat: 'Expand chat',
    closeChat: 'Close chat',
    sideContext: 'Page context',
    active: 'Active',
    inactive: 'Inactive',
    consentMissing: 'Athlete consent is missing - the AI chat cannot use athlete data',
    voiceOperatorBanner: 'Voice operator active: microphone, auto-send, and voice replies are on',
    confirmsActions: 'Confirms actions',
    stop: 'Stop',
    howCanIHelp: 'How can I help?',
    hasContext: (title: string) => `I have access to ${title.toLowerCase()}. Ask me anything about it.`,
    contextDisabled: 'Context is disabled. Click the button above to enable it.',
    defaultEmpty: 'Ask me about training programs, test analyses, or other questions about your athletes.',
    whatCanYouDo: 'What can you do?',
    operatorActive: 'Dashboard operator mode is active.',
    explainIssues: 'Explain issues',
    explainIssuesPrompt: 'Explain the most important issues in the analysis',
    improvementExercises: 'Improvement exercises',
    improvementExercisesPrompt: 'Give me specific exercises to improve technique',
    simpleSummary: 'Simple summary',
    simpleSummaryPrompt: 'Summarize the analysis in simple terms for the athlete',
    operatorBrief: 'Operator brief',
    weeklySummary: 'Weekly summary',
    operatorBriefPrompt: 'Create a proactive coach-operator brief from the dashboard work queue. Prioritize risks, feedback, pending test approvals, and the next app view to open.',
    weeklySummaryPrompt: 'Create a short proactive weekly summary from the coach dashboard operator mode and highlight what I should monitor next.',
    summarize: 'Summarize',
    summarizeDashboardPrompt: 'Summarize the coach dashboard from the page context and prioritize the three most important next steps.',
    whatNeedsAction: 'What needs action?',
    whatNeedsActionPrompt: 'What needs action on this dashboard right now? Separate urgent signals from things to follow up later.',
    explainCards: 'Explain cards',
    explainCardsPrompt: 'Explain the cards and signals on the dashboard so I quickly know how to read the page.',
    teamCaptureGuide: 'Team cardio setup',
    teamCaptureGuidePrompt: 'Explain how this Team cardio setup should work with Garmin, Concept2 PM5, station receivers, Bluetooth limits, and post-session Workout Evaluation.',
    teamStrengthGuide: 'Team strength setup',
    teamStrengthGuidePrompt: 'Explain how this Team strength screen works for shared strength logging, player switching, assigned workouts, set logging, and completion status.',
    summarizePage: 'Summarize page',
    summarizePagePrompt: 'Summarize this page and highlight what I should look at first.',
    nextSteps: 'Next steps',
    nextStepsPrompt: 'Suggest concrete next steps based on the page context.',
    explainConcepts: 'Explain concepts',
    explainConceptsPrompt: 'Explain the most important concepts on this page briefly and practically.',
    analyzeTrainingPrompt: (name: string) => `Analyze ${name}'s training history`,
    analyzeTraining: 'Analyze training',
    createProgramPrompt: (name: string) => `Create a training program for ${name}`,
    createProgram: 'Create program',
    tenKPrompt: 'How do I create an effective 10K program?',
    thresholdPrompt: 'Explain threshold training and zones',
    trainingZones: 'Training zones',
    recording: (duration: string) => `Recording ${duration}`,
    transcribingVoiceMessage: 'Transcribing voice message...',
    stopRecording: 'Stop recording',
    transcribingVoice: 'Transcribing voice',
    startVoiceInput: 'Start voice input',
    turnOffSpokenReplies: 'Turn off voice replies',
    turnOnSpokenReplies: 'Turn on voice replies',
    turnOffAutoSend: 'Turn off automatic voice sending',
    turnOnAutoSend: 'Turn on automatic voice sending',
    turnOffVoiceOperator: 'Turn off voice operator',
    turnOnVoiceOperator: 'Turn on voice operator',
    turnOffLiveVoice: 'Turn off live voice',
    startLiveVoice: 'Start live voice',
    apiKeyMissingTitle: 'API key missing',
    athleteAssistantUnavailable: 'AI assistant unavailable',
    athleteAssistantUnavailableDescription: 'Your coach has not activated the AI assistant yet. Contact your coach to enable this feature.',
    configureApiKeyDescription: 'Configure your API key (Anthropic or Google) to use the AI assistant.',
    goToSettings: 'Go to settings',
    weeks: 'weeks',
    chooseAthleteToSave: 'Select an athlete to save',
    saveProgram: 'Save program',
    inputPlaceholder: 'Write a message...',
    voiceAutoSendSoon: 'Sending the voice message soon...',
    cancel: 'Cancel',
    readingReply: 'Reading the reply...',
    aiVoiceGenerated: 'The voice is AI-generated.',
  },
  sv: {
    assistant: 'AI-assistent',
    browserVoice: 'Använder webbläsarens röst.',
    generatingVoice: 'Skapar AI-röst...',
    playingVoice: 'Spelar AI-röst...',
    spokenRepliesUnavailable: 'Röstsvar kunde inte spelas i den här webbläsaren.',
    spokenRepliesUnsupported: 'Röstsvar stöds inte i den här webbläsaren.',
    modernBrowser: 'Testa en modern version av Safari, Chrome eller Edge.',
    voiceOperatorNeedsSpeech: 'Voice operator-läget behöver röstsvar, men den här webbläsaren stödjer inte uppläsning.',
    voiceOperatorCannotStart: 'Voice operator kan inte startas',
    voiceOperatorActiveNotice: 'Voice operator-läget är aktivt. Jag lyssnar via mikrofonen, skickar efter en kort paus och säger mina svar högt. Åtgärder som skickar eller ändrar något kräver fortfarande bekräftelse.',
    voiceOperatorActiveTitle: 'Voice operator aktiv',
    voiceOperatorActiveDescription: 'Röstsvar och automatisk röstsändning är på.',
    voiceOperatorOffNotice: 'Voice operator-läget är avstängt. Du kan fortfarande använda mikrofonen manuellt.',
    voiceOperatorOffTitle: 'Voice operator avstängd',
    voiceOperatorOffDescription: 'Röstinställningarna kan fortfarande styras separat.',
    liveVoiceUnsupported: 'Live voice stöds inte i den här webbläsaren.',
    missingMicrophone: 'Jag kan inte starta live voice eftersom mikrofonåtkomst saknas.',
    missingMicrophoneTitle: 'Mikrofon saknas',
    allowMicrophone: 'Tillåt mikrofonåtkomst och försök igen.',
    startingLiveVoice: 'Startar live voice...',
    liveVoiceActiveConfirm: 'Live voice aktiv. Åtgärder kräver fortsatt bekräftelse i chatten.',
    liveVoiceDisconnected: 'Live voice är frånkopplad.',
    liveVoiceListening: 'Live voice lyssnar.',
    liveVoiceUnknownError: 'Live voice fick ett okänt fel.',
    liveVoiceCouldNotContinue: (message: string) => `Live voice kunde inte fortsätta: ${message}`,
    liveVoiceAnswered: 'Live voice svarade.',
    liveVoiceListeningEllipsis: 'Live voice lyssnar...',
    processingLiveVoice: 'Bearbetar live voice...',
    webRtcOfferFailed: 'Kunde inte skapa WebRTC-offer.',
    openAiLiveVoiceFailed: 'Kunde inte starta OpenAI live voice.',
    connectingLiveVoice: 'Ansluter live voice...',
    liveVoiceStartFailed: 'Kunde inte starta live voice.',
    liveVoiceStartNotice: (message: string) => `Jag kunde inte starta live voice: ${message}`,
    liveVoiceStartToastTitle: 'Live voice kunde inte starta',
    liveVoiceOff: 'Live voice är avstängd.',
    requestFailedNotice: (message: string) => `Jag kunde inte slutföra förfrågan: ${message}`,
    sendErrorTitle: 'Kunde inte skicka meddelande',
    noAthleteTitle: 'Ingen atlet vald',
    noAthleteDescription: 'Välj en atlet för att spara programmet.',
    programSavedTitle: 'Program sparat!',
    programSavedDescription: (name: string) => `"${name}" har sparats.`,
    saveProgramErrorTitle: 'Kunde inte spara programmet',
    tryAgainLater: 'Försök igen senare.',
    saveErrorTitle: 'Fel vid sparning',
    unexpectedError: 'Ett oväntat fel uppstod.',
    modelLoadingNotice: 'Jag kan inte skicka just nu eftersom AI-modellen inte är färdigladdad. Vänta några sekunder och försök igen.',
    transcribeError: 'Kunde inte transkribera röstmeddelandet.',
    noSpeechHeard: 'Jag hörde inget tydligt i röstmeddelandet.',
    voiceInputUnsupported: 'Röstinmatning stöds inte i den här webbläsaren.',
    noMicrophoneAudio: 'Jag fick ingen ljuddata från mikrofonen.',
    voiceTranscribedTitle: 'Röst transkriberad',
    voiceAutoSendDescription: 'Jag skickar meddelandet automatiskt om en liten stund.',
    voicePlacedDescription: 'Texten ligger i meddelandefältet.',
    voiceHandlingError: 'Kunde inte hantera röstmeddelandet.',
    voiceUseErrorNotice: (message: string) => `Jag kunde inte använda röstmeddelandet: ${message}`,
    voiceUseErrorTitle: 'Kunde inte använda rösten',
    contextAthlete: (name: string) => `Atlet: ${name}`,
    athleteContext: 'Atletkontext',
    programContext: 'Programkontext',
    testContext: 'Testkontext',
    videoContextTotal: (total?: number, done?: number) => `**Totalt**: ${total} videoanalyser (${done} klara)`,
    athletePseudonym: 'Atleten',
    type: 'Typ',
    status: 'Status',
    score: 'Poäng',
    issues: 'Problem',
    recommendations: 'Rekommendationer',
    exercise: 'Övning',
    identifiedIssues: 'Identifierade problem',
    poseAnalysis: 'MediaPipe Poseanalys',
    aiScore: 'AI-poäng',
    interpretation: 'Tolkning',
    technicalFeedback: 'Teknisk feedback',
    patterns: 'Mönster',
    overallAssessment: 'Övergripande bedömning',
    currentPageContext: (title: string) => `\n\n## AKTUELL SIDKONTEXT: ${title}\n`,
    newConversation: 'Ny konversation',
    chatHistory: 'Chatthistorik',
    loadConversationErrorTitle: 'Kunde inte ladda konversationen',
    selectAthlete: 'Välj atlet',
    searchAthletes: 'Sök atleter...',
    noAthletesFound: 'Inga atleter hittades',
    clearAthleteContext: 'Chatta utan atletkontext',
    athletesLoadError: 'Kunde inte hämta atleter',
    minimizeChat: 'Minimera chatten',
    expandChat: 'Expandera chatten',
    closeChat: 'Stäng chatten',
    sideContext: 'Sidkontext',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    consentMissing: 'Atletens samtycke saknas - AI-chatten kan inte använda atletdata',
    voiceOperatorBanner: 'Voice operator aktiv: mikrofon, auto-send och röstsvar är på',
    confirmsActions: 'Bekräftar åtgärder',
    stop: 'Stoppa',
    howCanIHelp: 'Hur kan jag hjälpa dig?',
    hasContext: (title: string) => `Jag har tillgång till ${title.toLowerCase()}. Fråga mig vad som helst om det!`,
    contextDisabled: 'Kontext är inaktiverad. Klicka på knappen ovan för att aktivera.',
    defaultEmpty: 'Fråga mig om träningsprogram, testanalyser, eller andra frågor om dina atleter.',
    whatCanYouDo: 'Vad kan du göra?',
    operatorActive: 'Dashboardens operatorläge är aktivt.',
    explainIssues: 'Förklara problem',
    explainIssuesPrompt: 'Förklara de viktigaste problemen i analysen',
    improvementExercises: 'Förbättringsövningar',
    improvementExercisesPrompt: 'Ge mig specifika övningar för att förbättra tekniken',
    simpleSummary: 'Enkel sammanfattning',
    simpleSummaryPrompt: 'Sammanfatta analysen i enkla termer för atleten',
    operatorBrief: 'Operatorbrief',
    weeklySummary: 'Veckosummering',
    operatorBriefPrompt: 'Gör en proaktiv coach-operator brief från dashboardens arbetskö. Prioritera risker, feedback, väntande testgodkännanden och nästa app-vy att öppna.',
    weeklySummaryPrompt: 'Gör en kort proaktiv veckosummering från coachdashboardens operatorläge och lyft vad jag bör bevaka härnäst.',
    summarize: 'Sammanfatta',
    summarizeDashboardPrompt: 'Sammanfatta coachdashboarden utifrån sidkontexten och prioritera de tre viktigaste nästa stegen.',
    whatNeedsAction: 'Vad kräver åtgärd?',
    whatNeedsActionPrompt: 'Vad kräver åtgärd på den här dashboarden just nu? Skilj på akuta signaler och saker att följa upp senare.',
    explainCards: 'Förklara korten',
    explainCardsPrompt: 'Förklara korten och signalerna på dashboarden så jag snabbt vet hur jag ska läsa sidan.',
    teamCaptureGuide: 'Lagkondition-upplägg',
    teamCaptureGuidePrompt: 'Förklara hur Lagkondition-upplägget ska fungera med Garmin, Concept2 PM5, station receivers, Bluetooth-begränsningar och Workout Evaluation efter passet.',
    teamStrengthGuide: 'Lagstyrka-upplägg',
    teamStrengthGuidePrompt: 'Förklara hur Lagstyrka-sidan fungerar för gemensam styrkeloggning, spelarbyte, tilldelade pass, setloggning och status.',
    summarizePage: 'Sammanfatta sidan',
    summarizePagePrompt: 'Sammanfatta den här sidan och lyft fram vad jag bör titta på först.',
    nextSteps: 'Nästa steg',
    nextStepsPrompt: 'Föreslå konkreta nästa steg baserat på sidkontexten.',
    explainConcepts: 'Förklara begrepp',
    explainConceptsPrompt: 'Förklara de viktigaste begreppen på den här sidan kort och praktiskt.',
    analyzeTrainingPrompt: (name: string) => `Analysera ${name}s träningshistorik`,
    analyzeTraining: 'Analysera träning',
    createProgramPrompt: (name: string) => `Skapa ett träningsprogram för ${name}`,
    createProgram: 'Skapa program',
    tenKPrompt: 'Hur skapar jag ett effektivt 10K-program?',
    thresholdPrompt: 'Förklara tröskelträning och zoner',
    trainingZones: 'Träningszoner',
    recording: (duration: string) => `Spelar in ${duration}`,
    transcribingVoiceMessage: 'Skriver ut röstmeddelandet...',
    stopRecording: 'Stoppa inspelning',
    transcribingVoice: 'Transkriberar röst',
    startVoiceInput: 'Starta röstinmatning',
    turnOffSpokenReplies: 'Stäng av röstsvar',
    turnOnSpokenReplies: 'Slå på röstsvar',
    turnOffAutoSend: 'Stäng av automatisk röstsändning',
    turnOnAutoSend: 'Slå på automatisk röstsändning',
    turnOffVoiceOperator: 'Stäng av voice operator',
    turnOnVoiceOperator: 'Slå på voice operator',
    turnOffLiveVoice: 'Stäng av live voice',
    startLiveVoice: 'Starta live voice',
    apiKeyMissingTitle: 'API-nyckel saknas',
    athleteAssistantUnavailable: 'AI-assistenten ej tillgänglig',
    athleteAssistantUnavailableDescription: 'Din coach har inte aktiverat AI-assistenten ännu. Kontakta din coach för att aktivera denna funktion.',
    configureApiKeyDescription: 'Konfigurera din API-nyckel (Anthropic eller Google) för att använda AI-assistenten.',
    goToSettings: 'Gå till inställningar',
    weeks: 'veckor',
    chooseAthleteToSave: 'Välj en atlet för att spara',
    saveProgram: 'Spara program',
    inputPlaceholder: 'Skriv ett meddelande...',
    voiceAutoSendSoon: 'Skickar röstmeddelandet snart...',
    cancel: 'Avbryt',
    readingReply: 'Läser upp svaret...',
    aiVoiceGenerated: 'Rösten är AI-genererad.',
  },
} satisfies Record<AppLocale, Record<string, string | ((value: string) => string) | ((total?: number, done?: number) => string)>>
