'use client'

/**
 * Weekly Reports Panel
 *
 * Admin UI for browsing weekly reports generated by operator agents:
 * - BI_WEEKLY (Business Intelligence)
 * - COMPETITOR (Competitor Intelligence)
 * - MARKETING_WEEKLY (Marketing Content)
 */

import { useState } from 'react'
import useSWR from 'swr'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  BarChart3,
  Eye,
  Megaphone,
  Mail,
  Loader2,
  FileText,
  X,
  AlertTriangle,
} from 'lucide-react'

const fetcher = (url: string) => fetch(url).then(r => r.json())

const REPORT_TYPE_INFO: Record<string, { label: string; icon: React.ElementType; color: string }> = {
  BI_WEEKLY: { label: 'Business Intelligence', icon: BarChart3, color: '#14b8a6' },
  COMPETITOR: { label: 'Competitor Intel', icon: Eye, color: '#ef4444' },
  MARKETING_WEEKLY: { label: 'Marketing', icon: Megaphone, color: '#ec4899' },
}

interface ReportSummary {
  id: string
  weekStart: string
  reportType: string
  title: string
  createdAt: string
  emailedAt: string | null
  readAt: string | null
}

interface ReportListData {
  reports: ReportSummary[]
  counts: Record<string, number>
  totalCount: number
}

interface FullReport {
  id: string
  weekStart: string
  reportType: string
  title: string
  fullContent: string
  createdAt: string
  emailedAt: string | null
  readAt: string | null
  structuredData: unknown
}

export function WeeklyReportsPanel() {
  const [typeFilter, setTypeFilter] = useState<string>('all')
  const [selectedId, setSelectedId] = useState<string | null>(null)

  const listUrl = typeFilter === 'all'
    ? '/api/admin/weekly-reports?weeks=12'
    : `/api/admin/weekly-reports?weeks=12&type=${typeFilter}`

  const { data, isLoading, error, mutate } = useSWR<ReportListData>(
    listUrl,
    fetcher,
    { refreshInterval: 300000 } // 5 minutes
  )

  const { data: selectedData } = useSWR<{ report: FullReport }>(
    selectedId ? `/api/admin/weekly-reports?id=${selectedId}` : null,
    fetcher
  )

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (error || !data) {
    return (
      <Card>
        <CardContent className="py-12 text-center">
          <AlertTriangle className="mx-auto h-8 w-8 text-yellow-500 mb-2" />
          <p className="text-muted-foreground">Failed to load weekly reports</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Weekly Reports</h2>
          <p className="text-muted-foreground">
            Reports generated by operator agents
          </p>
        </div>
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="w-48">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All types</SelectItem>
            <SelectItem value="BI_WEEKLY">Business Intelligence</SelectItem>
            <SelectItem value="COMPETITOR">Competitor Intel</SelectItem>
            <SelectItem value="MARKETING_WEEKLY">Marketing</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Count cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {Object.entries(REPORT_TYPE_INFO).map(([type, info]) => {
          const Icon = info.icon
          const count = data.counts[type] || 0
          return (
            <Card key={type}>
              <CardContent className="pt-4 pb-4">
                <div className="flex items-center gap-2">
                  <Icon className="h-4 w-4" style={{ color: info.color }} />
                  <span className="text-sm text-muted-foreground">{info.label}</span>
                </div>
                <p className="text-2xl font-bold mt-1">{count}</p>
                <p className="text-xs text-muted-foreground">last 12 weeks</p>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Reports list */}
      <Card>
        <CardHeader>
          <CardTitle>Reports ({data.totalCount})</CardTitle>
          <CardDescription>Click a report to view its full content</CardDescription>
        </CardHeader>
        <CardContent>
          {data.reports.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              No reports yet. Weekly reports appear here after agents run.
            </p>
          ) : (
            <div className="space-y-2">
              {data.reports.map(report => {
                const info = REPORT_TYPE_INFO[report.reportType] || {
                  label: report.reportType,
                  icon: FileText,
                  color: '#666',
                }
                const Icon = info.icon
                const isUnread = !report.readAt

                return (
                  <button
                    key={report.id}
                    onClick={() => setSelectedId(report.id)}
                    className="w-full text-left p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors flex items-center gap-3"
                  >
                    <div
                      className="p-2 rounded"
                      style={{ backgroundColor: `${info.color}20` }}
                    >
                      <Icon className="h-4 w-4" style={{ color: info.color }} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <p className="font-medium truncate">{report.title}</p>
                        {isUnread && (
                          <Badge variant="default" className="text-xs">New</Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground mt-1">
                        <span>Week of {new Date(report.weekStart).toLocaleDateString('sv-SE')}</span>
                        {report.emailedAt && (
                          <span className="flex items-center gap-1">
                            <Mail className="h-3 w-3" />
                            Emailed
                          </span>
                        )}
                      </div>
                    </div>
                  </button>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Selected report viewer (modal-style) */}
      {selectedId && selectedData?.report && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <Card className="max-w-4xl w-full max-h-[90vh] flex flex-col">
            <CardHeader className="flex-row items-center justify-between flex-shrink-0 border-b">
              <div>
                <CardTitle>{selectedData.report.title}</CardTitle>
                <CardDescription>
                  {REPORT_TYPE_INFO[selectedData.report.reportType]?.label} ·
                  Week of {new Date(selectedData.report.weekStart).toLocaleDateString('sv-SE')}
                </CardDescription>
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => {
                  setSelectedId(null)
                  mutate() // Refresh list to update readAt state
                }}
              >
                <X className="h-4 w-4" />
              </Button>
            </CardHeader>
            <CardContent className="overflow-y-auto flex-1 pt-4">
              <div className="prose prose-invert max-w-none whitespace-pre-wrap font-mono text-sm">
                {selectedData.report.fullContent}
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
